<?php	//	S:VA
$orderId     	= $this->getRequest()->getParam('order_id');
$getShippingURL	= Mage::helper('adminhtml')->getUrl('admin_shipment/adminhtml_index/changeShipping/order_id/'.$orderId);
?>
<?php /** @var $this Mage_Adminhtml_Block_Sales_Order_View_Tab_Info */ ?>
<?php $_order = $this->getOrder() ?>
<div>
    <div id="order-messages">
        <?php echo $this->getChildHtml('order_messages') ?>
    </div>
    <?php echo $this->getChildHtml('order_info') ?>
    <input type="hidden" name="order_id" value="<?php echo $_order->getId() ?>"/>
    <?php if ($_order->getIsVirtual()): ?>
    <div class="box-right">
    <?php else: ?>
    <div class="box-left">
    <?php endif; ?>
        <!--Payment Method-->
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-payment-method"><?php echo Mage::helper('sales')->__('Payment Information') ?></h4>
            </div>
            <fieldset>
                <?php echo $this->getPaymentHtml() ?>
                <div><?php echo Mage::helper('sales')->__('Order was placed using %s', $_order->getOrderCurrencyCode()) ?></div>
            </fieldset>
        </div>
    </div>
    <?php if (!$_order->getIsVirtual()): ?>
    <div class="box-right">
        <!--Shipping Method-->
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-shipping-method"><?php echo Mage::helper('sales')->__('Shipping &amp; Handling Information') ?></h4>
            </div>
            <fieldset>
                <?php  if ($_order->getTracksCollection()->count()) : ?>
                <a href="#" id="linkId" onclick="popWin('<?php echo $this->helper('shipping')->getTrackingPopupUrlBySalesModel($_order) ?>','trackorder','width=800,height=600,resizable=yes,scrollbars=yes')" title="<?php echo $this->__('Track Order') ?>"><?php echo $this->__('Track Order') ?></a>
                <br/>
                <?php endif; ?>
                
                <?php	//	S:VA
                $shippingMethods		=	Mage::helper('shipment')->getShippingMethods();
				$orderComments			=	Mage::helper('shipment')->getOrderHistoryComments($_order);
				$commentPrefix	=	Angara_Shipment_Helper_Data::shipping_method_comment;
				//	Check if comment prefix is matched in order history comments
				foreach ($orderComments as $comment) {
					if (strpos($comment, $commentPrefix) !== FALSE) { 
						$showPrice	=	1;
						break;
					}
				}
            	?>
                
                <?php if ($_order->getShippingDescription()): ?>
                    <strong><?php echo $this->escapeHtml($_order->getShippingDescription()) ?></strong>

                    <?php if ($this->helper('tax')->displayShippingPriceIncludingTax()): ?>
                        <?php $_excl = $this->displayShippingPriceInclTax($_order); ?>
                    <?php else: ?>
                        <?php $_excl = $this->displayPriceAttribute('shipping_amount', false, ' '); ?>
                    <?php endif; ?>
                    <?php $_incl = $this->displayShippingPriceInclTax($_order); ?>

                    <?php //	S:VA	
						if($showPrice!='1'){ echo $_excl; }
					 ?>
                    
                    <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                        (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                    <?php endif; ?>
                <?php else: ?>
                    <?php echo $this->helper('sales')->__('No shipping information available'); ?>
                <?php endif; ?>
                
                <?php 	//	S:VA
				if (count($shippingMethods)>0){
					$shippingMethodsDropdown	=	'<select id="shipping_methods_dropdown" class="select" name="shipping_method">';
					foreach($shippingMethods as $name => $method){
						$shippingMethodsDropdown.=	'<option value="'.$method.'">'.$method.'</option>';
					}
					$shippingMethodsDropdown.=	'</select>';
				?>
                <form name="change_shipping_form" id="change_shipping_form" action="<?php echo $getShippingURL ?>" method="post">
                    <div><a id="change_shipping_link" href="javascript:;<?php //echo $getShippingURL ?>">Change shipping method</a></div>
                    <div id="show_shipping_methods" style="display:none;">
                        <?php echo $shippingMethodsDropdown;?>
                        <button class="scalable save" type="button" title="Save" id="change_shipping_btn" name="change_shipping_btn"><span>Save</span></button>
                    </div>
                    <input type="hidden" name="current_shipping_method" value="<?php echo $this->escapeHtml($_order->getShippingDescription()) ?>"/>
                    <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
                </form>
              
                <script>
                    $('change_shipping_link').observe('click', function(event) {
                        $('show_shipping_methods').show();
                    })
                    $('change_shipping_btn').observe('click', function(event) {
                        event.stop();
                        if(confirm('Are you sure you want to change the Shipping?')){
                            $('change_shipping_form').submit();
                        }
                    })
                </script>
            <?php }
			//	E:VA?>
            </fieldset>
        </div>
    </div>
    <?php endif; ?>
    <div class="clear"></div>
    <?php echo $this->getGiftOptionsHtml() ?>
    <div class="clear"></div>
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-products"><?php echo Mage::helper('sales')->__('Items Ordered') ?></h4>
        </div>
    </div>
    <?php echo $this->getItemsHtml() ?>
    <div class="clear"></div>

    <div class="box-left">
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4><?php echo Mage::helper('sales')->__('Comments History') ?></h4>
            </div>
            <fieldset><?php echo $this->getChildHtml('order_history') ?></fieldset>
        </div>
		<!-- RMA Requests -->
		<?php $rmas = Mage::helper('awrma')->getAllRmaItems($_order->getId(), false);?>
		<?php if($rmas):?>
		<div class="entry-edit">
            <div class="entry-edit-head">
                <h4>Rma Requests</h4>
            </div>
            <fieldset>
			<ul>
			<?php 
				$_uniqueRmas = array();
				foreach($rmas as $_rmaItem){
					foreach($_rmaItem as $_rma){		//	S:VA	
						$_uniqueRmas[$_rma['rma']->getId()] = $_rma['rma'];
					}
				}
				arsort($_uniqueRmas);		//	Sort an array in descending order so that the recently raised rma shows first.
				foreach($_uniqueRmas as $_rma){
					?>
					<li><a href="<?php echo Mage::helper("adminhtml")->getUrl('awrma_admin/adminhtml_rma/edit',array('id' => $_rma->getId())); ?>"><?php echo $_rma->getTextId(); ?></a></li>
				<?php
						echo Mage::getSingleton('core/layout')
                        ->createBlock('awrma/adminhtml_rma_edit_tab_requestinformation_comments')
                        ->setRmaRequest(Mage::getModel('awrma/entity')->load($_rma->getId()))->toHtml();
				}
			?>
			</ul>
			</fieldset>
        </div>
		<?php endif;?>
    </div>
    <div class="box-right entry-edit">
		<?php /* Angara Modification Start */ ?>
		<!--HPRAHI CODE -->
    	<div class="entry-edit-head"><h4><?php echo Mage::helper('sales')->__('Ok To Ship') ?></h4></div>
    	<fieldset style="margin-bottom:20px"><?php echo $this->getChildHtml('order_oktoship') ?></fieldset>
        <div class="entry-edit-head"><h4><?php echo Mage::helper('sales')->__('Extra Comment') ?></h4></div>
    	<fieldset style="margin-bottom:20px"><?php echo $this->getChildHtml('order_extracomment') ?></fieldset>
        <!--HPRAHI CODE END -->
		<?php /* Angara Modification End */ ?>
        <div class="entry-edit-head"><h4><?php echo Mage::helper('sales')->__('Order Totals') ?></h4></div>
        <div class="order-totals"><?php echo $this->getChildHtml('order_totals') ?></div>
    </div>
    <div class="clear"></div>
</div>

<?php echo $this->getChildHtml('popup_window');?>
<script type="text/javascript">
//<![CDATA[
    /**
     * Retrieve gift options tooltip content
     */
    function getGiftOptionsTooltipContent(itemId) {
        var contentLines = [];
        var headerLine = null;
        var contentLine = null;

        $$('#gift_options_data_' + itemId + ' .gift-options-tooltip-content').each(function (element) {
            if (element.down(0)) {
                headerLine = element.down(0).innerHTML;
                contentLine = element.down(0).next().innerHTML;
                if (contentLine.length > 30) {
                    contentLine = contentLine.slice(0,30) + '...';
                }
                contentLines.push(headerLine + ' ' + contentLine);
            }
        });
        return contentLines.join('<br/>');
    }
    giftOptionsTooltip.setTooltipContentLoaderFunction(getGiftOptionsTooltipContent);
//]]>
</script>
