<div id="checkout-review" class="onepagecheckout_block">
	<div class="loading-indicator hide text-center">
	<div class="loader fa fa-spinner fa-spin fa-5x max-margin-top"></div>    
    </div>
    <div class="block-sub-heading high-padding-bottom padding-type-10" style="background-color:#D0D497">Order Summary</div>
    <div id="checkout-review-load" class="padding-type-10">
        <?php echo $this->getChildHtml('info') ?>
    </div>
    
</div>
