<style>
.txt {bottom:8%;left:0;right:0;text-align:center;width:80%;margin:0 auto;}
.txt .title {font-size:26px;}


</style>

<div class="banner max-padding-bottom relative">
		<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/imobile/images/landingpage/fine-jewelry/herobanner.jpg"/>
		<div class="absolute-placeholder txt">
			<span class="title max-padding-bottom">Fine Jewelry</span>
			<p>Jewelry that definess life's finest moments - rings, earrings and pendants adorned with the finest gemstones and handcrafted to perfection -there's one for everyone, every occasion and every special person in your life, including you.</p>
		</div>
</div>
	<div class="clearfix"></div>
<section class="container fine-jewelry">
<div class="clearfix"></div>
	<div class="full-width relative txt-holder max-padding-bottom">
		<a href="/jewelry/sapphire-jewelry?icid=jewelrypage|sapphire|09272016">
			<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/imobile/images/landingpage/fine-jewelry/1.jpg" alt="View Sapphire Jewelry" title="Shop Sapphire Jewelry"/>
		</a>
	</div>
	<div class="clearfix"></div>
	<div class="full-width relative txt-holder max-padding-bottom">
		<a href="/jewelry/ruby-jewelry?icid=jewelrypage|ruby|09272016">
			<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/imobile/images/landingpage/fine-jewelry/2.jpg" alt="View Ruby Jewelry" title="Shop Ruby Jewelry"/>
		</a>
	</div>
	<div class="clearfix"></div>
	<div class="full-width relative txt-holder max-padding-bottom">
		<a href="/jewelry/aquamarine-jewelry?icid=jewelrypage|aqua|09272016">
			<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/imobile/images/landingpage/fine-jewelry/3.jpg" alt="View Aquamarine Jewelry" title="Shop Aquamarine Jewelry"/>
		</a>
	</div>
<div class="clearfix"></div>
	<div class="full-width relative txt-holder max-padding-bottom">
		<a href="/jewelry/emerald-jewelry?icid=jewelrypage|emerald|09272016">
			<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/imobile/images/landingpage/fine-jewelry/4.jpg" alt="View Emerald Jewelry" title="Shop Emerald Jewelry"/>
		</a>
	</div>
	<div class="clearfix"></div>
	<div class="full-width relative txt-holder max-padding-bottom relative txt-holder">
		<a href="/jewelry/diamond-jewelry?icid=jewelrypage|diamond|09272016">
			<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/imobile/images/landingpage/fine-jewelry/5.jpg" alt="View Diamond Jewelry" title="Shop Diamond Jewelry"/>
		</a>
	</div>
	<div class="clearfix"></div>
	<div class="full-width relative txt-holder max-padding-bottom">
		<a href="/jewelry/pearl-jewelry?icid=jewelrypage|pearl|09272016">
			<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/imobile/images/landingpage/fine-jewelry/6.jpg" alt="View Pearl Jewelry" title="Shop Pearl Jewelry"/>
		</a>
	</div>
<div class="clearfix"></div>
	<div class="full-width relative txt-holder max-padding-bottom">
		<a href="/jewelry/morganite-jewelry?icid=jewelrypage|morganite|09272016">
			<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/imobile/images/landingpage/fine-jewelry/7.jpg" alt="View Morganite Jewelry" title="Shop Morganite Jewelry"/>
		</a>
	</div>
	<div class="clearfix"></div>
	<div class="full-width relative txt-holder max-padding-bottom relative txt-holder">
		<a href="/jewelry/peridot-jewelry?icid=jewelrypage|peridot|09272016">
			<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/imobile/images/landingpage/fine-jewelry/8.jpg" alt="View Peridot Jewelry" title="Shop Peridot Jewelry"/>
		</a>
	</div>
	<div class="clearfix"></div>
	<div class="full-width relative txt-holder max-padding-bottom">
		<a href="/jewelry/amethyst-jewelry?icid=jewelrypage|amethyst|09272016">
			<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/imobile/images/landingpage/fine-jewelry/9.jpg" alt="View Amethyst Jewelry" title="Shop Amethyst Jewelry"/>
		</a>
	</div>
<div class="clearfix"></div>
	<div class="full-width relative txt-holder max-padding-bottom">
		<a href="/jewelry/garnet-jewelry?icid=jewelrypage|garnet|09272016">
			<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/imobile/images/landingpage/fine-jewelry/10.jpg" alt="View Garnet Jewelry" title="Shop Garnet Jewelry"/>
		</a>
	</div>
	<div class="clearfix"></div>
	<div class="full-width relative txt-holder max-padding-bottom relative txt-holder">
		<a href="/jewelry/opal-jewelry?icid=jewelrypage|opal|09272016">
			<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/imobile/images/landingpage/fine-jewelry/11.jpg" alt="View Opal Jewelry" title="Shop Opal Jewelry"/>
		</a>
	</div>
	<div class="clearfix"></div>
	<div class="full-width relative txt-holder max-padding-bottom">
		<a href="/jewelry/citrine-jewelry?icid=jewelrypage|citrine|09272016">
			<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/imobile/images/landingpage/fine-jewelry/12.jpg" alt="View Citrine Jewelry" title="Shop Citrine Jewelry"/>
		</a>
	</div>
<div class="clearfix"></div>
	<div class="full-width relative txt-holder max-padding-bottom">
		<a href="/jewelry/pink-tourmaline-jewelry?icid=jewelrypage|pink-tourmaline|09272016">
			<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/imobile/images/landingpage/fine-jewelry/13.jpg" alt="View Pink Tourmaline Jewelry" title="Shop Pink Tourmaline Jewelry"/>
		</a>
	</div>
	<div class="clearfix"></div>
	<div class="full-width relative txt-holder max-padding-bottom relative txt-holder">
		<a href="/jewelry/blue-topaz-jewelry?icid=jewelrypage|topaz|09272016">
			<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/imobile/images/landingpage/fine-jewelry/14.jpg" alt="View Blue Topaz Jewelry" title="Shop Blue Topaz Jewelry"/>
		</a>
	</div>
	<div class="clearfix"></div>
	<div class="full-width relative txt-holder max-padding-bottom">
		<a href="/jewelry/black-onyx-jewelry?icid=jewelrypage|black-onyx|09272016">
			<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/imobile/images/landingpage/fine-jewelry/15.jpg" alt="View Black Onyx Jewelry" title="Shop Black Onyx Jewelry"/>
		</a>
	</div>
<div class="clearfix"></div>
	<div class="full-width relative txt-holder max-padding-bottom">
		<a href="/jewelry/colored-diamond-jewelry?filterable_stone_names=4555?icid=jewelrypage|black-diamond|09272016">
			<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/imobile/images/landingpage/fine-jewelry/16.jpg" alt="View Black Diamond Jewelry" title="Shop Black Diamond Jewelry"/>
		</a>
	</div>
	<div class="clearfix"></div>
	<div class="full-width relative txt-holder max-padding-bottom relative txt-holder">
		<a href="/jewelry/colored-diamond-jewelry?filterable_stone_names=4556?icid=jewelrypage|blue-diamond|09272016">
			<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/imobile/images/landingpage/fine-jewelry/17.jpg" alt="View Blue Diamond Jewelry" title="Shop Blue Diamond Jewelry"/>
		</a>
	</div>
	<div class="clearfix"></div>
	<div class="full-width relative txt-holder">
		<a href="/jewelry/tanzanite-jewelry?icid=jewelrypage|tanzanite|09272016">
			<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/imobile/images/landingpage/fine-jewelry/18.jpg" alt="View Tanzanite Jewelry" title="Shop Tanzanite Jewelry"/>
		</a>
	</div>
</section>