<?php	//	Check form submission
	$submit	=	Mage::getSingleton('core/session')->getData('frm_submit');	//	get the session
	//Mage::getSingleton('core/session')->setData('frm_submit',false);		//	expire the session
?>
<style>
.messages{display:none!important}

.col-4{
	width:100%;
	padding-left:8px;
	padding-right:8px;
	float:left;
	position:relative;
	cursor:pointer;
}
.col-4 span.btn{
	background: transparent;
    border: 1px solid #333333;
    border-radius: 2px;
    text-shadow: none;
    color: #333333;
    position: absolute;
    left: 50%;
    margin-left: -45px;
	bottom: 44%;
	cursor:pointer;
}
.col-4:hover span.btn{
	border: 1px solid #fa505a;
	color: #fa505a;
}
.col-4 span.btn.hd{
	bottom: 9%;
}

@media (max-width:500px){
	.thankyou-msg{clear:both}
	.black-cyber .signup-box .text{padding:16px;}
	.footer-newsletter{display:none!important}
	.footer-links{border-top:1px solid #efefef}
	.footer-links ul.links{margin-bottom:0px}
}
</style>
<div class="col-sm-12 no-padding head-banner">
	<img class="img-responsive mob" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/green-monday/gm-main-banner-mobile.jpg" alt="Green Monday"/>
</div>
<div class="clearfix"></div>
<div class="container showcase-bg-white min-padding-top relative-placeholder">
	<div class="black-friday black-cyber">
		<div class="col-sm-12 no-padding">
			<div class="col-sm-12 no-padding high-margin-top page-title category-title">
				<h1 class="no-margin text-center pull-left">
					<span class="pull-left">2016 Green Monday Deals</span>
				</h1>
			</div>
			<div class="clearfix"></div>
			<div class="col-sm-12 no-padding high-margin-top">
				<p>Fine jewelry shopping just got more exciting! Make the most of Angara’s Green Monday Deals to get your hands on exquisitely crafted jewelry, including rings, earrings, pendants and bracelets, at amazing prices. Whether you are looking to expand your collection or gift something unique to a special someone, what could be better than Angara’s Green Monday Deals to satiate your thirst from some bling? Cheers to shopping your heart out!</p>
			</div>
			<div class="clearfix"></div>
			<div class="col-sm-12 no-padding high-margin-top">
				<div class="col-4 no-padding high-margin-bottom">
					<a href="/deal-of-the-day?cid=gm-page|dod|20off|12112016">
						<img class="img-responsive des" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/green-monday/holiday-special.jpg" alt="Holiday Special"/>
						<span class="btn hd">Shop Now</span>
					</a>
				</div>
				<div class="col-4 no-padding high-margin-bottom">
					<a href="/products?cid=gm-page|offer|15off|12112016">
						<img class="img-responsive des" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/green-monday/holiday-special-sale.jpg" alt="Holiday Special Sale"/>
						<span class="btn">Shop Now</span>
					</a>
				</div>
				<div class="col-4 no-padding high-margin-bottom">
					<a href="/coupons?cid=gm-page|deals|more|12112016">
						<img class="img-responsive des" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/green-monday/more-deals.jpg" alt="More Deals"/>
						<span class="btn" style="margin-left:-64px">Select Your Deal</span>
					</a>
				</div>
			</div>
		</div>
		<div class="clearfix"></div>
	</div>
</div>