<section class="infinity-container">
    <div class="full-width">
		<a href="/jewelry/new-arrivals?order=position&dir=asc&no_cache=true&jewelry_styles=6189&icid=infinitypage|new-arrival|image-click|02082017">
            <img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/imobile/images/landingpage/infinity/one.jpg" alt="">
		</a>
    </div>
    <div class="clearfix"></div>
	<div class="full-width">
		<a href="/pendants/infinity-pendant-necklaces?icid=infinitypage|inf-pendants|explrcol|02082017">
            <img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/imobile/images/landingpage/infinity/two.jpg" alt="">
		</a>
    </div>
    <div class="clearfix"></div>
	<div class="full-width">
		<a href="/rings/infinity-rings?icid=infinitypage|inf-rings|explrcol|02082017">
            <img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/imobile/images/landingpage/infinity/three.jpg" alt="">
		</a>
    </div>
    <div class="clearfix"></div>
	<div class="full-width">
		<a href="/earrings/infinity-earrings?icid=infinitypage|inf-earrings|explrcol|02082017">
            <img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/imobile/images/landingpage/infinity/four.jpg" alt="">
		</a>
    </div>
    <div class="clearfix"></div>
	<div class="full-width">
		<a href="/bracelets/infinity-bracelets?icid=infinitypage|inf-bracelets|explrcol|02082017">
            <img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/imobile/images/landingpage/infinity/five.jpg" alt="">
		</a>
    </div>
    <div class="clearfix"></div>
</section>