<style>
	.sep{
		position: absolute;
		height: 1px;
		background: #888888;
		left: 0px;
		right: 0px;
		top: 50%;
	}
	.kh-pro{
		font-size:23px;
	}
	.kh-pro .col-md-3{
		padding-bottom:10px;
		border-bottom:1px solid #dfdfdf;
	}
	.kh-pro .col-md-3:last-child{
		border-bottom:none;
	}
	.kh-pro .col-md-3 a{
		font-size:18px;
	}
	.kh-pro .col-md-3 a img{
		margin-bottom:10px;
		border:1px solid transparent;
	}
	.kh-pro .col-md-3 a img:hover{
		border:1px solid #fa505a;
	}
	.kh-collection-banner{
		width:33.85%; 
		left:50%; 
		margin-left:-16.58%;
	}
	
.play {
	width:14.417%;
    left: 0;
    right: 0;
	margin: 0 auto;
	top: 50%;
    margin-top: -25px;
}


.video-popup {
	position: fixed;
    left: 0px;
    right: 0px;
    top: 0px;
    bottom: 0px;
    background: rgba(0,0,0,0.5);
	z-index: 1042;
}


.video-popup div {width:90%;margin: 0 auto;}

.popup-close {
	position:absolute; 
	margin-top:-9px !important; 
	right:-9px; 
	cursor:pointer; 
	background:url(/skin/frontend/ress/default/images/sprite.jpg) -229px -151px no-repeat; 
	border-radius: 11px; 
	height: 18px; 
	width: 18px !important;
	z-index: 2;
}

</style>

<div class="relative relative-placeholder the-perfect-gift">
		<img class="img-responsive kh-mb-1" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/imobile/images/landingpage/knotty-heart/kh-mb-01.jpg" alt="Knotty Heart Jewelry From Angara" title="Celebrate Love With Knotty Heart Jewelry"/>
		<a href="javascript:void(0)" class="absolute-placeholder play">
			<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/play-btn.png"/> 
		</a>
</div>
<div class="clearfix"></div>

<div class="col-sm-12 heading text-center text-bold max-margin-top">
	<span style="font-size:17px;">Collection dedicated to the</span>
	<br>
	<span style="font-size:22px;">love of togetherness</span>
</div>
<div class="clearfix"></div>

<div class="col-sm-12 no-padding knotty-heart-rings">
	<div class="col-sm-12 heading text-center text-bold" style="font-size:20px;">
		<span style="width:90px;padding:0px 15px;display:block;margin:0 auto;background:#ffffff;position: relative;z-index: 1;"><img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/knotty-heart.png"/></span>
		<span class="sep"></span>
	</div>
	<div class="clearfix"></div>
	<div class="col-sm-12 heading apricot-text text-center" style="font-size:25px; font-family:cinzelregular; letter-spacing:1px;">
		KNOTTY HEART RINGS
	</div>
	<div class="clearfix"></div>
	<div class="kh-pro text-center max-margin-top high-margin-bottom">
		<div class="col-sm-4 col-md-3 text-center">
			<a href="/p/pave-set-diamond-pretzel-knot-ring-sr1499d?icid=knottyheartpage|knotty-heart-ring|sr1499d|02152017">
				<img style="max-width:60%" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/knotty-heart/products/sr1499d.jpg" alt="Pave-Set Diamond Pretzel Knot Ring" title="Pave-Set Diamond Pretzel Knot Ring">
			</a>
			<div class="clearfix"></div>
			<a href="/p/pave-set-diamond-pretzel-knot-ring-sr1499d?icid=knottyheartpage|knotty-heart-ring|sr1499d|02152017"  style="font-weight:300">
				Pave-Set Diamond Pretzel Knot Ring
			</a>
			<div class="clearfix"></div>
			<span class="apricot-text"   style="font-weight:500">
				From $789
			</span>
		</div>
		
		<div class="col-sm-4 col-md-3 text-center">
			<a href="/p/two-stone-diamond-twin-heart-knot-ring-sr1501d?icid=knottyheartpage|knotty-heart-ring|sr1501d|02152017">
				<img style="max-width:60%" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/knotty-heart/products/sr1501d.jpg" alt="Two Stone Diamond Twin Heart Knot Ring" title="Two Stone Diamond Twin Heart Knot Ring">
			</a>
			<div class="clearfix"></div>
			<a href="/p/two-stone-diamond-twin-heart-knot-ring-sr1501d?icid=knottyheartpage|knotty-heart-ring|sr1501d|02152017"  style="font-weight:300">
				Two Stone Diamond Twin Heart Knot Ring
			</a>
			<div class="clearfix"></div>
			<span class="apricot-text"   style="font-weight:500">
				From $589
			</span>
		</div>
		
		<div class="col-sm-4 col-md-3 text-center">
			<a href="/p/pave-set-diamond-knotted-heart-ring-sr1500d?icid=knottyheartpage|knotty-heart-ring|sr1500d|02152017">
				<img style="max-width:60%" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/knotty-heart/products/sr1500d.jpg" alt="Pave-Set Diamond Knotted Heart Ring" title="Pave-Set Diamond Knotted Heart Ring">
			</a>
			<div class="clearfix"></div>
			<a href="/p/pave-set-diamond-knotted-heart-ring-sr1500d?icid=knottyheartpage|knotty-heart-ring|sr1500d|02152017"  style="font-weight:300">
				Pave-Set Diamond Knotted Heart Ring
			</a>
			<div class="clearfix"></div>
			<span class="apricot-text"   style="font-weight:500">
				From $719
			</span>
		</div>
		
		<div class="col-sm-4 col-md-3 text-center">
			<a href="/p/split-diamond-knotted-twin-heart-ring-sr1502d?icid=knottyheartpage|knotty-heart-ring|sr1502d|02152017">
				<img style="max-width:60%" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/knotty-heart/products/sr1502d.jpg" alt="Split Diamond Knotted Twin Heart Ring" title="Split Diamond Knotted Twin Heart Ring">
			</a>
			<div class="clearfix"></div>
			<a href="/p/split-diamond-knotted-twin-heart-ring-sr1502d?icid=knottyheartpage|knotty-heart-ring|sr1502d|02152017"  style="font-weight:300">
				Split Diamond Knotted Twin Heart Ring
			</a>
			<div class="clearfix"></div>
			<span class="apricot-text"   style="font-weight:500">
				From $1,009
			</span>
		</div>
		
		<div class="col-sm-4 col-md-3 text-center">
			<a href="/p/round-diamond-classic-halo-ring-with-pretzel-heart-motif-sr1504d?icid=knottyheartpage|knotty-heart-ring|sr1504d|02152017">
				<img style="max-width:60%" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/knotty-heart/products/sr1504d.jpg" alt="Round Diamond Classic Halo Ring With Pretzel Heart-Motif" title="Round Diamond Classic Halo Ring With Pretzel Heart-Motif">
			</a>
			<div class="clearfix"></div>
			<a href="/p/round-diamond-classic-halo-ring-with-pretzel-heart-motif-sr1504d?icid=knottyheartpage|knotty-heart-ring|sr1504d|02152017"  style="font-weight:300">
				Round Diamond Classic Halo Ring With Pretzel Heart-Motif
			</a>
			<div class="clearfix"></div>
			<span class="apricot-text"   style="font-weight:500">
				From $1,529
			</span>
		</div>

		<div class="col-sm-4 col-md-3 text-center">
			<a href="/p/round-diamond-classic-solitaire-ring-with-pretzel-heart-motif-sr1505d?icid=knottyheartpage|knotty-heart-ring|sr1505d|02152017">
				<img style="max-width:60%" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/knotty-heart/products/sr1505d.jpg" alt="Round Diamond Classic Solitaire Ring With Pretzel Heart-Motif" title="Round Diamond Classic Solitaire Ring With Pretzel Heart-Motif">
			</a>
			<div class="clearfix"></div>
			<a href="/p/round-diamond-classic-solitaire-ring-with-pretzel-heart-motif-sr1505d?icid=knottyheartpage|knotty-heart-ring|sr1505d|02152017"  style="font-weight:300">
				Round Diamond Classic Solitaire Ring With Pretzel Heart-Motif
			</a>
			<div class="clearfix"></div>
			<span class="apricot-text"   style="font-weight:500">
				From $1,039
			</span>
		</div>

		<div class="col-sm-4 col-md-3 text-center">
			<a href="/p/solitaire-diamond-split-shank-ring-with-knotted-heart-motif-sr1503d?icid=knottyheartpage|knotty-heart-ring|sr1503d|02152017">
				<img style="max-width:60%" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/knotty-heart/products/sr1503d.jpg" alt="Solitaire Diamond Split Shank Ring With Knotted Heart-Motif" title="Solitaire Diamond Split Shank Ring With Knotted Heart-Motif">
			</a>
			<div class="clearfix"></div>
			<a href="/p/solitaire-diamond-split-shank-ring-with-knotted-heart-motif-sr1503d?icid=knottyheartpage|knotty-heart-ring|sr1503d|02152017"  style="font-weight:300">
				Solitaire Diamond Split Shank Ring With Knotted Heart-Motif
			</a>
			<div class="clearfix"></div>
			<span class="apricot-text"   style="font-weight:500">
				From $2,189
			</span>
		</div>	
		
	</div>
</div>
<div class="clearfix"></div>

<div class="col-sm-12 no-padding knotty-heart-rings">
	<div class="col-sm-12 heading text-center text-bold" style="font-size:20px;">
		<span style="width:90px;padding:0px 15px;display:block;margin:0 auto;background:#ffffff;position: relative;z-index: 1;"><img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/knotty-heart.png"/></span>
		<span class="sep"></span>
	</div>
	<div class="clearfix"></div>
	<div class="col-sm-12 heading apricot-text text-center" style="font-size:25px; font-family:cinzelregular; letter-spacing:1px;">
		KNOTTY HEART PENDANTS
	</div>
	<div class="clearfix"></div>
	<div class="kh-pro text-center max-margin-top high-margin-bottom">
		<div class="col-sm-4 col-md-3 text-center">
			<a href="/p/prong-set-diamond-knotted-infinity-heart-pendant-sp1122d?icid=knottyheartpage|knotty-heart-pendant|sp1122d|02152017">
				<img style="max-width:60%;" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/knotty-heart/products/sp1122d.jpg" alt="Prong-Set Diamond Knotted Infinity Heart Pendant" title="Prong-Set Diamond Knotted Infinity Heart Pendant">
			</a>
			<div class="clearfix"></div>
			<a href="/p/prong-set-diamond-knotted-infinity-heart-pendant-sp1122d?icid=knottyheartpage|knotty-heart-pendant|sp1122d|02152017"  style="font-weight:300">
				Prong-Set Diamond Knotted Infinity Heart Pendant
			</a>
			<div class="clearfix"></div>
			<span class="apricot-text"   style="font-weight:500">
				From $739
			</span>
		</div>
		<div class="col-sm-4 col-md-3 text-center">
			<a href="/p/eternal-diamond-open-twin-heart-necklace-sp1121d?icid=knottyheartpage|knotty-heart-pendant|sp1121d|02152017">
				<img style="max-width:60%" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/knotty-heart/products/sp1121d.jpg" alt="Eternal Diamond Open Twin Heart Necklace" title="Eternal Diamond Open Twin Heart Necklace">
			</a>
			<div class="clearfix"></div>
			<a href="/p/eternal-diamond-open-twin-heart-necklace-sp1121d?icid=knottyheartpage|knotty-heart-pendant|sp1121d|02152017"  style="font-weight:300">
				Eternal Diamond Open Twin Heart Necklace
			</a>
			<div class="clearfix"></div>
			<span class="apricot-text"   style="font-weight:500">
				From $729
			</span>
		</div>
		
		<div class="col-sm-4 col-md-3 text-center">
			<a href="/p/solitaire-heart-dangle-diamond-pretzel-knot-pendant-sp1123d?icid=knottyheartpage|knotty-heart-pendant|sp1123d|02152017">
				<img style="max-width:60%" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/knotty-heart/products/sp1123d.jpg" alt="Solitaire Heart Dangle Diamond Pretzel Knot Pendant" title="Solitaire Heart Dangle Diamond Pretzel Knot Pendant">
			</a>
			<div class="clearfix"></div>
			<a href="/p/solitaire-heart-dangle-diamond-pretzel-knot-pendant-sp1123d?icid=knottyheartpage|knotty-heart-pendant|sp1123d|02152017"  style="font-weight:300">
				Solitaire Heart Dangle Diamond Pretzel Knot Pendant
			</a>
			<div class="clearfix"></div>
			<span class="apricot-text"   style="font-weight:500">
				From $939
			</span>
		</div>
		<div class="col-sm-4 col-md-3 text-center">
			<a href="/p/entwined-diamond-tilted-heart-knot-pendant-sp1128d?icid=knottyheartpage|knotty-heart-pendant|sp1128d|02152017">
				<img style="max-width:60%" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/knotty-heart/products/sp1128d.jpg" alt="Entwined Diamond Tilted Heart Knot Pendant" title="Entwined Diamond Tilted Heart Knot Pendant">
			</a>
			<div class="clearfix"></div>
			<a href="/p/entwined-diamond-tilted-heart-knot-pendant-sp1128d?icid=knottyheartpage|knotty-heart-pendant|sp1128d|02152017"  style="font-weight:300">
				Entwined Diamond Tilted Heart Knot Pendant
			</a>
			<div class="clearfix"></div>
			<span class="apricot-text"   style="font-weight:500">
				From $719
			</span>
		</div>
		
		<div class="col-sm-4 col-md-3 text-center">
			<a href="/p/round-diamond-interlocking-heart-dangle-pendant-sp1124d?icid=knottyheartpage|knotty-heart-pendant|sp1124d|02152017">
				<img style="max-width:60%" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/knotty-heart/products/sp1124d.jpg" alt="Round Diamond Interlocking Heart Dangle Pendant" title="Round Diamond Interlocking Heart Dangle Pendant">
			</a>
			<div class="clearfix"></div>
			<a href="/p/round-diamond-interlocking-heart-dangle-pendant-sp1124d?icid=knottyheartpage|knotty-heart-pendant|sp1124d|02152017"  style="font-weight:300">
				Round Diamond Interlocking Heart Dangle Pendant
			</a>
			<div class="clearfix"></div>
			<span class="apricot-text"   style="font-weight:500">
				From $749
			</span>
		</div>
		<div class="col-sm-4 col-md-3 text-center">
			<a href="/p/prong-set-diamond-concentric-heart-pendant-sp1125d?icid=knottyheartpage|knotty-heart-pendant|sp1125d|02152017">
				<img style="max-width:60%" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/knotty-heart/products/sp1125d.jpg" alt="Prong-Set Diamond Concentric Heart Pendant" title="Prong-Set Diamond Concentric Heart Pendant">
			</a>
			<div class="clearfix"></div>
			<a href="/p/prong-set-diamond-concentric-heart-pendant-sp1125d?icid=knottyheartpage|knotty-heart-pendant|sp1125d|02152017"  style="font-weight:300">
				Prong-Set Diamond Concentric Heart Pendant
			</a>
			<div class="clearfix"></div>
			<span class="apricot-text"   style="font-weight:500">
				From $879
			</span>
		</div>
		<div class="col-sm-4 col-md-3 text-center">
			<a href="/p/entwined-diamond-ribbon-heart-pendant-sp1126d?icid=knottyheartpage|knotty-heart-pendant|sp1126d|02152017">
				<img style="max-width:60%" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/knotty-heart/products/sp1126d.jpg" alt="Entwined Diamond Ribbon Heart Pendant" title="Entwined Diamond Ribbon Heart Pendant">
			</a>
			<div class="clearfix"></div>
			<a href="/p/entwined-diamond-ribbon-heart-pendant-sp1126d?icid=knottyheartpage|knotty-heart-pendant|sp1126d|02152017"  style="font-weight:300">
				Entwined Diamond Ribbon Heart Pendant
			</a>
			<div class="clearfix"></div>
			<span class="apricot-text"   style="font-weight:500">
				From $729
			</span>
		</div>
		<div class="col-sm-4 col-md-3 text-center">
			<a href="/p/prong-set-diamond-interlocking-twin-heart-pendant-sp1127d?icid=knottyheartpage|knotty-heart-pendant|sp1127d|02152017">
				<img style="max-width:60%" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/knotty-heart/products/sp1127d.jpg" alt="Prong-Set Diamond Interlocking Twin Heart Pendant" title="Prong-Set Diamond Interlocking Twin Heart Pendant">
			</a>
			<div class="clearfix"></div>
			<a href="/p/prong-set-diamond-interlocking-twin-heart-pendant-sp1127d?icid=knottyheartpage|knotty-heart-pendant|sp1127d|02152017"  style="font-weight:300">
				Prong-Set Diamond Interlocking Twin Heart Pendant
			</a>
			<div class="clearfix"></div>
			<span class="apricot-text"   style="font-weight:500">
				From $729
			</span>
		</div>
		
	</div>
</div>

<div class="video-popup hidden">
	<div class="relative-placeholder vholder">
		<div class="popup-close"></div>
		<video id="video" width="100%" controls>
		  <source src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/video/knoty-hearts.mp4" type="video/mp4">
		  Your browser does not support HTML5 video.
		</video>
		
	</div>
</div>

<script language="javascript">
jQuery(function(){
	
	var video = jQuery('#video').get(0);

	jQuery('.play').click(function(){
		var winheight = jQuery(window).height();
		var videoheight = jQuery('.vholder').height();
		var toppadding = (winheight-videoheight)/3;
		jQuery(".video-popup").removeClass('hidden').find('.vholder').css({'padding-top': toppadding+'px'});
		jQuery('body').css({'overflow-y':'hidden'});
		video.play();
	});
	 jQuery('.video-popup').on('click', function(ev) {
		if(ev.target.id != 'video'){
			jQuery('.vholder').css({'padding-top': '0px'});
			jQuery(this).addClass('hidden');
			jQuery('body').css({'overflow-y':'auto'});
			video.pause();
		}
	});
	
});
</script>