<div class="education-main-banner relative-placeholder max-margin-bottom max-padding-bottom"> <img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/pearl/education-main-banner.jpg" alt="">
		<div class="absolute-placeholder banner-txt">
			<h1>All About Pearls</h1>
			<p>Nature’s Exquisite Beauty</p>
		</div>
</div>
<div class="clearfix"></div>
<section class="container">
		 <div class="full-width">
            <img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/pearl/symbolism-mob.jpg" alt="">
        </div>
        <div class="full-width bg-one max-margin-bottom">
            <div class="details-box text-center max-padding-bottom max-padding-top">
                <h1>Symbolism</h1>
                <p>Treasured for thousands of years,
                    <br/>pearls symbolize perfection, purity,
                    <br/>and innocence.</p>
                <a href="/cultured-pearls/all-about-pearls#Symbolism">Learn More</a>
            </div>
        </div>
    <div class="clearfix"></div>
		<div class="full-width">
            <img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/pearl/pearl-types.jpg" alt="">
        </div>
		 <div class="full-width bg-one max-margin-bottom">
            <div class="details-box text-center max-padding-bottom max-padding-top">
                <h1>Pearl Types</h1>
                <p>The different types of cultured pearls
                    <br/>available include Akoya, Freshwater,
                    <br/> South Sea, and Tahitian pearls.</p>
                <a href="/cultured-pearls/all-about-pearls#PearlTypes">Learn More</a>
            </div>
        </div>
    <div class="clearfix"></div>
		<div class="full-width">
            <img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/pearl/quality-grading.jpg" alt="">
        </div>
        <div class="full-width bg-one max-margin-bottom">
            <div class="details-box text-center max-padding-bottom hm">
                <h1>Quality & Grading</h1>
                <p>Pearls are graded on the basis of several
                    <br/> quality factors such as luster, nacre,
                    <br/>surface, shape, color, and size.</p>
                <a href="/cultured-pearls/all-about-pearls#QualityGrading">Learn More</a> 
            </div>
        </div>
    <div class="clearfix"></div>
		<div class="full-width max-margin-top max-padding-top">
            <img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/pearl/identifing-pearls.jpg" alt="">
        </div>
        <div class="full-width">
            <div class="details-box text-center max-padding-bottom hm">
                <h1>Identifying Pearls</h1>
                <p>Real pearls are rarely perfect and come with minor surface ridges. They also have a lustrous overtone.</p>
                <a href="/cultured-pearls/all-about-pearls#IdentifyingPearls">Learn More</a>
            </div>
        </div>
    <div class="clearfix"></div>
		<div class="full-width">
            <img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/pearl/care-instrucations.jpg" alt="">
        </div>
        <div class="full-width bg-one max-margin-bottom">
            <div class="details-box text-center max-padding-bottom max-padding-top">
                <h1>Care Instructions</h1>
                <p>Delicate and exceptionally sensitive,
                    <br/>pearls require special care.</p>
                <a href="/cultured-pearls/all-about-pearls#CareInstructions">Learn More</a>
            </div>
        </div>
    <div class="clearfix"></div>
	<!--<div class="go2top">
		<a href="javascript:void(0)" data-go-to="#come2top">top</a>
	</div> -->
</section>

<script language="javascript">
jQuery(function(){
	jQuery('.tab li a, .go2top a').click(function(){
		var id = jQuery(this).attr('data-go-to');
		var headerHeight = jQuery("#main-head-inner").height();
		if(jQuery(window).width() >= 768){
			jQuery('html, body').animate({
				scrollTop: jQuery(id).offset().top - headerHeight
			}, 500);
		}else{
			jQuery('html, body').animate({
				scrollTop: jQuery(id).offset().top - 55
			}, 500);
		}
	});
});
</script>