<style>
@media (max-width:767px) {
	body{margin-bottom:30px;}
}
@media (min-width: 999px) {
	.col-md-offset-1 {margin-left: 15.33333%;} 
}
</style>
<section class="container valentine-top20">
	<div class="ruby-top20-head">
		<div class="banner-text col-md-4 col-md-offset-1">
		<h1> Top 20 Ruby Jewelry</h1> <p>Our Top 20 consists of rings, earrings and pendants in timeless designs. Brilliant red rubies accentuate the beauty of these designs that our customers have found hard to resist. The choice in stone quality, metal type and total carat weight makes it easy for you to select a piece that suits your requirements.</p>
		</div>
	</div>
	<div class="clearfix"></div>
<div class="row item">
	<div class="col-md-2 col-sm-2 fore1"><div class="num hidden-xs"> 1 </div> </div>
	<div class="col-md-4 col-sm-4 fore2">
		<a href="/p/round-ruby-solitaire-pendant-sp0108r?icid=top20|rubyjewel|sp0108r|07052016"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/angara-place-holder.jpg" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/ruby/top-1.jpg" width="200" height="200" alt="Prong Set Round Ruby Solitaire Pendant" title="Prong Set Round Ruby Solitaire Pendant"/></a></div>
	<div class="col-md-6 col-sm-6 fore3">
		<h2><a href="/p/round-ruby-solitaire-pendant-sp0108r?icid=top20|rubyjewel|sp0108r|07052016" class="text-uppercase">Prong Set Round Ruby Solitaire Pendant</a></h2>
		<p>Dangling from a single bale is a fiery red ruby mounted in a prong setting. This ruby pendant has a simple design with all the attention drawn towards the precious red gemstone. Gift this ruby solitaire pendant on a special occasion for assured smiles.</p>
		<p class="starting-at"><span class="text-md">$149 - $3,779</span></p>
		<div class="vw-collection"><a href="/p/round-ruby-solitaire-pendant-sp0108r?icid=top20|rubyjewel|sp0108r|07052016">SHOP NOW</a></div>
	</div>
</div>
<div class="clearfix"></div>
<div class="row item">
	<div class="col-md-2 col-sm-2 fore1"><div class="num hidden-xs">2</div></div>
	<div class="col-md-4 col-sm-4 fore2"><a href="/p/round-ruby-studs-in-14k-yellow-gold-se0102r?icid=top20|rubyjewel|se0102r|07052016"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/angara-place-holder.jpg" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/ruby/top-2.jpg" width="200" height="200" alt="Basket Set Ruby Stud Earrings" title="Basket Set Ruby Stud Earrings"/></a></div>
	<div class="col-md-6 col-sm-6 fore3">
		<h2><a href="/p/round-ruby-studs-in-14k-yellow-gold-se0102r?icid=top20|rubyjewel|se0102r|07052016" class="text-uppercase">Basket Set Ruby Stud Earrings</a></h2>
		<p>The beauty of these ruby stud earrings is in their minimalist design and striking red hue. Held in a basket setting these round ruby stud earrings are a picture of understated elegance and can make a great addition to your daily ensemble.</p>
		<p class="starting-at"> <span class="text-md">$219 - $6,769</span></p>
		<div class="vw-collection"><a href="/p/round-ruby-studs-in-14k-yellow-gold-se0102r?icid=top20|rubyjewel|se0102r|07052016">SHOP NOW</a></div>
	</div>
</div>
<div class="clearfix"></div>
<div class="row item">
	<div class="col-md-2 col-sm-2 fore1"><div class="num hidden-xs">3</div></div>
	<div class="col-md-4 col-sm-4 fore2"><a href="/p/round-ruby-martini-earrings-in-14k-white-gold-se0125r?icid=top20|rubyjewel|se0125r|07052016"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/angara-place-holder.jpg" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/ruby/top-3.jpg" width="200" height="200" alt="3 Prong Martini Setting Ruby Stud Earrings" title="3 Prong Martini Setting Ruby Stud Earrings"/></a></div>
	<div class="col-md-6 col-sm-6 fore3">
		<h2  ><a href="/p/round-ruby-martini-earrings-in-14k-white-gold-se0125r?icid=top20|rubyjewel|se0125r|07052016" class="text-uppercase">3 Prong Martini Setting Ruby Stud Earrings</a></h2>
		<p>These ruby stud earrings resemble fresh red blossoms. Cut and faceted to perfection, the brilliant red gemstones are secured in a three-prong martini setting for a delicate and elegant appeal. Crafted with ingenuity, this pair of martini stud earrings makes for an amazing jewelry gift or daily wear accessory.</p> <p class="starting-at"> <span class="text-md">$339 - $6,789</span></p>
		<div class="vw-collection"><a href="/p/round-ruby-martini-earrings-in-14k-white-gold-se0125r?icid=top20|rubyjewel|se0125r|07052016">SHOP NOW</a></div>
	</div>
</div>
<div class="clearfix"></div>
<div class="row item">
	<div class="col-md-2 col-sm-2 fore1"><div class="num hidden-xs">4</div></div>
	<div class="col-md-4 col-sm-4 fore2"><a href="/p/pear-ruby-and-diamond-v-bale-pendant-sp0169r?icid=top20|rubyjewel|sp0169r|07052016"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/angara-place-holder.jpg" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/ruby/top-4.jpg" width="200" height="200" alt="Pear Ruby Teardrop Pendant Necklace with Diamond" title="Pear Ruby Teardrop Pendant Necklace with Diamond"/></a></div>
	<div class="col-md-6 col-sm-6 fore3">
		<h2><a href="/p/pear-ruby-and-diamond-v-bale-pendant-sp0169r?icid=top20|rubyjewel|sp0169r|07052016" class="text-uppercase">Pear Ruby Teardrop Pendant Necklace with Diamond</a></h2>
		<p>The dainty teardrop ruby solitaire hangs from a V bale. For enhanced appeal an accent diamond is placed between the bale and the sparkling red gemstone in this teardrop ruby pendant necklace. Sculpted to perfection, this ruby and diamond pendant is a gorgeous piece of jewelry that's just perfect for a gift or a personal indulgence.</p>
		<p class="starting-at"> <span class="text-md">$199 - $10,819</span></p>
		<div class="vw-collection"><a href="/p/pear-ruby-and-diamond-v-bale-pendant-sp0169r?icid=top20|rubyjewel|sp0169r|07052016">SHOP NOW</a></div>
	</div>
</div>
<div class="clearfix"></div>
<div class="row item">
	<div class="col-md-2 col-sm-2 fore1"><div class="num hidden-xs">5</div></div>
	<div class="col-md-4 col-sm-4 fore2"><a href="/p/round-ruby-and-diamond-seven-stone-ring-sr0118rd?icid=top20|rubyjewel|sr0118rd|07052016"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/angara-place-holder.jpg" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/ruby/top-5.jpg" width="200" height="200" alt="Diamond & Ruby Half Eternity Ring" title="Diamond & Ruby Half Eternity Ring"/></a></div>
	<div class="col-md-6 col-sm-6 fore3">
		<h2><a href="/p/round-ruby-and-diamond-seven-stone-ring-sr0118rd?icid=top20|rubyjewel|sr0118rd|07052016" class="text-uppercase">Diamond & Ruby Half Eternity Ring</a></h2>
		<p>This gorgeous ruby ring evokes a graceful exuberance that will completely mesmerize you. Four round rubies and three brilliant diamonds are set to perfection in prongs in this ruby and diamond half eternity ring. Perfect for occasions like weddings or anniversaries this is a ring that's sure to make a woman happy.</p>
		<p class="starting-at"> <span class="text-md">$219 - $1,889</span></p>
		<div class="vw-collection"><a href="/p/round-ruby-and-diamond-seven-stone-ring-sr0118rd?icid=top20|rubyjewel|sr0118rd|07052016">SHOP NOW</a></div>
	</div>
</div>
<div class="clearfix"></div>
<div class="row item">
	<div class="col-md-2 col-sm-2 fore1"><div class="num hidden-xs">6</div></div>
	<div class="col-md-4 col-sm-4 fore2"><a href="/p/round-ruby-and-diamond-v-bale-pendant-sp0155r?icid=top20|rubyjewel|sp0155r|07052016"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/angara-place-holder.jpg" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/ruby/top-6.jpg" width="200" height="200" alt="V Bale Ruby Solitaire Pendant with Diamond" title="V Bale Ruby Solitaire Pendant with Diamond"/></a></div>
	<div class="col-md-6 col-sm-6 fore3">
		<h2><a href="/p/round-ruby-and-diamond-v-bale-pendant-sp0155r?icid=top20|rubyjewel|sp0155r|07052016" class="text-uppercase">V Bale Ruby Solitaire Pendant with Diamond</a></h2>
		<p>Featuring a round ruby suspended from a V bale, this simple ruby solitaire pendant personifies sophisticated charm. A prong set diamond sits pretty on the ruby and enhances its elegance. This ruby and diamond pendant is a classic piece of jewelry that can be a woman's constant companion.</p>
		<p class="starting-at"> <span class="text-md">$169 - $3,879</span></p>
		<div class="vw-collection"><a href="/p/round-ruby-and-diamond-v-bale-pendant-sp0155r?icid=top20|rubyjewel|sp0155r|07052016">SHOP NOW</a></div>
	</div>
</div>
<div class="clearfix"></div>
<div class="row item">
	<div class="col-md-2 col-sm-2 fore1"><div class="num hidden-xs">7</div></div>
	<div class="col-md-4 col-sm-4 fore2"><a href="/p/square-ruby-studs-in-14k-white-gold-se0105r?icid=top20|rubyjewel|se0105r|07052016"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/angara-place-holder.jpg" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/ruby/top-7.jpg" width="200" height="200" alt="Classic Basket Set Square Ruby Stud Earrings" title="Classic Basket Set Square Ruby Stud Earrings"/></a></div>
	<div class="col-md-6 col-sm-6 fore3">
		<h2><a href="/p/square-ruby-studs-in-14k-white-gold-se0105r?icid=top20|rubyjewel|se0105r|07052016" class="text-uppercase">Classic Basket Set Square Ruby Stud Earrings</a></h2>
		<p>Ruby studs look stylish and are convenient to wear everyday. Featuring square cut rubies mounted on a basket setting, these ruby solitaire earrings are must-have in every woman's jewelry wardrobe. These stunning square ruby stud earrings make for the perfect gift for graduation, birthdays or anniversaries.</p> 
		<p class="starting-at"> <span class="text-md">$299 - $1,529</span></p>
		<div class="vw-collection"><a href="/p/square-ruby-studs-in-14k-white-gold-se0105r?icid=top20|rubyjewel|se0105r|07052016">SHOP NOW</a></div>
	</div>
</div>
<div class="clearfix"></div>
<div class="row item">
	<div class="col-md-2 col-sm-2 fore1"><div class="num hidden-xs">8</div></div>
	<div class="col-md-4 col-sm-4 fore2"><a href="/p/oval-ruby-and-round-diamond-v-bale-pendant-sp0519r?icid=top20|rubyjewel|sp0519r|07052016"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/angara-place-holder.jpg" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/ruby/top-8.jpg" width="200" height="200" alt="Oval Ruby Solitaire Pendant with Trio Diamond" title="Oval Ruby Solitaire Pendant with Trio Diamond"/></a></div>
	<div class="col-md-6 col-sm-6 fore3">
		<h2><a href="/p/oval-ruby-and-round-diamond-v-bale-pendant-sp0519r?icid=top20|rubyjewel|sp0519r|07052016" class="text-uppercase">Oval Ruby Solitaire Pendant with Trio Diamond</a></h2>
		<p>This ethereal ruby solitaire pendant makes a luxurious style statement. A glimmering oval ruby is accentuated with three round diamonds. These diamonds look like a splendid cluster between the V bale and the gemstone. You can be sure to make a lasting impression with this ruby drop pendant. </p>
		<p class="starting-at"> <span class="text-md">$149 - $3,189</span></p>
		<div class="vw-collection"><a href="/p/oval-ruby-and-round-diamond-v-bale-pendant-sp0519r?icid=top20|rubyjewel|sp0519r|07052016">SHOP NOW</a></div>
	</div>
</div>
<div class="clearfix"></div>
<div class="row item">
	<div class="col-md-2 col-sm-2 fore1"><div class="num hidden-xs">9</div></div>
	<div class="col-md-4 col-sm-4 fore2"><a href="/p/round-ruby-and-diamond-five-stone-ring-sr0101rd?icid=top20|rubyjewel|sr0101rd|07052016"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/angara-place-holder.jpg" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/ruby/top-9.jpg" width="200" height="200" alt="Half Eternity Five Stone Ruby and Diamond Ring" title="Half Eternity Five Stone Ruby and Diamond Ring"/></a></div>
	<div class="col-md-6 col-sm-6 fore3">
		<h2><a href="/p/round-ruby-and-diamond-five-stone-ring-sr0101rd?icid=top20|rubyjewel|sr0101rd|07052016" class="text-uppercase">Half Eternity Five Stone Ruby and Diamond Ring</a></h2>
		<p>This ruby and diamond ring is a gorgeous combination of bold red and dazzling white stones. Beautifully studded in prongs are three rubies and two diamonds that look feminine and elegant. The splendid gemstones are arranged in a half-eternity style and perfectly complement the lustrous gold band. This five stone ruby ring is sure to dazzle everyone.</p>
		<p class="starting-at"> <span class="text-md">$319 - $2,739</span></p>
		<div class="vw-collection"><a href="/p/round-ruby-and-diamond-five-stone-ring-sr0101rd?icid=top20|rubyjewel|sr0101rd|07052016">SHOP NOW</a></div>
	</div>
</div>
<div class="clearfix"></div>
<div class="row item">
	<div class="col-md-2 col-sm-2 fore1"><div class="num hidden-xs">10</div></div>
	<div class="col-md-4 col-sm-4 fore2"><a href="/p/heart-ruby-solitaire-pendant-sp0152r?icid=top20|rubyjewel|sp0152r|07052016"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/angara-place-holder.jpg" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/ruby/top-10.jpg" width="200" height="200" alt="Bezel Set Solitaire Heart Shaped Ruby Pendant" title="Bezel Set Solitaire Heart Shaped Ruby Pendant"/></a></div>
	<div class="col-md-6 col-sm-6 fore3">
		<h2><a href="/p/heart-ruby-solitaire-pendant-sp0152r?icid=top20|rubyjewel|sp0152r|07052016" class="text-uppercase">Bezel Set Solitaire Heart Shaped Ruby Pendant</a></h2>
		<p>This ruby solitaire pendant will steal your heart with its winsome red splendor. It is designed with a solitaire heart shaped ruby, secured in a bezel setting. The fire in the red heart ruby reflects your love and makes this ruby pendant necklace simply irresistible.</p>
		<p class="starting-at"> <span class="text-md">$369 - $3,519</span></p>
		<div class="vw-collection"><a href="/p/heart-ruby-solitaire-pendant-sp0152r?icid=top20|rubyjewel|sp0152r|07052016">SHOP NOW</a></div>
	</div>
</div>
<div class="clearfix"></div>
<div class="row item">
	<div class="col-md-2 col-sm-2 fore1"><div class="num hidden-xs">11</div></div>
	<div class="col-md-4 col-sm-4 fore2"><a href="/p/round-ruby-and-diamond-three-stone-ring-sr0160r?icid=top20|rubyjewel|sr0160r|07052016"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/angara-place-holder.jpg" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/ruby/top-11.jpg" width="200" height="200" alt="Classic Prong Set Ruby & Diamond Three Stone Ring" title="Classic Prong Set Ruby & Diamond Three Stone Ring"/></a></div>
	<div class="col-md-6 col-sm-6 fore3">
		<h2><a href="/p/round-ruby-and-diamond-three-stone-ring-sr0160r?icid=top20|rubyjewel|sr0160r|07052016" class="text-uppercase">Classic Prong Set Ruby & Diamond Three Stone Ring</a></h2>
		<p>Designed to cast a spell, this three-stone ruby and diamond ring exudes an aura of sophistication. A stunning round ruby is set between two equally alluring diamonds that add to the splendor of the center stone. Handcrafted to perfection, this ruby and diamond three stone ring is the perfect representation of your memorable past, exciting present and promising future.</p>
		<p class="starting-at"> <span class="text-md">$319 - $14,859</span></p>
		<div class="vw-collection"><a href="/p/round-ruby-and-diamond-three-stone-ring-sr0160r?icid=top20|rubyjewel|sr0160r|07052016">SHOP NOW</a></div>
	</div>
</div>
<div class="clearfix"></div>
<div class="row item">
	<div class="col-md-2 col-sm-2 fore1"><div class="num hidden-xs">12</div></div>
	<div class="col-md-4 col-sm-4 fore2"><a href="/p/oval-ruby-and-diamond-split-shank-ring-sr0112r?icid=top20|rubyjewel|sr0112r|07052016"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/angara-place-holder.jpg" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/ruby/top-12.jpg" width="200" height="200" alt="Split Shank Oval Ruby and Diamond Ring" title="Split Shank Oval Ruby and Diamond Ring"/></a></div>
	<div class="col-md-6 col-sm-6 fore3">
		<h2><a href="/p/oval-ruby-and-diamond-split-shank-ring-sr0112r?icid=top20|rubyjewel|sr0112r|07052016" class="text-uppercase">Split Shank Oval Ruby and Diamond Ring</a></h2>
		<p>Make a fashion forward statement with this beautifully crafted ruby and diamond ring. The oval ruby set in four prongs captivates the senses with its regal hue. Sparkling round accent diamonds add an extra dash of extravagance. The stylish split shank is designed to heighten the beauty of this ruby ring. It is a must-have accessory for women with a classic sense of style.</p> <p class="starting-at"> <span class="text-md">$239 - $8,209</span></p>
		<div class="vw-collection"><a href="/p/oval-ruby-and-diamond-split-shank-ring-sr0112r?icid=top20|rubyjewel|sr0112r|07052016">SHOP NOW</a></div>
	</div>
</div>
<div class="clearfix"></div>
<div class="row item">
	<div class="col-md-2 col-sm-2 fore1"><div class="num hidden-xs">13</div></div>
	<div class="col-md-4 col-sm-4 fore2"><a href="/p/oval-ruby-and-diamond-border-pendant-sp0149r-n?icid=top20|rubyjewel|sp0149r_n|07052016"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/angara-place-holder.jpg" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/ruby/top-13.jpg" width="200" height="200" alt="Vintage Inspired Diamond Halo Oval Ruby Pendant" title="Vintage Inspired Diamond Halo Oval Ruby Pendant"/></a></div>
	<div class="col-md-6 col-sm-6 fore3">
		<h2><a href="/p/oval-ruby-and-diamond-border-pendant-sp0149r-n?icid=top20|rubyjewel|sp0149r_n|07052016" class="text-uppercase">Vintage Inspired Diamond Halo Oval Ruby Pendant</a></h2>
		<p>This ruby and diamond pendant is a visual treat crafted with an oval ruby in the center. The round white diamonds decorate the V bale and the gorgeous red ruby in vintage style. This spectacular ruby halo pendant has 27 sparkling diamonds and ruby mounted in prong settings.</p>
		<p class="starting-at"> <span class="text-md">$609 - $8,469</span></p>
		<div class="vw-collection"><a href="/p/oval-ruby-and-diamond-border-pendant-sp0149r-n?icid=top20|rubyjewel|sp0149r_n|07052016">SHOP NOW</a></div>
	</div>
</div>
<div class="clearfix"></div>
<div class="row item">
	<div class="col-md-2 col-sm-2 fore1"><div class="num hidden-xs">14</div></div>
	<div class="col-md-4 col-sm-4 fore2"><a href="/p/ruby-encrusted-love-knot-heart-pendant-sp0664r?icid=top20|rubyjewel|sp0664r|07052016"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/angara-place-holder.jpg" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/ruby/top-14.jpg" width="200" height="200" alt="Ruby Studded Infinity Knot Pendant with Puffed Heart" title="Ruby Studded Infinity Knot Pendant with Puffed Heart"/></a></div>
	<div class="col-md-6 col-sm-6 fore3">
		<h2><a href="/p/ruby-encrusted-love-knot-heart-pendant-sp0664r?icid=top20|rubyjewel|sp0664r|07052016" class="text-uppercase">Ruby Studded Infinity Knot Pendant with Puffed Heart</a></h2>
		<p>A glistening puffed heart entwined in an infinity knot studded with bright red rubies is hard to miss. This infinity knot pendant will make a precious and intimate gift for your beloved. It features a beautiful design with the intricate infinity knot and the heart crafted to delight. The prong set rubies are eye-catching and offer a romantic appeal to the classic infinity love knot pendant.</p>
		<p class="starting-at"> <span class="text-md">$489 - $1,209</span></p>
		<div class="vw-collection"><a href="/p/ruby-encrusted-love-knot-heart-pendant-sp0664r?icid=top20|rubyjewel|sp0664r|07052016">SHOP NOW</a></div>
	</div>
</div>
<div class="clearfix"></div>
<div class="row item">
	<div class="col-md-2 col-sm-2 fore1"><div class="num hidden-xs">15</div></div>
	<div class="col-md-4 col-sm-4 fore2"><a href="/p/oval-ruby-and-diamond-split-shank-ring-sr0354r?icid=top20|rubyjewel|sr0354r|07052016"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/angara-place-holder.jpg" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/ruby/top-15.jpg" width="200" height="200" alt="Split Shank Oval Ruby and Diamond Halo Ring" title="Split Shank Oval Ruby and Diamond Halo Ring"/></a></div>
	<div class="col-md-6 col-sm-6 fore3">
		<h2><a href="/p/oval-ruby-and-diamond-split-shank-ring-sr0354r?icid=top20|rubyjewel|sr0354r|07052016" class="text-uppercase">Split Shank Oval Ruby and Diamond Halo Ring</a></h2>
		<p>This striking halo ruby ring is the perfect blend of style and sparkle. A fiery red oval ruby is prong set at the centre of a sparkling halo of diamonds. Intricate detailing on the gallery and diamond accents on the split shank add charm to the luxurious design of this ruby and diamond ring. Perfect for adding a hint of color to your day and evening outfits.</p> <p class="starting-at"> <span class="text-md">$819 - $9,139</span></p>
		<div class="vw-collection"><a href="/p/oval-ruby-and-diamond-split-shank-ring-sr0354r?icid=top20|rubyjewel|sr0354r|07052016">SHOP NOW</a></div>
	</div>
</div>
<div class="clearfix"></div>
<div class="row item">
	<div class="col-md-2 col-sm-2 fore1"><div class="num hidden-xs">16</div></div>
	<div class="col-md-4 col-sm-4 fore2"><a href="/p/round-ruby-bezel-set-pendant-sp0159r?icid=top20|rubyjewel|sp0159r|07052016"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/angara-place-holder.jpg" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/ruby/top-16.jpg" width="200" height="200" alt="Bezel Set Round Ruby Solitaire Pendant" title="Bezel Set Round Ruby Solitaire Pendant"/></a></div>
	<div class="col-md-6 col-sm-6 fore3">
		<h2><a href="/p/round-ruby-bezel-set-pendant-sp0159r?icid=top20|rubyjewel|sp0159r|07052016" class="text-uppercase">Bezel Set Round Ruby Solitaire Pendant</a></h2>
		<p>This simple and versatile ruby pendant is designed with a glowing red ruby that is secured in a bezel setting. The elegant design is a unique combination of simplicity and bold style that makes it one-of-a-kind.</p> <p class="starting-at"> <span class="text-md">$329 - $3,929</span></p>
		<div class="vw-collection"><a href="/p/round-ruby-bezel-set-pendant-sp0159r?icid=top20|rubyjewel|sp0159r|07052016">SHOP NOW</a></div>
	</div>
</div>
<div class="clearfix"></div>
<div class="row item">
	<div class="col-md-2 col-sm-2 fore1"><div class="num hidden-xs">17</div></div>
	<div class="col-md-4 col-sm-4 fore2"><a href="/p/round-ruby-and-diamond-crossover-ring-sr0256r?icid=top20|rubyjewel|sr0256r|07052016"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/angara-place-holder.jpg" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/ruby/top-17.jpg" width="200" height="200" alt="Round Ruby and Diamond Crossover Ring" title="Round Ruby and Diamond Crossover Ring"/></a></div>
	<div class="col-md-6 col-sm-6 fore3">
		<h2><a href="/p/round-ruby-and-diamond-crossover-ring-sr0256r?icid=top20|rubyjewel|sr0256r|07052016" class="text-uppercase">Round Ruby and Diamond Crossover Ring</a></h2>
		<p>This exquisite ruby crossover ring features a design that is both unique and appealing. The crossover band holds four round rubies and three round diamonds in prongs. The perfectly matched rubies and diamonds are set alternately on the shank. Birthdays, anniversaries or just any occasion to express love, this ring is the perfect choice for a gift.</p> <p class="starting-at"> <span class="text-md">$459 - $1,109</span></p>
		<div class="vw-collection"><a href="/p/round-ruby-and-diamond-crossover-ring-sr0256r?icid=top20|rubyjewel|sr0256r|07052016">SHOP NOW</a></div>
	</div>
</div>
<div class="clearfix"></div>
<div class="row item">
	<div class="col-md-2 col-sm-2 fore1"><div class="num hidden-xs">18</div></div>
	<div class="col-md-4 col-sm-4 fore2"><a href="/p/round-ruby-three-stone-ring-sr0226r?icid=top20|rubyjewel|sr0226r|07052016"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/angara-place-holder.jpg" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/ruby/top-18.jpg" width="200" height="200" alt="Classic Prong Set Ruby Three Stone Ring" title="Classic Prong Set Ruby Three Stone Ring"/></a></div>
	<div class="col-md-6 col-sm-6 fore3">
		<h2><a href="/p/round-ruby-three-stone-ring-sr0226r?icid=top20|rubyjewel|sr0226r|07052016" class="text-uppercase">Classic Prong Set Ruby Three Stone Ring</a></h2>
		<p>This gorgeous three stone ruby ring is the perfect combination of elegance and luxuriousness. A bright red ruby at the center is flanked by two more equally stunning rubies on the sides to create a visual treat of pure red brilliance. Designed with a cathedral style shank, this three stone ruby ring exudes a distinctive style and charm.</p> 
		<p class="starting-at"> <span class="text-md">$309 - $4,859</span></p>
		<div class="vw-collection"><a href="/p/round-ruby-three-stone-ring-sr0226r?icid=top20|rubyjewel|sr0226r|07052016">SHOP NOW</a></div>
	</div>
</div>
<div class="clearfix"></div>
<div class="row item">
	<div class="col-md-2 col-sm-2 fore1"><div class="num hidden-xs">19</div></div>
	<div class="col-md-4 col-sm-4 fore2"><a href="/p/oval-ruby-and-diamond-ring-sr0169r?icid=top20|rubyjewel|sr0169r|07052016"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/angara-place-holder.jpg" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/ruby/top-19.jpg" width="200" height="200" alt="Princess Diana Inspired Ruby Ring with Diamond Halo" title="Princess Diana Inspired Ruby Ring with Diamond Halo"/></a></div>
	<div class="col-md-6 col-sm-6 fore3">
		<h2><a href="/p/oval-ruby-and-diamond-ring-sr0169r?icid=top20|rubyjewel|sr0169r|07052016" class="text-uppercase">Princess Diana Inspired Ruby Ring with Diamond Halo</a></h2>
		<p>Inspired by princess Diana’s unrivalled style statement, the princess Diana ruby ring features a radiant oval ruby that sits majestically at the core of a dazzling diamond halo. Designed to create a simple and majestic floral design, this ruby and diamond ring is a symbol of glamour and elegance.</p> <p class="starting-at"> <span class="text-md">$599 - $8,659</span></p>
		<div class="vw-collection"><a href="/p/oval-ruby-and-diamond-ring-sr0169r?icid=top20|rubyjewel|sr0169r|07052016">SHOP NOW</a></div>
	</div>
</div>
<div class="clearfix"></div>
<div class="row item last">
	<div class="col-md-2 col-sm-2 fore1"><div class="num hidden-xs">20</div></div>
	<div class="col-md-4 col-sm-4 fore2"><a href="/p/ruby-encrusted-infinity-knot-ring-sr0808r?icid=top20|rubyjewel|sr0808r|07052016"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/angara-place-holder.jpg" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/ruby/top-20.jpg" width="200" height="200" alt="Encrusted Ruby Infinity Love Knot Ring" title="Encrusted Ruby Infinity Love Knot Ring"/></a></div>
	<div class="col-md-6 col-sm-6 fore3">
		<h2><a href="/p/ruby-encrusted-infinity-knot-ring-sr0808r?icid=top20|rubyjewel|sr0808r|07052016" class="text-uppercase">Encrusted Ruby Infinity Love Knot Ring</a></h2>
		<p>Crafted to perfection, this infinity knot ring is designed to speak of everlasting love. Gold loops intertwine to make this beautiful love knot. 22 striking rubies adorn one of the loops and strike the perfect combination with the glowing yellow gold. Great choice to express love and commitment, this ring says it all.</p> <p class="starting-at"> <span class="text-md">$599 - $1,379</span></p>
		<div class="vw-collection"><a href="/p/ruby-encrusted-infinity-knot-ring-sr0808r?icid=top20|rubyjewel|sr0808r|07052016">SHOP NOW</a></div>
	</div>
</div>
</section>



<?php //To show offer box ?>
<?php 
$offerText		=	Mage::helper('function')->getOfferText();
$offerData 		= 	$this->getLayout()->createBlock('promotions/offer')->getOfferHeaderImage();
$image_path		=	$offerData['image_path'];
$image_title	=	$offerData['image_title'];
$image_alt_text	=	$offerData['image_alt_text']; 
?>
<div class="clickable" id="exclusive-offer-footer-opener" style="position:fixed; bottom:-1px; left:0px; right:0px; background:#ffffff; display:block!important;z-index:1;">		  	 
	<div class="offer-text-holder" style="font-size:14px;height:34px;line-height:34px;padding-left:5px;background:#fa505a; color:#ffffff;">
		<?php echo $offerText;?><span class="fr"><i style="font-size:20px;" class="fa fa-fw fa-angle-up"> </i></span>
	</div>
	<img src="<?php echo $image_path;?>" alt="<?php echo $image_alt_text;?>" title="<?php echo $image_title;?>" class="img-responsive" style="display:none; padding:0 25%;"/>
</div>
<script>
	jQuery(function(){
		jQuery('#exclusive-offer-footer-opener').click(function(){
			jQuery(this).find('img').slideToggle(100);
			jQuery('.fa-angle-up, .fa-angle-donw').toggleClass('.fa-angle-up .fa-angle-donw');
		});
	});
</script>
<?php //To show offer box ?>


