<?php
/**
 * @category    Inchoo
 * @package     Inchoo_Facebook
 * @author      Ivan Weiler <ivan.weiler@gmail.com>
 * @copyright   Inchoo (http://inchoo.net)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php /* ?>
<br />
<div class="account-login facebook-login">
  <div class="content new-users" style="min-height: 50px;">
    <h2><?php echo $this->__('Connect with Facebook') ?></h2>
  </div>
  <div class="buttons-set"> <a rel="facebook-connect" title="Connect with Facebook"> <img src="/skin/frontend/angara/default/images/fb_login-button.png" /> </a> </div>
</div>
<?php */ ?>
<?php
/*
<button rel="facebook-connect" type="button" title="<?php echo $this->__('Connect with Facebook') ?>" class="button">
	<span><span><?php echo $this->__('Connect with Facebook') ?></span></span>
</button>
*/
?>