<div class="landingcategory_list">
	<ul>
		<li><a href="/earrings.html" class="activetab"><span class="detailholder"><span class="categorydetails">All Earrings</span></span></a></li>
		<li><a href="/earrings/sapphire-earrings.html"><span class="detailholder"><span class="categorydetails">Sapphire Earrings</span></span></a></li>
		<li><a href="/earrings/ruby-earrings.html"><span class="detailholder"><span class="categorydetails">Ruby Earrings</span></span></a></li>
		<li><a href="/earrings/emerald-earrings.html"><span class="detailholder"><span class="categorydetails">Emerald Earrings</span></span></a></li>
		<li><a href="/earrings/tanzanite-earrings.html"><span class="detailholder"><span class="categorydetails">Tanzanite Earrings</span></span></a></li>
		<li><a href="/earrings/diamond-earrings.html"><span class="detailholder"><span class="categorydetails">Diamond Earrings</span></span></a></li>
		<li><a href="/birthstone-jewelry/june-birthstone-pearl-jewelry.html"><span class="detailholder"><span class="categorydetails">Pearl Earrings</span></span></a></li>
		<li><a href="/earrings/peridot-earrings.html"><span class="detailholder"><span class="categorydetails">Peridot Earrings</span></span></a></li>
		<li><a href="/earrings/citrine-earrings.html"><span class="detailholder"><span class="categorydetails">Citrine Earrings</span></span></a></li>
		<li><a href="/earrings/opal-earrings.html"><span class="detailholder"><span class="categorydetails">Opal Earrings</span></span></a></li>
		<li><a href="/earrings/garnet-earrings.html"><span class="detailholder"><span class="categorydetails">Garnet Earrings</span></span></a></li>
		<li><a href="/earrings/black-onyx-earrings.html"><span class="detailholder"><span class="categorydetails">Black Onyx Earrings</span></span></a></li>
		<li><a href="/earrings/amethyst-earrings.html"><span class="detailholder"><span class="categorydetails">Amethyst Earrings</span></span></a></li>
		<li><a href="/earrings/aquamarine-earrings.html"><span class="detailholder"><span class="categorydetails">Aquamarine Earrings</span></span></a></li>
		<li><a href="/earrings/colored-diamond-earrings.html"><span class="detailholder"><span class="categorydetails">Colored Diamond Earrings</span></span></a></li>
		<li><a href="/earrings/colored-diamond-earrings/enhanced-black-diamond.html"><span class="detailholder"><span class="categorydetails">Black Diamond Earrings</span></span></a></li>
		<li><a href="/earrings/colored-diamond-earrings/enhanced-blue-diamond.html"><span class="detailholder"><span class="categorydetails">Blue Diamond Earrings</span></span></a></li>
		<li><a href="/birthstone-jewelry/birthstone-earrings.html"><span class="detailholder"><span class="categorydetails">Birthstone Earrings</span></span></a></li>
		<?php /*?><li><a href="/mothers-jewelry/mothers-earrings.html"><span class="detailholder"><span class="categorydetails">Mother's Earrings</span></span></a></li><?php */?>
	</ul>
</div>