<div class="landingcategory_list">
	<ul>
		<li><a href="/jewelry-gifts.html" class="activetab"><span class="detailholder"><span class="categorydetails">All Jewelry Gifts</span></span></a></li>
		<li><a href="/jewelry-gifts/graduation-gifts.html"><span class="detailholder"><span class="categorydetails">Graduation Jewelry Gifts</span></span></a></li>
		<li><a href="/jewelry-gifts/anniversary-gifts.html"><span class="detailholder"><span class="categorydetails">Anniversary Jewelry Gifts</span></span></a></li>
		<li><a href="/jewelry-gifts/birthday-gifts.html"><span class="detailholder"><span class="categorydetails">Birthday Jewelry Gifts</span></span></a></li>
		<li><a href="/jewelry-gifts/christmas-gifts.html"><span class="detailholder"><span class="categorydetails">Christmas Jewelry Gifts</span></span></a></li>
		<li><a href="/jewelry-gifts/valentine-gifts.html"><span class="detailholder"><span class="categorydetails">Valentine Jewelry Gifts</span></span></a></li>
		<li><a href="/jewelry-gifts/st-patricks-gifts.html"><span class="detailholder"><span class="categorydetails">St. Patricks Jewelry Gifts</span></span></a></li>
		<li><a href="/jewelry-gifts/thanksgiving-gifts.html"><span class="detailholder"><span class="categorydetails">Thanks Giving Jewelry Gifts</span></span></a></li>
		<li><a href="/jewelry-gifts/sweet-16-gifts.html"><span class="detailholder"><span class="categorydetails">Sweet 16 Jewelry Gifts</span></span></a></li>
		<li><a href="/jewelry-gifts/baby-jewelry.html"><span class="detailholder"><span class="categorydetails">Baby Jewelry Gifts</span></span></a></li>
		<li><a href="/jewelry-gifts/prom-jewelry.html"><span class="detailholder"><span class="categorydetails">Prom Jewelry Gifts</span></span></a></li>
	</ul>
</div>