<div class="landingcategory_list">
	<ul>
		<li><a href="/pendants.html" class="activetab"><span class="detailholder"><span class="categorydetails">All Necklaces</span></span></a></li>
		<li><a href="/pendants/sapphire-necklace-pendants.html"><span class="detailholder"><span class="categorydetails">Sapphire Necklaces</span></span></a></li>
		<li><a href="/pendants/ruby-necklace-pendants.html"><span class="detailholder"><span class="categorydetails">Ruby Necklaces</span></span></a></li>
		<li><a href="/pendants/emerald-necklace-pendants.html"><span class="detailholder"><span class="categorydetails">Emerald Necklaces</span></span></a></li>
		<li><a href="/pendants/tanzanite-necklace-pendants.html"><span class="detailholder"><span class="categorydetails">Tanzanite Necklaces</span></span></a></li>
		<li><a href="/pendants/diamond-necklace-pendants.html"><span class="detailholder"><span class="categorydetails">Diamond Necklaces</span></span></a></li>
		<li><a href="/birthstone-jewelry/june-birthstone-pearl-jewelry.html"><span class="detailholder"><span class="categorydetails">Pearl Necklaces</span></span></a></li>
		<li><a href="/pendants/peridot-necklace-pendants.html"><span class="detailholder"><span class="categorydetails">Peridot Necklaces</span></span></a></li>
		<li><a href="/pendants/citrine-necklace-pendants.html"><span class="detailholder"><span class="categorydetails">Citrine Necklaces</span></span></a></li>
		<li><a href="/pendants/opal-necklace-pendants.html"><span class="detailholder"><span class="categorydetails">Opal Necklaces</span></span></a></li>
		<li><a href="/pendants/garnet-necklace-pendants.html"><span class="detailholder"><span class="categorydetails">Garnet Necklaces</span></span></a></li>
		<li><a href="/pendants/black-onyx-necklace-pendants.html"><span class="detailholder"><span class="categorydetails">Black Onyx Necklaces</span></span></a></li>
		<li><a href="/pendants/amethyst-necklace-pendants.html"><span class="detailholder"><span class="categorydetails">Amethyst Necklaces</span></span></a></li>
		<li><a href="/pendants/aquamarine-necklace-pendants.html"><span class="detailholder"><span class="categorydetails">Aquamarine Necklaces</span></span></a></li>
		<li><a href="/pendants/colored-diamond-necklace-pendants.html"><span class="detailholder"><span class="categorydetails">Colored Diamond Necklaces</span></span></a> </li>
		<li><a href="/pendants/colored-diamond-necklace-pendants/enhanced-black-diamond.html"><span class="detailholder"><span class="categorydetails">Black Diamond  Necklaces</span></span></a></li>
		<li><a href="/pendants/colored-diamond-necklace-pendants/enhanced-blue-diamond.html"><span class="detailholder"><span class="categorydetails">Blue Diamond Necklaces</span></span></a></li>
		<li><a href="/birthstone-jewelry/birthstone-necklace-pendants.html"><span class="detailholder"><span class="categorydetails">Birthstone Necklaces</span></span></a></li>
		<?php /*?><li><a href="/mothers-jewelry/mothers-necklace-pendants.html"><span class="detailholder"><span class="categorydetails">Mother's Necklaces</span></span></a></li><?php */?>
	</ul>
</div>