<div class="landingcategory_list">
	<ul>
		<li><a href="/rings.html" class="activetab"><span class="detailholder"><span class="categorydetails">All Rings</span></span></a></li>
		<li><a href="/rings/sapphire-rings.html"><span class="detailholder"><span class="categorydetails">Sapphire Rings</span></span></a></li>
		<?php /*?><li><a href="/rings/sapphire-rings/blue-sapphire.html"><span class="detailholder"><span class="categorydetails">Blue Sapphire Rings</span></span></a></li>
		<li><a href="/rings/sapphire-rings/pink-sapphire.html"><span class="detailholder"><span class="categorydetails">Pink Sapphire Rings</span></span></a></li><?php */?>
		<li><a href="/rings/ruby-rings.html"><span class="detailholder"><span class="categorydetails">Ruby Rings</span></span></a></li>
		<li><a href="/rings/emerald-rings.html"><span class="detailholder"><span class="categorydetails">Emerald Rings</span></span></a></li>
		<li><a href="/rings/tanzanite-rings.html"><span class="detailholder"><span class="categorydetails">Tanzanite Rings</span></span></a></li>
		<li><a href="/rings/diamond-rings.html"><span class="detailholder"><span class="categorydetails">Diamond Rings</span></span></a></li>
		<li><a href="/birthstone-jewelry/june-birthstone-pearl-jewelry.html"><span class="detailholder"><span class="categorydetails">Pearl Rings</span></span></a></li>
		<li><a href="/rings/peridot-rings.html"><span class="detailholder"><span class="categorydetails">Peridot Rings</span></span></a></li>
		<li><a href="/rings/citrine-rings.html"><span class="detailholder"><span class="categorydetails">Citrine Rings</span></span></a></li>
		<li><a href="/rings/opal-rings.html"><span class="detailholder"><span class="categorydetails">Opal Rings</span></span></a></li>
		<li><a href="/rings/garnet-rings.html"><span class="detailholder"><span class="categorydetails">Garnet Rings</span></span></a></li>
		<li><a href="/rings/black-onyx-rings.html"><span class="detailholder"><span class="categorydetails">Black Onyx Rings</span></span></a></li>
		<li><a href="/rings/amethyst-rings.html"><span class="detailholder"><span class="categorydetails">Amethyst Rings</span></span></a></li>
		<li><a href="/rings/aquamarine-rings.html"><span class="detailholder"><span class="categorydetails">Aquamarine Rings</span></span></a></li>
		<li><a href="/rings/colored-diamond-rings.html"><span class="detailholder"><span class="categorydetails">Colored Diamond Rings</span></span></a> </li>
		<li><a href="/rings/colored-diamond-rings/enhanced-black-diamond.html"><span class="detailholder"><span class="categorydetails">Black Diamond Rings</span></span></a></li>
		<li><a href="/rings/colored-diamond-rings/enhanced-blue-diamond.html"><span class="detailholder"><span class="categorydetails">Blue Diamond Rings</span></span></a></li>
		<li><a href="/birthstone-jewelry/birthstone-rings.html"><span class="detailholder"><span class="categorydetails">Birthstone Rings</span></span></a></li>
		<?php /*?><li><a href="/mothers-jewelry/mother-rings.html"><span class="detailholder"><span class="categorydetails">Mother's Rings</span></span></a></li><?php */?>
	</ul>
</div>
