<div class="social-media text-center max-margin-top">
    <i class="pinShare fa fa-pinterest-square px32 min-margin-right clickable" onclick="myPinFunction()" style="color:#C92228;"></i>									
    <i class="tweetShare fa fa-twitter-square px32 min-margin-right clickable" onclick="myTweetFunction()" style="color:#1dcaff;"></i>
    <i class="googleShare fa fa-google-plus-square px32 min-margin-right clickable" onclick="myGoogleFunction()" style="color:#d34836;"></i>						
    <i class="fbShare fa fa-facebook-square px32 min-margin-right clickable" onclick="myFbFunction()" style="color:#3B5998;"></i>
</div>