<?php 
if($crumbs && is_array($crumbs)): ?>
	<div id="breadcrumb" xmlns:v="http://rdf.data-vocabulary.org/#"><?php // Added by Vaseem for Google Rich Snippets?>
	<?php 
	foreach($crumbs as $_crumbName=>$_crumbInfo): 
		if($_crumbInfo['link']):?>
        	<?php // Added by Vaseem for Google Rich Snippets?>
			<a href="<?php echo $_crumbInfo['link'] ?>" title="<?php echo $this->htmlEscape($_crumbInfo['title']) ?>" typeof="v:Breadcrumb">		<?php // Added by Vaseem for Google Rich Snippets?>
				<span rel="v:url" property="v:title"><?php echo $this->htmlEscape($_crumbInfo['label']) ?></span></a>
		<?php 
		elseif($_crumbInfo['last']): ?>
        	<?php // Added by Vaseem for Google Rich Snippets?>
			<span class="last-item" rel="v:child" property="v:title">
				<?php echo $this->htmlEscape($_crumbInfo['label']) ?>
			</span>
		<?php 
		else: 
			echo $this->htmlEscape($_crumbInfo['label']); 
		endif;
		 
		if(!$_crumbInfo['last']): ?>
			<span class="divider-breadcrumb"> / </span>
		<?php 
		endif; ?>
	<?php 
	endforeach; ?>
	</div>
<?php 
endif; ?>