<style>
#mini-hero-showcase-xs{ height:53px;}
.close-nav-xs{ bottom:1px;}
</style>
<div id="content-showcase" class="container-fluid">
	<div class="container-fluid" style="background-color:#fffbef;">
        <div  class="visible-xs  showcase-border-bottom-1px">
            <img  src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/promotion/default/mini-hero-xs.jpg" class="center-block" style="width:320px;" />
        </div>
    </div>
	
	<?php /*?><div class="container relative-placeholder visible-xs">
        <div class="close-nav-xs clickable hidden" style="left:auto;" id="hide-mini-hero-banner-xs">
            <i class="fa fa-angle-up text-on-dark high-padding-left fontsize-type7"></i>
        </div>
    </div><?php */?>
</div>