<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<style>
.md-pro{ border: 1px solid #d9d9d9; box-shadow: 0px 0px 5px 0px #eeeeee; padding:0px; height: 1317px;}
.md-pro-title{background: #989898; color: #fff; text-align: center; padding: 15px 10px; text-transform: uppercase; font-weight: bold;}
#block-popular li .border-bottom-1px{}
#block-popular li{display:block; width: 100%; height: 253px; padding: 0px 5px;border-bottom:1px solid #efefef}
#block-popular li:last-child{border-bottom:none}
.md-price{margin-top:10px}
.price-extra-text-related { display:none !important; }

@media (min-width:768px) and (max-width:999px){
	.md-pro{height:983px;margin-bottom: 1px;}
	#block-popular li img{width:70%; height:auto;}
	#block-popular li{height: 234px;}
	#block-popular li:nth-last-child(2){border:none;}
	#block-popular li:last-child{display:none;}
}
@media(max-width:767px){
	.md-sp-pro{display:none}
}
</style>
<div class="col-md-3 col-sm-4 col-xs-6 max-margin-bottom md-sp-pro" style="float:right">
<div class="md-pro">
<div class="md-pro-title col-sm-12">
<?php echo $this->escapeHtml($this->getTitle());?>
</div>
<?php 
$_productCollection=$this->getLoadedProductCollection(); 
?>
<?php 
if($_productCollection->count()): ?> 
<?php $_iterator = 0; ?>
        <ol id="block-popular">
        <?php foreach($_productCollection as $_item): ?>
			<li>
                <div class="product high-margin-bottom high-padding-bottom border-bottom-1px">
                    <a href="<?php echo $_item->getProductUrl() ?>?icid=catalog|last-minute-delivery|05072015" title="<?php echo $this->htmlEscape($_item->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(166) ?>" width="166" height="166" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" class="center-block"  /></a>
                    <div>
                        <div class="fontsize-type2 text-center"><a href="<?php echo $_item->getProductUrl() ?>?icid=catalog|last-minute-delivery|05072015"><?php echo $this->htmlEscape($_item->getName()) ?></a></div>
                       <div class="text-center md-price"><?php echo $this->getPriceHtml($_item, true, '-related') ?></div>
                    </div>
                </div>
            </li>
			<?php $_iterator++; ?>
        <?php endforeach ?>
        </ol>
<?php endif; ?>
</div>
</div>