<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<div class="showcase-border-left-1px max-padding-left">
<?php 
$_productCollection=$this->getLoadedProductCollection(); 
//echo $this->getNumProducts();
?>
<?php 
if($_productCollection->count()): ?> 
<?php $_iterator = 0; ?>
        <ol id="block-popular">
        <?php foreach($_productCollection as $_item): ?>
            <?php
			if($_iterator >= $this->getNumProducts()){
				break;
			}
			?>
			<li>
                <div class="product high-margin-bottom high-padding-bottom showcase-dotted-border-bottom-1px">
                    <a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(166) ?>" width="166" height="166" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" class="center-block"  /></a>
                    <div>
                        <div class="fontsize-type2 text-center"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a></div>
                       <div class="text-center"><?php echo $this->getPriceHtml($_item, true, '-related') ?></div>
                    </div>
                </div>
            </li>
			<?php $_iterator++; ?>
        <?php endforeach ?>
        </ol>
<?php endif; ?>
</div>