<div class="container col-sm-12 showcase-bg-white max-padding-top max-padding-bottom"><?php if (Mage::helper('awrma')->checkExtensionVersion('Mage_Core', '0.8.25')) : ?>
    <div class="buttons-set">
        <p class="back-link"><a href="<?php echo $this->getBackLink() ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
    </div>
<?php else : ?>
    <div class="button-set">
        <a class="left" href="<?php echo $this->getBackLink() ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a>
    </div>
<?php endif ?>
</div>