<?php
/**
 * Product media data template
 *
 * @see Mage_Catalog_Block_Product_View_Media
 */
$product = $this->getProduct();
$freeProdSku = array(/*'fr','fb','fe',*/'fp');
$strLowerFreeProd = strtolower(substr($product->getSku(), 0, 2));
$helper  = $this->helper('catalog/output');
//$_imgSize = 450;

// Get the base image path
$baseImageFile = ($product->getImage() != 'no_selection' and $product->getImage()) ? $product->getImage() : false;
$galleryImages = array();
$video = $helper->productAttribute($product, $this->htmlEscape($product->getVideo()), 'video');

// Process the gallery images
foreach ($this->getGalleryImages() as $image) {
    if ($baseImageFile and $image->getFile() === $baseImageFile) {
        //only add images that aren't the baseImage
        continue;
    }
    $galleryImages[] = $image;
} ?>
<?php if($video != ''){ echo '<style>video{background-color:transparent!important}</style>'; } ?>
<div style="position:relative">
	<?php 
    if($baseImageFile){ ?>
        <div class="row">
            <div id="moreviews1" style="min-height:250px">
                <div class="slider-media">
					<?php 
					list($width, $height) = getimagesize($this->helper('catalog/image')->init($product, 'image'));?>
						<div class="img-1 pro-images hidden">
							<?php /* if( $width > 350 ) { ?>
								<span class="zoom-icon"><i class="fa fa-search-plus"></i></span>
							<?php } */ ?>
							<img itemprop="image" id="image" class="slider-image img-responsive" src="<?php echo $this->helper('catalog/image')->init($product, 'image');?>" alt="<?php echo $product->getShortDescription();?> - Angara.com" title="<?php echo $product->getShortDescription();?>" data-width="<?php echo $width;?>">
						</div>
					<?php 	
					$i = 2; 
					foreach($galleryImages as $image){ 
						list($width, $height) = getimagesize($this->helper('catalog/image')->init($product, 'image', $image->getFile()));
						if($i == 3){
							# @todo handle product video here				
							if($video != ''){
								echo $this->getChildHtml('videoupload');
							}
						}?>
						<div class="img-<?php echo $i; ?> pro-images hidden">
							<?php /* if( $width > 350 ) { ?>
								<span class="zoom-icon"><i class="fa fa-search-plus"></i></span>
							<?php } */ ?>
							<img itemprop="image" class="slider-image img-responsive" src="<?php echo $this->helper('catalog/image')->init($product, 'image', $image->getFile()); ?>" alt="<?php echo $this->htmlEscape($image->getLabel()); ?>"  title="<?php echo $this->htmlEscape($image->getLabel()); ?>" data-width="<?php echo $width;?>">
						</div>
						<?php
						$i++; 
					} ?>
                </div> 
            </div>          
            <script>
				jQuery(document).ready(function(){
					jQuery('.slider-media').slick({
						dots	: 	true,
						arrows	: 	true
					});
					jQuery('.slider-media').find('.pro-images, .provideo-holder').removeClass('hidden');	//	show the remaining slides after slider initialised
					jQuery('#moreviews1').removeAttr('style');
				});
				
				jQuery(document).on('touchend',function(e){
					if(e.target.closest('.slick-arrow') || e.target.closest('.slider-image')){
						moreViewClicked();
					}
				}); 
				
			</script>
			<?php 
			if($video != ''){?>
			<script> 
			var myVideo = document.getElementById("angvideo"),
			video = jQuery('#angvideo');
			
			myVideo.style.marginTop = '20px';
			
			myVideo.addEventListener('click',function(){
			  myVideo.play();
			},false);
			
			myVideo.addEventListener('play',function(){
			  productVideoClicked(); //Tracking
			},false);
			
			function playPause() {
				myVideo.play();
				productVideoClicked(); //Tracking
			}
			function pauseVideo(){
				myVideo.pause();
				//myHandler();
			}
			jQuery(document).on('touchend',function(e){
				if(e.target.closest('.slick-arrow')){
					if(!myVideo.paused){
						pauseVideo();
					}
				}else if(e.target.nodeName.toLowerCase() == 'video'){
					if(myVideo.paused){
						jQuery('.replay-video').remove();
					}
				}
			}); 
			function videoWidth(){
				var videoWidth = jQuery('.pro-images').width();		
				myVideo.width = videoWidth - 20;
			}
			jQuery(function(){
				videoWidth();
				//myHandler(); 
			});
			jQuery(window).resize(function(){
				videoWidth();
				//myHandler();
			});
			jQuery(document).on('click', '.replay-video' ,function(){
				myVideo.play();
				jQuery(this).remove();
			});
			
			// S:pause video on slide
			var touch = [];
			jQuery(document).bind('touchstart', function(e){
				jQuery('#moreviews1 .slick-dots li').each(function(){
					if(jQuery(this).attr('aria-hidden') == 'false'){
						touch.push(jQuery(this).index());
					}
				});
			}).bind('touchend', function(e){
				jQuery('#moreviews1 .slick-dots li').each(function(){
					if(jQuery(this).attr('aria-hidden') == 'false'){
						touch.push(jQuery(this).index());
						if(touch[0] == 2 && (touch[1] == 1 || touch[1] == 3)){
							pauseVideo();
						}
						touch = [];
					}
				});
			});
			// E:pause video on slide
			</script>
			<?php 
			}?>
        </div>
    <?php }
        
    // Code Added by Pankaj for Chain Message on product page.
    /*if($product->getChain1Length()){?>
		<style>
			.wishlist, .special-offer-tag{bottom:40px!important}
		</style>
        <div class="text-center small max-padding-bottom">
        <?php 
        $exclude_chain_prod_arr = array('SP0359PR','SP0358PR','SP0357PR','SP0355PR','SP0137R','SP0137S','SP0138R','SP0138S','SP0139R','SP0139S','SPY0138R','SP0373D','SP0352PR','SP0371D');
        if(!in_array($product->getSku(), $exclude_chain_prod_arr)){ 
        // skip chain message for selected products Ticket: #500?>
            (<?php echo $product->getChain1Length(); ?> inch <span id="pendantmsg" class="dyn_metal1_type"><?php if($product->getAttributeText('default_metal1_type')){ echo $product->getAttributeText('default_metal1_type'); }else if($product->getAttributeText('metal1_type')){ echo $product->getAttributeText('metal1_type'); }?></span> chain comes FREE with pendant.)
        <?php 
        }?>
        </div>
    <?php 
    }*/ // Code Ended by Pankaj for Chain Message on product page.
    ?>
	<?php
	//if($product->getChain1Length()){
		if(in_array($strLowerFreeProd, $freeProdSku)){?>
			<div class="text-center small max-padding-bottom">(Chain not included with purchase, chain buying options available at cart.)</div>
		<?php
		}
	//}?>
</div>


<div class="more-views-box low-margin-top" style="display:none!important">
	<div id="more-views-left" class="pull-left"><i class="fa fa-angle-left low-padding-left hide clickable"></i></div>	
	<div id="moreviews" class="more-views pull-left" style="height:auto!important">
		<div class="mv-box">
			<ul class="list-inline"><li onclick="productThumbnailClicked(this,'<?php echo $this->helper('catalog/image')->init($product, 'image'); ?>');" class="clickable active"><img itemprop="image" src="<?php echo $this->helper('catalog/image')->init($product, 'image')->resize($galleryImageSize['x'], $galleryImageSize['y']) ?>" alt="<?php echo $product->getShortDescription(); ?>"></li><?php foreach($galleryImages as $image): ?><li onclick="productThumbnailClicked(this,'<?php echo $this->helper('catalog/image')->init($product, 'image', $image->getFile()); ?>');" class="clickable"><img itemprop="image" src="<?php echo $this->helper('catalog/image')->init($product, 'image', $image->getFile())->resize($galleryImageSize['x'], $galleryImageSize['y']) ?>" alt="<?php echo $product->getShortDescription(); ?>"></li><?php endforeach; ?></ul>
		</div>
	</div>
	<div id="more-views-right" class="pull-right"><i class="fa fa-angle-right low-padding-left hide clickable"></i></div>
	<div class="clearfix"></div>
</div>


<!--S:VA Image Zoom-->
<div class="pro-popup row hidden">
	<div style="position:relative; height:100%">
		<div id="zoomview" class="full-width">
			<img itemprop="image" id="image1" class="img-responsive" src="">
		 </div>  
		 <!-- Trigger -->
		 <a href="javascript:void(0)" class="zoom-close"><i class="fa fa-long-arrow-left"></i> Back</a>   
	</div>
</div>
    
<script>
jQuery('.pro-images img, .zoom-icon, .tap-to-zoom').click(function(){
	var currentImageIndex	=	jQuery('.slick-dots').find('.slick-active :button').html();
	var imagePath			=	jQuery('div.img-' + currentImageIndex + ' img').attr('src');		//	get the clicked image src
	if( jQuery('div.img-' + currentImageIndex + ' img').data('width') > 350){
		jQuery('.pro-popup').removeClass('hidden');
		jQuery('body').css('overflow-y','hidden');		
		jQuery('#image1').attr('src',imagePath);
		jQuery( "#zoomview" ).scrollLeft( 200 );		//	Scroll image portion to middle
	}
});

jQuery('.zoom-close').click(function(){
	jQuery('.pro-popup').addClass('hidden');
	jQuery('body').css('overflow-y','initial');
});

jQuery(document).ready(function(){
	var wH = jQuery(window).height();
	jQuery('.pro-popup').css('height',wH);
	jQuery('#zoomview').css('height',wH-20);
})
</script>