<script>
hp_cartpopupflag=0;
</script>
<?php
$shoppingCartPriceRule = Mage::getModel('salesrule/rule');
$cartpopupactive = 0;
$percentage = '0';
$db = Mage::getSingleton('core/resource')->getConnection('core_write');
if($db)
{
	$result = $db->query("SELECT * FROM `salesrule` where name='DO NOT DELETE' and is_active='1' limit 0,1");
	if($result)
	{
		$rows = $result->fetch(PDO::FETCH_ASSOC);
		if($rows) 
		{
			$cartpopupactive = 1;
			$rule = $shoppingCartPriceRule->load($rows['rule_id']);
			$percentage = $rule->getData('discount_amount');
		}
	}
}

$count = Mage::helper('checkout/cart')->getItemsCount();
$cart = Mage::helper('checkout/cart')->getCart()->getQuote()->getShippingAddress();
$spdisc = $cart->getSpdisc();
$subtotal = $cart->getSubtotal();
$spdiscount = $subtotal * $percentage/100;
if($spdisc != 1 && $count > 0 && $cartpopupactive == 1)
{
?>
<script>
hp_cartpopupflag = 1;
</script>
<?php	
}
?>
<div id="cartpopup" style="display:none">
    <div style='position:fixed;z-index:100000;width:100%;height:100%;top:0;left:0;background:#ccc;opacity:.4;filter: alpha(opacity = 40);' onClick="document.getElementById('cartpopup').style.display='none'"></div>
    <div style="position:fixed;z-index:100001;width:375px;height:257px;top:10px;left:10px;background-color:#fff;border:5px solid #9e2a13;overflow:auto">
    	<div style="text-align:center;"><img src="/skin/frontend/angara/default/images/logo.gif" style="160px"></div>
        <div style="font-size:20px; margin-top:12px; text-align:center;color:#9e2a13; font-family:Arial, Helvetica, sans-serif, Tahoma; font-weight:bold" >Limited Time Offer!</div>
        <div style="font-size:12px; padding-top:10px; text-align:center;color:#000; font-family:Arial, Helvetica, sans-serif, Tahoma;">Act Now! for a total saving of</div>
        <div style="font-size:13px;text-align:center; padding-top:2px;  color:#000; font-family:Arial, Helvetica, sans-serif, Tahoma; font-weight:bold"><?php echo Mage::helper('checkout')->formatPrice($spdiscount);?></div>
        
        <div  style="font-size:12px; text-align:center;color:#000; font-family:Arial, Helvetica, sans-serif, Tahoma;">to proceed with your order and save<strong> <?php echo Mage::helper('checkout')->formatPrice($spdiscount);?></strong></div>
      <div  style="font-size:12px;  padding-top:10px; text-align:center;color:#000; font-family:Arial, Helvetica, sans-serif, Tahoma;">First click <strong>STAY ON PAGE</strong> on the adjacent window</div>
         <div style="font-size:12px; padding-top:10px; padding-bottom:10px;   color:#000;text-align:center; font-family:Arial, Helvetica, sans-serif, Tahoma;">And Then</div>
         <div style="width:214px; height:28px; margin:0 auto; background-color:#9e2a13;width:214px; height:28px; text-align:center; font:bold 12px/28px Arial, Helvetica, sans-serif, Tahoma;">
         <a href="javascript:needToConfirm=false;document.getElementById('spdiscform').submit()" style="color:#fff; text-decoration:none;">Click to Save <?php echo Mage::helper('checkout')->formatPrice($spdiscount);?>!</a></div>
  </div>
</div>
<form action="/cartpopup/discount/apply" method="post" id='spdiscform'><input type='hidden' value='<?php echo $percentage;?>' name='percentage_spdisc' /> </form>