<script>
hp_cartpopupflag=0;
</script>
<?php
$shoppingCartPriceRule = Mage::getModel('salesrule/rule');
$percentage = '0';
$db = Mage::getSingleton('core/resource')->getConnection('core_write');
if($db)
{
	$result = $db->query("SELECT * FROM `salesrule` where name='DO NOT DELETE' and is_active='1' limit 0,1");
	if($result)
	{
		$rows = $result->fetch(PDO::FETCH_ASSOC);
		if($rows) 
		{
			$rule = $shoppingCartPriceRule->load($rows['rule_id']);
			$percentage = $rule->getData('discount_amount');
			$percentage = round($percentage,2);
		}
	}
}
$spdiscount = 0;
$count = Mage::helper('checkout/cart')->getItemsCount();
if($count > 0){
	$cart = Mage::helper('checkout/cart')->getCart()->getQuote()->getShippingAddress();
	$subtotal = $cart->getSubtotal();
	$spdiscount = $subtotal * $percentage/100;
}
else
{
	?>
<script>
	var currentproductpriceshow_hp = '<?php echo $percentage;?>';
</script>    
    <?php
}
$curproduct = Mage::Registry('current_product');
?>
<script>
function checkbackajaxpopup(i)
{
	hp_cartpopupflag = i;
}
jQuery.post('/cartpopup/discount/check',{product:<?php echo $curproduct->getId(); ?>},checkbackajaxpopup);
</script>
<div id="cartpopup" style="display:none">
    <div style='position:fixed;z-index:100000;width:100%;height:100%;top:0;left:0;background:#ccc;opacity:.4;filter: alpha(opacity = 40);' onClick="document.getElementById('cartpopup').style.display='none'"></div>
    <div style="position:fixed;z-index:100001;width:375px;height:157px;top:10px;left:10px;background-color:#fff;border:5px solid #9e2a13;overflow:auto">
    	<div style="text-align:center;"><img src="/skin/frontend/angara/default/images/logo.gif" style="160px"></div>
        <div style="font-size:20px; margin-top:12px; margin-bottom:10px;text-align:center;color:#9e2a13; font-family:Arial, Helvetica, sans-serif, Tahoma; font-weight:bold" >One Time Offer!</div>
        <div style="display:none">
       		<span id="spdiscamount1"><?php echo Mage::helper('checkout')->formatPrice($spdiscount);?></span><span id="spdiscamount2"><?php echo Mage::helper('checkout')->formatPrice($spdiscount);?></span>
         </div>   
         <div style="width:300px; height:28px; margin:0 auto; background-color:#9e2a13;text-align:center; font:bold 12px/28px Arial, Helvetica, sans-serif, Tahoma;">
         <a href="javascript:needToConfirm=false;document.getElementById('spdiscform').submit()" style="color:#fff; text-decoration:none;">Click to Save an Additional <span id="spdiscamount3"><?php echo Mage::helper('checkout')->formatPrice($spdiscount);?></span> at Checkout!!</a></div>
  </div>
</div>
<form action="/cartpopup/discount/apply" method="post" id='spdiscform'><input type='hidden' value='<?php echo $percentage;?>' name='percentage_spdisc' /> </form>