<style>
.shop-jewel-by-stone{width:100%; float:left; border-top: 1px solid #f2f2f2; border-bottom: 1px solid #f2f2f2; padding-bottom: 22px; margin-top: 20px;}
.shop-jewel-by-stone .stone-box{width:10%;float:left}
.shop-jewel-by-stone .stone-holder{width:100%; padding:0px 5%; float:left}
@media (max-width:768px){
	.shop-jewel-by-stone .stone-box{width: 11%; font-size: 11px;}
	.shop-jewel-by-stone .stone-holder{padding:0px}
}
:root .shop-jewel-by-stone .stone-box { width:10% \0/IE9; }  /* IE9 + IE10pp4 */
</style>
<div class="shop-jewel-by-stone">
	<div class="clearfix"></div>
	<div class="heading text-center full-width max-margin-top max-margin-bottom px22">
		Shop Jewelry By Gemstone
	</div>
	<div class="clearfix"></div>
	<div class="stone-holder">
		<div class="visible-md" style="min-height:50px; width:5%;float:left"></div>
		<div class="stone-box">
			<a href="/jewelry/sapphire-jewelry.html?icid=home|jewelry-by-gems|SJ|12142015">
				<span class="col-sm-12" style="display:block">
				<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/stones/sapphire.jpg" alt="" title="" class="img-responsive"/>
				</span>
				<span class="text-uppercase text-bold">Sapphire</span>
			</a>
		</div>
		<div class="stone-box">
			<a href="/jewelry/ruby-jewelry.html?icid=home|jewelry-by-gems|RJ|12142015">
				<span class="col-sm-12" style="display:block">
				<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/stones/ruby.jpg" alt="" title="" class="img-responsive"/>
				</span>
				<span class="text-uppercase text-bold">Ruby</span>
			</a>
		</div>
		<div class="stone-box">
			<a href="/jewelry/opal-jewelry.html?icid=home|jewelry-by-gems|OJ|12142015">
				<span class="col-sm-12" style="display:block">
				<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/stones/opal.jpg" alt="" title="" class="img-responsive"/>
				</span>
				<span class="text-uppercase text-bold">Opal</span>
			</a>
		</div>
		<div class="stone-box">
			<a href="/jewelry/emerald-jewelry.html?icid=home|jewelry-by-gems|EJ|12142015">
				<span class="col-sm-12" style="display:block">
				<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/stones/emerald.jpg" alt="" title="" class="img-responsive"/>
				</span>
				<span class="text-uppercase text-bold">Emerald</span>
			</a>
		</div>
		<div class="stone-box">
			<a href="/jewelry/diamond-jewelry.html?icid=home|jewelry-by-gems|DJ|12142015">
				<span class="col-sm-12" style="display:block">
				<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/stones/diamond.jpg" alt="" title="" class="img-responsive"/>
				</span>
				<span class="text-uppercase text-bold">Diamond</span>
			</a>
		</div>
		<div class="stone-box">
			<a href="/jewelry/tanzanite-jewelry.html?icid=home|jewelry-by-gems|TJ|12142015">
				<span class="col-sm-12" style="display:block">
				<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/stones/tanzanite.jpg" alt="" title="" class="img-responsive"/>
				</span>
				<span class="text-uppercase text-bold">Tanzanite</span>
			</a>
		</div>
		<div class="stone-box">
			<a href="/jewelry/aquamarine-jewelry.html?icid=home|jewelry-by-gems|AQ|12142015">
				<span class="col-sm-12" style="display:block">
				<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/stones/aquamarine.jpg" alt="" title="" class="img-responsive"/>
				</span>
				<span class="text-uppercase text-bold">Aquamarine</span>
			</a>
		</div>
		<div class="stone-box">
			<a href="/jewelry/amethyst-jewelry.html?icid=home|jewelry-by-gems|AJ|12142015">
				<span class="col-sm-12" style="display:block">
				<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/stones/amethyst.jpg" alt="" title="" class="img-responsive"/>
				</span>
				<span class="text-uppercase text-bold">Amethyst</span>
			</a>
		</div>
		<div class="stone-box">
			<a href="/jewelry/garnet-jewelry.html?icid=home|jewelry-by-gems|GJ|12142015">
				<span class="col-sm-12" style="display:block">
					<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/stones/garnet.jpg" alt="" title="" class="img-responsive"/>
				</span>
				<span class="text-uppercase text-bold">Garnet</span>
			</a>
		</div>
		<div class="visible-md" style="min-height:50px; width:5%;float:left"></div>
	</div>
</div>