<?php
/**
 * @var $this Mage_Tax_Block_Checkout_Subtotal
 * @see Mage_Tax_Block_Checkout_Subtotal
 */

if($this->displayBoth()):?>
	<tr>
		<td style="<?php echo $this->getStyle();?>" class="a-left" colspan="<?php echo $this->getColspan();?>">
			<?php echo $this->helper('tax')->__('Subtotal (Excl. Tax)');?>:
		</td>
		<td style="<?php echo $this->getStyle();?>" class="a-right">
			<?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValueExclTax());?>
		</td>
	</tr>
	<tr>
		<td style="<?php echo $this->getStyle();?>" class="a-left" colspan="<?php echo $this->getColspan();?>">
			<?php echo $this->helper('tax')->__('Subtotal (Incl. Tax)');?>:
		</td>
		<td style="<?php echo $this->getStyle();?>" class="a-right">
			<?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValueInclTax());?>
		</td>
	</tr>
<?php 
else : ?>
	<?php /*<tr>
		<td style="<?php echo 'text-align:left;'.$this->getStyle();?>" class="a-left" colspan="<?php echo $this->getColspan();?>">
			Item(s) 
		</td>
		<td style="<?php echo $this->getStyle();?>" class="a-right">
			<?php  echo Mage::getBlockSingleton('checkout/cart')->getCheckout()->getQuote()->getItemsCount();?>
		</td>
	</tr> */ ?>
	<tr>
		<td style="<?php echo $this->getStyle();?>" class="a-left" colspan="<?php echo $this->getColspan();?>">
			Subtotal
		</td>
		<td style="<?php echo $this->getStyle();?>" class="a-right">
			<?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValue());?>
		</td>
	</tr>
<?php 
endif;?>