<?php //	Code added by Vaseem to show Fraud Check to admin only
$user 		=	Mage::getSingleton('admin/session');
$userId 	= 	$user->getUser()->getUserId();
//$acl 	= Mage::getSingleton('admin/session')->getAcl();
//echo '<pre>'; print_r($acl);die;
$isAdmin	=	Mage::helper('function')->checkAdmin($userId);
?>

<?php if($this->getTitle()): ?>
    <h3><?php echo $this->getTitle() ?></h3>
<?php endif ?>
<?php if(!empty($tabs)): ?>
<ul id="<?php echo $this->getId() ?>" class="tabs">
<?php foreach ($tabs as $_tab): ?>
<?php if (!$this->canShowTab($_tab)): continue;  endif; ?>

<?php //	Code added by Vaseem to show Fraud Check to admin only
if( ($this->getTabLabel($_tab)=='Fraud Check') ){ 
	if( $isAdmin ){
?>
    <li <?php if($this->getTabIsHidden($_tab)): ?> style="display:none"<?php endif; ?>>
        <a href="<?php echo $this->getTabUrl($_tab) ?>" id="<?php echo $this->getTabId($_tab) ?>" name="<?php echo $this->getTabId($_tab, false) ?>" title="<?php echo $this->getTabTitle($_tab) ?>" class="tab-item-link <?php echo $this->getTabClass($_tab) ?><?php if (preg_match('/\s?ajax\s?/', $_tab->getClass())) {?> notloaded<?php }?>">
            <span><span class="changed" title="<?php echo $this->__('The information in this tab has been changed.') ?>"></span><span class="error" title="<?php echo $this->__('This tab contains invalid data. Please solve the problem before saving.') ?>"></span><?php echo $this->getTabLabel($_tab); ?></span>
        </a>
        <div id="<?php echo $this->getTabId($_tab) ?>_content" style="display:none;"><?php echo $this->getTabContent($_tab) ?></div>
    </li>
<?php }
} else{	?>
    <li <?php if($this->getTabIsHidden($_tab)): ?> style="display:none"<?php endif; ?>>
        <a href="<?php echo $this->getTabUrl($_tab) ?>" id="<?php echo $this->getTabId($_tab) ?>" name="<?php echo $this->getTabId($_tab, false) ?>" title="<?php echo $this->getTabTitle($_tab) ?>" class="tab-item-link <?php echo $this->getTabClass($_tab) ?><?php if (preg_match('/\s?ajax\s?/', $_tab->getClass())) {?> notloaded<?php }?>">
            <span><span class="changed" title="<?php echo $this->__('The information in this tab has been changed.') ?>"></span><span class="error" title="<?php echo $this->__('This tab contains invalid data. Please solve the problem before saving.') ?>"></span><?php echo $this->getTabLabel($_tab); ?></span>
        </a>
        <div id="<?php echo $this->getTabId($_tab) ?>_content" style="display:none;"><?php echo $this->getTabContent($_tab) ?></div>
    </li>
<?php } ?>

<?php endforeach; ?>
</ul>
<script type="text/javascript">
    <?php echo $this->getJsObjectName() ?> = new varienTabs('<?php echo $this->getId() ?>', '<?php echo $this->getDestElementId() ?>', '<?php echo $this->getActiveTabId() ?>', <?php echo $this->getAllShadowTabs()?>);
</script>
<?php endif; ?>
