<?php
 /* @var $this Mage_Catalog_Block_Product_View_Abstract */
 
$_product 		= 	$this->getProduct();
$_taxHelper 	= 	$this->helper('tax');
$_coreHelper 	= 	Mage::helper('core');

echo $this->getChildHtml('product_type_data_extra');?>
<div class="price-holder full-width">
<div class="price-block fl"> 
	<div class="price-box" <?php /*itemprop="offers" itemscope itemtype="http://schema.org/Offer"*/?>>
		<?php /*<meta itemprop="priceCurrency" content="<?php echo Mage::app()->getStore()->getCurrentCurrencyCode();?>" />
		<link itemprop="availability" href="http://schema.org/InStock" />*/?>
		<span><?php echo $this->getPriceHtml($_product);?></span>
    </div>
</div>

<?php 
$categories 	= 	$this->getProduct()->getCategoryIds();
if(!in_array(96, $categories)): 
	$_easyPayOptions = $_taxHelper->getEasyPayOptions($_product, $_taxHelper->getPrice($_product, $_product->getFinalPrice())); ?>
        <div class="or-sep fl">
            <span>Or</span>
        </div>
        <div class="easy-pay fl" style="width:59%">		
            <label for="#easy-pay-box"><span>Easy Pay Installments <i class="fa fa-angle-down"></i></span> <i id="easy-pay-info" class="fa fa-info-circle fa-fw text-lighter fontsize-type4 clickable" style="display:none" data-html="true" data-placement="bottom" data-trigger="click" data-toggle="tooltip" title="
                <div class='block-sub-heading high-margin-bottom'>What is Easy Pay?</div>
                <ul class='list-style-disc'>
                    <li>Pay in 2 or 3 equal monthly Interest FREE installments.</li>
                    <li class='low-padding-bottom'>First payment is charged at the time of purchase.</li>
                    <li class='low-padding-bottom'>The order is processed for shipment immediately upon checkout.</li>
                    <li class='low-padding-bottom'>Your credit card will be charged for 2 or 3 equal installments starting <?php echo Mage::helper('function')->freeReturnDays();?> days from the date of purchase.
                    <li class='low-padding-bottom'>No interest or additional fees are charged by Angara.</li>
                    <li>The merchandise remains the property of Angara until the full payment is made and Angara reserves the right to collect the same or send a collection agency if a payment is not made.</li>
                </ul>"></i>
            </label>
            <select id="easy-pay-box" class="form-control high-margin-bottom input-text" name="easyopt">
				<?php 
                foreach($_easyPayOptions as $key => $val): ?>
                    <option value="<?php echo $key; ?>" <?php if($key == 0): ?> selected="selected" <?php endif; ?>><?php echo ($key + 1) . ' payment(s) of ' . $_coreHelper->currency($val, true, false) ?></option>
                <?php 
                endforeach; ?>
            </select><br>
			<div class="special-offer-tag fl mT10">Special Offer</div>
        </div>  
<?php else:?>
<style>
.product-retail-price-range, .product-retail-price { visibility: hidden; }
</style>
<?php	 
endif; ?>
</div>

<?php /* if(!in_array(96, $_product->getCategoryIds())): ?>
    <div id="special-offer-click" class="full-width">
        <span class="fl text-green">Tap here to get Offers</span><span class="fr"><i class="fa fa-caret-right fontsize-type2"></i></span>
    </div>
    <div class="clearfix"></div>
    <div class="row absolute-placeholder zi1" style="width:100%; top:33px; display:none;" id="special-offer-details">
        <div class="col-xs-12">
            <div class="padding-type-5 showcase-bg-white" style="border:dashed 1px #b5b5b5;">
                <div id="spinner-offer" class="high-padding-top high-padding-bottom" style="width:100%; text-align:center; display:none;"><i class="fa fa-spinner fa-2x fa-spin"></i></div>      	
                <div class="clearfix"><i id="close-special-offer" class="fa fa-times close fontsize-type5 hidden"></i></div>
                <div id="special-offer-text" class="" style="border:1px dashed #b5b5b5; background:#f6f6f6;padding:10px 10px 0px 10px;width:100%;float:left; margin-bottom: 10px; display:none"></div>
            </div>
        </div>
    </div>
<?php endif; */ ?>    