<style type="text/css">
@font-face {
 font-family: 'ProximaNova';
 src: url('/skin/frontend/angara/ultimate/fonts/proximanova-regular-webfont.eot');
 src: url('/skin/frontend/angara/ultimate/fonts/proximanova-regular-webfont.eot?#iefix') format('embedded-opentype'), url('/skin/frontend/angara/ultimate/fonts/proximanova-regular-webfont.woff') format('woff'), url('/skin/frontend/angara/ultimate/fonts/proximanova-regular-webfont.ttf') format('truetype'), url('/skin/frontend/angara/ultimate/fonts/proximanova-regular-webfont.svg#ProximaNova') format('svg');
 font-weight: normal;
 font-style: normal;
}
 @font-face {
 font-family: 'ProximaNova_Bold';
 src: url('/skin/frontend/angara/ultimate/fonts/proximanova-bold-webfont.eot');
 src: url('/skin/frontend/angara/ultimate/fonts/proximanova-bold-webfont.eot?#iefix') format('embedded-opentype'), url('/skin/frontend/angara/ultimate/fonts/proximanova-bold-webfont.woff') format('woff'), url('/skin/frontend/angara/ultimate/fonts/proximanova-bold-webfont.ttf') format('truetype'), url('/skin/frontend/angara/ultimate/fonts/proximanova-bold-webfont.svg#ProximaNova_Bold') format('svg');
 font-weight: normal;
 font-style: normal;
}
body {
	margin-left: 0px;
	margin-top: 0px;
	margin-right: 0px;
	margin-bottom: 0px;
	font-family:ProximaNova, Arial, Helvetica, sans-serif;
	font-size:12px;
	color:#1f1f1f;
}
#main {
	width:750px;
	margin:0 auto;
}
</style>

<!--Started Modification regarding bug id :493 by Pankaj-->

<script type="text/javascript" src="http://www.angara.com/js/adobe/s_code.js"></script>
<script type="text/javascript">
	s.pageName="NewsletterThankyouPage";
	s.t();
</script>

<div id="main">
  <table width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="f6f6f6" style="font-family:ProximaNova, Arial, Helvetica, sans-serif;">
    <tr>
      <td bgcolor="#FFFFFF" style="text-align:left;"><a href="http://www.angara.com/" target="_blank"><img src="/skin/frontend/angara/default/images/popup/logo.jpg" border="none" /></a></td>
    </tr>
    <tr>
      <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td width="44%" style="border-right:5px solid #c0c0c0" valign="top"><img src="/skin/frontend/angara/default/images/popup/model-photo3.jpg" align="left" /></td>
            <td width="56%" style="padding:10px;" valign="top"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tr>
                  <td style="font-size:18px; font-family:ProximaNova_Bold, Arial, Helvetica, sans-serif; color:#6a2d3a;">THANK YOU!<br />
                    <br /></td>
                </tr>
                <tr>
                  <td> Please check your inbox you will shortly receive our email with instructions to receive your $50 Gemstone Pendant.<br /><br /><span style="font:11px Arial, Helvetica, sans-serif;">This promotion is only applicable for legal resident(s) of United States of America and only participants that give a valid US Shipping Address can participate.</span><br />
                    <br />
                  </td>
                </tr>
                <tr>
                  <td style="padding-top:20px; padding-bottom:20px;"><a href="http://www.angara.com/" target="_blank"><img src="/skin/frontend/angara/default/images/popup/offer-img.png" border="none" /></a></td>
                  
                  <!--Ended Modification regarding bug id :493 by Pankaj-->
                  
                </tr>
                <tr>
                  <td style="font-size:18px; font-weight:bold; color:#6a2d3a; padding-top:10px; padding-bottom:10px;">CONNECT WITH US</td>
                </tr>
                <tr>
                  <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
                      <tr>
                        <td width="9%" style="padding:5px;"><a href="https://www.facebook.com/Angaradotcom" target="_blank"><img src="/skin/frontend/angara/default/images/popup/fb-icon.jpg" border="none"/></a></td>
                        <td width="91%" style="font-size:12px; color:#6a2d3a; padding:5px"><a href="https://www.facebook.com/Angaradotcom" style="text-decoration:none; color:#6a2d3a;" target="_blank">"Like" Angara on Facebook</a></td>
                      </tr>
                      <tr>
                        <td style="padding:5px;"><a href="https://twitter.com/angara" target="_blank"><img src="/skin/frontend/angara/default/images/popup/twt-icon.jpg" border="none" alt="" /></a></td>
                        <td style="font-size:12px; color:#6a2d3a; padding:5px"><a href="https://twitter.com/angara" style="text-decoration:none; color:#6a2d3a;" target="_blank">Follow Angara on Twitter</a></td>
                      </tr>
                      <tr>
                        <td style="padding:5px;"><a href="http://pinterest.com/angarajewelry/" target="_blank"><img src="/skin/frontend/angara/default/images/popup/pin-icon.jpg" border="none" alt="" /></a></td>
                        <td style="font-size:12px; color:#6a2d3a; padding:5px"><a href="http://pinterest.com/angarajewelry/" style="text-decoration:none; color:#6a2d3a;" target="_blank">Follow Angara on Pinterest</a></td>
                      </tr>
                    </table></td>
                </tr>
              </table></td>
          </tr>
        </table></td>
    </tr>
    <tr>
      <td style="font-size:16px; font-weight:bold; text-align:center; color:#737272; padding:10px;" bgcolor="FFFFFF" >Call Us: 1-888-926-4272</td>
    </tr>
  </table>
</div>
