<?php 
$params		= 	Mage::app()->getRequest()->getParams(); 
$_product 	= 	$this->getProduct();
$_wishlistSubmitUrl 	= 	Mage::helper('wishlist')->getAddUrl($_product); 
?>
	<?php if(strstr($_SERVER['HTTP_USER_AGENT'],'iPad')){ 
		$mainWidth = '740px';
		$childWidth = '390px';
		$height = '410px';
	}else{
		$mainWidth = '860px';
		$childWidth = '510px';
		$height = '510px';
	} ?>

	<div style="width:<?php echo $mainWidth; ?>; height:<?php echo $height; ?>; background:#ffffff; margin:8% auto 0px; border-radius:3px; position:relative">
		<div class="dismiss-popup" style="position:absolute; width:18px; height:18px; top:-9px; right:-9px; cursor:pointer; background:url('<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/sprite.jpg') no-repeat; background-position: -229px -151px; border-radius: 11px;;" data-dismiss="modal"></div>
		<div style="width:<?php echo $childWidth; ?>; height:<?php echo $height; ?>; position:relative; border-right:1px solid #dedede; padding:0px 50px 90px; float:left">
			<?php 
			$params = Mage::app()->getRequest()->getParams(); 
			if($params['pagetype']!='product'){?>
				<a href="<?php echo $this->getBaseUrl().$_product->getUrlPath(); ?>"><img class="img-responsive" src="<?php echo Mage::helper('catalog/image')->init($_product, 'image'); ?>" alt="<?php echo $_product->getShortDescription();?> - Angara.com"/></a>
			<?php } else{ ?>
            	<img class="img-responsive" src="<?php echo Mage::helper('catalog/image')->init($_product, 'image'); ?>" alt="<?php echo $_product->getShortDescription();?> - Angara.com"/>
            <?php } ?>
			<div style="position:absolute; left:9%; right:9%; bottom:20px">

				<div style="width:100%; float:left; font-size:15px; font-weight:500; line-height:25px;"><?php echo $this->stripTags($_product->getShortDescription(), null, true);?></div>
				<div style="width:100%; float:left" class="ratings-wishlist">
					<?php echo Mage::getBlockSingleton('review/helper')->getSummaryHtml($_product, false, true);?>
				</div>
			</div>
		</div>
		<div style="width:350px; float:left; padding:30px;">
			<div style="width:100%; float:left;">
				<?php /*?><a class="login_with_facebook_btn" rel="facebook-connect" href="" style="display:block; width:100%; height:60px; border-radius:2px; float:left; padding:20px 20px 20px 60px; position:relative; text-align:center; color:#ffffff!important; text-decoration:none!important; font-size:16px; background:#3B5998">
					<i class="fa fa-facebook" style="position:absolute; left:30px; top:23px"></i>
					Continue with Facebook
				</a>
                
				<span style="display:block; width:100%; height:1px; text-align:center; float:left; margin:30px 0px; background:#cccccc">
					<span style="display:inline-block; padding:5px; background:#ffffff; position:relative; top:-15px;">
						or
					</span>
				</span><?php */?>
				
				<div class="heading text-center col-sm-12">
					<span class="text-bold col-sm-12 no-padding block-inline-display low-margin-bottom" style="font-size:22px;">Sign up to Create Wishlist</span>
					<span class="text-bold col-sm-12 no-padding block-inline-display max-margin-bottom" style="color:#666666;">Create an account so you will have a place to store your favorites</span>
				</div>
				<div class="clearfix"></div>
				<a href="<?php echo $_wishlistSubmitUrl.'c/1'//echo Mage::getUrl('customer/account/create');?>" style="display:block; width:100%; height:60px; border-radius:2px; float:left; padding:20px 20px 20px 60px; position:relative; text-align:center; color:#ffffff!important; text-decoration:none!important; font-size:16px; background:#fa505a" class="high-margin-top">
					<i class="fa fa-envelope-o" style="position:absolute;left:30px;top:23px;border: none;height: auto;line-height: normal;width: auto;"></i>
					Sign up with Email
				</a>
				<span style="width:100%; float:left; margin-top:20px; font-size:0.85em; line-height:1.7em; padding-bottom:20px; border-bottom:1px solid #eeeeee">
					By signing up, I agree to Angara’s <a href="/term-of-use" target="_blank" class="apricot-text">Terms of Service</a> and <a href="/privacy-and-security" target="_blank" class="apricot-text">Privacy Policy</a>.
				</span>
			</div>
			<div style="width:100%; float:left; margin-top:20px;">
				<span style="line-height:35px; font-size:16px; float:left">Already an Angara member?</span>
				<a href="<?php echo $_wishlistSubmitUrl;?>" style="display:block; line-height:35px; font-size:14px; float:right; border:1px solid #fa505a; border-radius:2px; color:#fa505a; text-decoration:none; padding:0px 10px;">Log in</a>
			</div>
		</div>
	</div>