<?php	
$category 	=	$this->getCategory();
$imagePath	=	Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN).'frontend/ress/default/images/';
switch($category){
	
	case 'tanzanite':
		$tabsHtml = '   <div class="col-md-3 col-sm-4 cat">
                            <a href="/rings/tanzanite-rings.html?icid=home|slider|tj|r|09142015">
                                <div class="cat-image">
                                    <img class="img-responsive" src="'.$imagePath.'homepage/category/sr0231t.jpg" alt="Tanzanite Rings" title="Tanzanite Rings"/>
                                </div>
                                <div class="cat-title"> RINGS <br /> <small class="text-underline" style="color:#d60b0b;"> Shop Now </small> </a></div>
                            </a>
                        </div>
                        <div class="col-md-3 col-sm-4 cat">
                            <a href="/earrings/tanzanite-earrings.html?icid=home|slider|tj|e|09142015">
                                <div class="cat-image">
                                    <img class="img-responsive" src="'.$imagePath.'homepage/category/se0983td.jpg" alt="Tanzanite Earrings" title="Tanzanite Earrings"/>
                                </div>
                                <div class="cat-title">Earrings <br /> <small class="text-underline" style="color:#d60b0b;"> Shop Now </small> </a></div>
                            </a>
                        </div>
                        <div class="col-md-3 col-sm-4 cat">
                            <a href="/pendants/tanzanite-necklace-pendants.html?icid=home|slider|tj|pn|09142015">
                                <div class="cat-image">
                                    <img class="img-responsive" src="'.$imagePath.'homepage/category/sp0155t.jpg" alt="Tanzanite Pendants" title="Tanzanite Pendants"/>
                                </div>
                                <div class="cat-title">Necklaces<br /><small class="text-underline" style="color:#d60b0b;"> Shop Now </small> </a></div>
                            </a>
                        </div>
                        <div class="col-md-3 col-sm-4 cat">
                            <a href="/engagement-rings/tanzanite-engagement-rings.html?icid=home|slider|tj|r|er|09142015">
                                <div class="cat-image">
                                    <img class="img-responsive" src="'.$imagePath.'homepage/category/sr0152t_n.jpg" alt="Tanzanite Engagement Rings" title="Tanzanite Engagement Rings"/>
                                </div>
                                <div class="cat-title">Engagement<br /> <small class="text-underline" style="color:#d60b0b;"> Shop Now </small> </a></div>
                            </a>
                        </div>
                        <div class="col-md-3 col-sm-4 cat">
                            <a href="/wedding-rings/wedding-bands.html?icid=home|slider|tj|r|wr|09142015">
                                <div class="cat-image">
                                    <img class="img-responsive" src="'.$imagePath.'homepage/category/sr0118td.jpg" alt="Tanzanite Wedding Bands" title="Tanzanite Wedding Bands"/>
                                </div>
                                <div class="cat-title">Wedding<br /> <small class="text-underline" style="color:#d60b0b;"> Shop Now </small> </a></div>
                            </a>
                        </div>
                        <div class="col-md-3 col-sm-4 cat">
                            <a href="/bracelets/gemstone-bracelets.html?icid=home|slider|tj|br|09142015">
                                <div class="cat-image">
                                    <img class="img-responsive" src="'.$imagePath.'homepage/category/sb0206td.jpg" alt="Tanzanite Bracelets" title="Tanzanite Bracelets"/>
                                </div>
                                <div class="cat-title">Bracelets<br /><small class="text-underline" style="color:#d60b0b;"> Shop Now </small> </a></div>
                            </a>
                        </div>
						<div class="col-md-3 col-sm-4 cat">
                            <a href="/jewelry/tanzanite-jewelry.html" class="view-all">
                                <span class="text-underline" style="padding-top:115px; display:block;">View All <br /> Tanzanite Jewelry </span>
                            </a>
                        </div>';
		break;
	case 'ruby':
		/* S: Ruby Block */
		$tabsHtml = '<div class="col-md-3 col-sm-4 cat">
                            <a href="/rings/ruby-rings.html?icid=home|slider|rj|r|09142015">
                                <div class="cat-image">
                                    <img class="img-responsive" src="'.$imagePath.'homepage/category/sr0150r.jpg" alt="Ruby Rings" title="Ruby Rings"/>
                                </div>
                                <div class="cat-title">Rings <br /><small class="text-underline" style="color:#d60b0b;"> Shop Now </small></div>
                            </a>
                        </div>
                        <div class="col-md-3 col-sm-4 cat">
                            <a href="/earrings/ruby-earrings.html?icid=home|slider|rj|e|09142015">
                                <div class="cat-image">
                                    <img class="img-responsive" src="'.$imagePath.'homepage/category/se0964rd.jpg" alt="Ruby Earrings" title="Ruby Earrings"/>
                                </div>
                                <div class="cat-title">Earrings <br /><small class="text-underline" style="color:#d60b0b;"> Shop Now </small></div>
                            </a>
                        </div>
                        <div class="col-md-3 col-sm-4 cat">
                            <a href="/pendants/ruby-necklace-pendants.html?icid=home|slider|rj|pn|09142015">
                                <div class="cat-image">
                                    <img class="img-responsive" src="'.$imagePath.'homepage/category/sp0149r.jpg" alt="Ruby Pendants" title="Ruby Pendants"/>
                                </div>
                                <div class="cat-title">Necklaces <br /><small class="text-underline" style="color:#d60b0b;"> Shop Now </small></div>
                            </a>
                        </div>
                        <div class="col-md-3 col-sm-4 cat">
                            <a href="/engagement-rings/ruby-engagement-rings.html?icid=home|slider|rj|r|er|09142015">
                                <div class="cat-image">
                                    <img class="img-responsive" src="'.$imagePath.'homepage/category/sr0354r.jpg" alt="Ruby Engagement Rings" title="Ruby Engagement Rings"/>
                                </div>
                                <div class="cat-title">Engagement <br /><small class="text-underline" style="color:#d60b0b;"> Shop Now </small></div>
                            </a>
                        </div>
                        <div class="col-md-3 col-sm-4 cat">
                            <a href="/wedding-rings/wedding-bands.html?filterable_stone_names=4143&amp;order=position&amp;dir=asc&amp;no_cache=true&amp;icid=home|slider|rj|r|wr|09142015">
                                <div class="cat-image">
                                    <img class="img-responsive" src="'.$imagePath.'homepage/category/wrgd_sr0673rd.jpg" alt="Ruby Wedding Bands" title="Ruby Wedding Bands"/>
                                </div>
                                <div class="cat-title">Wedding <br /><small class="text-underline" style="color:#d60b0b;"> Shop Now </small></div>
                            </a>
                        </div>
                        <div class="col-md-3 col-sm-4 cat">
                            <a href="/bracelets/gemstone-bracelets.html?filterable_stone_names=4143&amp;icid=home|slider|rj|br|09142015">
                                <div class="cat-image">
                                    <img class="img-responsive" src="'.$imagePath.'homepage/category/sb0205rd.jpg" alt="Ruby Bracelets" title="Ruby Bracelets" />
                                </div>
                                <div class="cat-title">Bracelets <br /> <small class="text-underline" style="color:#d60b0b;"> Shop Now </small></div>
                            </a>
                        </div>
						<div class="col-md-3 col-sm-4 cat">
                            <a href="/jewelry/ruby-jewelry.html" class="view-all">
                                <span class="text-underline" style="padding-top:115px; display:block;">View All <br /> Ruby Jewelry</span>
                            </a>
                        </div>';
		break;
	case 'sapphire':
		$tabsHtml = '
                        <div class="col-md-3 col-sm-4 cat">
                            <a href="/rings/sapphire-rings.html?icid=home|slider|sj|r|09142015">
                                <div class="cat-image">
                                    <img class="img-responsive" src="'.$imagePath.'homepage/category/sr0152s.jpg" alt="Sapphire Rings" title="Sapphire Rings"/>
                                </div>
                                <div class="cat-title">Rings <br /><small class="text-underline" style="color:#d60b0b;"> Shop Now </small></div>
                            </a>
                        </div>
                        <div class="col-md-3 col-sm-4 cat">
                            <a href="/earrings/sapphire-earrings.html?icid=home|slider|sj|e|09142015">
                                <div class="cat-image">
                                    <img class="img-responsive" src="'.$imagePath.'homepage/category/se0139s.jpg" alt="Sapphire Earrings" title="Sapphire Earrings"/>
                                </div>
                                <div class="cat-title">Earrings <br /><small class="text-underline" style="color:#d60b0b;"> Shop Now </small></div>
                            </a>
                        </div>
                        <div class="col-md-3 col-sm-4 cat">
                            <a href="/pendants/sapphire-necklace-pendants.html?icid=home|slider|sj|pn|09142015">
                                <div class="cat-image">
                                    <img class="img-responsive" src="'.$imagePath.'homepage/category/sp0169s.jpg" alt="Sapphire Pendants" title="Sapphire Pendants"/>
                                </div>
                                <div class="cat-title">Necklaces <br /> <small class="text-underline" style="color:#d60b0b;"> Shop Now </small></div>
                            </a>
                        </div>
                        <div class="col-md-3 col-sm-4 cat">
                            <a href="/engagement-rings/sapphire-engagement-rings.html?icid=home|slider|sj|r|er|09142015">
                                <div class="cat-image">
                                    <img class="img-responsive" src="'.$imagePath.'homepage/category/sr0160s.jpg" alt="Sapphire Engagement Rings" title="Sapphire Engagement Rings"/>
                                </div>
                                <div class="cat-title">Engagement<br /><small class="text-underline" style="color:#d60b0b;"> Shop Now </small></div>
                            </a>
                        </div>
                        <div class="col-md-3 col-sm-4 cat">
                            <a href="/wedding-rings/wedding-bands.html?filterable_stone_names=4144-4140&amp;order=position&amp;dir=asc&amp;no_cache=true&amp;icid=home|slider|sj|r|wr|09142015">
                                <div class="cat-image">
                                    <img class="img-responsive" src="'.$imagePath.'homepage/category/sr0101sd.jpg" alt="Sapphire Wedding Bands" title="Sapphire Wedding Bands" />
                                </div>
                                <div class="cat-title">Wedding<br /><small class="text-underline" style="color:#d60b0b;"> Shop Now </small></div>
                            </a>
                        </div>
                        <div class="col-md-3 col-sm-4 cat">
                            <a href="/bracelets/gemstone-bracelets.html?filterable_stone_names=4144&amp;icid=home|slider|sj|br|09142015">
                                <div class="cat-image">
                                    <img class="img-responsive" src="'.$imagePath.'homepage/category/sb0177sd.jpg" alt="Sapphire Bracelets" title="Sapphire Bracelets" />
                                </div>
                                <div class="cat-title">Bracelets<br /> <small class="text-underline" style="color:#d60b0b;"> Shop Now </small></div>
                            </a>
                        </div>
						<div class="col-md-3 col-sm-4 cat">
                            <a href="/jewelry/sapphire-jewelry.html" class="view-all">
                                <span class="text-underline" style="padding-top:115px; display:block;">View All <br /> Sapphire Jewelry</span>
                            </a>
                        </div>';
		break;
	case 'emerald':
		$tabsHtml = '
                        <div class="col-md-3 col-sm-4 cat">
                            <a href="/rings/emerald-rings.html?icid=home|slider|ej|r|09142015">
                                <div class="cat-image">
                                    <img class="img-responsive" src="'.$imagePath.'homepage/category/sr0112e.jpg" alt="Emerald Rings" title="Emerald Rings"/>
                                </div>
                                <div class="cat-title">Rings<br /> <small class="text-underline" style="color:#d60b0b;"> Shop Now </small></div>
                            </a>
                        </div>
                        <div class="col-md-3 col-sm-4 cat">
                            <a href="/earrings/emerald-earrings.html?icid=home|slider|ej|e|09142015">
                                <div class="cat-image">
                                    <img class="img-responsive" src="'.$imagePath.'homepage/category/se0118e.jpg" alt="Emerald Earrings" title="Emerald Earrings"/>
                                </div>
                                <div class="cat-title">Earrings<br /><small class="text-underline" style="color:#d60b0b;"> Shop Now </small></div>
                            </a>
                        </div>
                        <div class="col-md-3 col-sm-4 cat">
                            <a href="/pendants/emerald-necklace-pendants.html?icid=home|slider|ej|pn|09142015">
                                <div class="cat-image">
                                    <img class="img-responsive" src="'.$imagePath.'homepage/category/sp0102e.jpg" alt="Emerald Pendants" title="Emerald Pendants"/>
                                </div>
                                <div class="cat-title">Necklaces<br /> <small class="text-underline" style="color:#d60b0b;"> Shop Now </small></div>
                            </a>
                        </div>
                        <div class="col-md-3 col-sm-4 cat">
                            <a href="/engagement-rings/emerald-engagement-rings.html?icid=home|slider|ej|r|er|09142015">
                                <div class="cat-image">
                                    <img class="img-responsive" src="'.$imagePath.'homepage/category/sr0217e.jpg" alt="Emerald Engagement Rings" title="Emerald Engagement Rings"/>
                                </div>
                                <div class="cat-title">Engagement<br /> <small class="text-underline" style="color:#d60b0b;"> Shop Now </small></div>
                            </a>
                        </div>
                        <div class="col-md-3 col-sm-4 cat">
                            <a href="/wedding-rings/wedding-bands.html?filterable_stone_names=4131&amp;order=position&amp;dir=asc&amp;no_cache=true&amp;icid=home|slider|ej|r|wr|09142015">
                                <div class="cat-image">
                                    <img class="img-responsive" src="'.$imagePath.'homepage/category/wrgd_sr0702ed.jpg" alt="Emerald Wedding Bands" title="Emerald Wedding Bands"/>
                                </div>
                                <div class="cat-title">Wedding<br /> <small class="text-underline" style="color:#d60b0b;"> Shop Now </small></div>
                            </a>
                        </div>
                        <div class="col-md-3 col-sm-4 cat">
                            <a href="/bracelets/gemstone-bracelets.html?filterable_stone_names=4131&amp;icid=home|slider|ej|br|09142015">
                                <div class="cat-image">
                                    <img class="img-responsive" src="'.$imagePath.'homepage/category/sb0164ed.jpg" alt="Emerald Bracelets" title="Emerald Bracelets"/>
                                </div>
                                <div class="cat-title">Bracelets<br /><small class="text-underline" style="color:#d60b0b;"> Shop Now </small></div>
                            </a>
                        </div>
						<div class="col-md-3 col-sm-4 cat">
                            <a href="/jewelry/emerald-jewelry.html" class="view-all">
                                <span class="text-underline" style="padding-top:115px; display:block;">View All <br /> Emerald Jewelry</span>
                            </a>
                        </div>';
		break;
	case 'diamond':
		$tabsHtml = '<div class="col-md-3 col-sm-4 cat">
                            <a href="/rings/diamond-rings.html?icid=home|slider|dj|r|09142015">
                                <div class="cat-image">
                                    <img class="img-responsive" src="'.$imagePath.'homepage/category/wrd_sr1023d.jpg" alt="Diamond Rings" title="Diamond Rings"/>
                                </div>
                                <div class="cat-title">Rings<br /> <small class="text-underline" style="color:#d60b0b;"> Shop Now </small></div>
                            </a>
                        </div>
                        <div class="col-md-3 col-sm-4 cat">
                            <a href="/earrings/diamond-earrings.html?icid=home|slider|dj|e|09142015">
                                <div class="cat-image">
                                    <img class="img-responsive" src="'.$imagePath.'homepage/category/se0976d.jpg" alt="Diamond Earrings" title="Diamond Earrings"/>
                                </div>
                                <div class="cat-title">Earrings<br /><small class="text-underline" style="color:#d60b0b;"> Shop Now </small></div>
                            </a>
                        </div>
                        <div class="col-md-3 col-sm-4 cat">
                            <a href="/pendants/diamond-necklace-pendants.html?icid=home|slider|dj|pn|09142015">
                                <div class="cat-image">
                                    <img class="img-responsive" src="'.$imagePath.'homepage/category/sp0724d.jpg" alt="Diamond Pendants" title="Diamond Pendants"/>
                                </div>
                                <div class="cat-title">Necklaces<br /><small class="text-underline" style="color:#d60b0b;"> Shop Now </small></div>
                            </a>
                        </div>
                        <div class="col-md-3 col-sm-4 cat">
                            <a href="/engagement-rings/diamond-engagement-rings.html?icid=home|slider|dj|r|er|09142015">
                                <div class="cat-image">
                                    <img class="img-responsive" src="'.$imagePath.'homepage/category/sr0647d.jpg" alt="Diamond Engagement Rings" title="Diamond Engagement Rings"/>
                                </div>
                                <div class="cat-title">Engagement<br /><small class="text-underline" style="color:#d60b0b;"> Shop Now </small></div>
                            </a>
                        </div>
                        <div class="col-md-3 col-sm-4 cat">
                            <a href="/wedding-rings/wedding-bands.html?filterable_stone_names=4130&amp;order=position&amp;dir=asc&amp;no_cache=true&amp;icid=home|slider|dj|r|wr|09142015">
                                <div class="cat-image">
                                    <img class="img-responsive" src="'.$imagePath.'homepage/category/wrd_sr0865d.jpg" alt="Diamond Wedding Bands" title="Diamond Wedding Bands"/>
                                </div>
                                <div class="cat-title">Wedding<br /><small class="text-underline" style="color:#d60b0b;"> Shop Now </small></div>
                            </a>
                        </div>
                        <div class="col-md-3 col-sm-4 cat">
                            <a href="/bracelets/diamond-bracelets.html?icid=home|slider|dj|br|09142015">
                                <div class="cat-image">
                                    <img class="img-responsive" src="'.$imagePath.'homepage/category/sb0167d.jpg" alt="Diamond Bracelets" title="Diamond Bracelets"/>
                                </div>
                                <div class="cat-title">Bracelets<br /><small class="text-underline" style="color:#d60b0b;"> Shop Now </small></div>
                            </a>
                        </div>
						<div class="col-md-3 col-sm-4 cat">
                            <a href="/jewelry/diamond-jewelry.html" class="view-all">
                                <span class="text-underline" style="padding-top:115px; display:block;">View All <br /> Diamond Jewelry</span>
                            </a>
                        </div>';
		break;
	
		case 'opal':
		$tabsHtml = '<div class="col-md-3 col-sm-4 cat">
						<a href="/rings/opal-rings.html?icid=home|slider|oj|r|12172015">
							<div class="cat-image">
								<img class="img-responsive" src="'.$imagePath.'homepage/category/sr1077opd.jpg" alt="Opal Rings" title="Opal Rings"/>
							</div>
							<div class="cat-title">Rings<br /><small class="text-underline" style="color:#d60b0b;"> Shop Now </small></div>
						</a>
					</div>
					<div class="col-md-3 col-sm-4 cat">
						<a href="/earrings/opal-earrings.html?icid=home|slider|oj|e|12172015">
							<div class="cat-image">
								<img class="img-responsive" src="'.$imagePath.'homepage/category/se1040op.jpg" alt="Opal Earrings" title="Opal Earrings"/>
							</div>
							<div class="cat-title">Earrings<br /><small class="text-underline" style="color:#d60b0b;"> Shop Now </small></div>
						</a>
					</div>
					<div class="col-md-3 col-sm-4 cat">
						<a href="/pendants/opal-necklace-pendants.html?icid=home|slider|oj|pn|12172015">
							<div class="cat-image">
								<img class="img-responsive" src="'.$imagePath.'homepage/category/sp0738opd.jpg" alt="Opal Pendants" title="Opal Pendants"/>
							</div>
							<div class="cat-title">Necklaces<br /><small class="text-underline" style="color:#d60b0b;"> Shop Now </small></div>
						</a>
					</div>
					<div class="col-md-3 col-sm-4 cat">
						<a href="/jewelry/opal-jewelry.html" class="view-all">
							<span class="text-underline" style="padding-top:115px; display:block;">View All <br /> Opal Jewelry</span>
						</a>
					</div>';
		break;
		
		case 'aquamarine':
		$tabsHtml = '<div class="col-md-3 col-sm-4 cat">
                            <a href="/rings/aquamarine-rings.html?icid=home|slider|aq|r|12172015">
                                <div class="cat-image">
                                    <img class="img-responsive" src="'.$imagePath.'homepage/category/sr0112aq.jpg" alt="Aquamarine Rings" title="Aquamarine Rings"/>
                                </div>
                                <div class="cat-title">Rings<br /><small class="text-underline" style="color:#d60b0b;"> Shop Now </small></div>
                            </a>
                        </div>
                        <div class="col-md-3 col-sm-4 cat">
                            <a href="/earrings/aquamarine-earrings.html?icid=home|slider|aq|e|12172015">
                                <div class="cat-image">
                                    <img class="img-responsive" src="'.$imagePath.'homepage/category/se0102aq.jpg" alt="Aquamarine Earrings" title="Aquamarine Earrings"/>
                                </div>
                                <div class="cat-title">Earrings<br />  <small class="text-underline" style="color:#d60b0b;"> Shop Now </small></div>
                            </a>
                        </div>
                        <div class="col-md-3 col-sm-4 cat">
                            <a href="/pendants/aquamarine-necklace-pendants.html?icid=home|slider|aq|pn|12172015">
                                <div class="cat-image">
                                    <img class="img-responsive" src="'.$imagePath.'homepage/category/sp0155aq.jpg" alt="Aquamarine Pendants" title="Aquamarine Pendants"/>
                                </div>
                                <div class="cat-title">Necklaces<br /> <small class="text-underline" style="color:#d60b0b;"> Shop Now </small></div>
                            </a>
                        </div>
                        <div class="col-md-3 col-sm-4 cat">
                            <a href="/engagement-rings.html?filterable_stone_names=4124&icid=home|slider|aq|er|12172015">
                                <div class="cat-image">
                                    <img class="img-responsive" src="'.$imagePath.'homepage/category/wrs-sr0683aq.jpg" alt="Aquamarine Engagement Rings" title="Aquamarine Engagement Rings"/>
                                </div>
                                <div class="cat-title">Engagement<br /> <small class="text-underline" style="color:#d60b0b;"> Shop Now </small></div>
                            </a>
                        </div>
                        <div class="col-md-3 col-sm-4 cat">
                            <a href="/wedding-rings/wedding-bands.html?order=position&dir=asc&no_cache=true&filterable_stone_names=4124&icid=home|slider|aq|wr|12172015">
                                <div class="cat-image">
                                    <img class="img-responsive" src="'.$imagePath.'homepage/category/sr0118aq.jpg" alt="Aquamarine Wedding Bands" title="Aquamarine Wedding Bands"/>
                                </div>
                                <div class="cat-title">Wedding<br /><small class="text-underline" style="color:#d60b0b;"> Shop Now </small></div>
                            </a>
                        </div>
                  
						<div class="col-md-3 col-sm-4 cat">
                            <a href="/jewelry/aquamarine-jewelry.html" class="view-all">
                                <span class="text-underline" style="padding-top:115px; display:block;">View All <br /> Aquamarine Jewelry</span>
                            </a>
                        </div>';
		break;
		
		case 'garnet':
		$tabsHtml = '<div class="col-md-3 col-sm-4 cat">
                            <a href="/rings/garnet-rings.html?icid=home|slider|gj|r|12172015">
                                <div class="cat-image">
                                    <img class="img-responsive" src="'.$imagePath.'homepage/category/sr1055gd.jpg" alt="Garnet Rings" title="Garnet Rings"/>
                                </div>
                                <div class="cat-title">Rings<br /><small class="text-underline" style="color:#d60b0b;"> Shop Now </small></div>
                            </a>
                        </div>
                        <div class="col-md-3 col-sm-4 cat">
                            <a href="/earrings/garnet-earrings.html?icid=home|slider|gj|e|12172015">
                                <div class="cat-image">
                                    <img class="img-responsive" src="'.$imagePath.'homepage/category/se1021gd.jpg" alt="Garnet Earrings" title="Garnet Earrings"/>
                                </div>
                                <div class="cat-title">Earrings<br /><small class="text-underline" style="color:#d60b0b;"> Shop Now </small></div>
                            </a>
                        </div>
                        <div class="col-md-3 col-sm-4 cat">
                            <a href="/pendants/garnet-necklace-pendants.htmlicid=home|slider|gj|pn|12172015">
                                <div class="cat-image">
                                    <img class="img-responsive" src="'.$imagePath.'homepage/category/sp0583g.jpg" alt="Garnet Pendants" title="Garnet Pendants"/>
                                </div>
                                <div class="cat-title">Necklaces<br /><small class="text-underline" style="color:#d60b0b;"> Shop Now </small></div>
                            </a>
                        </div>
                        <div class="col-md-3 col-sm-4 cat">
                            <a href="/bracelets.html?filterable_stone_names=4132&icid=home|slider|gj|b|12172015">
                                <div class="cat-image">
                                    <img class="img-responsive" src="'.$imagePath.'homepage/category/sb0189g.jpg" alt="Garnet Bracelets" title="Garnet Bracelets"/>
                                </div>
                                <div class="cat-title">Bracelets<br /><small class="text-underline" style="color:#d60b0b;"> Shop Now </small></div>
                            </a>
                        </div>
						<div class="col-md-3 col-sm-4 cat">
                            <a href="/jewelry/garnet-jewelry.html" class="view-all">
                                <span class="text-underline" style="padding-top:115px; display:block;">View All <br /> Garnet Jewelry</span>
                            </a>
                        </div>';
		break;
		
		case 'shop_by_gemstone':
		$tabsHtml = '<div class="container"><div class="col-sm-12 full-width text-center" style="padding:8px 5px 1px">'.$this->getLayout()->createBlock('core/template')->setTemplate('homepage/shop_by_gemstone.phtml')->toHTML().'</div></div>';
		break;
		
		case 'customer_stories':
		$tabsHtml = '		<p class="hp-block-title text-center px22 fontcolor-type1 high-padding-top">Customer Stories</p>
							<div class="col-sm-12" id="customer-stories"><div class="padding-type-5">
								<a href="/customer-stories.html"><img src="'.$imagePath.'customer-reviews/cs-1.jpg" alt="" class="img-responsive"/></a>
							</div>
							<div class="padding-type-5">
								<a href="/customer-stories.html"><img src="'.$imagePath.'customer-reviews/cs-2.jpg" alt="" class="img-responsive"/></a>
							</div>
							<div class="padding-type-5">
								<a href="/customer-stories.html"><img src="'.$imagePath.'customer-reviews/cs-3.jpg" alt="" class="img-responsive"/></a>
							</div>
							<div class="padding-type-5">
								<a href="/customer-stories.html"><img src="'.$imagePath.'customer-reviews/cs-4.jpg" alt="" class="img-responsive"/></a>
							</div>
							<div class="padding-type-5">
								<a href="/customer-stories.html"><img src="'.$imagePath.'customer-reviews/cs-5.jpg" alt="" class="img-responsive"/></a>
							</div>
							<div class="padding-type-5">
								<a href="/customer-stories.html"><img src="'.$imagePath.'customer-reviews/cs-6.jpg" alt="" class="img-responsive"/></a>
							</div>
							<div class="padding-type-5">
								<a href="/customer-stories.html"><img src="'.$imagePath.'customer-reviews/cs-7.jpg" alt="" class="img-responsive"/></a>
							</div></div>
						';
		break;
		
		default:
		$tabsHtml = ' default';		
} 
echo $tabsHtml;?>
