<div class="container hidden-xs">
<?php 
if($crumbs && is_array($crumbs)): ?>
<?php 
/*$product = Mage::registry('current_product');
if(( Mage::getModel('catalog/product')->isUserFromSearch() && isset($product)))
	{
		$refererlink=Mage::helper('core/http')->getHttpReferer();
		$crumbs=array("home" =>array("label"=> "Back to Search Results " , "title"=>"Go Back to Search Results ", "link" =>$refererlink, "first" =>true, "last"=>"", "readonly"=>"" ), "product" =>end($crumbs));
	}*/
if(Mage::app()->getRequest()->getParam('showdeal') == 'true'):
?>
<ul class="breadcrumb high-padding-top" itemscope itemtype="http://schema.org/BreadcrumbList">
    <li class="home" itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
    	<strong itemprop="name">Deals</strong>
    </li>           
</ul>
<?php
else:
?>
	<ul class="breadcrumb high-padding-top" itemscope itemtype="http://schema.org/BreadcrumbList">
    <?php 
	$i=1;
	foreach($crumbs as $_crumbName=>$_crumbInfo): ?>
        <li class="<?php echo $_crumbName;?>" itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
        <?php 
		if($_crumbInfo['link']): ?>
            <a itemprop="item" href="<?php echo $_crumbInfo['link'];?>" title="<?php echo $this->htmlEscape($_crumbInfo['title']);?>"><span itemprop="name"><?php echo $this->htmlEscape($_crumbInfo['label']);?></span></a>
            <meta itemprop="position" content="<?php echo $i;?>" />
        <?php 
		elseif($_crumbInfo['last']): ?>
            <strong itemprop="name"><?php echo $this->htmlEscape($_crumbInfo['label']);?></strong>
            <meta itemprop="position" content="<?php echo $i;?>" />
        <?php 
		else: 
			echo $this->htmlEscape($_crumbInfo['label']);
		endif; ?>
        </li>
    <?php $i++;
	endforeach; ?>
	</ul>
<?php 
endif;
endif; ?>
</div>