<style>
.last-minute-shopping-tag{position:fixed;top:552px;right:-1px;}
.nav li{margin-top:12px; margin-right:30px;}
.nav li:last-child{margin-right:0px;}
.nav li a{padding:0px; line-height:14px;}
.p0{padding:0px;}
.sm{display:none}
.main-menu-box{position:absolute;top:18px;left:240px;right:270px;}

.secondary-navbar{display:none}
.navbar-nav-li{cursor:pointer;}
li.navbar-nav-li.active:before,
li.navbar-nav-li.active:after {
	content: "";
	position: absolute;
	border-top: 7px solid transparent;
    border-left: 7px solid transparent;
    border-right: 7px solid transparent;
    z-index: 999999;
    left: 50%;
    margin-left: -7px;
}
li.navbar-nav-li.active:before {
    border-bottom: 8px solid #cccccc;
    bottom: -26px;
}
li.navbar-nav-li.active:after {
    border-bottom: 8px solid #ffffff;
    bottom: -27px;
}
@media (max-width: 1599px){
	.main-menu-box{
		right:100px!important;
	}
}
@media (max-width: 1299px){
	.nav li{margin-right:20px;}
	.nav li a{font-size:14px;}
}
@media (max-width:1150px ){
	.nav li{margin-right:10px;}
	.nav li a{font-size: 13px;}
}

<?php if(strstr($_SERVER['HTTP_USER_AGENT'],'iPad')){ ?>
@media (max-width:1024px ){
	.nav > li > a{pointer-events:none!important;}
}
<?php } ?>
@media (min-width:769px) and (max-width:1024px ){
	#sub-navigation{
		width:1024px;
	}
}
@media (min-width: 768px ) and (max-width: 999px) {
	.sm{display:block}
	.md{display:none}
}
.secondary-navbar-wrapper .showcase-bg-light{
	background: none;
    color: #a0a0a0;
    border-bottom: 1px solid #a0a0a0;
}
.secondary-navbar-wrapper .showcase-bg-light strong{
	font-weight: 400;
}

</style>
<!--[if IE 8]> 
<style>
.ie8-remove{display:none!important}
</style>
<![endif]-->
<div id="main-menu" class="main-menu-box">
  	<div class="hidden-xs">
    	<div class="container-fluid">
      		<div class="container">
        		<div class="row">
          			<div class="text-center">
            			<nav id="navbar-main" class="navbar navbar-default navbar-main text-uppercase" role="navigation">
              				<div class="primary-navbar">
								<ul class="nav navbar-nav">
                  					<li class="navbar-nav-li"><a href="/rings" class="no-transition" onclick="categoryNavSelect('Rings|topnav')"><span class="nav-link-text no-transition">Rings</span><i class="fa low-padding-left fa-angle-down no-transition"></i></a></li>
                  					<li class="navbar-nav-li"><a href="/pendants" class="no-transition" onclick="categoryNavSelect('Necklaces|topnav')"><span class="nav-link-text no-transition">Necklaces</span><i class="fa low-padding-left fa-angle-down no-transition"></i></a></li>
                  					<li class="navbar-nav-li"><a href="/earrings" class="no-transition" onclick="categoryNavSelect('Earrings|topnav')"><span class="nav-link-text no-transition">Earrings</span><i class="fa low-padding-left fa-angle-down no-transition"></i></a></li>
                  					<li class="navbar-nav-li"><a href="/engagement-rings" class="no-transition" onclick="categoryNavSelect('Engagement|topnav')"><span class="nav-link-text no-transition">Engagement</span><i class="fa low-padding-left fa-angle-down no-transition"></i></a></li>
                  					<li class="navbar-nav-li"><a href="/wedding-rings" class="no-transition" onclick="categoryNavSelect('Wedding|topnav')"><span class="nav-link-text no-transition">Wedding</span><i class="fa low-padding-left fa-angle-down no-transition"></i></a></li>
				  					<li class="navbar-nav-li"><a href="/bracelets" class="no-transition" onclick="categoryNavSelect('Bracelets|topnav')"><span class="nav-link-text no-transition">Bracelets</span><i class="fa low-padding-left fa-angle-down no-transition"></i></a></li>
									<li class="navbar-nav-li"><a href="/jewelry-gifts" class="no-transition" onclick="categoryNavSelect('Gifts|topnav')"><span class="nav-link-text no-transition"><i class="fa fa-gift"></i> Gifts</span><i class="fa low-padding-left fa-angle-down no-transition"></i></a></li>
                				</ul>
              				</div>
            			</nav>
          			</div>
        		</div>
      		</div>
    	</div>
    	<div id="sub-navigation" class="showcase-bg-white showcase-border-bottom container-fluid relative-placeholder">
      		<div class="container showcase-bg-white">
        		<div class="row">
          			<div class="col-sm-12 has-slider">
            			<nav role="navigation" id="main_navigation">
              				<div class="secondary-navbar-wrapper ress-slider-wrapper" style="min-height:290px">
                				<div class="secondary-navbar-container ress-slider ress-slider-horizontal"> 
                                <?php //ring categories starts ?>
                                <div class="secondary-navbar ress-slider-item pull-left" id="sub-nav-ring">
									<div class="row">
										<div class="col-md-5 col-sm-6 col-xs-5 high-padding-bottom">
											<div class="high-margin-top low-margin-bottom showcase-bg-light padding-type-3 low-padding-left"><strong>Shop By Colored Gemstone</strong></div>
											<div class="clearfix"></div>
											<ul class="pull-left low-padding-left">
												<li><a href="/rings/sapphire-rings" onclick="categoryNavSelect('Sapphire Rings|topnav')">Sapphire</a></li>
												<li><a href="/rings/ruby-rings" onclick="categoryNavSelect('Ruby Rings|topnav')">Ruby</a></li>
												<li><a href="/rings/emerald-rings" onclick="categoryNavSelect('Emerald Rings|topnav')">Emerald</a></li>
												<li><a href="/rings/tanzanite-rings" onclick="categoryNavSelect('Tanzanite Rings|topnav')">Tanzanite</a></li>
												<li><a href="/rings/aquamarine-rings" onclick="categoryNavSelect('Aquamarine Rings|topnav')">Aquamarine</a></li>
												<li><a href="/rings/blue-topaz-rings" onclick="categoryNavSelect('Blue Topaz Rings|topnav')">Blue Topaz</a></li>
												<li><a href="/rings/black-onyx-rings" onclick="categoryNavSelect('Black Onyx Rings|topnav')">Black Onyx</a></li>
												<li><a href="/rings/citrine-rings" onclick="categoryNavSelect('Citrine Rings|topnav')">Citrine</a></li>
											</ul>
											<ul class="pull-left max-padding-left low-margin-left">
												<li><a href="/rings/pearl-rings" onclick="categoryNavSelect('Pearl Rings|topnav')">Pearl</a></li>
												<li><a href="/rings/morganite-rings" onclick="categoryNavSelect('Morganite Rings|topnav')">Morganite</a></li>
												<li><a href="/rings/garnet-rings" onclick="categoryNavSelect('Garnet Rings|topnav')">Garnet</a></li>
												<li><a href="/rings/opal-rings" onclick="categoryNavSelect('Opal Rings|topnav')">Opal</a></li>  
												<li><a href="/rings/amethyst-rings" onclick="categoryNavSelect('Amethyst Rings|topnav')">Amethyst</a></li>
												<li><a href="/rings/peridot-rings" onclick="categoryNavSelect('Peridot Rings|topnav')">Peridot</a></li>											
												<li><a href="/rings/pink-tourmaline-rings" onclick="categoryNavSelect('Pink Tourmaline Rings|topnav')">Pink Tourmaline</a></li>
											</ul>
											<ul class="pull-left max-padding-left low-margin-left">                 
												<li><a href="/rings/moissanite-rings" onclick="categoryNavSelect('Moissanite Rings|topnav')">Moissanite</a></li>
												<li><a href="/lab-jewelry/lab-created-sapphire-rings" onclick="categoryNavSelect('Lab Created Sapphire Rings|topnav')">Lab Created Sapphire</a></li>
												<li><a href="/lab-jewelry/lab-created-emerald-rings" onclick="categoryNavSelect('Lab Created Emerald Rings|topnav')">Lab Created Emerald</a></li>
												<li><a href="/lab-jewelry/lab-created-ruby-rings" onclick="categoryNavSelect('Lab Created Ruby Rings|topnav')">Lab Created Ruby</a></li>
											</ul>
										</div>
										<div class="col-sm-3 col-xs-2 col-md-2 high-padding-bottom">
											<div class="high-margin-top low-margin-bottom showcase-bg-light padding-type-3 low-padding-left"><strong>Shop By Diamond</strong></div>
											<div class="clearfix"></div>
											<ul class="low-padding-left">
												<li class="ie8-remove"><a href="/buildyourown/ring?userStartWithPreference=diamonds" onclick="categoryNavSelect('Design Your Own Diamond Ring|topnav')">Design Your Own Diamond Ring</a></li>
												<li><a href="/rings/diamond-rings" onclick="categoryNavSelect('Diamond Rings|topnav')">Diamond</a></li>
												<li><a href="/rings/colored-diamond-rings/enhanced-blue-diamond" onclick="categoryNavSelect('Blue Diamond Rings|topnav')">Blue Diamond</a></li>
												<li><a href="/rings/colored-diamond-rings/enhanced-black-diamond" onclick="categoryNavSelect('Black Diamond Rings|topnav')">Black Diamond</a></li>
												<li><a href="/rings/coffee-diamond-rings" onclick="categoryNavSelect('Coffee Diamond Rings|topnav')">Coffee Diamond</a></li>
											</ul>
										</div>
										<div class="col-sm-3 col-xs-3 high-padding-bottom">
											<div class="high-margin-top low-margin-bottom showcase-bg-light padding-type-3 low-padding-left"><strong>Shop By Style</strong></div>
											<div class="clearfix"></div>
											<div class="col-sm-6 no-padding">
												<ul class="low-padding-left">
													<li><a href="/engagement-rings/halo-rings" onclick="categoryNavSelect('Halo Rings|topnav')">Halo</a></li>
													<li><a href="/rings/eternity-rings" onclick="categoryNavSelect('Eternity Rings|topnav')">Eternity</a></li>
													<li><a href="/engagement-rings/solitaire-rings" onclick="categoryNavSelect('Solitaire Rings|topnav')">Solitaire</a></li>
													<li><a href="/engagement-rings/three-stone-rings" onclick="categoryNavSelect('Three Stone Rings|topnav')">Three Stone</a></li>
													<li><a href="/collection/stackables" onclick="categoryNavSelect('Stackables Rings|topnav')">Stackables</a></li>
													<li><a href="/collection/vintage" onclick="categoryNavSelect('Vintage Rings|topnav')">Vintage</a></li>
													
													<?php /* <li><a href="/rings/cocktail-rings" onclick="categoryNavSelect('Cocktail Rings|topnav')">Cocktail</a></li> */ ?>
												</ul>
											</div>
											<div class="col-sm-6 col-xs-6 no-padding">
												<ul class="low-padding-left">
													<li><a href="/rings/heart-rings"  onclick="categoryNavSelect('Hearts Rings|topnav')">Heart</a></li>
													<li><a href="https://www.angara.com/rings?jewelry_styles=5944&amp;dir=asc" onclick="categoryNavSelect('Knot Rings|topnav')">Knot</a></li>
													<li><a href="/rings?order=position&amp;dir=asc&amp;no_cache=true&amp;jewelry_styles=4181" onclick="categoryNavSelect('Five Stone Rings|topnav')">Five Stone</a></li>
													<li><a href="/rings/split-shank-rings" onclick="categoryNavSelect('Split Shank Rings|topnav')">Split Shank</a></li>
													<?php /* <li><a href="/jewelry/illusion-set-diamonds" onclick="categoryNavSelect('Illusion Set Rings|topnav')">Illusion Set</a></li> */?>
													<li><a href="/mothers-jewelry/mother-rings" onclick="categoryNavSelect('Mothers Rings|topnav')">Mother's</a></li>
													<li><a href="/birthstone-jewelry/birthstone-rings" onclick="categoryNavSelect('Birthstone Rings|topnav')">Birthstone</a></li>
													<?php /* <li><a href="/collection/high-jewelry" onclick="categoryNavSelect('High Jewelry|topnav')">High Jewelry</a></li>
													<li><a href="/collection/tajmahal-sugarloaf" onclick="categoryNavSelect('Taj Mahal Rings|topnav')">Taj Mahal</a></li>
													<li><a href="/engagement-rings/wedding-ring-set" onclick="categoryNavSelect('Ring Set Rings|topnav')">Ring Set</a></li> */?>
												</ul>
											</div>
										</div>
										<div class="col-sm-2 col-xs-2 high-padding-bottom hidden-sm">
											<div class="high-margin-top low-margin-bottom showcase-bg-light padding-type-3 low-padding-left"><strong>Shop By Price</strong></div>
											<div class="clearfix"></div>
											<ul class="low-padding-left">
												<li><a href="/rings?content=no&amp;dir=asc&amp;order=price&amp;p=1&amp;price=1,250" onclick="categoryNavSelect('$250 & Under Rings|topnav')">$250 &amp; Under</a></li>
												<li><a href="/rings?content=no&amp;dir=asc&amp;order=price&amp;p=1&amp;price=251,500" onclick="categoryNavSelect('$251 - $500 Rings|topnav')">$251 - $500</a></li>
												<li><a href="/rings?content=no&amp;dir=asc&amp;order=price&amp;p=1&amp;price=501,1000" onclick="categoryNavSelect('$501 - $1000 Rings|topnav')">$501 - $1000</a></li>
												<li><a href="/rings?content=no&amp;dir=asc&amp;order=price&amp;p=1&amp;price=1001,1500" onclick="categoryNavSelect('$1001 - $1500 Rings|topnav')">$1001 - $1500</a></li>
												<li><a href="/rings?content=no&amp;dir=asc&amp;order=price&amp;p=1&amp;price=1501,2500" onclick="categoryNavSelect('$1501 - $2500 Rings|topnav')">$1501 - $2500</a></li>
												<li><a href="/rings?content=no&amp;dir=asc&amp;order=price&amp;p=1&amp;price=2501,99999" onclick="categoryNavSelect('Over $2500 Rings|topnav')">Over $2500</a></li>
											</ul>
										</div>
									</div>
								</div>
								<?php //necklaces categories starts ?>
								<div class="secondary-navbar ress-slider-item pull-left" id="sub-nav-necklaces">
									<div class="row">
										<div class="col-md-5 col-sm-6 col-xs-5 high-padding-bottom">
											<div class="high-margin-top low-margin-bottom showcase-bg-light padding-type-3 low-padding-left"><strong>Shop By Colored Gemstone</strong></div>
											<div class="clearfix"></div>
											<ul class="pull-left low-padding-left" >
												<li><a href="/pendants/sapphire-necklace-pendants" onclick="categoryNavSelect('Sapphire Necklaces|topnav')">Sapphire</a></li>
												<li><a href="/pendants/ruby-necklace-pendants" onclick="categoryNavSelect('Ruby Necklaces|topnav')">Ruby</a></li>
												<li><a href="/pendants/emerald-necklace-pendants" onclick="categoryNavSelect('Emerald Necklaces|topnav')">Emerald</a></li>
												<li><a href="/pendants/tanzanite-necklace-pendants" onclick="categoryNavSelect('Tanzanite Necklaces|topnav')">Tanzanite</a></li>
												<li><a href="/pendants/aquamarine-necklace-pendants" onclick="categoryNavSelect('Aquamarine Necklaces|topnav')">Aquamarine</a></li>
												<li><a href="/pendants/blue-topaz-necklace-pendants" onclick="categoryNavSelect('Blue Topaz Necklaces|topnav')">Blue Topaz</a></li>
												<li><a href="/pendants/black-onyx-necklace-pendants" onclick="categoryNavSelect('Black Onyx Necklaces|topnav')">Black Onyx</a></li>
												<li><a href="/pendants/citrine-necklace-pendants" onclick="categoryNavSelect('Citrine Necklaces|topnav')">Citrine</a></li>
											</ul>
											<ul class="pull-left max-padding-left low-margin-left">
												<li><a href="/pendants/pearl-necklace-pendants" onclick="categoryNavSelect('Pearl Necklaces|topnav')">Pearl</a></li>
												<li><a href="/pendants/morganite-necklace-pendants" onclick="categoryNavSelect('Morganite Necklaces|topnav')">Morganite</a></li>
												<li><a href="/pendants/garnet-necklace-pendants" onclick="categoryNavSelect('Garnet Necklaces|topnav')">Garnet</a></li>
												<li><a href="/pendants/opal-necklace-pendants" onclick="categoryNavSelect('Opal Necklaces|topnav')">Opal</a></li>
												<li><a href="/pendants/amethyst-necklace-pendants" onclick="categoryNavSelect('Amethyst Necklaces|topnav')">Amethyst</a></li>
												<li><a href="/pendants/peridot-necklace-pendants" onclick="categoryNavSelect('Peridot Necklaces|topnav')">Peridot</a></li>
												<li><a href="/pendants/pink-tourmaline-necklace-pendants" onclick="categoryNavSelect('Pink Tourmaline Necklaces|topnav')">Pink Tourmaline</a></li>
												
											</ul>
											<ul class="pull-left max-padding-left low-margin-left">
												<li><a href="/pendants/moissanite-necklace-pendants" onclick="categoryNavSelect('Moissanite Necklaces|topnav')">Moissanite</a></li>
												<li><a href="/lab-jewelry/lab-created-sapphire-necklace-pendants" onclick="categoryNavSelect('Lab Created Necklaces|topnav')">Lab Created Sapphire</a></li>
												<li><a href="/lab-jewelry/lab-created-emerald-necklace-pendants" onclick="categoryNavSelect('Lab Created Necklaces|topnav')">Lab Created Emerald</a></li>
												<li><a href="/lab-jewelry/lab-created-ruby-necklace-pendants" onclick="categoryNavSelect('Lab Created Necklaces|topnav')">Lab Created Ruby</a></li>
											</ul>
										</div>
										<div class="col-sm-3 col-xs-2 col-md-2 high-padding-bottom">
											<div class="high-margin-top low-margin-bottom showcase-bg-light padding-type-3 low-padding-left"><strong>Shop By Diamond</strong></div>
											<div class="clearfix"></div>
											<ul class="low-padding-left">	
												<li class="ie8-remove"><a href="/buildyourown/pendant?userStartWithPreference=diamonds" onclick="categoryNavSelect('Design Your Own Diamond Pendant|topnav')">Design Your Own Diamond Pendant</a></li>
												<li><a href="/pendants/diamond-necklace-pendants" onclick="categoryNavSelect('Diamond Necklaces|topnav')">Diamond</a></li>
												<li><a href="/pendants/colored-diamond-necklace-pendants/enhanced-blue-diamond" onclick="categoryNavSelect('Blue Diamond Necklace|topnav')">Blue Diamond</a></li>
												<li><a href="/pendants/colored-diamond-necklace-pendants/enhanced-black-diamond" onclick="categoryNavSelect('Black Diamond Necklace|topnav')">Black Diamond</a></li>
												<li><a href="/pendants/coffee-diamond-pendant-necklaces" onclick="categoryNavSelect('Coffee Diamond Necklace|topnav')">Coffee Diamond</a></li>
											</ul>
										</div>
										<div class="col-sm-3 col-xs-3 high-padding-bottom">
											<div class="high-margin-top low-margin-bottom showcase-bg-light padding-type-3 low-padding-left"><strong>Shop By Style</strong></div>
											<div class="clearfix"></div>
											<div class="col-sm-6 col-xs-6">
												<ul class="low-padding-left">
													<li><a href="/pendants?order=position&amp;dir=asc&amp;no_cache=true&amp;jewelry_styles=4183" onclick="categoryNavSelect('Halo Necklaces|topnav')">Halo</a></li>
													<li><a href="/pendants/v-bale-pendants" onclick="categoryNavSelect('V-Bale Necklaces|topnav')">V-Bale</a></li>
													<li><a href="/pendants/solitaire-necklace-pendants" onclick="categoryNavSelect('Solitaire Necklaces|topnav')">Solitaire</a></li>
													<li><a href="/pendants?order=position&amp;dir=asc&amp;no_cache=true&amp;jewelry_styles=4176" onclick="categoryNavSelect('Dangle Necklaces|topnav')">Dangle</a></li>
													<li><a href="/pendants/journey-necklace-pendants" onclick="categoryNavSelect('Journey Necklaces|topnav')">Journey</a></li>
													<li><a href="/pendants/cross-necklace-pendants" onclick="categoryNavSelect('Crosses Necklaces|topnav')">Crosses</a></li>
													<?php /* <li><a href="/pendants/fashion-necklace-pendants" onclick="categoryNavSelect('Fashion Necklaces|topnav')">Fashion</a></li> */ ?>
												</ul>
											</div>
											<div class="col-sm-6 col-xs-6">
												<ul class="low-padding-left">
													<li><a href="/pendants/heart-necklace-pendants" onclick="categoryNavSelect('Heart Necklaces|topnav')">Heart</a></li>
													<li><a href="/pendants?jewelry_styles=5944&amp;dir=asc" onclick="categoryNavSelect('Knot Necklaces|topnav')">Knot</a></li>
													<li><a href="/pendants?jewelry_styles=4172"  onclick="categoryNavSelect('Cluster Necklaces|topnav')">Cluster</a></li>
													<li><a href="/collection/facets" onclick="categoryNavSelect('Matching Set|topnav')">Matching Set</a></li>
													<li><a href="/jewelry/dancing-gemstone-jewelry" onclick="categoryNavSelect('Dancing Diamonds|topnav')">Dancing Gemstones</a></li>
													<li><a href="/birthstone-jewelry/birthstone-pendants" onclick="categoryNavSelect('Birthstone Necklaces|topnav')">Birthstone</a></li>
												</ul>
											</div>
										</div>
										<div class="col-sm-2 col-xs-2 high-padding-bottom hidden-sm">
											<div class="high-margin-top low-margin-bottom showcase-bg-light padding-type-3 low-padding-left"><strong>Shop By Price</strong></div>
											<div class="clearfix"></div>
											<ul class="low-padding-left">
												<li><a href="/pendants?content=no&amp;dir=asc&amp;order=price&amp;p=1&amp;price=1,250" onclick="categoryNavSelect('$250 & Under Necklaces|topnav')">$250 &amp; Under</a></li>
												<li><a href="/pendants?content=no&amp;dir=asc&amp;order=price&amp;p=1&amp;price=251,500" onclick="categoryNavSelect('$251 - $500 Necklaces|topnav')">$251 - $500</a></li>
												<li><a href="/pendants?content=no&amp;dir=asc&amp;order=price&amp;p=1&amp;price=501,1000" onclick="categoryNavSelect('$501 - $1000 Necklaces|topnav')">$501 - $1000</a></li>
												<li><a href="/pendants?content=no&amp;dir=asc&amp;order=price&amp;p=1&amp;price=1001,1500" onclick="categoryNavSelect('$1001 - $1500 Necklaces|topnav')">$1001 - $1500</a></li>
												<li><a href="/pendants?content=no&amp;dir=asc&amp;order=price&amp;p=1&amp;price=1501,2500" onclick="categoryNavSelect('$1501 - $2500 |topnav')">$1501 - $2500</a></li>
												<li><a href="/pendants?content=no&amp;dir=asc&amp;order=price&amp;p=1&amp;price=2501,99999" onclick="categoryNavSelect('Over $2500 Necklaces|topnav')">Over $2500</a></li>
											</ul>
										</div>
									</div>
								</div>
								<?php //earrings categories starts ?>
								<div class="secondary-navbar ress-slider-item pull-left" id="sub-nav-earrings">
									<div class="row">
										<div class="col-md-5 col-sm-6 col-xs-5 high-padding-bottom">
											<div class="high-margin-top low-margin-bottom showcase-bg-light padding-type-3 low-padding-left"><strong>Shop By Colored Gemstone</strong></div>
											<div class="clearfix"></div>
											<ul class="pull-left low-padding-left">
												<li><a href="/earrings/sapphire-earrings" onclick="categoryNavSelect('Sapphire Earrings|topnav')">Sapphire</a></li>
												<li><a href="/earrings/ruby-earrings" onclick="categoryNavSelect('Ruby Earrings|topnav')">Ruby</a></li>
												<li><a href="/earrings/emerald-earrings" onclick="categoryNavSelect('Emerald Earrings|topnav')">Emerald</a></li>
												<li><a href="/earrings/tanzanite-earrings" onclick="categoryNavSelect('Tanzanite Earrings|topnav')">Tanzanite</a></li>
												<li><a href="/earrings/aquamarine-earrings" onclick="categoryNavSelect('Aquamarine Earrings|topnav')">Aquamarine</a></li>
												<li><a href="/earrings/blue-topaz-earrings" onclick="categoryNavSelect('Blue Topaz Earrings|topnav')">Blue Topaz</a></li>
												<li><a href="/earrings/black-onyx-earrings" onclick="categoryNavSelect('Black Onyx Earrings|topnav')">Black Onyx</a></li>
												<li><a href="/earrings/citrine-earrings" onclick="categoryNavSelect('Citrine Earrings|topnav')">Citrine</a></li>
											</ul>
											<ul class="pull-left max-padding-left low-margin-left">
												<li><a href="/earrings/pearl-earrings" onclick="categoryNavSelect('Pearl Earrings|topnav')">Pearl</a></li>
												<li><a href="/earrings/morganite-earrings" onclick="categoryNavSelect('Morganite Earrings|topnav')">Morganite</a></li>
												<li><a href="/earrings/garnet-earrings" onclick="categoryNavSelect('Garnet Earrings|topnav')">Garnet</a></li>
												<li><a href="/earrings/opal-earrings" onclick="categoryNavSelect('Opal Earrings|topnav')">Opal</a></li>
												<li><a href="/earrings/amethyst-earrings" onclick="categoryNavSelect('Amethyst Earrings|topnav')">Amethyst</a></li>
												<li><a href="/earrings/peridot-earrings" onclick="categoryNavSelect('Peridot Earrings|topnav')">Peridot</a></li>
												<li><a href="/earrings/pink-tourmaline-earrings" onclick="categoryNavSelect('Pink Tourmaline Earrings|topnav')">Pink Tourmaline</a></li>
											</ul>
											<ul class="pull-left max-padding-left low-margin-left">
												<li><a href="/earrings/moissanite-earrings" onclick="categoryNavSelect('Moissanite Earrings|topnav')">Moissanite</a></li>
												<li><a href="/lab-jewelry/lab-created-sapphire-earrings" onclick="categoryNavSelect('Lab Created Sapphire Earrings|topnav')">Lab Created Sapphire</a></li>
												<li><a href="/lab-jewelry/lab-created-emerald-earrings" onclick="categoryNavSelect('Lab Created Emerald Earrings|topnav')">Lab Created Emerald</a></li>
												<li><a href="/lab-jewelry/lab-created-ruby-earrings" onclick="categoryNavSelect('Lab Created Ruby Earrings|topnav')">Lab Created Ruby</a></li>
											</ul>
										</div>
										<div class="col-sm-3 col-xs-2 col-md-2 high-padding-bottom">
											<div class="high-margin-top low-margin-bottom showcase-bg-light padding-type-3 low-padding-left"><strong>Shop By Diamond</strong></div>
											<div class="clearfix"></div>
											<ul class="low-padding-left">							
												<li><a href="/earrings/diamond-earrings" onclick="categoryNavSelect('Diamond Earrings|topnav')">Diamond</a></li>
												<li><a href="/earrings/colored-diamond-earrings/enhanced-blue-diamond" onclick="categoryNavSelect('Blue Diamond Earrings|topnav')">Blue Diamond</a></li>
												<li><a href="/earrings/colored-diamond-earrings/enhanced-black-diamond" onclick="categoryNavSelect('Black Diamond Earrings|topnav')">Black Diamond</a></li>
												<li><a href="/earrings/coffee-diamond-earrings" onclick="categoryNavSelect('Coffee Diamond Earrings|topnav')">Coffee Diamond</a></li>
											</ul>
										</div>
										<div class="col-sm-3 col-xs-3 high-padding-bottom">
											<div class="high-margin-top low-margin-bottom showcase-bg-light padding-type-3 low-padding-left"><strong>Shop By Style</strong></div>
											<div class="clearfix"></div>
											<div class="col-sm-6 col-xs-6 no-padding">
												<ul class="low-padding-left">
													<li><a href="/earrings?jewelry_styles=4183&amp;order=position&amp;dir=asc&amp;no_cache=true" onclick="categoryNavSelect('Halo Earrings|topnav')">Halo</a></li>
													<li><a href="/earrings/drop-earrings" onclick="categoryNavSelect('Drops Earrings|topnav')">Drops</a></li>
													<li><a href="/earrings/hoop-earrings" onclick="categoryNavSelect('Hoops Earrings|topnav')">Hoops</a></li>
													<li><a href="/earrings/journey-earrings" onclick="categoryNavSelect('Journey Earrings|topnav')">Journey</a></li>
													<li><a href="/earrings/three-stone-earrings" onclick="categoryNavSelect('Three Stone Earrings|topnav')">Three Stone</a></li>
													<li><a href="/earrings/leverback-earrings" onclick="categoryNavSelect('Leverback Earrings|topnav')">Leverback</a></li>
													<?php /* <li><a href="/earrings/fashion-earrings" onclick="categoryNavSelect('Fashion Earrings|topnav')">Fashion</a></li> */ ?>
												</ul>
											</div>
											<div class="col-sm-6 col-xs-6 no-padding">
												<ul class="low-padding-left">
													<li><a href="/earrings/stud-earrings" onclick="categoryNavSelect('Stud Earrings|topnav')">Stud Earrings</a></li>
													<li><a href="/earrings/heart-earrings"  onclick="categoryNavSelect('Hearts Earrings|topnav')">Heart</a></li>
													<li><a href=" https://www.angara.com/earrings?jewelry_styles=5944&amp;dir=asc" onclick="categoryNavSelect('Knot Earrings|topnav')">Knot</a></li>
													<li><a href="/jewelry/dancing-gemstone-jewelry" onclick="categoryNavSelect('Dancing Diamonds|topnav')">Dancing Gemstones</a></li>
													<li><a href="/birthstone-jewelry/birthstone-earrings" onclick="categoryNavSelect('Birthstone Earrings|topnav')">Birthstone</a></li>
												</ul>
											</div>
										</div>
										<div class="col-sm-2 col-xs-2 high-padding-bottom hidden-sm">
											<div class="high-margin-top low-margin-bottom showcase-bg-light padding-type-3 low-padding-left"><strong>Shop By Price</strong></div>
											<div class="clearfix"></div>
											<ul class="low-padding-left">
												<li><a href="/earrings?content=no&amp;dir=asc&amp;order=price&amp;p=1&amp;price=1,250" onclick="categoryNavSelect('$250 & Under Earrings|topnav')">$250 &amp; Under</a></li>
												<li><a href="/earrings?content=no&amp;dir=asc&amp;order=price&amp;p=1&amp;price=251,500" onclick="categoryNavSelect('$251 - $500 Earrings|topnav')">$251 - $500</a></li>
												<li><a href="/earrings?content=no&amp;dir=asc&amp;order=price&amp;p=1&amp;price=501,1000" onclick="categoryNavSelect('$501 - $1000 Earrings|topnav')">$501 - $1000</a></li>
												<li><a href="/earrings?content=no&amp;dir=asc&amp;order=price&amp;p=1&amp;price=1001,1500" onclick="categoryNavSelect('$1001 - $1500 Earrings|topnav')">$1001 - $1500</a></li>
												<li><a href="/earrings?content=no&amp;dir=asc&amp;order=price&amp;p=1&amp;price=1501,2500" onclick="categoryNavSelect('$1501 - $2500 Earrings|topnav')">$1501 - $2500</a></li>
												<li><a href="/earrings?content=no&amp;dir=asc&amp;order=price&amp;p=1&amp;price=2501,99999" onclick="categoryNavSelect('Over $2500 Earrings|topnav')">Over $2500</a></li>
											</ul>
										</div>
									</div>
								</div>
								<?php //engagement categories starts ?>
								<div class="secondary-navbar ress-slider-item pull-left" id="sub-nav-engagement">
									<div class="row">
										<div class="col-sm-4 col-xs-3 col-md-3 high-padding-bottom">
											<div class="high-margin-top low-margin-bottom showcase-bg-light padding-type-3 low-padding-left"><strong>Shop By Stone</strong></div>
											<div class="clearfix"></div>
											<ul class="pull-left low-padding-left">
												<li><a href="/engagement-rings/sapphire-engagement-rings" onclick="categoryNavSelect('Sapphire Engagement|topnav')">Sapphire</a></li>
												<li><a href="/engagement-rings/ruby-engagement-rings" onclick="categoryNavSelect('Ruby Engagement|topnav')">Ruby</a></li>
												<li><a href="/engagement-rings/emerald-engagement-rings" onclick="categoryNavSelect('Emerald Engagement|topnav')">Emerald</a></li>
												<li><a href="/engagement-rings/tanzanite-engagement-rings" onclick="categoryNavSelect('Tanzanite Engagement|topnav')">Tanzanite</a></li>
											</ul>
											<ul class="pull-left max-padding-left max-margin-left">
												<li><a href="/engagement-rings/diamond-engagement-rings" onclick="categoryNavSelect('Diamond Engagement|topnav')">Diamond</a></li>
												<li><a href="/engagement-rings/colored-diamond-engagement-rings/enhanced-black-diamond-engagement" onclick="categoryNavSelect('Black Diamond Engagement|topnav')">Black Diamond</a></li>
												<li><a href="/engagement-rings/colored-diamond-engagement-rings/enhanced-blue-diamond-engagement" onclick="categoryNavSelect('Blue Diamond Engagement|topnav')">Blue Diamond</a></li> 
												<li><a href="/engagement-rings/black-onyx-engagement-rings" onclick="categoryNavSelect('Black Onyx Engagement|topnav')">Black Onyx</a></li>                         
											</ul>
										</div>
										<div class="col-sm-2 col-xs-2 high-padding-bottom">
											<div class="high-margin-top low-margin-bottom showcase-bg-light padding-type-3 low-padding-left"><strong>Shop By Style</strong></div>
											<div class="clearfix"></div>
											<ul class="low-padding-left">
												<li><a href="/engagement-rings/halo-rings" onclick="categoryNavSelect('Halo Engagement|topnav')">Halo</a></li>
												<li><a href="/rings/eternity-rings" onclick="categoryNavSelect('Eternity Engagement|topnav')">Eternity</a></li>
												<li><a href="/engagement-rings/solitaire-rings" onclick="categoryNavSelect('Solitaire Engagement|topnav')">Solitaire</a></li>
												<li><a href="/engagement-rings/three-stone-rings" onclick="categoryNavSelect('Three Stone Engagement|topnav')">Three Stone</a></li>
												<li><a href="/rings?jewelry_styles=4169&amp;order=position&amp;dir=asc&amp;no_cache=true" onclick="categoryNavSelect('Cathedral Engagement|topnav')">Cathedral</a></li>
												<?php /* <li><a href="/engagement-rings?content=no&amp;order=position&amp;dir=asc&amp;no_cache=true&amp;jewelry_styles=4180" onclick="categoryNavSelect('Fashion Engagement|topnav')">Fashion</a></li> */ ?>
											</ul>
										</div>
										<div class="col-sm-3 col-xs-2 col-md-2 high-padding-bottom">
											<div class="high-margin-top low-margin-bottom showcase-bg-light padding-type-3 low-padding-left"><strong>Shop By Collection</strong></div>
											<div class="clearfix"></div>
											<ul class="low-padding-left">                          
												<li><a href="/collection/vintage" onclick="categoryNavSelect('Vintage Engagement|topnav')">Vintage</a></li>
												<li><a href="/engagement-rings/promise-rings" onclick="categoryNavSelect('Promise Engagement|topnav')">Promise</a></li>
												<li><a href="/wedding-rings/wedding-bands" onclick="categoryNavSelect('Wedding Engagement|topnav')">Wedding</a></li>
												<li><a href="/engagement-rings/wedding-ring-set" onclick="categoryNavSelect('Ring Set Engagement|topnav')">Bridal Set</a></li>
											</ul>
										</div>
										<div class="col-sm-2 col-xs-2 high-padding-bottom">
											<div class="high-margin-top low-margin-bottom showcase-bg-light padding-type-3 low-padding-left"><strong>Shop By Metal</strong></div>
											<div class="clearfix"></div>
											<ul class="low-padding-left">
												<li><a href="/engagement-rings?content=no&amp;filterable_metal_types=4159&amp;order=position&amp;dir=asc&amp;no_cache=true"
								onclick="categoryNavSelect('Silver Engagement|topnav')">Silver</a></li>
												<li><a href="/engagement-rings?content=no&amp;filterable_metal_types=4160&amp;order=position&amp;dir=asc&amp;no_cache=true"
								onclick="categoryNavSelect('White Gold Engagement|topnav')">White Gold</a></li>
												<li><a href="/engagement-rings?content=no&amp;filterable_metal_types=4161&amp;order=position&amp;dir=asc&amp;no_cache=true"
								onclick="categoryNavSelect('Yellow Gold Engagement|topnav')">Yellow Gold</a></li>
												<?php /* <li><a href="/engagement-rings?content=no&amp;filterable_metal_types=4164&amp;order=position&amp;dir=asc&amp;no_cache=true"
								onclick="categoryNavSelect('Two Tone Gold Engagement|topnav')">Two Tone Gold</a></li> */ ?>
												<li><a href="/engagement-rings?content=no&amp;filterable_metal_types=4162&amp;order=position&amp;dir=asc&amp;no_cache=true"        
								onclick="categoryNavSelect('Platinum Engagement|topnav')">Platinum</a></li>
												<li><a href="/engagement-rings?content=no&filterable_metal_types=4163&order=position&dir=asc&no_cache=true"        
								onclick="categoryNavSelect('Rose Gold Engagement|topnav')">Rose Gold</a></li>
											</ul>
										</div>
										<div class="col-sm-2 col-xs-2 high-padding-bottom hidden-sm">
											<div class="high-margin-top low-margin-bottom showcase-bg-light padding-type-3 low-padding-left"><strong>Shop By Price</strong></div>
											<div class="clearfix"></div>
											<ul class="low-padding-left">
												<li><a href="/engagement-rings?content=no&amp;dir=asc&amp;order=price&amp;p=1&amp;price=1,250" 
								onclick="categoryNavSelect('$250 & Under Engagement|topnav')">$250 &amp; Under</a></li>
												<li><a href="/engagement-rings?content=no&amp;dir=asc&amp;order=price&amp;p=1&amp;price=251,500" 
								onclick="categoryNavSelect('$251 - $500 Engagement|topnav')">$251 - $500</a></li>
												<li><a href="/engagement-rings?content=no&amp;dir=asc&amp;order=price&amp;p=1&amp;price=501,1000" 
								onclick="categoryNavSelect('$501 - $1000 Engagement|topnav')">$501 - $1000</a></li>
												<li><a href="/engagement-rings?content=no&amp;dir=asc&amp;order=price&amp;p=1&amp;price=1001,1500" 
								onclick="categoryNavSelect('$1001 - $1500 Engagement|topnav')">$1001 - $1500</a></li>
												<li><a href="/engagement-rings?content=no&amp;dir=asc&amp;order=price&amp;p=1&amp;price=1501,2500" 
								onclick="categoryNavSelect('$1501 - $2500 Engagement|topnav')">$1501 - $2500</a></li>
												<li><a href="/engagement-rings?content=no&amp;dir=asc&amp;order=price&amp;p=1&amp;price=2501,99999" 
								onclick="categoryNavSelect('Over $2500 Engagement|topnav')">Over $2500</a></li>
											</ul>
										</div>
									</div>
								</div>
								<?php //wedding categories starts ?>
								<div class="secondary-navbar ress-slider-item pull-left" id="sub-nav-wedding">
									<div class="row">
										<div class="col-md-5 col-sm-6 col-xs-5 no-padding">
											<div class="col-sm-4 col-xs-4">
												<div class="high-margin-top low-margin-bottom showcase-bg-light padding-type-3 low-padding-left"><strong>For Him</strong></div>
												<div class="clearfix"></div>
												<ul class="low-padding-left">
													<li class="low-margin-left"><a href="/wedding-rings/mens-plain-wedding-bands" onclick="categoryNavSelect('Plain Wedding Bands|topnav')">Plain</a></li>
													<li class="low-margin-left"><a href="/wedding-rings/mens-gemstone-and-diamond-bands" onclick="categoryNavSelect('Gemstone Wedding Bands|topnav')">Gemstone</a></li>
													<li class="low-margin-left"><a href="/wedding-rings/mens-diamond-wedding-bands" onclick="categoryNavSelect('Diamond Wedding Bands|topnav')">Diamond</a></li>
													<li class="low-margin-left"><a href="/wedding-rings/mens-wedding-bands" onclick="categoryNavSelect('All Bands|topnav')">All Bands</a></li>
												</ul>
											</div>
											<div class="col-sm-4 col-xs-4">
												<div class="high-margin-top low-margin-bottom showcase-bg-light padding-type-3 low-padding-left"><strong>For Her</strong></div>
												<div class="clearfix"></div>
												<ul class="low-padding-left">
													<li class="low-margin-left"><a href="/wedding-rings/womens-plain-wedding-bands" onclick="categoryNavSelect('Plain Wedding Bands|topnav')">Plain</a></li>
													<li class="low-margin-left"><a href="/wedding-rings/womens-gemstone-and-diamond-bands" onclick="categoryNavSelect('Gemstone Wedding Bands|topnav')">Gemstone</a></li>
													<li class="low-margin-left"><a href="/wedding-rings/womens-diamond-wedding-bands" onclick="categoryNavSelect('Diamond Wedding Bands|topnav')">Diamond</a></li>
													<li class="low-margin-left"><a href="/wedding-rings/womens-wedding-bands" onclick="categoryNavSelect('All Bands|topnav')">All Bands</a></li>
												</ul>
											</div>
											<div class="col-sm-4 col-xs-4">
												<div class="high-margin-top low-margin-bottom showcase-bg-light padding-type-3 low-padding-left"><strong>Shop By Type</strong></div>
												<div class="clearfix"></div>
												<ul class="low-padding-left">
													<li><a href="/wedding-rings/wedding-bands?order=position&amp;dir=asc&amp;no_cache=true&amp;jewelry_styles=4553" onclick="categoryNavSelect('Half Eternity Wedding Bands|topnav')">Half Eternity</a></li>
													<li><a href="/wedding-rings/wedding-bands?jewelry_styles=4179&amp;order=position&amp;dir=asc&amp;no_cache=true" onclick="categoryNavSelect('Eternity Wedding Bands|topnav')">Eternity</a></li>
													<li><a href="/rings/stackable-bands" onclick="categoryNavSelect('Stackables Wedding Bands|topnav')">Stackables</a></li>
													<li><a href="/wedding-rings/comfort-fit-wedding-bands" onclick="categoryNavSelect('Comfort-Fit Wedding Bands|topnav')">Comfort-Fit</a></li>
												</ul>
											</div>
										</div>
										<div class="col-sm-6 col-xs-7 col-md-7">
											<div class="col-sm-8 col-xs-6 col-md-6">
												<div class="high-margin-top low-margin-bottom showcase-bg-light padding-type-3 low-padding-left"><strong>Shop By Stone</strong></div>
												<div class="clearfix"></div>
												<div class="col-sm-6 col-xs-6">
													<ul class="low-padding-left">
														<li><a href="/wedding-rings/wedding-bands?filterable_stone_names=4130&amp;order=position&amp;dir=asc&amp;no_cache=true" onclick="categoryNavSelect('Diamond Wedding Bands|topnav')">Diamond</a></li>
														<li><a href="/wedding-rings/wedding-bands?filterable_stone_names=4556&amp;order=position&amp;dir=asc&amp;no_cache=true" onclick="categoryNavSelect('Blue Diamond Wedding Bands|topnav')">Blue Diamond</a></li>
														<li><a href="/wedding-rings/wedding-bands?filterable_stone_names=4555&amp;order=position&amp;dir=asc&amp;no_cache=true" onclick="categoryNavSelect('Black Diamond Wedding Bands|topnav')">Black Diamond</a></li>
													</ul>
												</div>
												<div class="col-sm-6 col-xs-6">
													<ul class="low-padding-left">
														<li><a href="/wedding-rings/wedding-bands?filterable_stone_names=4144&amp;order=position&amp;dir=asc&amp;no_cache=true" onclick="categoryNavSelect('Sapphire Wedding Bands|topnav')">Sapphire</a></li>
														<li><a href="/wedding-rings/wedding-bands?filterable_stone_names=4143&amp;order=position&amp;dir=asc&amp;no_cache=true" onclick="categoryNavSelect('Ruby Wedding Bands|topnav')">Ruby</a></li>
														<li><a href="/wedding-rings/wedding-bands?filterable_stone_names=4131&amp;order=position&amp;dir=asc&amp;no_cache=true" onclick="categoryNavSelect('Emerald Wedding Bands|topnav')">Emerald</a></li>
														<li><a href="/wedding-rings/wedding-bands?order=position&amp;dir=asc&amp;no_cache=true&amp;filterable_stone_names=4124" onclick="categoryNavSelect('Aquamarine Wedding Bands|topnav')">Aquamarine</a></li>
														<li><a href="/wedding-rings/wedding-bands?order=position&amp;dir=asc&amp;no_cache=true&amp;filterable_stone_names=4146" onclick="categoryNavSelect('Tanzanite Wedding Bands|topnav')">Tanzanite</a></li>
													</ul>
												</div>
											</div>
											<div class="col-sm-4 col-xs-3 col-md-3">
												<div class="high-margin-top low-margin-bottom showcase-bg-light padding-type-3 low-padding-left"><strong>Shop By Metal</strong></div>
												<div class="clearfix"></div>
												<ul class="low-padding-left">
													<li><a href="/wedding-rings/wedding-bands?filterable_metal_types=4159&amp;order=position&amp;dir=asc&amp;no_cache=true" onclick="categoryNavSelect('Silver Wedding Bands|topnav')">Silver</a></li>
													<li><a href="/wedding-rings/wedding-bands?filterable_metal_types=4160&amp;order=position&amp;dir=asc&amp;no_cache=true" onclick="categoryNavSelect('White Gold Wedding Bands|topnav')">White Gold</a></li>
													<li><a href="/wedding-rings/wedding-bands?filterable_metal_types=4161&amp;order=position&amp;dir=asc&amp;no_cache=true" onclick="categoryNavSelect('Yellow Gold Wedding Bands|topnav')">Yellow Gold</a></li>
													<li><a href="/wedding-rings/wedding-bands?filterable_metal_types=4164&amp;order=position&amp;dir=asc&amp;no_cache=true" onclick="categoryNavSelect('Two Tone Gold Wedding Bands|topnav')">Two Tone Gold</a></li>
													<li><a href="/wedding-rings/wedding-bands?filterable_metal_types=4162&amp;order=position&amp;dir=asc&amp;no_cache=true" onclick="categoryNavSelect('Platinum Wedding Bands|topnav')">Platinum</a></li>
												</ul>
											</div>
											<div class="col-sm-3 col-xs-3">
												<div class="high-margin-top low-margin-bottom showcase-bg-light padding-type-3 low-padding-left"><strong>Shop By Price</strong></div>
												<div class="clearfix"></div>
												<ul class="low-padding-left">
													<li><a href="/wedding-rings/wedding-bands?dir=asc&amp;order=price&amp;p=1&amp;price=1,250" onclick="categoryNavSelect('$250 & Under Wedding Bands|topnav')">$250 &amp; Under</a></li>
													<li><a href="/wedding-rings/wedding-bands?dir=asc&amp;order=price&amp;p=1&amp;price=251,500" onclick="categoryNavSelect('$251 - $500 Wedding Bands|topnav')">$251 - $500</a></li>
													<li><a href="/wedding-rings/wedding-bands?dir=asc&amp;order=price&amp;p=1&amp;price=501,1000" onclick="categoryNavSelect('$501 - $1000 Wedding Bands|topnav')">$501 - $1000</a></li>
													<li><a href="/wedding-rings/wedding-bands?dir=asc&amp;order=price&amp;p=1&amp;price=1001,1500" onclick="categoryNavSelect('$1001 - $1500 Wedding Bands|topnav')">$1001 - $1500</a></li>
													<li><a href="/wedding-rings/wedding-bands?dir=asc&amp;order=price&amp;p=1&amp;price=1501,2000" onclick="categoryNavSelect('$1501 - $2000 Wedding Bands|topnav')">$1501 - $2000</a></li>
													<li><a href="/wedding-rings/wedding-bands?dir=asc&amp;order=price&amp;p=1&amp;price=2001,99999" onclick="categoryNavSelect('Over $2000 Wedding Bands|topnav')">Over $2000</a></li>
												</ul>
											</div>
										</div>
									</div>
								</div>
								<?php //bracelet categories starts ?>
								<div class="secondary-navbar ress-slider-item pull-left" id="sub-nav-bracelet">
									<div class="row">
										<div class="col-sm-2 col-xs-2 high-padding-bottom">
											<div class="high-margin-top low-margin-bottom showcase-bg-light padding-type-3 low-padding-left"><strong>Shop By Stone</strong></div>
											<div class="clearfix"></div>
											<ul class="pull-left low-padding-left">
												<li><a href="/bracelets/diamond-bracelets" onclick="categoryNavSelect('Diamond Bracelets|topnav')">Diamond</a></li>
												<li><a href="/bracelets/gemstone-bracelets?filterable_stone_names=4144" onclick="categoryNavSelect('Sapphire Bracelets|topnav')">Sapphire</a></li>
												<li><a href="/bracelets/gemstone-bracelets?filterable_stone_names=4143" onclick="categoryNavSelect('Ruby Bracelets|topnav')">Ruby</a></li>
												<li><a href="/bracelets/gemstone-bracelets?filterable_stone_names=4131" onclick="categoryNavSelect('Emerald Bracelets|topnav')">Emerald</a></li>             
											</ul>
										</div>
										<div class="col-sm-2 col-xs-2 high-padding-bottom">
											<div class="high-margin-top low-margin-bottom showcase-bg-light padding-type-3 low-padding-left"><strong>Shop By Style</strong></div>
											<div class="clearfix"></div>
											<ul class="low-padding-left">
												<li><a href="/bracelets?jewelry_styles=4184" onclick="categoryNavSelect('Heart Bracelets|topnav')">Heart</a></li>
												<li><a href="/bracelets?jewelry_styles=6188" onclick="categoryNavSelect('Tennis Bracelets|topnav')">Tennis</a></li>
												<li><a href="/bracelets?jewelry_styles=6189" onclick="categoryNavSelect('Infinity Bracelets|topnav')">Infinity</a></li>
												<?php /* <li><a href="/bracelets?jewelry_styles=4180" onclick="categoryNavSelect('Fashion Bracelets|topnav')">Fashion</a></li> */ ?>
												<li><a href="/bracelets/charm-bracelets" onclick="categoryNavSelect('Charms Bracelets|topnav')">Charms</a></li>
											</ul>
										</div>
										<div class="col-sm-3 col-xs-2 col-md-2 high-padding-bottom">
											<div class="high-margin-top low-margin-bottom showcase-bg-light padding-type-3 low-padding-left"><strong>Shop By Metal</strong></div>
											<div class="clearfix"></div>
											<ul class="low-padding-left">							
												<li><a href="/bracelets?filterable_metal_types=4159" onclick="categoryNavSelect('Silver Bracelets|topnav')">Silver</a></li>                          
												<li><a href="/bracelets?filterable_metal_types=4160" onclick="categoryNavSelect('White Gold Bracelets|topnav')">White Gold</a></li>
												<li><a href="/bracelets?filterable_metal_types=4161" onclick="categoryNavSelect('Yellow Gold Bracelets|topnav')">Yellow Gold</a></li>
											</ul>
										</div>
										<div class="col-sm-2 col-xs-2 high-padding-bottom hidden-sm">
											<div class="high-margin-top low-margin-bottom showcase-bg-light padding-type-3 low-padding-left"><strong>Shop By Price</strong></div>
											<div class="clearfix"></div>
											<ul class="low-padding-left">
												<li><a href="/bracelets?dir=asc&amp;order=price&amp;p=1&amp;price=1,500" onclick="categoryNavSelect('$500 & Under Bracelets|topnav')">$500 &amp; Under</a></li>
												<li><a href="/bracelets?dir=asc&amp;order=price&amp;p=1&amp;price=501,1000" onclick="categoryNavSelect('$501 - $1000 Bracelets|topnav')">$501 - $1000</a></li>
												<li><a href="/bracelets?dir=asc&amp;order=price&amp;p=1&amp;price=1001,1500" onclick="categoryNavSelect('$1000 - $1500 Bracelets|topnav')">$1000 - $1500</a></li>
												<li><a href="/bracelets?dir=asc&amp;order=price&amp;p=1&amp;price=1501,2000" onclick="categoryNavSelect('$1500 - $2000 Bracelets|topnav')">$1500 - $2000</a></li>
												<li><a href="/bracelets?dir=asc&amp;order=price&amp;p=1&amp;price=2001,99999" onclick="categoryNavSelect('Over $2000 Bracelets|topnav')">Over $2000</a></li>
											</ul>
										</div>
									</div>
								</div>
								<?php //gift categories starts ?>
								<div class="secondary-navbar ress-slider-item pull-left" id="sub-nav-gifts">
									<div class="row">
										<div class="col-md-5 col-sm-4 col-xs-5">
											<div class="col-md-4 col-sm-6 col-xs-4 high-padding-bottom">
												<div class="high-margin-top low-margin-bottom showcase-bg-light padding-type-3 low-padding-left"><strong>Collection</strong></div>
												<div class="clearfix"></div>
												<ul class="pull-left low-padding-left" >
													<li><a href="/collection/knotty-heart-jewelry" onclick="categoryNavSelect('Knotty Heart Collection|topnav')">Knotty Heart</a></li>
													<li><a href="/collection/infinity-jewelry" onclick="categoryNavSelect('Infinity Collection|topnav')">Infinity</a></li>
													<li><a href="/jewelry/coffee-diamond-jewelry" onclick="categoryNavSelect('Coffee Diamond Collection|topnav')">Coffee Diamond</a></li>
													<li><a href="/jewelry/two-stone-jewelry" onclick="categoryNavSelect('MeWe Collection|topnav')">Me We</a></li>
													<li><a href="/collection/wear-your-luck" onclick="categoryNavSelect('wear your luck Collection|topnav')">Wear Your Luck</a></li>
												</ul>
											</div>
											<div class="col-md-4 col-sm-6 col-xs-4 high-padding-bottom">
												<div class="high-margin-top low-margin-bottom showcase-bg-light padding-type-3 low-padding-left"><strong>Special Day</strong></div>
												<div class="clearfix"></div>
												<ul class="pull-left low-padding-left" >  
													<li><a href="/valentine-gifts" onclick="categoryNavSelect('Valentines Day Gifts|topnav')">Valentine's Day</a></li>
													<li><a href="/mothers-jewelry" onclick="categoryNavSelect('Mothers Day Jewelry Gifts|topnav')">Mother's Day</a></li>
													<li><a href="/jewelry-gifts/st-patricks-gifts" onclick="categoryNavSelect('St. Patricks Gifts|topnav')">St. Patrick's Day</a></li>
													<li><a href="/jewelry-gifts/thanksgiving-gifts" onclick="categoryNavSelect('Thanksgiving Gifts|topnav')">Thanksgiving</a></li>
													<li><a href="/jewelry-gifts/christmas-gifts" onclick="categoryNavSelect('Christmas Gifts|topnav')">Christmas</a></li>
													<li><a href="/jewelry-gifts/birthday-gifts" onclick="categoryNavSelect('Birthday Gifts|topnav')">Birthday</a></li>
													<li><a href="/anniversary-gifts" onclick="categoryNavSelect('Anniversary Gifts|topnav')">Anniversary</a></li>
													<li><a href="/wedding-rings" onclick="categoryNavSelect('Wedding Gifts|topnav')">Wedding</a></li>
													<li><a href="/jewelry-gifts/graduation-gifts" onclick="categoryNavSelect('Sapphire Gifts|topnav')">Graduation</a></li>
													<?php /* <li><a href="/black-friday-deals" onclick="categoryNavSelect('Black Friday|topnav')">Black Friday</a></li>
													<li><a href="/cyber-monday-deals" onclick="categoryNavSelect('Cyber Monday|topnav')">Cyber Monday</a></li>
													<li><a href="/green-monday-deals" onclick="categoryNavSelect('Green Monday|topnav')">Green Monday</a></li> */ ?>
												</ul>
											</div>
											<div class="col-sm-4 col-xs-4 high-padding-bottom">
												<div class="high-margin-top low-margin-bottom showcase-bg-light padding-type-3 low-padding-left"><strong>Category</strong></div>
												<div class="clearfix"></div>
												<ul class="pull-left low-padding-left" >
													<li><a href="/jewelry/pantone-color-of-the-year" onclick="categoryNavSelect('Pantone Color 2017 Gifts|topnav')">Pantone Color 2017</a></li>
													<li><a href="/collection/high-jewelry" onclick="categoryNavSelect('Certified Jewelry Gifts|topnav')">Certified Jewelry</a></li>
													<li><a href="/wedding-rings/mens-wedding-bands" onclick="categoryNavSelect('Gifts for Him Gifts|topnav')">Gifts for Him</a></li>
													<li><a href="/mothers-jewelry" onclick="categoryNavSelect('Mothers Jewelry Gifts|topnav')">Mother's Jewelry</a></li>
													<li><a href="/jewelry-gifts/baby-jewelry" onclick="categoryNavSelect('Gifts for Kids Gifts|topnav')">Gifts for Kids</a></li>
													<li><a href="/jewelry-gifts/gift-cards" onclick="categoryNavSelect('Gift Cards|topnav')">Gift Cards</a></li>
													<li><a href="/birthstone-jewelry" onclick="categoryNavSelect('Birthstone Gifts|topnav')">Birthstone Jewelry</a></li>
													<li><a href="/jewelry-gifts/gifts-for-her" onclick="categoryNavSelect('Gifts for Her Gifts|topnav')">Gifts for Her</a></li>
													<li><a href="/jewelry/two-stone-jewelry" onclick="categoryNavSelect('Two Stone Jewelry|topnav')">Two Stone Jewelry</a></li>
													<?php /* <li><a href="/jewelry/illusion-set-diamonds" onclick="categoryNavSelect('Illusion Set Gifts|topnav')">Illusion Set</a></li>  */ ?>
												</ul>
											</div>
										</div>
										<div class="col-md-7 col-sm-8 col-xs-7">
											<div class="col-md-9 col-xs-9 col-sm-9 high-padding-bottom">
												<div class="high-margin-top low-margin-bottom showcase-bg-light padding-type-3 low-padding-left"><strong>Shop By Gemstone</strong></div>
												<div class="clearfix"></div>
												<div class="col-sm-4 col-xs-4 no-padding">
												<ul class="pull-left" >
													<li><a href="/jewelry/sapphire-jewelry" onclick="categoryNavSelect('Sapphire Gifts|topnav')">Sapphire</a></li>
													<li><a href="/jewelry/ruby-jewelry" onclick="categoryNavSelect('Ruby Gifts|topnav')">Ruby</a></li>
													<li><a href="/jewelry/emerald-jewelry" onclick="categoryNavSelect('Emerald Gifts|topnav')">Emerald</a></li>
													<li><a href="/jewelry/diamond-jewelry" onclick="categoryNavSelect('Diamond Rings|topnav')">Diamond</a></li>
													<li><a href="/jewelry/colored-diamond-jewelry?filterable_stone_names=4556&amp;order=position&amp;dir=asc&amp;no_cache=true" onclick="categoryNavSelect('Blue Diamond Gifts|topnav')">Blue Diamond</a></li>
													<li><a href="/jewelry/colored-diamond-jewelry?filterable_stone_names=4555&amp;order=position&amp;dir=asc&amp;no_cache=true" onclick="categoryNavSelect('Black Diamond Gifts|topnav')">Black Diamond</a></li>
													<li><a href="/jewelry/peridot-jewelry" onclick="categoryNavSelect('Peridot Gifts|topnav')">Peridot</a></li>
													<li><a href="/jewelry/pink-tourmaline-jewelry" onclick="categoryNavSelect('Pink Tourmaline Gifts|topnav')">Pink Tourmaline</a></li>
													<li><a href="/jewelry/citrine-jewelry" onclick="categoryNavSelect('Citrine Gifts|topnav')">Citrine</a></li>
												</ul>
												</div>
												<div class="col-sm-4 col-xs-4 no-padding">
												<ul class="pull-left high-padding-left" >   
													<li><a href="/jewelry/pearl-jewelry" onclick="categoryNavSelect('Pearl Gifts|topnav')">Pearl</a></li>
													<li><a href="/jewelry/morganite-jewelry" onclick="categoryNavSelect('Morganite Gifts|topnav')">Morganite</a></li>
													<li><a href="/jewelry/tanzanite-jewelry" onclick="categoryNavSelect('Tanzanite Gifts|topnav')">Tanzanite</a></li>
													<li><a href="/jewelry/opal-jewelry" onclick="categoryNavSelect('Opal Gifts|topnav')">Opal</a></li>
													<li><a href="/jewelry/garnet-jewelry" onclick="categoryNavSelect('Garnet Gifts|topnav')">Garnet</a></li>
													<li><a href="/jewelry/amethyst-jewelry" onclick="categoryNavSelect('Amethyst Gifts|topnav')">Amethyst</a></li>
													<li><a href="/jewelry/aquamarine-jewelry" onclick="categoryNavSelect('Aquamarine Gifts|topnav')">Aquamarine</a></li>
													<li><a href="/jewelry/blue-topaz-jewelry" onclick="categoryNavSelect('Blue Topaz Gifts|topnav')">Blue Topaz</a></li>
													<li><a href="/jewelry/black-onyx-jewelry" onclick="categoryNavSelect('Black Onyx Gifts|topnav')">Black Onyx</a></li>
												</ul>
												</div>
												<div class="col-sm-4 col-xs-4 no-padding">
												<ul class="pull-left high-padding-left" >
													<li><a href="/jewelry/moissanite-jewelry" onclick="categoryNavSelect('Moissanite Gifts|topnav')">Moissanite</a></li>
													<li><a href="/lab-jewelry/lab-created-sapphire-jewelry" onclick="categoryNavSelect('Lab Created Sapphire Gifts|topnav')">Lab Created Sapphire</a></li>
													<li><a href="/lab-jewelry/lab-created-emerald-jewelry" onclick="categoryNavSelect('Lab Created Emerald Gifts|topnav')">Lab Created Emerald</a></li>
													<li><a href="/lab-jewelry/lab-created-ruby-jewelry" onclick="categoryNavSelect('Lab Created Ruby Gifts|topnav')">Lab Created Ruby</a></li>
												</ul>
												</div>
											</div>
											<div class="col-sm-3 col-xs-3 high-padding-bottom">
												<div class="high-margin-top low-margin-bottom showcase-bg-light padding-type-3 low-padding-left"><strong>Price</strong></div>
												<div class="clearfix"></div>
												<ul class="low-padding-left">
													<li><a href="/products?dir=asc&amp;order=price&amp;p=1&amp;price=1,250" onclick="categoryNavSelect('$250 & Under Gifts|topnav')">$250 &amp; Under</a></li>
													<li><a href="/products?dir=asc&amp;order=price&amp;p=1&amp;price=251,500" onclick="categoryNavSelect('$251 - $500 Gifts|topnav')">$251 - $500</a></li>
													<li><a href="/products?dir=asc&amp;order=price&amp;p=1&amp;price=501,1000" onclick="categoryNavSelect('$501 - $1000 Gifts|topnav')">$501 - $1000</a></li>
													<li><a href="/products?dir=asc&amp;order=price&amp;p=1&amp;price=1001,1500" onclick="categoryNavSelect('$1001 - $1500 Gifts|topnav')">$1001 - $1500</a></li>
													<li><a href="/products?dir=asc&amp;order=price&amp;p=1&amp;price=1501,2500" onclick="categoryNavSelect('$1501 - $2500 Gifts|topnav')">$1501 - $2500</a></li>
													<li><a href="/products?dir=asc&amp;order=price&amp;p=1&amp;price=2501,99999" onclick="categoryNavSelect('Over $2500 Gifts|topnav')">Over $2500</a></li>
												</ul>
											</div>
										</div>
									</div>
								</div>
                                </div>
              				</div>
            			</nav>
          			</div>
        		</div>
      		</div>
      		<div class="close-nav clickable text-center" onclick="closeNavigation();"><i class="fa fa-angle-up text-on-dark fontsize-type7 min-padding-top"></i></div>
    	</div>
  	</div>
</div>
<?php $pageType = Mage::helper('function')->getPageType();  ?>
<script>
	function closeNavigation(){
		jQuery('#sub-navigation').removeClass('active').slideUp(50);
		jQuery('.navbar-nav li').removeClass('active');
		jQuery('.nav-header, .snow-f').addClass('header-hover');
		<?php /* 
		if($pageType == 'home'){ ?>
			jQuery('.nav-header .logo img').attr('src','/skin/frontend/ress/default/images/logo-white.png');
		<?php }
		*/ ?>
		if(jQuery('.nav-header').hasClass('sticky-header')){
			jQuery('.nav-header').removeClass('header-hover');
			<?php if($pageType == 'home'){ ?>
				jQuery('.nav-header .logo img').attr('src','/skin/frontend/ress/default/images/logo.png');
			<?php } ?>
		}
	}
	
	<?php if(strstr($_SERVER['HTTP_USER_AGENT'],'iPad')){ ?>
		jQuery('.navbar-nav li').click(function(){
			if(jQuery(this).hasClass('active')){
				closeNavigation();
			}else{
				jQuery('.nav-header, .snow-f').removeClass('header-hover');
				<?php if($pageType == 'home'){ ?>
					jQuery('.nav-header .logo img').attr('src','/skin/frontend/ress/default/images/logo.png');
				<?php } ?>
				var itemPos = jQuery(this).index();
				jQuery(this).addClass('active').siblings().removeClass('active');
				jQuery('.secondary-navbar-container .secondary-navbar').hide();
				jQuery('.secondary-navbar-container .secondary-navbar:eq('+itemPos+')').show();
				jQuery('#sub-navigation').slideUp(50);
				//setTimeout(function(){
					jQuery('#sub-navigation').addClass('active').slideDown(100);
				//}, 150);			
			}
		}); 
	<?php } else { ?>
		jQuery('.navbar-nav li').mouseover(function(){
			if(!jQuery(this).hasClass('active')){
				jQuery('#sub-navigation').slideUp(50);
			}
			jQuery('.nav-header, .snow-f').removeClass('header-hover');
			<?php if($pageType == 'home'){ ?>
				jQuery('.nav-header .logo img').attr('src','/skin/frontend/ress/default/images/logo.png');
			<?php } ?>
			var itemPos = jQuery(this).index();
			jQuery(this).addClass('active').siblings().removeClass('active');
			jQuery('.secondary-navbar-container .secondary-navbar').hide();
			jQuery('.secondary-navbar-container .secondary-navbar:eq('+itemPos+')').show();
			//setTimeout(function(){
				jQuery('#sub-navigation').addClass('active').slideDown(100);
			//}, 150);
			
			jQuery('#sub-navigation').attr('is-visible','1');
			
		}).mouseleave(function(){
			jQuery('#sub-navigation').removeAttr('is-visible');
			setTimeout(function(){
				if(jQuery('#sub-navigation').attr('is-visible') != 1){
					closeNavigation();
				}
			}, 1000);
		});
		
		jQuery('#sub-navigation').mouseover(function(){
			jQuery('#sub-navigation').attr('is-visible','1');
			<?php if($pageType == 'home'){ ?>
				jQuery('.nav-header .logo img').attr('src','/skin/frontend/ress/default/images/logo.png');
			<?php } ?>
		}).mouseleave(function(){
			jQuery('#sub-navigation').removeAttr('is-visible');
			setTimeout(function(){
				if(jQuery('#sub-navigation').attr('is-visible') != 1){
					jQuery('.navbar-nav li').removeClass('active');
					closeNavigation();
				}
			}, 1000);
		});
	<?php } ?>
	
	jQuery(document).on('click', function(e){
		if(!jQuery(e.target).closest('#sub-navigation').length && !jQuery(e.target).closest('.navbar-nav-li').length && jQuery('#sub-navigation').hasClass('active')) {
			closeNavigation();
		}
	});
</script>