<div class="columns ">
  <div id="page:left" class="side-col">
    <h3>Import Record(s)</h3>
  </div>
  <div id="content" class="main-col">
    <div class="main-col-inner">
      <div id="messages"></div>
      <div class="content-header">
        <p class="form-buttons">
          <button onclick="setLocation('<?php echo $this->getUrl('*/*/')?>')" class="scalable back" type="button" title="Back"><span>Back</span></button>
          <button onclick="editForm.submit();" class="scalable save" type="button" title="save synonym" id="id_43a2c5286a471707a0086bb2dae2b44d"><span>Submit</span></button>
        </p>
      </div>
      <div class="entry-edit">
        <form id="export_records" action="<?php echo $this->getUrl('*/*/import') ?>" method="post" enctype="multipart/form-data">
          <?php echo $this->getBlockHtml('formkey')?>
          <div style="" id="synonym_tabs_form_section_content">
            <div class="entry-edit">
              <div class="entry-edit-head">
                <h4 class="icon-head head-edit-form fieldset-legend">Import Record(s)</h4>
                <div class="form-buttons"></div>
              </div>
              <div id="synonym_form" class="fieldset ">
                <div class="hor-scroll">
                  <table cellspacing="0" class="form-list">
                    <tbody>
                      <tr>
                        <label for="input_file">Please upload a <a href="<?php echo Mage::getUrl('media').'sample/import_synonyms.csv'?>" title="Download sample file">csv file</a> to import record(s):</label>
                        <input type="file" id="input_file" name="input_file" accept=".csv" required class="required-entry">
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </form>
      </div>
      <script type="text/javascript">
		editForm = new varienForm('export_records', '');
	</script> 
    </div>
  </div>
</div>
