<?php echo $this->getLayout()->createBlock('catalog/navigation')->setTemplate('catalog/navigation/product-promotions.phtml')->toHtml();?>

<style type="text/css">
/*Start Request Shipping Label by Pankaj regarding bug id:774*/
.ui-dialog .ui-dialog-content{
	padding:0px;
	padding-top:3px;	
}
/*End Request Shipping Label by Pankaj regarding bug id:774*/
</style>

<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>

<!--Start Request Shipping Label by Pankaj regarding bug id:774-->
<script type="text/javascript">
	jQuery(function(){
		
		jQuery("#requestlabel-dialog").dialog({
			autoOpen: false,
			show: "blind",
			hide: "explode",			
			width:450,
			zIndex:11000,
			resizable:false,
   			draggable:false,
			minHeight:290
		});
		 
		jQuery("#returnshipping-dialog-opener").click(function() {
			jQuery('#resultsuccess').hide();
			jQuery('#formrequestlabel').each (function(){  
				this.reset();
			});
            jQuery('#formrequestlabel').show();
			jQuery("#requestlabel-dialog").dialog("open");
			if(jQuery("#requestlabel-dialog").data('loaded')!== 'true'){
				jQuery("#requestlabel-dialog").load('/popup/index/openreturnshippinglabel',function(){					
					dataForm = new VarienForm('formrequestlabel', true);
					dataForm.validator.options.onFormValidate = function (result, form){}
					jQuery('#formrequestlabel').submit(function(){
						return submitReturnShippingLabel();
					});
				}); 
				jQuery("#requestlabel-dialog").data('loaded','true'); 
			}
			return false;
		 });
	});
	
	function submitReturnShippingLabel(){
		if(dataForm.validator.validate()===true){
			jQuery('#LoadingImage').show();
			jQuery.post('/popup/index/requestreturnshippinglabel',jQuery('#formrequestlabel').serialize(),function(res){	
				jQuery('#LoadingImage').hide();			
				jQuery('#resultsuccess').html(res);
				jQuery('#formrequestlabel').hide();
                jQuery('#resultsuccess').show();
			})
			setTimeout(function(){
				  jQuery('#requestlabel-dialog').dialog('close');                
			}, 5000);
            return false;
		}
		return false;
	}	
</script>
<!--End Request Shipping Label by Pankaj regarding bug id:774-->

<script type="text/javascript">
	jQuery(function(){
		jQuery('.custom-scroll').mCustomScrollbar({
			scrollButtons:{
				enable:true,
			},
			callbacks:{
				onScroll: function (){}
			},
			advanced:{ 
				updateOnContentResize:true
			}
		});
		
		jQuery('.know-more-icon').hover(
			function(){
				jQuery(this).find('.popupbox-block').show();
			},function(){
				jQuery(this).find('.popupbox-block').hide();
			}
		)
	})
	
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
	if(optionsPrice.priceFormat) {
		var currencySign = optionsPrice.priceFormat.pattern;
		currencySign = currencySign.substring(0, currencySign.indexOf('%'));
	}
	
	/* Start Ring Sizer */

	jQuery.fx.speeds._default = 100;
	jQuery(function() {
		jQuery( "#ringsizer-dialog" ).dialog({
			autoOpen: false,
			show: "blind",
			hide: "explode",			
			width:400,
			zIndex:11000,
			dialogClass:'ringsizerwrapper',
			minHeight:550
		});

		jQuery( "#ringsize-dialog-opener" ).click(function() {
			jQuery( "#ringsizer-dialog" ).dialog( "open" );
			jQuery('.ringsizerwrapper').show();
			jQuery('#detailsform').show();
			jQuery('#result_success').hide();
			jQuery('#result_fail').hide();
			//jQuery('#ringsizer-dialog').height(jQuery('#detailsform').height());
			if(jQuery( "#ringsizer-dialog" ).data('loaded')!== 'true'){
				jQuery( "#ringsizer-dialog" ).load('/popup/index/openringsizer',function(){					
					dataForm = new VarienForm('formringsizer', true);
					
					dataForm.validator.options.onFormValidate = function (result, form){
						//jQuery('#ringsizer-dialog').height(jQuery('#detailsform').height());
					}
					
						jQuery('#rs-Preferreddate').datepicker({minDate:0, maxDate:'+1M +10D'});
						
						jQuery("#rs-Preferredtime").focusin(function(){
							if(jQuery(this).val() == "e.g. 8:30 PM"){
								jQuery(this).val('');
							}
						})
						
						jQuery("#rs-Preferredtime").focusout(function(){
							if(jQuery(this).val() == ""){
								jQuery(this).val('e.g. 8:30 PM');
							}
						})
						
						//jQuery(function() {
							//jQuery( "#rs-Preferredtime" ).timespinner();
						//});
					
						jQuery('#formringsizer').submit(function(){
							//console.log(jQuery('#formringsizer').serialize());
							
							return submitRingSizer();
						});
					
				});
				jQuery( "#ringsizer-dialog" ).data('loaded','true');
				jQuery('#ringsizer-dialog').height(jQuery('#detailsform').height());
			}
			
			return false;
		});
	});
	
	
	
	function submitRingSizer(){
		if(dataForm.validator.validate()===true){
			jQuery('#LoadingImage').show();
			jQuery.post('/popup/index/requestringsizer',jQuery('#formringsizer').serialize(),function(res){					
				jQuery('#LoadingImage').hide();
				//alert(res);
				//console.log(res);
				jQuery('#rs-req-result').html(res);
				jQuery('#result_success').show();
				//jQuery('#ringsizer-dialog').height(jQuery('#detailsform').height());
			})
			//jQuery('#ringsizer-dialog').height(jQuery('#detailsform').height());
			return false;
		}
		//jQuery('#ringsizer-dialog').height(jQuery('#detailsform').height());
		return false;
	}

/* End Ring Sizer */
jQuery(function() {
jQuery('.stonesizeround').click(function(){	
			jQuery('.popupboxnew').hide().html('');
			jQuery('#roundstonepopup').show();
			//if(jQuery('#roundstonepopup').data('loaded')!='yes'){
				jQuery.ajax({
				url:'/skin/frontend/angara/default/staticdata/stonesize-round.html',
				success: function(matter){
						jQuery('#roundstonepopup').html(matter);
						jQuery('#roundstonepopup').data('loaded','yes');
						jQuery('.popupboxcross').click(function(){
							jQuery('.popupboxnew').hide().html('');
						})				
					}
				})
			//}
		})
		
			
		jQuery('.stonesize').click(function(){		
			jQuery('.popupboxnew').hide().html('');	
			jQuery('#ovalstonepopup').show();
			//if(jQuery('#ovalstonepopup').data('loaded')!='yes'){
				jQuery.ajax({
				url:'/skin/frontend/angara/default/staticdata/stonesize.html',
				success: function(matter){
						jQuery('#ovalstonepopup').html(matter);
						jQuery('#ovalstonepopup').data('loaded','yes');
						jQuery('.popupboxcross').click(function(){
							jQuery('.popupboxnew').hide().html('');
						})				
					}
				})
			//}
		})
		
		
		jQuery('.retailpricepopup').click(function(){		
			jQuery('.popupboxnew').hide().html('');	
			jQuery('#retailpricepopup').show();
			//if(jQuery('#retailpricepopup').data('loaded')!='yes'){
				jQuery.ajax({
				url:'/skin/frontend/angara/default/staticdata/retailprice.html',
				success: function(matter){
						jQuery('#retailpricepopup').html(matter);
						jQuery('#retailpricepopup').data('loaded','yes');
						jQuery('.popupboxcross').click(function(){
							jQuery('.popupboxnew').hide().html('');
						})				
					}
				})
			//}
		})
		
	jQuery('.internetjeweler').click(function(){
			jQuery('.popupboxnew').hide().html('');			
			jQuery('#internetjewelerpopup').show();
			//if(jQuery('#internetjewelerpopup').data('loaded')!='yes'){
				jQuery.ajax({
				url:'/skin/frontend/angara/default/staticdata/internetjeweler.html',
				success: function(matter){
						jQuery('#internetjewelerpopup').html(matter);
						jQuery('#internetjewelerpopup').data('loaded','yes');
						jQuery('.popupboxcross').click(function(){
							jQuery('.popupboxnew').hide().html('');
						})				
					}
				})
			//}
		})
		
			jQuery('.valuequality').click(function(){
			jQuery('.popupboxnew').hide().html('');
			jQuery('#valuequalitypopup').show();
			//if(jQuery('#valuequalitypopup').data('loaded')!='yes'){
				jQuery.ajax({
				url:'/skin/frontend/angara/default/staticdata/valuequality.html',
				success: function(matter){
						jQuery('#valuequalitypopup').html(matter);
						jQuery('#valuequalitypopup').data('loaded','yes');
						jQuery('.popupboxcross').click(function(){
							jQuery('.popupboxnew').hide().html('');
						})				
					}
				})
			//}
		})
	})
		

	
</script>

<form id='pdfform' action="<?php echo Mage::getBaseUrl();?>hprcv/Index/pdf" method="post" target="_blank">
  <input id="cert_image" type="hidden" name="cert_image" value="<?php echo $this->helper('catalog/image')->init($_product, 'image') ?>" />
  <input id="cert_id" type="hidden" name="cert_id" value="<?php echo $_product->getId()?>" />
  <input id="cert_quality" type="hidden" name="cert_quality" value="<?php echo ($_product->getEmbQualityGrade2())?$_product->getAttributeText('emb_quality_grade2'):''; ?>" />
  <input id="cert_metal" type="hidden" name="cert_metal" value="<?php echo ($_product->getMetal())?$_product->getAttributeText('metal'):''; ?>" />
  <input type="hidden" id='cert_sync_count' name="cert_sync_count" value="" />
  <input type="hidden" id='cert_sync_size' name="cert_sync_size" value="" />
  <input type="hidden" id='cert_sync_weight' name="cert_sync_weight" value="" />
</form>

<div id="qualitypopup" class="popupboxnew" style="display: none;"></div>
<div id="roundstonepopup" class="popupboxnew" style="display: none;"></div>
<div id="ovalstonepopup" class="popupboxnew" style="display: none;"></div>
<div id="retailpricepopup" class="popupboxnew" style="display: none;"></div>
<div id="internetjewelerpopup" class="popupboxnew" style="display: none;"></div>
<div id="valuequalitypopup" class="popupboxnew" style="display: none;"></div>

<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div id="product-page-inner">
<form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
	<div id="product-page-upper">		
			<div class="no-display">
				<input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                <input type="hidden" name="category" value = "<?php echo $tracCategory ?>"/>
			</div>
			<!-- Start Product Page Breadcrumbs -->
				<div id="product-page-breadcrumb">
				<?php
					/* # Todo put this code inside a new block */
					$cumbs = $this->getLayout()->getBlock('breadcrumbs')->_crumbs;
					$count_cumbs =  count($cumbs);
					if($cumbs && is_array($cumbs)) {
						$i=1;
						$tracCategory;
						foreach($cumbs as $_crumbName=>$_crumbInfo){
							if($_crumbInfo['link']){
								if( $i != $count_cumbs - 1){
									$i = $i+1;
								} 
								else {
									$tracCategory = $_crumbInfo['label'] ; 
									$i = $i+1;
								}
							}
						}
						foreach($cumbs as $_crumbName => $_crumbInfo){
							if($_crumbInfo['link']){
								?>
                               
							<div class="breadcrumb-item <?php echo ($tracCategory == $_crumbInfo['label'])?'last-item':'';?>">
									<a href="<?php echo $_crumbInfo['link'];?>">
                                        <span><?php echo $_crumbInfo['label']." "; ?></span>
                                        <span class="crumbarrow">&gt;</span>
                                    </a>
								</div>
                                
								<?php
							}
						}
					}
				?>
                <div style="clear:both;"></div>
				</div>
				<!-- End Product Page Breadcrumbs --> 
			
			<!-- Start Product Page Upper Left Block -->
			<div id="product-page-upper-right"> 
				
				<!-- Start Product media Block -->
				<div id="product-media"> <?php //echo $this->getChildHtml('video') ?>
					<div class="product-img-box"> <?php echo $this->getChildHtml('media') ?>
					</div>
                    <div class="clear"></div>
				</div>
				<?php 
					$newmediaval = $_helper->productAttribute($_product, $this->htmlEscape($_product->getNewmedia()), 'newmedia');	
					if($newmediaval!=''){	
						echo $this->getChildHtml('videoupload');
					}
				?>
				<!-- End Product media Block --> 
				
				<!-- Start Product price & action Block -->
				<div id="product-price-and-action"> 
					
					<!-- Start Product price Block -->
					<div id="product-price-details"> <?php echo $this->getChildHtml('product_type_data') ?>
						<?php echo $this->getChildHtml('addtocart') ?>
                        <div class="clear"></div>
					</div>
					<!-- End Product price Block --> 
					
					<!-- Start Product action Block -->
					<div id="product-page-action">
						<div id="product-selection-continue-button" onclick="productPageContinueClicked()">CONTINUE</div>
						<div id="product-selection-back-button">&lt; BACK</div>
					</div>
					<script>
						jQuery(function(){
							//jQuery('#ringsizemaindiv').prependTo(jQuery('#product-price-details'));
							//jQuery('#ringsizemaindiv').after(jQuery('#freeringsizer-link'));

							jQuery('#product-selection-continue-button').click(function(){
								jQuery('#product-variations-box').hide();
								jQuery('#product-variations-box').parent().append(jQuery('#product-price-details'));
								jQuery('#product-selection-back-button').show();
								jQuery('#product-selection-continue-button').hide();
								jQuery('#product-page-lower').hide();
								jQuery('#ringsizerguide,.appraisalcert,.addwarrenty, #spacer_engraving, #ringsizemaindiv, #freeringsizer-link').show();
								jQuery('#show-review-btn').hide();								
								jQuery('#ultimate-engraving').css('left','12px');
							});
							jQuery('#product-selection-back-button').click(function(){
								jQuery('#product-variations-box').show();
								jQuery('#product-price-details').prependTo(jQuery('#product-price-and-action'));
								jQuery('#product-selection-continue-button').show();
								jQuery('#product-selection-back-button').hide();
								jQuery('#product-page-lower').show();
								jQuery('#ringsizerguide,.appraisalcert,.addwarrenty, #spacer_engraving, #ringsizemaindiv, #freeringsizer-link').hide();
								jQuery('#show-review-btn').show();
								jQuery('#ultimate-engraving').css('left','-9999px');
							});
						});
					</script>
					<!-- End Product action Block --> 
					
				</div>
				<!-- End Product price & action Block --> 
				
				<!-- Start Product extra info Block -->
				<div id="product-extra-info"> </div>
				<!-- End Product extra info Block --> 				
			</div>
			<!-- End Product Page Upper Left Block --> 
			
			<!-- Start Product Page Upper Right Block -->
				
            <div id="product-page-upper-left"> 				
				<div id="product-details-overview">				
				<!-- Start Product About Block -->
				<div id="product-about">
					<h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
					<div class="review-block"><?php echo $this->getReviewsSummaryHtml($_product, false, true)?></div>
				</div>
				<!-- End Product About Block --> 
              
                <?php if($_product->getAttributeSetId() == 10): // if ring ?>
						<div id="ringsizemaindiv" style="position:relative; padding-top:11px;">
							<div style='float:left;margin-top:0px !important' class="ringsize">
								<label class="required">Ring Size: </label>
							</div>
							<div style="float:left;margin:-3px 0 6px 10px" id='ringsizediv'></div>
							<div class="clear"></div>
                        </div>		
                        <!--Started Modified by Pankaj regarding bug id:642-->					
                        <div id="freeringsizer-link" class="freeringsizer" ><a id="ringsize-dialog-opener" href="Javascript:void(0)"><?php /*?>Get a FREE ring sizer shipped to your doorstep<?php */?></a></div>
                        <!--Ended Modified by Pankaj regarding bug id:642-->	
                         <div id="ringsizer-dialog" title="Ring Sizer"></div>
				<?php endif; // end if ring ?>
                
                <?php if(!isset($cids))
	$cids = $this->getProduct()->getCategoryIds();?>
<?php // ignoring gift cards (id:96)
if(!in_array(96, $cids)): ?>
<?php 
	$appraisal_price = $this->helper('core')->currency(65,true,false);
	$appraisal_price = ($appraisal_price=='$65.00')?'$65':$appraisal_price;
	$pmain_sku = $_product->getSku();
	$presku = strtolower(substr($pmain_sku, 0, 3)); // SD_
?>
		<?php if($presku != 'sd_' && $presku != 'SD_'): ?>
		<div class="appraisalcert">
			<span class="certspanbox">
				<label onclick="">
				   <input name="appraisal" type="checkbox" id="jewelryappraisal" autocomplete="off"/><?php // Code Added by Vaseem for BT 346?>
					<span class="appraisaltxt">Add Jewelry Appraisal for <?php echo ($appraisal_price=='$65')?$appraisal_price:'<br />'.$appraisal_price; ?></span>   
				</label>
			</span>
			<span class="know-more-icon" id="know-more-appraisal">
                 <div class="popupbox-block" style="width:auto;" id="knowmoreappraisal"> 
                    <div class="appraisalcertimg">Add Jewelry Appraisal for <?php echo $appraisal_price ?></div>	
                </div>
            </span>
			 <div class="refundtxt" id="nonjewelry" style="display:none;">*Jewelry Appraisal cost is non refundable</div>
		</div>
		<?php endif; ?>

<?php /*Added by Saurabh for insurance module for issue 0000248*/ ?>
<?php 
$currencyPrice=Mage::helper('core')->currency($_product->getPrice(),false,false); 
if($currencyPrice<200){
	$insPrice=40;
}
else{
	$insPrice=$currencyPrice*.1;
}
?>
<div class="addwarrenty">
    <span class="certspanbox">
        <label onclick="">
           <input name="insurance" type="checkbox" autocomplete="off"/>
             <span class="appraisaltxt">Add Warranty For <?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol(); ?><span id="insprice"><?php echo round($insPrice); ?></span></span>
        </label>
    </span>
    <span class="know-more-icon" id="know-more-warranty">
  	  <div class="popupbox-block" id="knowmorewarranty">
        The Total Protection Warranty Plan protects your jewelry for the next 5 years against any accidental damage and/or wear and tear in order to ensure that your jewelry looks like new whenever you wear it.  If the warranty is unused over the next 5 years, you can use the full amount paid for the warranty towards any future Angara purchase.<br />
 <a href="/total-protection-warranty.html" target="_blank" style="text-decoration:underline;">Click here</a> for more information.
    </div>
    </span>
</div>
<?php /*End Added by Saurabh for insurance module for issue 0000248*/ ?>
<?php endif; ?>

<?php //	Code modified by Vaseem for Engraving Work Id 241
	echo $this->getLayout()->createBlock('catalog/product/view')->setProduct($_product)->setTemplate('catalog/product/view/engraving_popup.phtml')->toHtml(); 
	 //	Code modified by Vaseem for Engraving Work Id 241	
?>
<div id="spacer_engraving"></div>

				
				<!-- Start Product Variations Box -->
				<div id="product-variations-box">
					<div class="spacing" style="padding-top:0px;display:none">
						<?php if ($_product->isSaleable() && $this->hasOptions()):?>
						<?php echo $this->getChildChildHtml('container2', '', true, true) ?>
						<?php endif;?>
						<br clear="all" />
					</div>
					
					<!-- HPRAHI STARTS CODE -->
					<div id="detailsection"> 
						<script type="text/javascript">
						var arroptions = new Array();
						<?php foreach ($_product->getOptions() as $o): ?>
							index1 = arroptions.length;
							arroptions[index1] = new Array();
							arroptions[index1][arroptions[index1].length] = "<?php echo $o->getType();?>";
							arroptions[index1][arroptions[index1].length] = "<?php echo $o->getTitle();?>";
							<?php if($o->getTitle() == 'VariationInfoToOrder'): ?>
								arroptions[index1][arroptions[index1].length] = "<?php echo $o->getOptionId();?>";
							<?php endif;?>
							<?php $values = $o->getValues(); $ic =0;?>
							<?php foreach ($values as $v): ?>
								<?php if($ic==0): ?>
									arroptions[index1][arroptions[index1].length] = "<?php echo $v->getOptionId();?>";
								<?php $ic = 1;?>
								<?php endif; ?>
									arroptions[index1][arroptions[index1].length] = "<?php echo $v->getOptionTypeId();?>";
									arroptions[index1][arroptions[index1].length] = "<?php echo $v->getSku();?>";
									arroptions[index1][arroptions[index1].length] = "<?php echo $v->getTitle();?>";
									arroptions[index1][arroptions[index1].length] = "<?php echo $v->getPrice();?>";
									arroptions[index1][arroptions[index1].length] = "<?php echo $v->getSortOrder();?>";
							<?php endforeach; ?>
						<?php endforeach; ?>
						
						var curstone = '<?php echo $_product->getAttributeText('de_stone_type');?>';
						var curmetal = '<?php echo $_product->getAttributeText('metal_type');?>';
						var cursku = '<?php echo $_product->getSku()?>';
						var curid = '<?php echo $_product->getId()?>';
						var curshape = '<?php echo $_product->getAttributeText('de_stone_shape');?>';
						var curstonesize = '';
						
						var embStoneName = '<?php echo $_product->getAttributeText('emb_stone_name'); ?>';
						var embStoneName2 = '<?php echo $_product->getAttributeText('emb_stone_name2'); ?>';
						var embStoneName3 = '<?php echo $_product->getAttributeText('emb_stone_name3'); ?>';
						
						var embDimension1 = '<?php echo $_product->getData('emb_dimension1'); ?>';
						var embDimension2 = '<?php echo $_product->getData('emb_dimension2'); ?>';
						var embDimension3 = '<?php echo $_product->getData('emb_dimension3'); ?>';
						<?php if($_product->getEmbStoneName() || $_product->getEmbStoneName2() || $_product->getEmbStoneName3() ): ?>
							<?php if($_product->getData('emb_dimension2')): ?>
								curstonesize = 	'<?php echo $_product->getData('emb_dimension2')?>';
							<?php elseif($_product->getData('emb_dimension1')):	?>
								curstonesize = 	'<?php echo $_product->getData('emb_dimension2')?>';
							<?php endif; ?>
						<?php endif; ?>
						</script>
                        
						
						
						<div id="stonesizemaindiv" style="margin-bottom:10px">
							<div class="small-title">SELECT TOTAL CARAT WEIGHT</div>
							<div>
								<div id="stonesizebox"></div>								
								<div style="clear:both"></div>
							</div>
							<div type="best-qualitytype" class="qualitydescription" style="display: block;" id="gemstonesizedesc"> </div>
						</div>
						<div id="qualitymaindiv" style="margin-bottom:10px">
							<div class="small-title">Select Gemstone quality</div>
							<div>
								<div id="qualitybox"></div>							
								<div style="clear:both"></div>
							</div>
							<div type="best-qualitytype" class="qualitydescription" style="display: block;" id="qualitydescription"> </div>
						</div>
						<div id="metaltypemaindiv" style="margin-bottom:10px">
							<div class="small-title">Select metal type</div>
							<div class="" id="metaltypebox"></div>
							<div type="best-qualitytype" class="qualitydescription" style="display: block;" id="metaldescription"> </div>
						</div>
					</div>
					<script>
				ringsizetransfer();
				cj_generatehtml();
				</script> 
					<!-- HPRAHI CODE ENDS --> 
					
				</div>
				<!-- End Product Variations Box --> 
				</div>
			</div>		
			<!-- End Product Page Upper Right Block -->
            	
            <!-- Start Ring Sizer PDF link Block -->	            
            <div id="ringsizerguide"><a href="/skin/frontend/angara/default/PDF/AngaraRingSizer00.pdf" target="_blank"></a></div>		
		 <!-- End  Ring Sizer PDF link Block -->	
		<div style="clear:both"></div>
	</div>
    </form>
	<div id="product-page-lower">
   <div id="detailstab" style="display:block;">
        <ul>
         <li id="productdescription" class="activeted1"><a href="javascript:void(0);" onclick="showDiveSection('product-description');" onmouseover="showDiveSection('product-description');">Product Details</a></li>     
          <li id="shippingreturns" class="alltab"><a href="javascript:void(0);" onmouseover="showDiveSection('shipping-returns');">Shipping &amp; Returns</a></li>
          <li id="angaradifference" class="difference"><a href="javascript:void(0);" onmouseover="showDiveSection('angara-difference');">The Angara Difference</a></li>
          <li id="productreview" class="alltab"><a href="javascript:void(0);" onmouseover="showDiveSection('product-review');">Product Reviews</a></li>
        </ul>
      </div>
      
       <div class="productalldetail">
      <div id="product-description" class="descriptiontab" style="display: block; ">
           <div style="margin-bottom:25px;">
            <div class="heading2"><?php echo $_product->getShortDescription() ?>
            <span class="writeareviewlink"  style="text-decoration:underline;font-size:12px;font-weight:normal;margin-left:10px; cursor:pointer;">Write a Review</span>             </div>
            <div style="padding:10px 0 0 0; font-weight:bold; text-decoration:underline;"><a id="authenticity-cert" href='javascript:void(0)' onclick="jQuery('#cert_image').val(jQuery('#image').attr('src'));document.getElementById('pdfform').submit()">View Certificate Of Authenticity<img src="/skin/frontend/angara/default/images/certificate.png" width="25" height="19"></a></div>
            <?php /*?><h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1> <?php */?>
            <?php if(
						
							($_product->getAttributeText('emb_stone_name3')=="Diamond" || $_product->getAttributeText('emb_stone_name3') =='')
							&&
							($_product->getAttributeText('emb_stone_name2')=="Diamond" || $_product->getAttributeText('emb_stone_name2') =='')
							&&
							($_product->getAttributeText('emb_stone_name')=="Diamond" || $_product->getAttributeText('emb_stone_name') =='')) : ?>
            <div class="headingtag">
              <?php if ($_product->getDescription()): ?>
              <?php //echo $_product->getDescription() ?>
              <?php endif ?>
            </div>
            <?php endif?>
            <div style="clear:both"></div>
          </div>
          <div class="item-details-box-wrapper">
            <?php
					if($_product->getGemstoneCaratWeight()){
						$tmp_width = '290px';
					}else{
						$tmp_width = '198px';
					}                    
					?>
            <div id="details-heading-top" style="width:<?php echo $tmp_width?>;line-height:normal">
              <div class="detail-box-title">Product Details:</div>
              <div class="field">
                <div class="fieldtitle">Angara Item #:</div>
                <div class="fieldvalue"><?php echo $_helper->productAttribute($_product, $_product->getSku(), 'sku') ?></div>
                <div style="clear:both"></div>
              </div>
              <?php if($_product->getPendantChainLength ()): ?>
              <div class="field">
                <div class="fieldtitle">Chain Length:</div>
                <div class="fieldvalue"><?php echo $_product->getAttributeText('pendant_chain_length') ?> inches</div>
                <div style="clear:both"></div>
              </div>
              <?php endif?>
              <?php if($_product->getMetal()): ?>
              <div class="field">
                <div class="fieldtitle">Metal:</div>
                <div class="fieldvalue" id="metal-desc"><?php echo $_product->getAttributeText('metal') ?></div>
                <div style="clear:both"></div>
              </div>
              <?php endif?>
              <?php if($_product->getGemstoneType()): ?>
              <div class="field">
                <div class="fieldtitle">Gemstone Type:</div>
                <div class="fieldvalue"><?php echo $_product->getAttributeText('gemstone_type') ?></div>
                <div style="clear:both"></div>
              </div>
              <?php endif;
							if($_product->getGemstoneShape ()): ?>
              <div class="field">
                <div class="fieldtitle">Gemstone Shape:</div>
                <div class="fieldvalue"><?php echo $_product->getAttributeText('gemstone_shape') ?></div>
                <div style="clear:both"></div>
              </div>
              <?php endif;
                            if($_product->getGemstoneCaratWeight()): ?>
              <div class="field">
                <div class="fieldtitle">Approximate Carat Total Weight:</div>
                <div class="fieldvalue" id="Emb-weight"><?php echo $_product->getData('gemstone_carat_weight') ?> cts</div>
                <div style="clear:both"></div>
              </div>
              <?php endif;
							if($_product->getGemstoneColor ()): ?>
              <div class="field">
                <div class="fieldtitle">Gemstone Color:</div>
                <div class="fieldvalue"><?php echo $_product->getAttributeText('gemstone_color') ?></div>
                <div style="clear:both"></div>
              </div>
              <?php endif;
                            if($_product->getGemstoneClarity ()): ?>
              <div class="field">
                <div class="fieldtitle">Gemstone Clarity:</div>
                <div class="fieldvalue"><?php echo $_product->getAttributeText('gemstone_clarity') ?></div>
                <div style="clear:both"></div>
              </div>
              <?php endif;
							if($_product->getGemstoneDimension()): ?>
              <div class="field">
                <div class="fieldtitle">Approximate Dimensions:</div>
                <div class="fieldvalue" id="Emb-size"><?php echo $_product->getData('gemstone_dimension') ?> mm</div>
                <div style="clear:both"></div>
              </div>
              <?php endif;
							if($_product->getGemstoneBrilliance ()): ?>
              <div class="field">
                <div class="fieldtitle">Gemstone Brilliance:</div>
                <div class="fieldvalue"><?php echo $_product->getAttributeText('gemstone_brilliance') ?></div>
                <div style="clear:both"></div>
              </div>
              <?php endif;
							if($_product->getGemstoneEnhancement ()): ?>
              <div class="field">
                <div class="fieldtitle">Gemstone Enhancement:</div>
                <div class="fieldvalue"><?php echo $_product->getAttributeText('gemstone_enhancement') ?></div>
                <div style="clear:both"></div>
              </div>
              <?php endif?>
              
              <!--<div class="field">
								<div class="fieldtitle">Purity:</div>
								<div class="fieldvalue">100% Natural</div>
                                 <div style="clear:both"></div>
							</div>--> 
            </div>
            <?php if($_product->getEmbStoneName() || $_product->getEmbStoneName2() || $_product->getEmbStoneName3() ): ?>
            <div class="stones-details-box">
              <?php if($_product->getEmbStoneName3()): ?>
              <div id="Emb3-stone-detail-box" class="stone-detail-box-odd">
                <div class="detail-box-title"><!-- 3 -->
                  <?php if($_product->getAttributeText('emb_stone_name3')=="Diamond" || $_product->getAttributeText('emb_stone_name3')=="Simulated Diamond"): ?>
                  Diamond
                  <?php else:?>
                  Gemstone
                  <?php endif?>
                  Information:</div>
                <?php if($_product->getEmbNumberOfStones3()): ?>
                <div class="field">
                  <div class="fieldtitle">Number of <?php echo $_product->getAttributeText('emb_shape3') ?>
                  <span id="Emb3-name"><?php 
					if($_product->getData('emb_number_of_stones3') > 1){						 
						if($_product->getAttributeText('emb_stone_name3')=="Ruby"){
							echo "Rubies";
						} elseif($_product->getAttributeText('emb_stone_name3')=="Lab Created Ruby"){
							echo "Lab Created Rubies";
						} else{
							echo $_product->getAttributeText('emb_stone_name3')."s";
						}
					}else{
						echo $_product->getAttributeText('emb_stone_name3');
					}
					?></span>:</div>
                  <div class="fieldvalue" id="Emb3-count"><?php echo $_product->getData('emb_number_of_stones3') ?></div>
                  <div style="clear:both"></div>
                </div>
                <?php endif?>
                <?php if($_product->getEmbDimension3()): ?>
                <div class="field">
                  <div class="fieldtitle"> Approximate Dimensions: </div>
                  <div class="fieldvalue" id="Emb3-size"><?php echo $_product->getData('emb_dimension3') ?> mm</div>
                  <div style="clear:both"></div>
                </div>
                <?php endif?>
                <?php if($_product->getEmbCaratWeight3()): ?>
                <div class="field">
                  <div class="fieldtitle">Approximate Carat Total Weight: </div>
                  <div class="fieldvalue" id="Emb3-weight"><?php echo $_product->getData('emb_carat_weight3') ?> cts</div>
                  <div style="clear:both"></div>
                </div>
                <?php endif?>
                <?php if($_product->getEmbQualityGrade3()): ?>
                <div class="field">
                  <div class="fieldtitle"> Quality Grade:
                    <?php
                                          	if(Mage::getModel('hprcv/hprcv')->qualitygradecomparison($_product->getAttributeText('emb_stone_name3'))){
										?>
                    <span onclick="qualitypopupclick('<?php echo $_product->getAttributeText('emb_stone_name3');?>','<?php echo $_product->getAttributeText('emb_shape3');?>')" class="popupicon qualitypopupbtn quality-popup-help"></span>
                    <?php }?>
                  </div>
                  <div class="fieldvalue" id="Emb3-grade" about="<?php echo strtolower($_product->getAttributeText('emb_stone_name3').  $_product->getAttributeText('emb_quality_grade3')) ?>"><?php echo $_product->getAttributeText('emb_quality_grade3') ?></div>
                  <div style="clear:both"></div>
                </div>
                <?php endif?>
              </div>
              <?php endif;
                                
                                if($_product->getEmbStoneName2()): ?>
              <div id="Emb2-stone-detail-box" class="<?php echo ($_product->getEmbStoneName3())?'stone-detail-box':'stone-detail-box-odd'; ?>">
                <div class="detail-box-title"><!-- 2 -->
                  <?php if($_product->getAttributeText('emb_stone_name2')=="Diamond" || $_product->getAttributeText('emb_stone_name2')=="Simulated Diamond"): ?>
                  Diamond
                  <?php else:?>
                  Gemstone
                  <?php endif?>
                  Information:</div>
                <?php if($_product->getEmbNumberOfStones2()): ?>
                <div class="field">
                  <div class="fieldtitle">Number of <?php echo $_product->getAttributeText('emb_shape2') ?> 
                  <span id="Emb2-name"><?php 
					if($_product->getData('emb_number_of_stones2') > 1){
                    	if($_product->getAttributeText('emb_stone_name2')=="Ruby"){
							echo "Rubies";
						} elseif($_product->getAttributeText('emb_stone_name2')=="Lab Created Ruby"){
							echo "Lab Created Rubies";
						} else{
							echo $_product->getAttributeText('emb_stone_name2')."s";
						}
					}else{
						echo $_product->getAttributeText('emb_stone_name2');
					}
					?></span>:</div>
                  <div class="fieldvalue" id="Emb2-count"><?php echo $_product->getData('emb_number_of_stones2') ?></div>
                  <div style="clear:both"></div>
                </div>
                <?php endif?>
                <?php if($_product->getEmbDimension2()): ?>
                <div class="field">
                  <div class="fieldtitle"> Approximate Dimensions:
                    <?php
                                          	if(Mage::getModel('hprcv/hprcv')->qualitygradecomparison($_product->getAttributeText('emb_stone_name2'))){
										?>
                    <span class="approx-dim-help popupicon" onclick="weightpopupclick('<?php echo $_product->getAttributeText('emb_stone_name2');?>','<?php echo $_product->getAttributeText('emb_shape2');?>')"></span>
                    <?php }?>
                  </div>
                  <div class="fieldvalue" id="Emb2-size"><?php echo $_product->getData('emb_dimension2') ?> mm</div>
                  <div style="clear:both"></div>
                </div>
                <?php endif?>
                <?php if($_product->getEmbCaratWeight2()): ?>
                <div class="field">
                  <div class="fieldtitle">Approximate Carat Total Weight:
                    <?php
                                          	if(Mage::getModel('hprcv/hprcv')->qualitygradecomparison($_product->getAttributeText('emb_stone_name2'))){
										?>
                    <span class="app-ctw-help popupicon" onclick="weightpopupclick('<?php echo $_product->getAttributeText('emb_stone_name2');?>','<?php echo $_product->getAttributeText('emb_shape2');?>')"></span> 
                    <script>
									   		transferupWeightPopup('<?php echo $_product->getAttributeText('emb_stone_name2');?>','<?php echo $_product->getAttributeText('emb_shape2');?>');
									   </script>
                    <?php }?>
                  </div>
                  <div class="fieldvalue" id="Emb2-weight"><?php echo $_product->getData('emb_carat_weight2') ?> cts</div>
                  <div style="clear:both"></div>
                </div>
                <?php endif?>
                <?php if($_product->getEmbQualityGrade2()): ?>
                <div class="field">
                  <div class="fieldtitle"> Quality Grade:
                    <?php
                                          	if(Mage::getModel('hprcv/hprcv')->qualitygradecomparison($_product->getAttributeText('emb_stone_name2'))){
										?>
                    <span onclick="qualitypopupclick('<?php echo $_product->getAttributeText('emb_stone_name2');?>','<?php echo $_product->getAttributeText('emb_shape2');?>')" class="popupicon qualitypopupbtn quality-popup-help"></span>
                    <?php }?>
                  </div>
                  <div class="fieldvalue" id="Emb2-grade" about="<?php echo strtolower($_product->getAttributeText('emb_stone_name2').$_product->getAttributeText('emb_quality_grade2')) ?>">
                    <?php
										if($_product->getAttributeText('emb_quality_grade2')=='A' || $_product->getAttributeText('emb_quality_grade2')=='AA' || $_product->getAttributeText('emb_quality_grade2')=='AAA' || $_product->getAttributeText('emb_quality_grade2')=='AAAA'){
											echo 'Natural '.$_product->getAttributeText('emb_quality_grade2');
										}else{	
											echo $_product->getAttributeText('emb_quality_grade2');
										}
										?>
                  </div>
                  <div style="clear:both"></div>
                </div>
                <?php endif?>
              </div>
              <?php endif;
                                
                                if($_product->getEmbStoneName()): ?>
              <?php 
                                $oddclass = ($_product->getEmbStoneName3())?'stone-detail-box-odd':(($_product->getEmbStoneName2())?'stone-detail-box':'stone-detail-box-odd'); ?>
              <?php if($_product->getEmbStoneName3()){
                                            echo '<div style="clear:both"></div>';
                                        }
                                ?>
              <div id="Emb1-stone-detail-box" class="<?php echo $oddclass; ?>">
                <div class="detail-box-title"><!-- 1 -->
                  <?php if($_product->getAttributeText('emb_stone_name')=="Diamond" || $_product->getAttributeText('emb_stone_name')=="Simulated Diamond"): ?>
                  Diamond
                  <?php else:?>
                  Gemstone
                  <?php endif?>
                  Information:</div>
                <?php if($_product->getEmbNumberOfStones1()): ?>
                <div class="field">
                  <div class="fieldtitle">Number of <?php echo $_product->getAttributeText('emb_shape1') ?> 
                  <span id="Emb1-name"><?php 
					if($_product->getData('emb_number_of_stones1') > 1){
                    	if($_product->getAttributeText('emb_stone_name')=="Ruby"){
							echo "Rubies";
						} elseif($_product->getAttributeText('emb_stone_name')=="Lab Created Ruby"){
							echo "Lab Created Rubies";
						} else{
							echo $_product->getAttributeText('emb_stone_name')."s";
						}
					}else{
						echo $_product->getAttributeText('emb_stone_name');
					}
					?></span>:<!--<span class="help-icon" about="<?php echo $_product->getAttributeText('emb_shape1') ?>"></span>--></div>
                  <div class="fieldvalue" id="Emb1-count"><?php echo $_product->getData('emb_number_of_stones1') ?></div>
                  <div style="clear:both"></div>
                </div>
                <?php endif?>
                <?php if($_product->getEmbDimension1()): ?>
                <div class="field">
                  <div class="fieldtitle"> Approximate Dimensions: </div>
                  <div class="fieldvalue" id="Emb1-size"><?php echo $_product->getData('emb_dimension1') ?> mm</div>
                  <div style="clear:both"></div>
                </div>
                <?php endif?>
                <?php if($_product->getEmbCaratWeight1()): ?>
                <div class="field">
                  <div class="fieldtitle">Approximate Carat Total Weight: </div>
                  <div class="fieldvalue" id="Emb1-weight"><?php echo $_product->getData('emb_carat_weight1') ?> cts</div>
                  <div style="clear:both"></div>
                </div>
                <?php endif?>
                <?php if($_product->getAttributeText('emb_stone_name')=="Diamond" && !($_product->getEmbStoneName2())): ?>
                <?php if($_product->getEmbColor1()): ?>
                <div class="field">
                  <div class="fieldtitle">Min Color:</div>
                  <div class="fieldvalue"><?php echo $_product->getAttributeText('emb_color1') ?></div>
                  <div style="clear:both"></div>
                </div>
                <?php endif?>
                <?php if($_product->getEmbClarity1()): ?>
                <div class="field">
                  <div class="fieldtitle">Min Clarity:</div>
                  <div class="fieldvalue"><?php echo $_product->getAttributeText('emb_clarity1') ?></div>
                  <div style="clear:both"></div>
                </div>
                <?php endif?>
                <?php elseif($_product->getEmbQualityGrade1()): ?>
                <div class="field">
                  <div class="fieldtitle"> Quality Grade:
                    <?php
                                          	if(Mage::getModel('hprcv/hprcv')->qualitygradecomparison($_product->getAttributeText('emb_stone_name'))){
										?>
                    <span onclick="qualitypopupclick('<?php echo $_product->getAttributeText('emb_stone_name');?>','<?php echo $_product->getAttributeText('emb_shape1');?>')" class="popupicon qualitypopupbtn quality-popup-help"></span>
                    <?php }?>
                  </div>
                  <div class="fieldvalue" id="Emb1-grade" about="<?php echo strtolower($_product->getAttributeText('emb_stone_name').$_product->getAttributeText('emb_quality_grade1')) ?>">
                    <?php
										if($_product->getAttributeText('emb_quality_grade1')=='A' || $_product->getAttributeText('emb_quality_grade1')=='AA' || $_product->getAttributeText('emb_quality_grade1')=='AAA' || $_product->getAttributeText('emb_quality_grade1')=='AAAA'){
											echo 'Natural '.$_product->getAttributeText('emb_quality_grade1');
										}else{	
											echo $_product->getAttributeText('emb_quality_grade1');
										}
										?>
                  </div>
                  <div style="clear:both"></div>
                </div>
                <?php endif?>
              </div>
              <?php endif?>
            </div>
            <?php endif?>
          </div>
          <div id="help-icon-tooltip">
            <div id="help-content"></div>
          </div>
          <script type="text/javascript">
								jQuery(function(){
									
									
									// view new certificate
									function viewnewcert(product){
										//alert(product);
									}
									
									jQuery.getJSON('/skin/frontend/angara/default/staticdata/gemstones.json', function(gemstones) {
									
									jQuery('.help-icon, .help-text').each(function(){
										
										
												var about = jQuery(this).attr('about');
												var content = null;
												if(about == null){
													if(!jQuery(this).hasClass('help-text'))
														jQuery(this).hide(); // hide this useless !@#$ crap help icon 
												}else if(about == 'Oval'){
													content = gemstones.shapes.oval.description;
												}else if(about == 'Round'){ 
													content = gemstones.shapes.round.description;
												}else if(about == 'Pear'){
													content = gemstones.shapes.pear.description;
												}else if(about == 'Trillion'){
													content = gemstones.shapes.trillion.description;
												}else if(about == 'Marquise'){
													content = gemstones.shapes.marquise.description;
												}else if(about == 'Princess'){
													content = gemstones.shapes.princess.description;
												}else if(about == 'Emerald'){
													content = gemstones.shapes.emerald.description;
												}else if(about == 'Cushion'){
													content = gemstones.shapes.cushion.description;
												}else if(about == 'Emeraldcut'){
													content = gemstones.shapes.emeraldcut.description;
												}else if(about == 'Ascher'){
													content = gemstones.shapes.ascher.description;
												}else if(about == 'Heart'){
													content = gemstones.shapes.heart.description;
												}else if(about == 'Baguette'){
													content = gemstones.shapes.baguette.description;
												}else if(about == 'whitegold18k'){
													content = gemstones.metals.whitegold18k.description;
												}else if(about == 'yellowgold18k'){
													content = gemstones.metals.yellowgold18k.description;
												}else if(about == 'whitegold14k'){
													content = gemstones.metals.whitegold14k.description;
												}else if(about == 'yellowgold14k'){
													content = gemstones.metals.yellowgold14k.description;
												}else if(about == 'whitegold10k'){
													content = gemstones.metals.whitegold10k.description;
												}else if(about == 'silver'){
													content = gemstones.metals.silver.description;
												}else if(about == 'sterlingsilver'){
													content = gemstones.metals.sterlingsilver.description;
												}else if(about == 'sterlingsilver925'){
													content = gemstones.metals.sterlingsilver925.description;
												}else if(about == 'platinum'){
													content = gemstones.metals.platinum.description;
												}else if(about == 'emeralda'){
													content = gemstones.quality.emeralda.description;
												}else if(about == 'emeraldaa'){
													content = gemstones.quality.emeraldaa.description;
												}else if(about == 'emeraldaaa'){
													content = gemstones.quality.emeraldaaa.description;
												}else if(about == 'emeraldaaaa'){
													content = gemstones.quality.emeraldaaaa.description;
												}else if(about == 'rubya'){
													content = gemstones.quality.rubya.description;
												}else if(about == 'rubyaa'){
													content = gemstones.quality.rubyaa.description;
												}else if(about == 'rubyaaa'){
													content = gemstones.quality.rubyaaa.description;
												}else if(about == 'rubyaaaa'){
													content = gemstones.quality.rubyaaaa.description;
												}else if(about == 'sapphirea'){
													content = gemstones.quality.sapphirea.description;
												}else if(about == 'sapphireaa'){

													content = gemstones.quality.sapphireaa.description;
												}else if(about == 'sapphireaaa'){
													content = gemstones.quality.sapphireaaa.description;
												}else if(about == 'sapphireaaaa'){
													content = gemstones.quality.sapphireaaaa.description;
												}else if(about == 'tanzanitea'){
													content = gemstones.quality.tanzanitea.description;
												}else if(about == 'tanzaniteaa'){
													content = gemstones.quality.tanzaniteaa.description;
												}else if(about == 'tanzaniteaaa'){
													content = gemstones.quality.tanzaniteaaa.description;
												}else if(about == 'tanzaniteaaaa'){
													content = gemstones.quality.tanzaniteaaaa.description;
												}else if(about == 'diamonda'){
													content = gemstones.quality.diamonda.description;
												}else if(about == 'diamondaa'){
													content = gemstones.quality.diamondaa.description;
												}else if(about == 'diamondaaa'){
													content = gemstones.quality.diamondaaa.description;
												}else if(about == 'diamondaaaa'){
													content = gemstones.quality.diamondaaaa.description;
												}else if(about == 'amethysta'){
													content = gemstones.quality.amethysta.description;
												}else if(about == 'amethystaa'){
													content = gemstones.quality.amethystaa.description;
												}else if(about == 'amethystaaa'){
													content = gemstones.quality.amethystaaa.description;
												}else if(about == 'amethystaaaa'){
													content = gemstones.quality.amethystaaaa.description;
												}else if(about == 'opala'){
													content = gemstones.quality.opala.description;
												}else if(about == 'opalaa'){
													content = gemstones.quality.opalaa.description;
												}else if(about == 'opalaaa'){
													content = gemstones.quality.opalaaa.description;
												}else if(about == 'opalaaaa'){
													content = gemstones.quality.opalaaaa.description;
												}else if(about == 'garneta'){
													content = gemstones.quality.garneta.description;
												}else if(about == 'garnetaa'){
													content = gemstones.quality.garnetaa.description;
												}else if(about == 'garnetaaa'){
													content = gemstones.quality.garnetaaa.description;
												}else if(about == 'garnetaaaa'){
													content = gemstones.quality.garnetaaaa.description;
												}else if(about == 'aquamarinea'){
													content = gemstones.quality.aquamarinea.description;
												}else if(about == 'aquamarineaa'){
													content = gemstones.quality.aquamarineaa.description;
												}else if(about == 'aquamarineaaa'){
													content = gemstones.quality.aquamarineaaa.description;
												}else if(about == 'aquamarineaaaa'){
													content = gemstones.quality.aquamarineaaaa.description;
												}else if(about.indexOf('pearla',(about.length-6)) !=-1){
													content = gemstones.quality.pearla.description;
												}else if(about.indexOf('pearlaa',(about.length-7)) !=-1){
													content = gemstones.quality.pearlaa.description;
												}else if(about.indexOf('pearlaaa',(about.length-8)) !=-1){
													content = gemstones.quality.pearlaaa.description;
												}else if(about.indexOf('pearlaaaa',(about.length-9)) !=-1){
													content = gemstones.quality.pearlaaaa.description;
												}else if(about == 'peridota'){
													content = gemstones.quality.peridota.description;
												}else if(about == 'peridotaa'){
													content = gemstones.quality.peridotaa.description;
												}else if(about == 'peridotaaa'){
													content = gemstones.quality.peridotaaa.description;
												}else if(about == 'peridotaaaa'){
													content = gemstones.quality.peridotaaaa.description;
												}else if(about == 'citrinea'){
													content = gemstones.quality.citrinea.description;
												}else if(about == 'citrineaa'){
													content = gemstones.quality.citrineaa.description;
												}else if(about == 'citrineaaa'){
													content = gemstones.quality.citrineaaa.description;
												}else if(about == 'citrineaaaa'){
													content = gemstones.quality.citrineaaaa.description;

												}
												else{
													if(!jQuery(this).hasClass('help-text'))
														jQuery(this).hide(); // hide this useless !@#$ crap help icon 
												}
												
												jQuery(this).data('content',content);

									})
									
									
										//alert(gemstones.shapes)
										//alert(gemstones.shapes.oval.description)
										jQuery('.help-icon').click(
											function(e){
												e.stopPropagation();
												
												content = jQuery(this).data('content');
												
												jQuery('#help-icon-tooltip').find('#help-content').html(content);
												jQuery(this).append(jQuery('#help-icon-tooltip').fadeIn())
											}
										)
										
										jQuery('.help-text').hover(
											function(e){
												content = jQuery(this).data('content');
												if(jQuery.trim(content)!=''){
													jQuery('#help-icon-tooltip').find('#help-content').html(content);
													jQuery(this).append(jQuery('#help-icon-tooltip').show())
												}
											},
											function(){
												jQuery('#help-icon-tooltip').hide();
											}
										)
									})
									
									jQuery('body').click(function(){
										jQuery('#help-icon-tooltip').fadeOut();
									})
								})
							</script>
          <div style="clear:both"></div>
       </div>
        <div id="shipping-returns" class="producttxtlink" style="display: none; ">
          <div class="headingtag"><b>Return Policy:</b></div>
           <?php /*Start Request Shipping Label by Pankaj regarding bug id:774*/?>
          <div id="requestlabel-dialog" title="Request For Return Shipping Label"></div>
        If you are not 100% satisfied with your purchase, you can return it for a full refund within 30 days of the purchase date. Returns must be unworn and in the state that you received them.<br><br>
         We offer FREE return shipping for US domestic orders. To request a return shipping label for your purchase, simply submit a form by <a id="returnshipping-dialog-opener" href="#" style="text-decoration:underline;">clicking here</a>. International customers will need to pay for return shipping. Returns may take up to 1 week to process.<br><br> 
         For international returns, return shipping and insurance are the responsibility of the customer.<br><br>
          <?php /*End Request Shipping Label by Pankaj regarding bug id:774*/?>
          <div class="headingtag"><b>Shipping Policy:</b></div>
          We ship FREE to over 60 countries - We offer FREE FedEx Ground shipping within the USA and FedEx International Shipping worldwide at no cost. Upgraded shipping options are available at Checkout for nominal fees. If you need the item to be shipped faster than the shipping date indicated above, please call 888 926 4272 to speak to one of our Angara Advisors or click <a href="https://server.iad.liveperson.net/hc/609151/?cmd=file&amp;file=visitorWantsToChat&amp;site=609151&amp;byhref=1&amp;imageUrl=https://server.iad.liveperson.nethttp://www.angara.com/store/images/lp/">Live Chat</a>. A tracking number will be sent to your email upon shipment. </div>
        <div id="angara-difference" class="producttxtlink" style="display: none;">
          <div class="headingtag"><b>The Internet's Family Jeweler:</b></div>
          We live and breathe gemstones and fine jewelry.  We are family owned and have been in the gemstone business for 3 generations.  As with a traditional family jeweler experience, we will work with you to find or create the jewelry piece of your dreams.  If you cannot find  the gemstone or fine jewelry piece that you are looking for on the website, simply call us at 888 926 4272 and our team will find or create your piece.  If we can't source it, it probably doesn't exist. <span class="internetjeweler" style="cursor:pointer; text-decoration:underline;">Our Customers Say It Best</span> <br>
          <br>
          <div class="headingtag"><b>Direct From The Source:</b></div>
          With manufacturing and sourcing offices in  Jaipur, India (commonly known as the World's Gemstone Capital),  Thailand (where the majority of the world's rubies and sapphires are cut and polished), and the USA, we are able to source the best quality gemstones directly from the mines and manufacturers.  Further, we manufacture the large majority of our gemstone jewelry - thus, we cut out all middlemen and are able to offer unparalleled prices. Independent surveys have verified that our jewelry prices are approximately 40% lower than those of our competition. <br>
          <br>
          <div class="headingtag"><b>Exceptional Value And Quality, Guaranteed By A 110% Refund Policy:</b></div>
          We guarantee exceptional value and quality.  We will refund 110% of the purchase price (up to an additional $250 refund) if any accredited jewelry appraiser values the piece for less than 125% of the purchase price or writes that the craftsmanship is not of exceptional quality.
          <?php if(strtolower($_product->getAttributeText('emb_stone_name3'))=="blue sapphire" || strtolower($_product->getAttributeText('emb_stone_name2'))=="blue sapphire" || strtolower($_product->getAttributeText('emb_stone_name'))=="blue sapphire"): ?>
          <span class="valuequality" style="cursor:pointer; text-decoration:underline;">Our Customers Say It Best</span>
          <?php endif; ?>
          <br>
          <br>
          <div class="headingtag"><b>30 Day Money Back Guarantee:</b></div>
          If you don't love it, simply send it back in its original condition for a full refund. Return shipping is FREE.
          <br><br>
          <div class="headingtag"><b>Higher Quality:</b></div>
          Our jewelry is meant to last for generations.  The focus is on maximizing beauty rather than on saving gold or gemstone weight by reducing quality.  While our competitors have reduced weight to 2-3 grams for most products as gold costs have gone up, our average product weight remains at 3-5 grams.  Even if this philosophy and commitment to fine jewelry costs us more, we believe that the customer will be much happier as a result. <br>
          <br>
        </div>
        
        <div id="product-review" style="display: none;">
     
          <div class="customer-review">
            <div><?php echo $this->getChildHtml('reviews') ?>
				<script>
					jQuery(function(){
						jQuery.ajax({url:'/crossreviews/index/index/id/'+curid,type:"GET",dataType:"html",success:function(html){jQuery('#cross-reviews').html(html);jQuery('#cross-reviews').data('reviews-loaded','true')}})
						loadStoneReviews(curQualityGrade);
					})
					
					
				</script></div>
            <div style="clear:both"></div>
          </div>
        </div>
   		</div>
   
   
    	<?php /*?><div class="customerreviewsection" id="customer-review-block" >
      <h3>CUSTOMER REVIEWS</h3>
		<div id="product-reviews" class="productcustomreview custom-scroll" onScroll="javascript:void(0);">
			<div>
				<?php echo $this->getChildHtml('reviews') ?>
				<script>
					jQuery(function(){
						jQuery.ajax({url:'/crossreviews/index/index/id/'+curid,type:"GET",dataType:"html",success:function(html){jQuery('#cross-reviews').html(html);jQuery('#cross-reviews').data('reviews-loaded','true')}})
						loadStoneReviews(curQualityGrade);
					})
					
					
				</script>
			</div>
		</div>
        </div>      
		<div id="shipping-returns">
			<h3>Shipping &amp; Returns</h3>
            <ul class="pointlist">
            	<li>Save up to 40% off retail</li>
                <li>Trusted gemstone source</li>
                <li>110% refund policy</li>                
            </ul>
			
		</div>
		<div id="angara-difference">
			<h3>The Angara Difference</h3>
            <ul class="pointlist">
            	<li>30 day return policy</li>
                <li>Free shipping within the USA</li>
                <li>Free international shipping on orders above USD 500</li>                
            </ul>
		
		</div><?php */?>
	</div>
	<div style="clear:both"></div>
</div>
<script type="text/javascript">
    //<![CDATA[
	
		function trackShoppingCart(res, form){
			if(res){
					_gaq.push(['_trackEvent', "<?php echo $tracCategory;?>", 'shoppingcart', "<?php echo $_product->getSku() ?>", undefined, true]);
				}
		}
		
        var productAddToCartForm = new VarienForm('product_addtocart_form');
		var productAddToCartFormValidator = new Validation('product_addtocart_form');
		
        productAddToCartForm.submit = function(button, url) {
			
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                   form.action = url;
                }
                var e = null;
                try {
                    this.form.submit();
                } catch (e) {
                }
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }

                if (button && button != 'undefined') {
                    button.disabled = true;
                }
            }
        }.bind(productAddToCartForm);

        productAddToCartForm.submitLight = function(button, url){
            if(this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);
		
    //]]>
</script>
<script language="javascript">
	jQuery(function(){
		if(typeof(s)!='undefined')
			s.t();
		
		<?php if(isset($_REQUEST['videoplay']) && !empty($_REQUEST['videoplay'])){ ?>	
			jQuery('#playvideoicon').trigger('click');	
		<?php } ?>	
	})
</script>
<?php 	// Added by Vaseem for Engraving
$_product 					= 	$this->getProduct();
		$product = Mage::getModel("catalog/product")->load($_product->getId());
    $i = 0;
    foreach ($product->getOptions() as $o) {
		$optionArray[$i]		=		array('Id'=>$o->getId(),'Title'=>$o->getTitle(),'Sku'=>$o->getSku(),'Price'=>$o->getPrice(),'MaxCharacters'=>$o->getMaxCharacters());
		$skuArray[]				=		$o->getSku();
        $i++;
    }
	if(in_array('engraving',$skuArray)){
		$key				=		array_search( "engraving", $skuArray); 
		$engravingOptionId	=		$optionArray[$key]['Id'];
		$title				=		$optionArray[$key]['Title'];
		$price				=		$optionArray[$key]['Price'];
		$maxCharacters		=		$optionArray[$key]['MaxCharacters']-25;
		$formattedPrice 	= 		Mage::helper('core')->currency($price, true, false);
		$formattedPrice 	= 		($formattedPrice=='$25.00')?'$25':$formattedPrice;

?>
<script type="text/javascript" language="javascript">
	// Code added by Hitesh
	function getMovie(movie) {
		var isIE = navigator.appName.indexOf("Microsoft") != -1;
		return document.getElementById(movie);
	}
	function updateEngravingText(str)
    {	
    	getMovie("engraving")._updateEngravingText(str);
    }
	function changeFontType(fontType, fontStyle){
		if(fontStyle){
			getMovie("engraving")._changeFontType(fontType, fontStyle);
		}else{
			getMovie("engraving")._changeFontType(fontType);
		}
	}
	function changeMetal(type){
		getMovie("engraving")._updateMetal(type);
	}
	// Code added by Hitesh
	
//	Opening popup by Vaseem Ansari
jQuery(function() {
	
	<!--[if !IE]><!-->
 	jQuery('#engraving_popup').appendTo('body');	// Grey box added
	<!--<![endif]-->
				
	jQuery("#engraveLink,#editEng").click(function(event){
		var whichClick = jQuery(this).attr('id');
		var value = jQuery.trim(jQuery("#engravedText").val());
		if(value != null && value != 'undefined' && value!='' && value != 'Your text here' && whichClick=='engraveLink'){
			event.preventDefault();
		}
		else{
			if(jQuery.browser.msie == true) {
				jQuery('#engraveDiv').css('top','-210px');
			}else{
				jQuery('#engraveDiv').css('top','191px');
			}
			<!--[if !IE]><!-->
			jQuery('#engraving_popup').css('top','0px');
			<!--<![endif]-->
			/* #todo modify it for customj etc. */
			if(jQuery('#metaldescription').length){ 
				var metalpage	=	jQuery('#metaldescription strong').html();
				if(metalpage=='14K Yellow Gold:'){
					changeMetal('Yellow');	
				}else{
					changeMetal('White');	
				}
			}
			// For ADVRP
			//alert(ringmetal);
			if(jQuery('.metaldescription').length){ 
				if(ringmetal != null && ringmetal!='' && ringmetal!= 'undefined' && ringmetal=='14K Yellow Gold:'){
					changeMetal('Yellow');	
				}else{
					changeMetal('White');	
				}
			}
		}
		estimateShipEngraving();
	});
});
//	Getting typed value by Vaseem Ansari
// # todo what if user chooses not to engrave text?
jQuery(function(){
	var fontValue;
	var value = 'Your text here';
		
	jQuery('#engravedText').focusin(function(){
		value 		= 	jQuery.trim(jQuery("#engravedText").val());
		if(value == 'Your text here'){
			jQuery("#engravedText").val('');
		}
	})
	.focusout(function(){
		value 		= 	jQuery.trim(jQuery("#engravedText").val());
		if(value == ''){
			jQuery("#engravedText").val('Your text here');
			updateEngravingText('Your text here');
			jQuery('#remainingChar').text('<?php echo $maxCharacters;?>');
		}
	})
	.bind('paste keyup',function(){
		value 		= 	jQuery.trim(jQuery("#engravedText").val());
		fontValue 	= 	jQuery("#engraveFont").val();
		finalValue	=	value + ' ' + fontValue;
		
		// Putting the character limit to text
		var $this = jQuery(this);
		if(value.length > <?php echo $maxCharacters;?>)
		$this.val(value.substr(0, <?php echo $maxCharacters;?>));

		//	Getting remaining characters by Vaseem Ansari
		var left = <?php echo $maxCharacters;?> - value.length;
		jQuery('#remainingChar').text(left);
		updateEngravingText(value);
		
	});
	
	// Changing the class for selected font
	jQuery(".fontbox").click(function(){
		jQuery(this).each(function(){ 
			jQuery("a.activefont").removeClass("activefont");
			jQuery(this).find('a').toggleClass("activefont");
			
			fontType	=	jQuery(this).find('a').attr("rel");
			jQuery("#showFontDiv").html(jQuery(this).find('a').attr("alt"));
			jQuery("#engraveFont").val(jQuery(this).find('a').attr("alt"));
			
			if(value!=null && value!='undefined' && value!=''){		
				finalValue	=	value + ' ' + fontType;
				jQuery('#options_<?php echo $engravingOptionId;?>_text').val(finalValue);		//	writing value to custom option input box
			}
		});
	})
	
	// Global function to remove text and reset the engraving
	function removeText(){
		jQuery('#engravedText').val('Your text here');
		updateEngravingText('Your text here');
		jQuery('#remainingChar').text(<?php echo $maxCharacters;?>);
		jQuery('#options_<?php echo $engravingOptionId;?>_text').val('');		//	removing the value to custom option input box
		jQuery('#removeEng,#editEng').hide();
		jQuery('#engraveringchk').attr('checked', false);
		jQuery('#engraveringchk').attr('disabled', false);
		opConfig.reloadPrice();
		estimateShipEngraving();
	}
	// Clearing the Text
	jQuery("#clearTxt").click(function(){
		removeText();
		value	=	'';
	});
	// Closing the dialog box
	jQuery('.close-popup').click(function(e){
		e.stopPropagation();
		jQuery('#engraveDiv').css('top','-9999px');
		<!--[if !IE]><!-->
		jQuery('#engraving_popup').css('top','-9999px');
		<!--<![endif]-->
		removeText();
		jQuery('#engraveTitle').html('Add Engraving <?php if($price>0) {echo ' For '.$formattedPrice;}?>');
	})
	// Remove engraving
	jQuery('#removeEng').click(function(e){
		e.stopPropagation();
		removeText();
		jQuery('#engraveTitle').html('Add Engraving <?php if($price>0) {echo ' For '.$formattedPrice;}?>');
	})
	
	jQuery("#engraveContinue").click(function(e){
		e.stopPropagation();
		var value = jQuery.trim(jQuery("#engravedText").val());
		jQuery('#engraveDiv').css('top','-9999px');
		if(value != null && value != 'undefined' && value!='' && value != 'Your text here'){
			fontValue 	= 	jQuery("#engraveFont").val();
			finalValue	=	value + ' ' + fontValue;
			jQuery('#options_<?php echo $engravingOptionId;?>_text').val(finalValue);		//	writing value to custom option input box
			jQuery('#removeEng,#editEng').show();
			jQuery('#engraveTitle').html('Engraving Added');
			jQuery('#engraveringchk').attr('checked', true);
			jQuery('#engraveringchk').attr('disabled', true);
		}
		else{
			jQuery('#options_<?php echo $engravingOptionId;?>_text').val('');
			jQuery('#removeEng,#editEng').hide();
			jQuery('#engraveTitle').html('Add Engraving <?php if($price>0) {echo ' For '.$formattedPrice;}?>');
			jQuery('#engraveringchk').attr('checked', false);
			jQuery('#engraveringchk').attr('disabled', false);
		}
		opConfig.reloadPrice();
		estimateShipEngraving();
		<!--[if !IE]><!-->
		jQuery('#engraving_popup').css('top','-9999px');
		<!--<![endif]-->
	});
});

function qualitypopupclick(curstone,curshape){
	rnd_num = parseInt(Math.random()*9999999);
	popupstonetype = curstone;
	popupstoneshape = curshape;
	jQuery('.view-more-popup-btn').show();
	jQuery('.view-more-popup').hide();
	jQuery('.popupboxnew').hide().html('');
	jQuery('#qualitypopup').show();
	jQuery.ajax({
	url:'/hprcv/qualitycompare/get/?stonetype='+popupstonetype+'&stoneshape=' + popupstoneshape + '&rnd=' + rnd_num,
	success: function(matter){
			jQuery('#qualitypopup').html(matter);
			jQuery('#qualitypopup').data('loaded','yes');
			jQuery('.popupboxcross').click(function(){
				jQuery('.popupboxnew').hide().html('');
			})
			
			jQuery('.view-more-popup-btn').click(function(){
				jQuery(this).parent().find('.view-more-popup').show();
				jQuery(this).hide();
			})
		}
	})	
}
function weightpopupclick(curstone,curshape){
	rnd_num = parseInt(Math.random()*9999999);
	popupstonetype = curstone;
	popupstoneshape = curshape;
	jQuery('.popupboxnew').hide().html('');
	jQuery('#roundstonepopup').show();
	//if(jQuery('#roundstonepopup').data('loaded')!='yes'){
		jQuery.ajax({
		url:'/hprcv/qualitycompare/getweightchart/?stonetype='+popupstonetype+'&stoneshape=' + popupstoneshape + '&rnd=' + rnd_num,
		success: function(matter){
				jQuery('#roundstonepopup').html(matter);
				jQuery('#roundstonepopup').data('loaded','yes');
				
				jQuery('.popupboxcross').click(function(){
					jQuery('.popupboxnew').hide().html('');
					
				}
				)
				
			}
		})
	//}	
}
</script>
<?php } // Added by Vaseem for Engraving?>