<?php $_code=$this->getMethodCode() ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">

    <li class="hidden">
        <div class="input-box">
        	Select Card Type
            <select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" <?php /*?>class="required-entry validate-cc-type-select"<?php */?>>
                <option value=""><?php echo $this->__('Amex / Visa / Master / Discover')?></option>
            <?php $_ccType = $this->getInfoData('cc_type') ?>
            <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                <option value="<?php echo $_typeCode ?>"<?php if($_typeCode==$_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
            <?php endforeach ?> 
            </select>
        </div>
    </li>
    
    <li class="max-margin-top full-width pull-left">
        <div class="input-box">
            <label class="ielabel hidden" for="<?php echo $_code ?>_cc_owner"><?php echo $this->__('Name on Card') ?></label>
            <input type="text" title="<?php echo $this->__('Name on Card') ?>" placeholder="<?php echo $this->__('Name on Card') ?>" class="input-text" id="<?php echo $_code ?>_cc_owner" name="payment[cc_owner]" value="<?php echo $this->htmlEscape($this->getInfoData('cc_owner')) ?>" />
        </div>
    </li>
    
    <li class="max-margin-top full-width pull-left">
        <div class="input-box">
			<label class="ielabel hidden" for="<?php echo $_code ?>_cc_number"><?php echo $this->__('Credit Card Number') ?></label>
            <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text validate-cc-number validate-cc-type" value="" placeholder="Card Number"/>
        </div>
        
        <script>
		jQuery(function() {
			jQuery('#<?php echo $_code ?>_cc_number').validateCreditCard(function(result) {
				jQuery('select[name^="payment[cc_type]"] option:selected').attr("selected",null);		//	reset card type
				jQuery('.cc-company-logos span').each(function(){
					jQuery(this).removeClass('grey-logo');
					if(result.card_type!= null){
						//	Select card type
						if(result.card_type.name=='visa'){
							jQuery("#<?php echo $_code ?>_cc_type").val("VI").attr('selected','selected');
							//jQuery('select[name^="payment[cc_type]"] option[value="VI"]').attr("selected","selected");
						}
						if(result.card_type.name=='amex'){
							jQuery("#<?php echo $_code ?>_cc_type").val("AE").attr('selected','selected');
							//jQuery('select[name^="payment[cc_type]"] option[value="AE"]').attr("selected","selected");
						}
						if(result.card_type.name=='mastercard'){
							jQuery("#<?php echo $_code ?>_cc_type").val("MC").attr('selected','selected');
							//jQuery('select[name^="payment[cc_type]"] option[value="MC"]').attr("selected","selected");
						}
						if(result.card_type.name=='discover'){
							jQuery("#<?php echo $_code ?>_cc_type").val("DI").attr('selected','selected');
							//jQuery('select[name^="payment[cc_type]"] option[value="DI"]').attr("selected","selected");
						}
						
						if(jQuery(this).attr('id') != (result.card_type.name)){
							jQuery(this).addClass('grey-logo');
						}
					}
				})
			});
		});
		</script>
		<img src="/skin/frontend/ress/default/images/ipad-cc-company-logos-grey.jpg" class="hidden"/>
		<div class="cc-company-logos">
			<span id="amex" class="amex"></span>
			<span id="visa" class="visa"></span>
			<span id="mastercard" class="mastercard"></span>
			<span id="discover" class="discover"></span>
		</div>
    </li>
    <li id="<?php echo $_code ?>_cc_type_exp_div" class="max-margin-top full-width pull-left">
        <div class="input-box">
			<div class="row">
            <div class="col-xs-12"><label class="ielabel hidden" for="<?php echo $_code ?>_expiration"><?php echo $this->__('Expiration Date') ?></label></div>
            <div class="clearfix"></div>
            <div class="col-sm-6 high-margin-bottom-xs">
                <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="month validate-cc-exp required-entry">
                <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
            </div>
            <div class="col-sm-6 high-margin-bottom-xs">
                <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="year required-entry">
                <?php foreach ($this->getCcYears() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
            </div>
			</div>
        </div>
    </li>
    <?php echo $this->getChildHtml() ?>
    <?php if($this->hasVerification()): ?>
    <li id="<?php echo $_code ?>_cc_type_cvv_div" class="max-margin-top full-width pull-left cvv">
        <div class="input-box">
            <div class="v-fix" style="width:45%;">
				<label class="ielabel hidden" for="<?php echo $_code ?>_cc_cid"><?php echo $this->__('Security Code') ?></label>
                <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" placeholder="Security Code"/>
            </div>
            <a href="#" class="cvv-what-is-this"><i class="fa fa-question-circle apricot-text" aria-hidden="true"></i><?php //echo $this->__('?') ?></a>
        </div>
    </li>
    <?php endif; ?>

    <?php if ($this->hasSsCardType()): ?>
    <li id="<?php echo $_code ?>_cc_type_ss_div" class="max-margin-top full-width pull-left">
        <ul class="inner-form">
            <li class="form-alt"><label for="<?php echo $_code ?>_cc_issue" class="required"><em>*</em><?php echo $this->__('Switch/Solo/Maestro Only') ?></label></li>
            <li>
                <label for="<?php echo $_code ?>_cc_issue"><?php echo $this->__('Issue Number') ?>:</label>
                <span class="input-box">
                    <input type="text" title="<?php echo $this->__('Issue Number') ?>" class="input-text validate-cc-ukss cvv" id="<?php echo $_code ?>_cc_issue" name="payment[cc_ss_issue]" value="" />
                </span>
            </li>
            <li>
                <label for="<?php echo $_code ?>_start_month"><?php echo $this->__('Start Date') ?>:</label>
                <div class="input-box">
                    <div class="v-fix">
                        <select id="<?php echo $_code ?>_start_month" name="payment[cc_ss_start_month]" class="validate-cc-ukss month">
                        <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                            <option value="<?php echo $k?$k:'' ?>"<?php if($k==$this->getInfoData('cc_ss_start_month')): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                        <?php endforeach ?>
                        </select>
                    </div>
                    <div class="v-fix">
                        <select id="<?php echo $_code ?>_start_year" name="payment[cc_ss_start_year]" class="validate-cc-ukss year">
                        <?php foreach ($this->getSsStartYears() as $k=>$v): ?>
                            <option value="<?php echo $k?$k:'' ?>"<?php if($k==$this->getInfoData('cc_ss_start_year')): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                        <?php endforeach ?>
                        </select>
                    </div>
                </div>
            </li>
            <li class="adv-container">&nbsp;</li>
        </ul>
        <script type="text/javascript">
        //<![CDATA[
        var SSChecked<?php echo $_code ?> = function() {
            var elm = $('<?php echo $_code ?>_cc_type');
            if (['SS','SM','SO'].indexOf(elm.value) != -1) {
                $('<?php echo $_code ?>_cc_type_ss_div').show();
            } else {
                $('<?php echo $_code ?>_cc_type_ss_div').hide();
            }
        };

        Event.observe($('<?php echo $_code ?>_cc_type'), 'change', SSChecked<?php echo $_code ?>);
        SSChecked<?php echo $_code ?>();
        //]]>
        </script>
    </li>
    <?php endif; ?>
</ul>