<?php if($crumbs && is_array($crumbs)): ?>
<div class="breadcrumb-studs">
    <ul xmlns:v="http://rdf.data-vocabulary.org/#">		<?php // Added by Vaseem for Google Rich Snippets?>
        <?php foreach($crumbs as $_crumbName=>$_crumbInfo): ?>
            <li class="<?php echo $_crumbName ?>" typeof="v:Breadcrumb">		<?php // Added by Vaseem for Google Rich Snippets?>
            <?php if($_crumbInfo['link']): ?>
                <a href="<?php echo $_crumbInfo['link'] ?>" title="<?php echo $this->htmlEscape($_crumbInfo['title']) ?>" rel="v:url" property="v:title"><?php echo $this->htmlEscape($_crumbInfo['label']) ?></a><?php // Added by Vaseem for Google Rich Snippets?>
            <?php elseif($_crumbInfo['last']): ?>
                <strong rel="v:child" property="v:title"><?php echo $this->htmlEscape($_crumbInfo['label']) ?></strong><?php // Added by Vaseem for Google Rich Snippets?>
            <?php else: ?>
                <?php echo $this->htmlEscape($_crumbInfo['label']) ?>
            <?php endif; ?>
            <?php if(!$_crumbInfo['last']): ?>
                <span> > </span>
            <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>
