<style>
.google-mailsignup-form{ width:967px;  background:url(/skin/frontend/ress/default/images/emailsignup-bg.jpg) no-repeat;}
.signup-sub-heading{ font-size:30px; line-height:36px; color:#7e0014; padding-top:20px;}
.signup-discriptive{ font-size:13px; line-height:18px; color:#7e0014; width:400px; padding:20px 0;}
.signup-form-wrapper{ width:400px;}
.input-text::-moz-placeholder{ color:#000!important;}
.calender-icon{ position:absolute; bottom:10px; right:10px; curser:pointer;}
#subscribeForm .input-text{ padding:6px 3px!important;font-size:11px;}
</style>
<div class="container showcase-bg-white min-padding-top relative-placeholder">
<div class="google-mailsignup-form">
<div class="signup-sub-heading">SUBSCRIBE NOW  <br /> FOR EXCLUSIVE OFFERS</div>
<div class="signup-discriptive">Be the first to know about Angara's newest jewelry, highest customer product reviews, exclusive offers, free jewelry gifts, shipping upgrades and much more before they take place. Subscribe now, and you'll become an Angara fan in no time.</div>
<div class="signup-form-wrapper">
<form action="<?php echo $this->getFormAction();?>" id="subscribeForm" method="post">
	<div class="row customer-name">
		<div class="col-sm-6 high-margin-bottom">
			<div class="data_area">  
				First Name     	
				<input type="text" id="subfname" class="input-text t1 " title="First Name" value="" 
				name="subfname">
			</div>
		</div>
		<div class="col-sm-6 high-margin-bottom">
			<div class="data_area"> 
				Last Name       
				<input type="text" id="sublname" class="input-text t1 " title="Last Name" value="" name="sublname" >
			</div>
		</div>
	</div>
	<div class="row">
		<div class="high-margin-bottom col-sm-12"> 
		Email Address<font color='#b94a48'>*</font>              	
		<input type="text" id="subemail" class="input-text required-entry validate-email" title="Email Address" value="" name="subemail">
		</div>
	</div>
	<div class="row customer-name">		
		<div class="col-sm-6 high-margin-bottom">
			<div class="data_area relative-placeholder">   
				Birth Date	
				<div class="row no-gutters">
				<div class="col-sm-4">
				<select class="validate-select input-text" name="subbirthmonth" id="subbirthmonth" autocomplete="off">
				 	<option value="MM">MM</option>
					<option value="01">01</option>
					<option value="02">02</option>
					<option value="03">03</option>
					<option value="04">04</option>
					<option value="05">05</option>
					<option value="06">06</option>
					<option value="07">07</option>
					<option value="08">08</option>
					<option value="09">09</option>
					<option value="10">10</option>
					<option value="11">11</option>
					<option value="12">12</option>                                  
				</select>
				</div>
				<div class="col-sm-4">
				<select class="validate-select input-text low-margin-right" name="subbirthdate" id="subbirthdate" autocomplete="off">
				 	<option value="DD">DD</option>
					<option value="01">01</option>
					<option value="02">02</option>
					<option value="03">03</option>
					<option value="04">04</option>
					<option value="05">05</option>
					<option value="06">06</option>
					<option value="07">07</option>
					<option value="08">08</option>
					<option value="09">09</option>
					<option value="10">10</option>
					<option value="11">11</option>
					<option value="12">12</option>
					<option value="13">13</option>
					<option value="14">14</option>
					<option value="15">15</option>
					<option value="16">16</option>
					<option value="17">17</option>
					<option value="18">18</option>
					<option value="19">19</option>
					<option value="20">20</option>
					<option value="21">21</option>
					<option value="22">22</option>
					<option value="23">23</option>
					<option value="24">24</option>
					<option value="25">25</option>
					<option value="26">26</option>
					<option value="27">27</option>
					<option value="28">28</option>
					<option value="29">29</option>
					<option value="30">30</option>
					<option value="31">31</option>                               
				</select>
				</div>
				<div class="col-sm-4">
				<select class="validate-select input-text" name="subbirthyear" id="subbirthyear" autocomplete="off">
					<option value="00">YYYY</option>
					<option value="15">2015</option>
					<option value="14">2014</option>
					<option value="13">2013</option>
					<option value="12">2012</option>
					<option value="11">2011</option>
					<option value="10">2010</option>
					<option value="09">2009</option>
					<option value="08">2008</option>
					<option value="07">2007</option>
					<option value="06">2006</option>
					<option value="05">2005</option>
					<option value="04">2004</option>
					<option value="03">2003</option>
					<option value="02">2002</option>
					<option value="01">2001</option>
					<option value="00">2000</option>
					<option value="99">1999</option>
					<option value="98">1998</option>
					<option value="97">1997</option>
					<option value="96">1996</option>
					<option value="95">1995</option>
					<option value="94">1994</option>
					<option value="93">1993</option>
					<option value="92">1992</option>
					<option value="91">1991</option>
					<option value="90">1990</option>
					<option value="89">1989</option>
					<option value="88">1988</option>
					<option value="87">1987</option>
					<option value="86">1986</option>
					<option value="85">1985</option>
					<option value="84">1984</option>
					<option value="83">1983</option>
					<option value="82">1982</option>
					<option value="81">1981</option>
					<option value="80">1980</option>
					<option value="79">1979</option>
					<option value="78">1978</option>
					<option value="77">1977</option>
					<option value="76">1976</option>
					<option value="75">1975</option>
					<option value="74">1974</option>
					<option value="73">1973</option>
					<option value="72">1972</option>
					<option value="71">1971</option>
					<option value="70">1970</option>
					<option value="69">1969</option>
					<option value="68">1968</option>
					<option value="67">1967</option>
					<option value="66">1966</option>
					<option value="65">1965</option>
					<option value="64">1964</option>
					<option value="63">1963</option>
					<option value="62">1962</option>
					<option value="61">1961</option>
					<option value="60">1960</option>
					<option value="59">1959</option>
					<option value="58">1958</option>
					<option value="57">1957</option>
					<option value="56">1956</option>
					<option value="55">1955</option>
					<option value="54">1954</option>
					<option value="53">1953</option>
					<option value="52">1952</option>
					<option value="51">1951</option>
					<option value="50">1950</option>
					<option value="49">1949</option>
					<option value="48">1948</option>
					<option value="47">1947</option>
					<option value="46">1946</option>
					<option value="45">1945</option>
					<option value="44">1944</option>
					<option value="43">1943</option>
					<option value="42">1942</option>
					<option value="41">1941</option>
					<option value="40">1940</option>
					<option value="39">1939</option>
					<option value="38">1938</option>
					<option value="37">1937</option>
					<option value="36">1936</option>
					<option value="35">1935</option>
					<option value="34">1934</option>
					<option value="33">1933</option>
					<option value="32">1932</option>
					<option value="31">1931</option>
					<option value="30">1930</option> 					
				</select>
				</div>
			</div>
			</div>
		</div>
		<div class="col-sm-6 high-margin-bottom">
			<div class="data_area relative-placeholder">   
				Wedding Date	
				<div class="row no-gutters">
				<div class="col-sm-4">
				<select class="validate-select input-text" name="subanniversarymonth" id="subanniversarymonth" autocomplete="off">
				 	<option value="MM">MM</option>
					<option value="01">01</option>
					<option value="02">02</option>
					<option value="03">03</option>
					<option value="04">04</option>
					<option value="05">05</option>
					<option value="06">06</option>
					<option value="07">07</option>
					<option value="08">08</option>
					<option value="09">09</option>
					<option value="10">10</option>
					<option value="11">11</option>
					<option value="12">12</option>                                  
				</select>
				</div>
				<div class="col-sm-4">
				<select class="validate-select input-text low-margin-right" name="subanniversarydate" id="subanniversarydate" autocomplete="off">
				 	<option value="DD">DD</option>
					<option value="01">01</option>
					<option value="02">02</option>
					<option value="03">03</option>
					<option value="04">04</option>
					<option value="05">05</option>
					<option value="06">06</option>
					<option value="07">07</option>
					<option value="08">08</option>
					<option value="09">09</option>
					<option value="10">10</option>
					<option value="11">11</option>
					<option value="12">12</option>
					<option value="13">13</option>
					<option value="14">14</option>
					<option value="15">15</option>
					<option value="16">16</option>
					<option value="17">17</option>
					<option value="18">18</option>
					<option value="19">19</option>
					<option value="20">20</option>
					<option value="21">21</option>
					<option value="22">22</option>
					<option value="23">23</option>
					<option value="24">24</option>
					<option value="25">25</option>
					<option value="26">26</option>
					<option value="27">27</option>
					<option value="28">28</option>
					<option value="29">29</option>
					<option value="30">30</option>
					<option value="31">31</option>                               
				</select>
				</div>
				<div class="col-sm-4">
				<select class="validate-select input-text" name="subanniversaryyear" id="subanniversaryyear" autocomplete="off">
					<option value="00">YYYY</option>
					<option value="15">2015</option>
					<option value="14">2014</option>
					<option value="13">2013</option>
					<option value="12">2012</option>
					<option value="11">2011</option>
					<option value="10">2010</option>
					<option value="09">2009</option>
					<option value="08">2008</option>
					<option value="07">2007</option>
					<option value="06">2006</option>
					<option value="05">2005</option>
					<option value="04">2004</option>
					<option value="03">2003</option>
					<option value="02">2002</option>
					<option value="01">2001</option>
					<option value="00">2000</option>
					<option value="99">1999</option>
					<option value="98">1998</option>
					<option value="97">1997</option>
					<option value="96">1996</option>
					<option value="95">1995</option>
					<option value="94">1994</option>
					<option value="93">1993</option>
					<option value="92">1992</option>
					<option value="91">1991</option>
					<option value="90">1990</option>
					<option value="89">1989</option>
					<option value="88">1988</option>
					<option value="87">1987</option>
					<option value="86">1986</option>
					<option value="85">1985</option>
					<option value="84">1984</option>
					<option value="83">1983</option>
					<option value="82">1982</option>
					<option value="81">1981</option>
					<option value="80">1980</option>
					<option value="79">1979</option>
					<option value="78">1978</option>
					<option value="77">1977</option>
					<option value="76">1976</option>
					<option value="75">1975</option>
					<option value="74">1974</option>
					<option value="73">1973</option>
					<option value="72">1972</option>
					<option value="71">1971</option>
					<option value="70">1970</option>
					<option value="69">1969</option>
					<option value="68">1968</option>
					<option value="67">1967</option>
					<option value="66">1966</option>
					<option value="65">1965</option>
					<option value="64">1964</option>
					<option value="63">1963</option>
					<option value="62">1962</option>
					<option value="61">1961</option>
					<option value="60">1960</option>
					<option value="59">1959</option>
					<option value="58">1958</option>
					<option value="57">1957</option>
					<option value="56">1956</option>
					<option value="55">1955</option>
					<option value="54">1954</option>
					<option value="53">1953</option>
					<option value="52">1952</option>
					<option value="51">1951</option>
					<option value="50">1950</option>
					<option value="49">1949</option>
					<option value="48">1948</option>
					<option value="47">1947</option>
					<option value="46">1946</option>
					<option value="45">1945</option>
					<option value="44">1944</option>
					<option value="43">1943</option>
					<option value="42">1942</option>
					<option value="41">1941</option>
					<option value="40">1940</option>
					<option value="39">1939</option>
					<option value="38">1938</option>
					<option value="37">1937</option>
					<option value="36">1936</option>
					<option value="35">1935</option>
					<option value="34">1934</option>
					<option value="33">1933</option>
					<option value="32">1932</option>
					<option value="31">1931</option>
					<option value="30">1930</option> 					
				</select>
				</div>
			</div>
			</div>
		</div>
	</div>
	<div class="row customer-name">
		<div class="col-sm-6 high-margin-bottom">
			<div class="data_area">   
				Looking For     
				<select class="validate-select input-text" name="subgender" id="subgender" autocomplete="off">
				 
					<option value="male">Male</option>
					<option value="female">Female</option>
					                                    
				</select>
			</div>
		</div>
		<div class="col-sm-6 high-margin-bottom">
			<div class="data_area"> 
				Status       	
				<select class="validate-select input-text" name="substatus" id="substatus" autocomplete="off">
				
					<option value="single">Single</option>
					<option value="engaged_soon">Engaged Soon</option>
					<option value="engaged">Engaged</option> 
					<option value="married">Married</option>
				</select>
			</div>
		</div>		
	</div>
	<div class="row max-margin-top">
	<div class="row"><div class="col-sm-12 small max-padding-left">We will never publish, share, or sell your information in any way. <a href="/privacy-and-security.html" class="text-underline" target="_blank">Privacy Policy</a></div></div>
	<div class="col-sm-6 high-margin-top">
	<button type="submit" class="btn btn-primary btn-block btn-place-order fontsize-type2" title="Get Your Offer" type="submit">Get Your Offer</button>
	</div>
	</div>
</form>
<script type="text/javascript">
    var subscribeForm = new VarienForm('subscribeForm',true);
</script>
</div>
</div>
</div>


