<form id="newsletter-validate-detail" method="post" action="<?php echo ((Mage::app()->getStore()->isCurrentlySecure())?'https://':'http://').Mage::app()->getRequest()->getHttpHost().'/newsletter/subscriber/confirmed/';?>" onsubmit="return checkFormFooter(this);">
    <div class="padding-type-10">
        <div class="row">
            <div class="col-md-8 col-xs-8 col-sm-8">
                <input id="footerEmail" type="text" name="email" class="input-text required-entry validate-email showcase-border-thick" placeholder="Enter your email address" title="<?php echo $this->__('Email Address');?>">
                <input type="hidden" value="<?php echo Mage::helper('core/url')->getCurrentUrl(); ?>" name="return_url">
                <input type="hidden" value="<?php echo $this->getNewsletterType();?>" name="newslettertype">
                <div class="visible-md"></div>
            </div>
            <div class="col-md-4 col-xs-4 col-sm-4">
                <input type="submit" value="JOIN" class="btn btn-block btn-primary visible-xs subscribe-button">
                <input type="submit" value="Subscribe" class="btn btn-block btn-primary hidden-xs subscribe-button">
            </div>
        </div>
        <div class="row low-margin-top">
            <div class="col-sm-12 small text-left">We will never publish, share, or sell your information in any way. <a href="/privacy-and-security" class="apricot-text" target="_blank">Privacy Policy</a></div>
        </div>
    </div>
</form>
<script type="text/javascript">
//&lt;![CDATA[
var newsletterSubscriberFormDetail 	= 	new VarienForm('newsletter-validate-detail');
function checkFormFooter(frm) {
	var regFooter = /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;
	if(frm.footerEmail.value != '' && regFooter.test(frm.footerEmail.value) !== false) {
		return true;												
	}
	return false;
}
//]]&gt;
</script>