<?php
/**
 * Product:     Layered Navigation Pro for Magento 20/04/11
 * Package:     AdjustWare_Nav_2.1.1_0.1.4_8_74006
 * Purchase ID: QgBMpw5YKeeQ8cDxt9xj7DfR5rzlpaEBHoIuAZvOxv
 * Generated:   2011-06-08 07:09:19
 * File path:   app/design/frontend/default/default/template/adjnav/layer.phtml
 * Copyright:   (c) 2011 AITOC, Inc.
 */
?>
<?php
/*
 * Adding javascript include
 */
if ('ajax' != Mage::app()->getRequest()->getControllerName())
{
    if(Aitoc_Aitsys_Abstract_Service::get()->isMagentoVersion('>=1.4')):
    ?>
	<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/adjnav-14.js'); ?>"></script>
    <?php
    else:
    ?>
    <script type="text/javascript" src="<?php echo $this->getSkinUrl('js/adjnav-13.js');?>"></script>
    <?php
    endif;
}
?>








<?php
    if(Aitoc_Aitsys_Abstract_Service::get()->isMagentoVersion('>=1.4')):
?>









<?php if($this->canShowBlock()): $state = $this->getStateInfo()?>
    <div class="block block-layered-nav adj-nav">

    <!--<div class="block-title">
        <strong><span><?php echo $this->__('Shop by')?></span></strong>
    </div>-->
        <div class="block-content">
		<?php echo $this->getStateHtml() ?>
        <?php if($this->canShowOptions()): ?>

            <div class="narrow-by">
            <input type="hidden" id="adj-nav-url" value="<?php echo $this->htmlEscape($state[0])?>"/>
            <input type="hidden" id="adj-nav-params" value="<?php echo $this->htmlEscape($state[1])?>"/>
            <input type="hidden" id="adj-nav-ajax" value="<?php echo $this->htmlEscape($state[2])?>"/>
            <dl id="narrow-by-list">
			<?php $obj = new Mage_Catalog_Block_Navigation(); ?>
<?php $_current_category=$obj->getCurrentCategory()->getData('category_article_posts'); ?>
<?php $subs = $obj->getCurrentCategory()->getAllChildren(true); ?>
			<dt class="adj-nav-dt even">Related Categories<div class="arrow"></div></dt>
		<dd id="adj-nav-filter-related_category" class="even">
			<ol>
				<li><a class="adj-nav-attribute-nochk " href="/sapphire-rings.html">Sapphire <?php echo $_current_category ?>Rings</a></li>
				<li><a class="adj-nav-attribute-nochk " href="/sapphire-earrings.html">Sapphire Earrings</a></li>
			</ol>
		</dd>

            <?php if ($state[1] AND $this->bNeedClearAll()): ?>
<div class="actions adj-clear-all"><a onclick="return false;" class="adj-nav-clearall" href="<?php echo $this->htmlEscape($this->getClearAllUrl())?>"><?php echo $this->__('Clear All') ?></a></div>
            <?php endif ?>

            <?php $_filters = $this->getFilters() ?>
                <?php foreach ($_filters as $_filter): ?>
                <?php if ($_filter->getItemsCount() && $_filter->getName() != "Category"): ?>
                <dt class="adj-nav-dt">
                    <?php if ($clearUrl = $_filter->getClearUrl()): ?>

                    <a onclick="return false;" id="<?php echo $_filter->getVar()?>-clear" <?php if(!$this->getIsRemoveLinks()): ?>href="<?php echo $this->htmlEscape($clearUrl)?>" <?php endif; ?> class="btn-remove adj-nav-clear" title="<?php echo $this->__('Remove This Item')?>"><?php echo $this->__('Remove This Item')?></a>
                    <?php endif ?>
                    <?php echo $this->__($_filter->getName()) ?>
					<div class="arrow"></div>
                </dt>
                <dd <?php echo $this->getHeightStyle()?> id="adj-nav-filter-<?php echo $_filter->getVar()?>"><?php echo $_filter->getHtml() ?></dd>
                <?php endif; ?>
                <?php endforeach; ?>
				
				
				
				
		<dt class="adj-nav-dt even">Related Categories<div class="arrow"></div></dt>
		<dd id="adj-nav-filter-related_category" class="even">
			<ol>
				<li><a class="adj-nav-attribute-nochk " href="/sapphire-rings.html">Sapphire Rings</a></li>
				<li><a class="adj-nav-attribute-nochk " href="/sapphire-earrings.html">Sapphire Earrings</a></li>
			</ol>
		</dd>
		<dt class="adj-nav-dt even">Related Categories<div class="arrow"></div></dt>
		<dd id="adj-nav-filter-related_category" class="even">
			<ol>
				<li><a class="adj-nav-attribute-nochk " href="/sapphire-rings.html">Sapphire Rings</a></li>
				<li><a class="adj-nav-attribute-nochk " href="/sapphire-earrings.html">Sapphire Earrings</a></li>
			</ol>
		</dd>
				
				
				
				
            </dl>
            <script type="text/javascript">
            decorateDataList('narrow-by-list');
            adj_nav_init();
            </script>
            </div>
            <?php endif; ?>
        </div>
        <div class="adj-nav-progress" style="display:none"></div>
    </div>
<?php endif; ?>

<script type="text/javascript">
if ('function' == typeof(sns_layer_add_attr))
{
    sns_layer_add_attr();
}
adj_nav_toolbar_init();
</script>

















<?php
    else:
?>













<?php if($this->canShowBlock()): $state = $this->getStateInfo()?>
    <div class="box layered-nav adj-nav">
        <div class="head">
            <h3><?php echo $this->__('Shop by')?></h3>
        </div>
        <div class="border-creator">
        <?php if($this->canShowOptions()): ?>
            <div class="narrow-by">
            <input type="hidden" id="adj-nav-url" value="<?php echo $this->htmlEscape($state[0])?>"/>
            <input type="hidden" id="adj-nav-params" value="<?php echo $this->htmlEscape($state[1])?>"/>
            <input type="hidden" id="adj-nav-ajax" value="<?php echo $this->htmlEscape($state[2])?>"/>
            <dl id="narrow-by-list">
            <?php if ($state[1] AND $this->bNeedClearAll()): ?>
<div class="actions adj-clear-all"><a onclick="return false;" class="adj-nav-clearall" href="<?php echo $this->htmlEscape($this->getClearAllUrl())?>"><?php echo $this->__('Clear All') ?></a></div>
            <?php endif ?>
            <?php $_filters = $this->getFilters() ?>
                <?php foreach ($_filters as $_filter): ?>
                <?php if ($_filter->getItemsCount()): ?>
                <dt class="adj-nav-dt">
                    <?php if ($clearUrl = $_filter->getClearUrl()): ?>

                    <a onclick="return false;" id="<?php echo $_filter->getVar()?>-clear" <?php if(!$this->getIsRemoveLinks()): ?>href="<?php echo $this->htmlEscape($clearUrl)?>" <?php endif; ?> class="btn-remove adj-nav-clear" title="<?php echo $this->__('Remove This Item')?>"><?php echo $this->__('Remove This Item')?></a>
                    <?php endif ?>
                    <?php echo Mage::helper('catalog')->__($_filter->getName()) ?>
                </dt>
                <dd <?php echo $this->getHeightStyle()?> id="adj-nav-filter-<?php echo $_filter->getVar()?>"><?php echo $_filter->getHtml() ?></dd>
                <?php endif; ?>
                <?php endforeach; ?>
            </dl>
            <script type="text/javascript">
            decorateDataList('narrow-by-list');
            adj_nav_init();
            </script>
            </div>
            <?php endif; ?>
        </div>
        <div class="adj-nav-progress" style="display:none"></div>
    </div>
<?php endif; ?>

















<?php
    endif;
?>
<script type="text/javascript">
jQuery(function(){
	jQuery('#narrow-by-list').find('dd').each(function(){
		if(jQuery(this).find('li').length > 5){
			var item = jQuery(this);
			jQuery(this).find('li:gt(4)').hide();
			jQuery('<div class="more-filter-link">More...</div>').appendTo(jQuery(this)).toggle(function(){
					item.find('li:gt(4)').show(400);
					jQuery(this).text('Less...')
				},
				function(){
					item.find('li:gt(4)').hide(400);
					jQuery(this).text('More...')
				}
			)
		}
	})
	
	if(jQuery('#categorycontent').hasClass('slide-effect-done')){
		if(jQuery('#categorycontent').text().length>300){
			jQuery('#categorycontent').parent().find('.view-more-content-link').text('View More');
			jQuery('#categorycontent').html(jQuery('#categorycontent').data('htmldata'));
			jQuery('#categorycontent').animate({height:26},500,'swing',function(){
				jQuery('#categorycontent').text(jQuery('#categorycontent').text().slice(0,180) + '...');
			});
		}
	}
	
	
	if(!jQuery('#categorycontent').hasClass('slide-effect-done')){
		if(jQuery('#categorycontent').text().length>180){
			jQuery('#categorycontent').data('maxlength',jQuery('#categorycontent').height());
			jQuery('#categorycontent').data('htmldata',jQuery('#categorycontent').html())
			jQuery('#categorycontent').text(jQuery('#categorycontent').text().slice(0,180) + '...');
			jQuery('#categorycontent').height(26).css('overflow','hidden');
			jQuery('<span class="view-more-content-link" style="text-align:right;cursor:pointer;background:#f9f9f9">View More</span>').appendTo(			jQuery('#categorycontent').parent()).toggle(
				function(){
					jQuery(this).text('View Less');
					jQuery('#categorycontent').html(jQuery('#categorycontent').data('htmldata'));
					jQuery('#categorycontent').animate({height:jQuery('#categorycontent').data('maxlength')},500,'swing');
				},
				function(){
					
					jQuery(this).text('View More');
					jQuery('#categorycontent').animate({height:26},500,'swing',function(){
						jQuery('#categorycontent').text(jQuery('#categorycontent').text().slice(0,180) + '...');
					});
				}
			)
		}
		jQuery('#categorycontent').addClass('slide-effect-done');
	}
})
</script>