<?php
/**
 * Product:     Layered Navigation Pro for Magento 20/04/11
 * Package:     AdjustWare_Nav_2.1.1_0.1.4_8_74006
 * Purchase ID: QgBMpw5YKeeQ8cDxt9xj7DfR5rzlpaEBHoIuAZvOxv
 * Generated:   2011-06-08 07:09:19
 * File path:   app/design/frontend/default/default/template/adjnav/layer.phtml
 * Copyright:   (c) 2011 AITOC, Inc.
 */
?>
<?php
/*
 * Adding javascript include
 */
if ('ajax' != Mage::app()->getRequest()->getControllerName())
{
    if(Aitoc_Aitsys_Abstract_Service::get()->isMagentoVersion('>=1.4')):
    ?>
	<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/adjnav-14.js'); ?>"></script>
    <?php
    else:
    ?>
    <script type="text/javascript" src="<?php echo $this->getSkinUrl('js/adjnav-13.js');?>"></script>
    <?php
    endif;
}
?>

<?php
    if(Aitoc_Aitsys_Abstract_Service::get()->isMagentoVersion('>=1.4')):
?>

<?php if($this->canShowBlock()): $state = $this->getStateInfo()?>
    <div class="block block-layered-nav adj-nav">

    <!--<div class="block-title">
        <strong><span><?php echo $this->__('Shop by')?></span></strong>
    </div>-->
        <div class="block-content">
		<?php echo $this->getStateHtml() ?>
        <?php if($this->canShowOptions()): ?>

            <div class="narrow-by">
            <input type="hidden" id="adj-nav-url" value="<?php echo $this->htmlEscape($state[0])?>"/>
            <input type="hidden" id="adj-nav-params" value="<?php echo $this->htmlEscape($state[1])?>"/>
            <input type="hidden" id="adj-nav-ajax" value="<?php echo $this->htmlEscape($state[2])?>"/>
            <dl id="narrow-by-list">
			<?php $obj = new Mage_Catalog_Block_Navigation(); ?>
			<?php if($_relCats=$obj->getCurrentCategory()->getCategoryRelatedCategories()): ?>
			<dt class="adj-nav-dt even">Related Categories<div class="arrow"></div></dt>
			<dd id="adj-nav-filter-related_category" class="even">
				<ol><?php echo $_relCats; ?></ol>
			</dd>
			<?php endif; ?>

            <?php if ($state[1] AND $this->bNeedClearAll()): ?>
<div class="actions adj-clear-all"><a onclick="return false;" class="adj-nav-clearall" href="<?php echo $this->htmlEscape($this->getClearAllUrl())?>"><?php echo $this->__('Clear All') ?></a></div>
            <?php endif ?>

            <?php $_filters = $this->getFilters() ?>
                <?php foreach ($_filters as $_filter): ?>
                <?php if ($_filter->getItemsCount() && $_filter->getName() != "Category"): ?>
                <dt class="adj-nav-dt">
                    <?php if ($clearUrl = $_filter->getClearUrl()): ?>

                    <a onclick="return false;" id="<?php echo $_filter->getVar()?>-clear" <?php if(!$this->getIsRemoveLinks()): ?>href="<?php echo $this->htmlEscape($clearUrl)?>" <?php endif; ?> class="btn-remove adj-nav-clear" title="<?php echo $this->__('Remove This Item')?>"><?php echo $this->__('Remove This Item')?></a>
                    <?php endif ?>
                    <?php echo $this->__($_filter->getName()) ?>
					<div class="arrow"></div>
                </dt>
                <dd <?php echo $this->getHeightStyle()?> id="adj-nav-filter-<?php echo $_filter->getVar()?>"><?php echo $_filter->getHtml() ?></dd>
                <?php endif; ?>
                <?php endforeach; ?>
				
				
				
		<?php if($_relSearch=$obj->getCurrentCategory()->getCategoryRelSearch()): ?>		
		<dt class="adj-nav-dt even">Top Searches<div class="arrow"></div></dt>
		<dd id="adj-nav-filter-related_category" class="even">
			<ol><?php echo $_relSearch ?></ol>
		</dd>
		<?php endif; 
		if($_buyGuides=$obj->getCurrentCategory()->getCategoryBuyGuides()):
		?>
		<dt class="adj-nav-dt even">Buying Guides<div class="arrow"></div></dt>
		<dd id="adj-nav-filter-related_category" class="even">
			<ol><?php echo $_buyGuides; ?></ol>
		</dd>
		<?php endif; ?>
				
				
				
            </dl>
            <script type="text/javascript">
            decorateDataList('narrow-by-list');
            adj_nav_init();
            </script>
            </div>
            <?php endif; ?>
        </div>
        <div class="adj-nav-progress" style="display:none"></div>
    </div>
<?php endif; ?>

<script type="text/javascript">
if ('function' == typeof(sns_layer_add_attr))
{
    sns_layer_add_attr();
}
adj_nav_toolbar_init();
</script>

<?php
    else:
?>


<?php if($this->canShowBlock()): $state = $this->getStateInfo()?>
    <div class="box layered-nav adj-nav">
        <div class="head">
            <h3><?php echo $this->__('Shop by')?></h3>
        </div>
        <div class="border-creator">
        <?php if($this->canShowOptions()): ?>
            <div class="narrow-by">
            <input type="hidden" id="adj-nav-url" value="<?php echo $this->htmlEscape($state[0])?>"/>
            <input type="hidden" id="adj-nav-params" value="<?php echo $this->htmlEscape($state[1])?>"/>
            <input type="hidden" id="adj-nav-ajax" value="<?php echo $this->htmlEscape($state[2])?>"/>
            <dl id="narrow-by-list">
            <?php if ($state[1] AND $this->bNeedClearAll()): ?>
<div class="actions adj-clear-all"><a onclick="return false;" class="adj-nav-clearall" href="<?php echo $this->htmlEscape($this->getClearAllUrl())?>"><?php echo $this->__('Clear All') ?></a></div>
            <?php endif ?>
            <?php $_filters = $this->getFilters() ?>
                <?php foreach ($_filters as $_filter): ?>
                <?php if ($_filter->getItemsCount()): ?>
                <dt class="adj-nav-dt">
                    <?php if ($clearUrl = $_filter->getClearUrl()): ?>

                    <a onclick="return false;" id="<?php echo $_filter->getVar()?>-clear" <?php if(!$this->getIsRemoveLinks()): ?>href="<?php echo $this->htmlEscape($clearUrl)?>" <?php endif; ?> class="btn-remove adj-nav-clear" title="<?php echo $this->__('Remove This Item')?>"><?php echo $this->__('Remove This Item')?></a>
                    <?php endif ?>
                    <?php echo Mage::helper('catalog')->__($_filter->getName()) ?>
                </dt>
                <dd <?php echo $this->getHeightStyle()?> id="adj-nav-filter-<?php echo $_filter->getVar()?>"><?php echo $_filter->getHtml() ?></dd>
                <?php endif; ?>
                <?php endforeach; ?>
            </dl>
            <script type="text/javascript">
            decorateDataList('narrow-by-list');
            adj_nav_init();
            </script>
            </div>
            <?php endif; ?>
        </div>
        <div class="adj-nav-progress" style="display:none"></div>
    </div>
<?php endif; ?>

<?php
    endif;
?>
<script type="text/javascript">
jQuery(function(){
	
		/* Adjust heights of left or main column to equalize both */
		var cm_oheight = jQuery('.col-main').outerHeight();
		var cln_oheight = jQuery('.catleftnav').outerHeight();
		if(cln_oheight>cm_oheight){
			jQuery('.col-main').height(jQuery('.catleftnav').height() - 20 );
		}
		else{
			jQuery('.catleftnav').height(jQuery('.col-main').height() + 20 );
		}
	
	/* adjust handle images*/
	jQuery('.handle').css('padding-right','100%')
	jQuery('.handle:last').addClass('handle-right');
	
	/* adjust left navigation list on ajax refresh */
	jQuery('#narrow-by-list').find('dt').each(function(){
		if(jQuery.trim(jQuery(this).text())!='Price' && jQuery(this).next('dd').find('li').length == 1){
			jQuery(this).hide().next('dd').hide();
		}
		else{
			jQuery(this).show().next('dd').show();
		}
	})
	jQuery('#narrow-by-list').find('dd').each(function(){
		if(jQuery(this).find('li').length > 5){
			var item = jQuery(this);
			var haschecked = false;
			jQuery(this).find('li:gt(4)').each(function(){
				if(jQuery(this).find('.adj-nav-attribute-selected').length>0){
					haschecked = true;
				}
			})
			
			if(!haschecked){
				jQuery(this).find('li:gt(4)').hide();
				jQuery('<div class="more-filter-link">More...</div>').appendTo(jQuery(this)).toggle(function(){
					item.find('li:gt(4)').show(400);
					jQuery(this).text('Less...')
				},
				function(){
					item.find('li:gt(4)').hide(400);
					jQuery(this).text('More...')
				}
				)
			}
			else{
				jQuery('<div class="more-filter-link">Less...</div>').appendTo(jQuery(this)).toggle(function(){
					item.find('li:gt(4)').hide(400);
					jQuery(this).text('More...')
				},
				function(){
					item.find('li:gt(4)').show(400);
					jQuery(this).text('Less...')
				}
				)
			}
		}
	})	
})
</script>