
<?php 
error_reporting(1);
//$b_hp = Mage::getBlockSingleton('hprcv/hprcv');
$review= $this->getReviewsCollection()->getItems();//Mage::getBlockSingleton('review/product_view');//$this->getLayout()->createBlock('review/view');
//->getItems();
$reviewnum=Mage::getModel('testimonials/reviewdetail')->getCollection();
//var_dump(Mage::helper('catalog/image'));
//var_dump($review);//->getReviewsCollection());
//echo var_dump($this->getTestimonials());
/*foreach($this->getTestimonials() as $each){
var_dump($each->getData());
}*/
$review1=$this->getReviewscount();
$itemscount=$this->getItemscount();
$tempvar=ceil((count($review1)/$itemscount));
$page=$this->getRequest()->getParams();
if(!$page)$page['page']=1;
?>


<div class="reviewwrapper">
  <div class="pageheading">Angara Customers Share Their Jewelry Stories</div>
  <!--<p class="readingnote">I had to let you know right away that my wife absolutely loves her ring! She thinks the vivid, deep purple color of the amethyst with flashes of red is spectacular. She loves the simple, sophisticated way the setting mirrors the marquise cut and lifts the gemstone, displaying it from many angles and opening it up to the light. "It just looks great on my finger. </p>-->
  <div class="displayoption">
    <div class="pages">
      <ol>
        <li class="pre"><a class="previous" <?php if($page['page']>1){?>href="/testimonials/index/index/page/<?php echo $page['page']-1?>"<?php }?>>Previous</a></li>
        <li class="pageno">Page <?php echo $page['page']?> of <?php echo $tempvar;?></li>
        <li class="next"><a class="next" <?php if($page['page']<$tempvar){?>href="/testimonials/index/index/page/<?php echo $page['page']+1?>"<?php }?>>Next</a></li>
      </ol>
    </div>
    <!--<div class="sortby">
      <div class="relevance">
        <select  class="relevanceselect">
          <option value="" selected="selected">per page</option>
        </select>
      </div>
    </div>-->
  </div>
<?php
$testi=$this->getTestimonials();
foreach($review as $testimonial){ 
$pro=Mage::getModel('catalog/product');
$_product=$pro->load($testimonial->getEntityPkValue());
if($_product->_data['price']>70){
//var_dump($_product->_data['entity_id']);
//if($_product->getImage()!='no_selection')var_dump($_product);
//var_dump($_product);
//$product=$testimonial->->getEntityPkValue()
$_votes = $testimonial->getRatingVotes();
?>
  <div class="reviewholderlist"> <span class="reviewproholder"> <span class="reviewproimg"><a href="<?php echo Mage::helper('catalog/product')->getProductUrl($_product)?>"><img src="<?php echo Mage::helper('catalog/image')->init($_product, 'image')// $_product->getImage()//Mage::helper('catalog/image')->init($_product, 'image')?>" width="172" height="172"></a>
<?php
        /*$_img = '<img id="image" src="'.$this->helper('catalog/image')->init($_product, 'image').'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).' "width="172" height="172" />';
        echo $_helper->productAttribute($_product, $_img, 'image');*/
    ?>
</span> <span class="reviewproname"><a href="<?php echo Mage::helper('catalog/product')->getProductUrl($_product)?>"><?php echo $_product->getName()?></a></span> </span> <span  class="reviewnoteholder"> <span class="reviewtitleholder"> <span class="reviewnoteheading"><?php echo $this->htmlEscape($testimonial->getTitle()) ?></span> <span class="reviewprorating">
  
  <table class="ratings-table">
          <col width="1" />
          <col />
          <tbody>
            <?php foreach ($_votes as $_vote): ?>
            <tr>
              <!--<th  class="review-headings"><?php //echo $this->escapeHtml($_vote->getRatingCode()) ?></th>-->
              <td nowrap="nowrap" style="padding:4px 0 0 0"><div class="rating-box">
                  <div class="rating" style="width:<?php echo $_vote->getPercent() ?>%;"></div>
                </div>
              <td valign="middle" style="padding:5px 0 0 5px"><?php printf("%.1f",($_vote->getPercent()* .05))?></td>
              </td>
            </tr>
            <?php endforeach; ?>
          </tbody>
        </table>
  
  </span> </span> <span class="reviewcontentbox readingnote"><?php echo nl2br($this->htmlEscape($testimonial->getDetail())) ?><img src="/skin/frontend/angara/default/images/speakicon.png" width="28" height="15"  class="speakicon"/> </span> <span class="reviewerdetails">- <?php echo $this->htmlEscape($testimonial->getNickname()) ?><br>
  <?php $_coreFormat = Mage_Core_Model_Locale::FORMAT_TYPE_FULL;
  $value = $this->__('%s', $this->formatDate($testimonial->getCreatedAt()), 'medium');?>
    <small class="reviewdate"><?php echo Mage::helper('core')->formatDate($value, $_coreFormat); /*$this->__('%s', $this->formatDate($testimonial->getCreatedAt()), 'medium');*/ ?><!--15 Sep, 2012--></small> </span> </span>
    <div style="clear:both;"></div>
    </div>
	
	<?php } 
	}
	
	?> 
     <div class="displayoption">
    <div class="pages">
      <ol>
        <li class="pre"><a class="previous" <?php if($page['page']>1){?>href="/testimonials/index/index/page/<?php echo $page['page']-1?>"<?php }?>>Previous</a></li>
        <li class="pageno">Page <?php echo $page['page']?> of <?php echo $tempvar;?></li>
        <li class="next"><a class="next" <?php if($page['page']<$tempvar){?>href="/testimonials/index/index/page/<?php echo $page['page']+1?>"<?php }?>>Next</a></li>
      </ol>
    </div>
  </div>
	 
</div>
