<title>
<?php 
if(Mage::app()->getRequest()->getParam('showdeal') != 'true'){
	echo $this->getTitle();
}
else{
	echo 'Valentine Jewelry Gifts';
}?>
</title>
<meta property="fb:app_id" content=118485508205347 />
<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />
<meta content="yes" name="apple-mobile-web-app-capable" />
<meta name="SKYPE_TOOLBAR" content="SKYPE_TOOLBAR_PARSER_COMPATIBLE" />
<meta content='True' name='HandheldFriendly' />
<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=no" />
<meta charset="UTF-8"/>
<?php
$product = Mage::registry('current_product');
if($product){
	$_coreHelper = $this->helper('core');
	$socialDescription	=	htmlspecialchars($product->getDescription()); 
	if(!$socialDescription){
		$socialDescription	=	htmlspecialchars($product->getMetaTitle()); 
	}	
	if(!$socialDescription){
		$socialDescription	=	htmlspecialchars($product->getShortDescription()); 
	}
	?>
<meta property="og:site_name" content="Angara" />
<meta property="og:title" content="<?php echo $product->getShortDescription();//$this->getTitle(); ?>" />
<meta property="og:description" content="<?php echo $socialDescription; ?>" />
<meta property="og:url" content="<?php echo $product->getProductUrl();?>" />
<meta property="og:type" content="product" />
<meta property="og:image" content="<?php echo 'http://www.angara.com/media/catalog/product'.$product->getImage();?>" />
<meta property="og:price:amount" content="<?php echo $product->getPrice(); ?>" />
<meta property="og:price:standard_amount" content="<?php echo $product->getMsrp(); ?>" />
<meta property="og:price:currency" content="<?php echo Mage::app()->getStore()->getCurrentCurrencyCode(); ?>" />
<meta property="og:availability" content="instock" />
<meta name="twitter:card" content="product">
<meta name="twitter:site" content="@Angara">
<meta name="twitter:title" content="<?php echo $product->getShortDescription();//$this->getTitle(); ?>">
<meta name="twitter:description" content="<?php echo $socialDescription; ?>">
<meta name="twitter:creator" content="@Angara">
<meta name="twitter:url" content="<?php echo $product->getProductUrl();?>" />
<meta name="twitter:image" content="<?php echo 'http://www.angara.com/media/catalog/product'.$product->getImage();?>">
<meta name="twitter:image:width" content="200">
<meta name="twitter:data1" content="<?php echo $_coreHelper->currency($this->htmlEscape($product->getPrice()),true,false);?>">
<meta name="twitter:label1" content="Price">
<meta name="twitter:data2" content="<?php echo $product->getSku();?>">
<meta name="twitter:label2" content="SKU"> 
<?php
} ?>
<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
<link rel="icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<!--[if lt IE 7]>
<script type="text/javascript">
//<![CDATA[
    var BLANK_URL = '<?php echo $this->helper('core/js')->getJsUrl('blank.html') ?>';
    var BLANK_IMG = '<?php echo $this->helper('core/js')->getJsUrl('spacer.gif') ?>';
//]]>
</script>
<![endif]-->
<?php	header("Vary: User-Agent");?>
<?php echo $this->getCssJsHtml() ?><?php echo $this->getChildHtml() ?><?php echo $this->helper('core/js')->getTranslatorScript() ?><?php echo $this->getIncludes() ?>
<!--[if lt IE 9]>
  <script type='text/javascript' src="/skin/frontend/ress/default/js/ie8/html5.js"></script>
  <script type='text/javascript' src="/skin/frontend/ress/default/js/ie8/respond.js"></script>
<![endif]-->
<link rel="dns-prefetch" href="http://cdn.angara.com">
<link rel="dns-prefetch" href="http://payments.amazon.com">
<link rel="dns-prefetch" href="http://facebook.com">
<link rel="dns-prefetch" href="http://angara.tt.omtrdc.net">
<link rel="dns-prefetch" href="http://images-na.ssl-images-amazon.com">
<link rel="dns-prefetch" href="http://nsg.symantec.com">
<link rel="dns-prefetch" href="http://server.iad.liveperson.net">
<link rel="dns-prefetch" href="http://seal-sanjose.bbb.org">
<link rel="dns-prefetch" href="http://google-analytics.com">
<link rel="dns-prefetch" href="http://seal.websecurity.norton.com">
<link rel="dns-prefetch" href="http://googleads.g.doubleclick.net">
<link rel="dns-prefetch" href="http://googleadservices.com">
<link rel="dns-prefetch" href="http://medals.bizrate.com">
<link rel="dns-prefetch" href="http://google.com">
<link rel="dns-prefetch" href="http://d2lo2tipcl3aii.cloudfront.net">
<link rel="dns-prefetch" href="http://metrics.angara.com">
<link rel="dns-prefetch" href="http://seal.verisign.com">
<link rel="dns-prefetch" href="http://s-static.ak.facebook.com">
<link rel="dns-prefetch" href="http://connect.facebook.net">
<link rel="dns-prefetch" href="http://static.ak.facebook.com">

