<div class="container-fluid showcase-bg-dark max-margin-top high-padding-top high-padding-bottom showcase-border-top showcase-border-bottom">
    <div class="container"> 
		<div class="row">
            <div class="col-md-12 text-center">
                <div class="center-block">	
                    <ul class="list-inline no-margin-bottom key-helights">
                        <li class="valign-middle fontsize-type1"><span class="text-orange">Why Customers Shop at Angara:</span></li>
                        
                        <li class="no-padding valign-middle fontsize-type1"><div class="clickable" data-html="true" data-placement="top" data-trigger="hover" data-toggle="tooltip" title="Free Shipping within the USA. We ship FREE to 64 countries on all International orders over <?php echo Mage::helper('function')->getFreeInternationalShippingPrice();?>. International orders below <?php echo Mage::helper('function')->getFreeInternationalShippingPrice();?> are charged &#36;39.99 each."><span class="text-blue">Free</span> Shipping Worldwide</div></li>                            
                        <li class="no-padding fontsize-type1"><i class="fa fa-circle fa-fw padding-type-2 valign-middle" style="font-size:5px;"></i></li>
                        
                        <li class="no-padding valign-middle fontsize-type1"><div class="clickable" data-html="true" data-placement="top" data-trigger="hover" data-toggle="tooltip" title="If you don't like the product, simply send it back to us within <?php echo Mage::helper('function')->freeReturnDays();?> days and get a 100&#37; refund. We will even email you a FREE return shipping label (for domestic orders)."><span class="text-green"><?php echo Mage::helper('function')->freeReturnDays();?>-Day</span> Returns</div></li>
                        
                        <li class="no-padding fontsize-type1"><i class="fa fa-circle fa-fw padding-type-2 valign-middle" style="font-size:5px;"></i></li>
                        
                        <li class="no-padding valign-middle fontsize-type1"><div class="clickable" data-html="true" data-placement="top" data-trigger="hover" data-toggle="tooltip" title="We will refund up to 110&#37; of the purchase price, if any accredited jewelry appraiser values your piece for less than 125&#37; of the purchase price."><span class="text-red">110%</span> Refund Policy</div></li>
                        
                        <li class="no-padding fontsize-type1"><i class="fa fa-circle fa-fw padding-type-2 valign-middle" style="font-size:5px;"></i></li>
                        
                        <li class="no-padding valign-middle fontsize-type1"><div class="clickable" data-html="true" data-placement="top" data-trigger="hover" data-toggle="tooltip" title="With our 0&#37; Interest Financing option, buy the jewelry of your choice in 2 or 3 equal monthly installments."><span class="text-sky">0%</span> Interest Financing</div></li>
                        
                        <li class="no-padding hidden-sm fontsize-type1"><i class="fa fa-circle fa-fw padding-type-2 valign-middle" style="font-size:5px;"></i></li>
                        <li class="hidden-sm no-padding valign-middle fontsize-type1"><div class="clickable" data-html="true" data-placement="top" data-trigger="hover" data-toggle="tooltip" title="We are a family owned gemstone business spanning 3 generations. We will work with you to find or create the perfect jewelry piece of your dreams."><span class="text-purpal">Trusted</span> Gemstone Source</div></li>
                    </ul>						
                </div>
            </div>
        </div>
	</div>    
</div> 