<?php 
$coupon = $this->getCoupon(); 
$productId = $this->getRequest()->getParam('productId');
$product = Mage::getModel('catalog/product')->load($productId);
$additionalCost = $this->getRequest()->getParam('additionalCost');
$_coreHelper = Mage::helper('core'); 
$freeGifts = $this->getFreeGifts(); ?>

<div class="coupon-block">
    <div class="heading">
        <div class="c-block radio-btn"><span><?php echo $this->getCode();?></span></div>
        <div class="c-block coupon-detail">
            <div class="discount"><?php echo $coupon->getShortDescription();?></div>
        </div>
        <div class="c-block toggle-icon nowrap">
			<span><i class="fa fa-plus fa-fw"></i> View Detail</span>
		</div>
    </div>
    <div class="detail">
    <?php //S:Free Gift ?>
		<span class="arrow"></span>
		<div class="col-md-12 col-sm-12">
			<?php if(!$product->getIsBuildYourOwn()){ ?>
			<div class="<?php if(!empty($freeGifts)){ ?>col-md-4 col-sm-4<?php }else{ ?>col-md-6 col-sm-6<?php } ?> amt tAc" style="<?php if(empty($freeGifts)){ ?> border-right:1px solid #e1e1e1; <?php } ?>">
				Get this Item for <span><?php echo $_coreHelper->currency($this->getAfterDiscountProductPrice($productId, $additionalCost),true,false);?></span>
			</div>
            <?php 
			}
			if(!empty($freeGifts)):?>
			<div class="col-md-4 col-sm-4 fg">
				<div class="free-gift tAc">
					<div class="title"><i class="fa fa-gift" style="color: #d83d29;" ></i> Free Gift<?php if(count($freeGifts) > 1):?>(s)<?php endif;?></div>
					<?php 
					foreach($freeGifts as $freeGift):?>
						<div class="img"><img class="img-responsive" src="<?php echo $this->helper('catalog/image')->init($freeGift, 'image')->resize(49);?>" alt="<?php echo $freeGift->getShortDescription();?> - Angara.com" title="<?php echo $freeGift->getShortDescription();?>" /></div>
					<?php 
					endforeach;?>    
				</div>
			</div>
            <?php
            endif;?>
			<div class="<?php if(!empty($freeGifts)){ ?>col-md-4 col-sm-4<?php }else{ ?>col-md-6 col-sm-6<?php } ?> code tAc">Use Discount Code <br><span><?php echo $this->getCode();?></span></div>
		</div>
		<div class="clearfix"></div>
		<div class="col-md-12 col-sm-12 tAc tnc">
			<?php echo $coupon->getLongDescription();?>
		</div>
    </div>
    <?php //E:Free Gift ?>		
</div>