<?php
$_item = $this->getItem();
$isVisibleProduct = $_item->getProduct()->isVisibleInSiteVisibility();
$_recInfo = $this->getRecurringInfo();

$_options = $this->getOptionList();

$product = Mage::getModel('catalog/product');
$_product = $product->load($_item->getProductId());
$mothersflag = 0;
$categoryIds = $_product->getCategoryIds();
foreach($categoryIds as $categoryId) {
	$category = Mage::getModel('catalog/category')->load($categoryId);
	$url = $category->getUrlPath();
	if($url == "mothers-jewelry.html") {
		$mothersflag = 1;
	}
}

$imgurl = '';
if($mothersflag == 1) {
	$b_hp = Mage::getBlockSingleton('hprcv/hprcv');
	$b_hp->getimageforcartproduct($_item,$this->getOptionList());
	$imgurl="/media/catalog/product/images/mothers/cartproducts/" . $_item->getId() . "_thumb.png";
}
// HPRAHI CODES CUSTOMISATION END
?>
<div class="showcase-border-bottom-1px cart-item-block full-width fl p10 <?php /*if($_item->getCalculationPrice() == 0){ echo 'free-gifts-block'; }*/ ?>">
	<div class="row no-gutters">
        <div class="col-sm-2 col-xs-3 cart-product-image pT10 pB10 fl" style="width:16%">
		<?php 
        if($mothersflag==1){
            $set_prod_arr = array('SG0107S','SG0108AM','SG0111P','SG0112PAMAQ','SG0113R','SG0109CT','SG0110PT');
            if(!in_array($_item->getProduct()->getData('sku'), $set_prod_arr)) {
            	// skip mother type image for set products ?>
            	<img src="<?php echo $imgurl;?>" width="100" height="100" alt="<?php echo $this->htmlEscape($_product->getProductName());?>"  class="img-responsive"/>
            <?php	
            } 
			else {?>
            	<img src="<?php echo $this->getProductThumbnail()->resize(100);?>" width="100" height="100" alt="<?php echo $this->htmlEscape($this->getProductName());?>" class="img-responsive" />
            <?php
            }
		}
		elseif($product->getSku() == 'ANGCBYO007'){
			$diamondShape = '';
			foreach($_options as $_option){
				if($_option['label'] == 'SecureInformation'){
					$diamondInfo = unserialize($_option['value']);
					$diamondShape = $diamondInfo['diamond']['shape'];
					$stockNumber = strrev('ANG'.$diamondInfo['diamond']['diamond_id']);
				}
			}
			?>
			<img src="/skin/frontend/ress/default/images/buildyourown/diamond/<?php echo $diamondShape; ?>_top_diamond.jpg" width="100" height="100" alt="<?php echo $this->htmlEscape($this->getProductName());?>" class="img-responsive" />
        <?php 
		}
		else{?>
            <img src="<?php echo $this->getProductThumbnail()->resize(100);?>" width="100" height="100" alt="<?php echo $this->htmlEscape($this->getProductName());?>" class="img-responsive" />
        <?php 
		}?>
        </div>
        <div class="col-sm-10 col-xs-9 cart-product-details pL10 fl" style="width:84%">
            <div class="detail-part">
            	<div class="showcase-border-thin-white padding-type-10">
                	<h2 class="product-name" style="padding-bottom:0px;">
                    <?php 
					if((strtolower(substr($_item->getProduct()->getData('sku'), 0, 2)) == 'by')){
						$additionalTextByo = '<span class="text-light fontsize-type0">(Setting Only)</span>';
					}
					else{
						$additionalTextByo = '';
					}
                    if($this->hasProductUrl()):
                        if($_item->getCalculationPrice() > 0){?>
                            <?php echo $_item->getName();//echo $_product->getShortDescription();?>
                        <?php 
                        }
                        else{
                            echo $this->htmlEscape($this->getProductName());
                        }
                    else:
                        echo $this->htmlEscape($this->getProductName());
                    endif; 
					
					echo $additionalTextByo;?>
               		</h2>
                    
                    <div class="cart-price pB10">
						<?php 
                        if($_recInfo):
                            echo $this->helper('core')->currency($_item->getProduct()->getFinalPrice() * $this->getQty());
                        elseif(Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()):
                            echo $this->helper('checkout')->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition());
                        else:
                            if($_item->getCalculationPrice() > 0){	
                                echo $this->helper('checkout')->formatPrice($_item->getRowTotal());
                            }else{
                                echo '<span class="text-green">Free</span> with code '.Mage::getSingleton('checkout/session')->getQuote()->getData('coupon_code');
                            }
                        endif; ?>
                    </div>
                    
                    <?php	//	S:VA	Dont show sku of free products
					if(strtolower( substr($_item->getProduct()->getData('sku'), 0, 2)) != 'fr'){	
					?>
                        <div class="cart-product-sku">
                            <span>
                            <?php 
                            if($_item->getProduct()->getData('sku') == 'ANGCBYO007'){?>						
                                <small>Stock Number: <span class="text-light"><?php echo $stockNumber;?></span></small>
                            <?php
                            }
                            else{?>						
                                <small>SKU: <span class="text-light"><?php echo $_item->getProduct()->getData('sku');?></span></small>
                            <?php 
                            }?>
                            </span>
                            <small class="visible-xs">Qty: <span class="text-light"><?php echo $this->getQty();?></span></small>
                        </div>
                <?php	}
				if($_options):?>
                	<div style="line-height:16px; margin-top:2px;">
                    <?php 
					foreach($_options as $_option) :
						if($_option['label'] != 'ItemType' && $_option['label'] != 'SecureInformation'):
							$_formatedOptionValue = $this->getFormatedOptionValue($_option);
							if($this->htmlEscape($_option['label']) != 'Center Diamond Size'):
								if($this->htmlEscape($_option['label']) == 'Accent Stone 1 Grade'):?>
									<div class="pull-left min-padding-right"><small style="padding-right:3px;"><?php if($this->htmlEscape($_option['label'])=='Free Jewelry Appraisal'){echo 'Jewelry Appraisal';}else{echo $this->htmlEscape("Diamond 2 Grade");}?>:</small></div>
								<?php 
								else:?>
									<div class="pull-left min-padding-right"><small style="padding-right:3px;"><?php if($this->htmlEscape($_option['label'])=='Free Jewelry Appraisal'){echo 'Jewelry Appraisal';}else{echo Mage::helper('function')->getStaticValues($this->htmlEscape($_option['label']));}?>:</small></div>
								<?php
								endif;?>
								<div class="pull-left text-light" style="word-break: break-all;">
									<small>
									<?php 
									if(isset($_formatedOptionValue['full_view'])):
										echo $_formatedOptionValue['full_view'];
									else:
										//	S:VA
										echo Mage::helper('function')->getStaticValues($_formatedOptionValue['value'], $_option['code'], $_item->getProduct()->getSku());
									endif;
									
									if(($this->htmlEscape($_option['label'])=='Engraving' || $this->htmlEscape($_option['label'])=='Free Jewelry Appraisal') && ($this->htmlEscape($_option['price'])=='0.00' || $this->htmlEscape($_option['price'])=='0' || $this->htmlEscape($_option['price'])=='0.0'))
										echo '<span class="fontcolor-type1"> (Free)</span>';?>
									</small>
								</div>
								<div class="clearfix"></div>
                    		<?php 	
							endif;
						endif;
					endforeach;?>
               	 	</div>
                <?php 
				endif;
				
				if($_recInfo):
					if(Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()):
						$am_hp = ($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition());
					else:
						$am_hp =  ($_item->getCalculationPrice());
					endif;
                	
					$ItemInstallmentAmt = Mage::getBlockSingleton('checkout/cart')->getCartItemInstallmentWithDiscAmount($_item->getCalculationPrice(),$_item->getNoOfInstallment(),$_recInfo['qty'],$_item->getDiscountAmount());
                	$am_hp = $ItemInstallmentAmt;?>
                    <div class="space max-padding-top">
                        <div class="pull-left min-padding-right"><small style="padding-right:3px;">You Selected:</small></div>
                        <div class="pull-left text-light"><small style="padding-right:3px;"><?php echo $_item->getNoOfInstallment();?> payments of <?php echo $this->helper('checkout')->formatPrice($ItemInstallmentAmt);?></small></div>
                        <div class="clearfix"></div>
                    </div>
                    <div id="pay-today-text" class="fontcolor-type1">
                        <div class="pull-left min-padding-right"><small class="text-red" style="padding-right:3px;">Pay Now:</small></div>
                        <div class="pull-left"><small><?php echo $this->helper('checkout')->formatPrice($am_hp);?>
                            <span class="text-light" style="font-size:10px">
                                (Order processes today for shipment)
                            </span></small>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                	<div>
                    <?php 
					if($_item->getNoOfInstallment() == 3):?>
                    	<div class="pull-left min-padding-right"><small style="padding-right:3px;">Amount to be charged on <?php echo date("m/d/Y",strtotime("+1 months"));?>:</small></div>
                    	<div class="pull-left text-light"><small><?php echo $this->helper('checkout')->formatPrice($ItemInstallmentAmt);?></small></div>
                    	<div class="clearfix"></div>
                    	<div class="pull-left min-padding-right"><small style="padding-right:3px;">Amount to be charged on <?php echo date("m/d/Y",strtotime("+2 months"));?>:</small></div>
                    	<div class="pull-left text-light"><small><?php echo $this->helper('checkout')->formatPrice($ItemInstallmentAmt);?></small></div>
                    	<div class="clearfix"></div>
                    <?php else: ?>
                        <div class="pull-left min-padding-right"><small style="padding-right:3px;">Amount to be charged on <?php echo date("m/d/Y",strtotime("+1 months"));?>:</small></div>
                        <div class="pull-left text-light"><small><?php echo $this->helper('checkout')->formatPrice($ItemInstallmentAmt);?></small></div>
                        <div class="clearfix"></div>
                    <?php 
					endif; ?>
                </div>
                <?php 
				endif;
				
				if($messages = $this->getMessages()):
					foreach($messages as $message):?>
                		<p class="item-msg <?php echo $message['type'] ?>">* <?php echo $message['text'];?></p>
                	<?php 
					endforeach;
				endif;
				
				if($addtInfoBlock = $this->getProductAdditionalInformationBlock()):
					echo $addtInfoBlock->setItem($_item)->toHtml();
				endif;?>
            	</div>
            </div>
        </div>
    </div>
</div>
<?php
//$currentCurrencyCode =  Mage::app()->getStore()->getCurrentCurrencyCode();
//$baseCurrencyCode = Mage::app()->getStore()->getBaseCurrencyCode();?>