<?php
/**
 * Product:     Layered Navigation Pro for Magento 20/04/11
 * Package:     AdjustWare_Nav_2.1.1_0.1.4_8_74006
 * Purchase ID: QgBMpw5YKeeQ8cDxt9xj7DfR5rzlpaEBHoIuAZvOxv
 * Generated:   2011-06-08 07:09:19
 * File path:   app/design/frontend/default/default/template/adjnav/filter_category_search.phtml
 * Copyright:   (c) 2011 AITOC, Inc.
 */
?>
<ol>
<?php
foreach ($this->getItems() as $_item):?>
    <li>
        <?php if ($_item->getIsCurrent()): ?>
            <span class="adj-nav-category-current"><?php echo $_item->getLabel() ?></span>
        <?php  else: ?>        
		<?php
		if (Mage::getStoreConfig('design/adjnav/reload_categories'))
		{
		?>
            <a id="cat-<?php echo $_item->getValue()?>" href="?dir=desc&p=clear&q=<?php echo isset($_GET['q']) ? $this->htmlEscape($_GET['q']) : ''?>&cat=<?php echo $_item->getValue()?>" class="adj-nav-pad<?php echo $_item->getLevel()?>"><?php echo $_item->getLabel() ?></a>			
		<?php } else { ?>
			<a onclick="return false;" id="cat-<?php echo $_item->getValue()?>" href="<?php echo $this->htmlEscape($_item->getUri()) ?>" class="adj-nav-category adj-nav-pad<?php echo $_item->getLevel()?>"><?php echo $_item->getLabel() ?></a>		
		<?php
		}
		if($_item->getCount()): ?>  (<?php echo $_item->getCount() ?>) <?php endif ?>
        <?php endif ?>
    </li>
<?php endforeach ?>
</ol>