<?php
/**
 * Product:     Layered Navigation Pro for Magento 20/04/11
 * Package:     AdjustWare_Nav_2.1.1_0.1.4_8_74006
 * Purchase ID: QgBMpw5YKeeQ8cDxt9xj7DfR5rzlpaEBHoIuAZvOxv
 * Generated:   2011-06-08 07:09:19
 * File path:   app/design/frontend/default/default/template/adjnav/layer_pager.phtml
 * Copyright:   (c) 2011 AITOC, Inc.
 */
?>
<?php
/*
 * Adding javascript include
 */
if ('ajax' != Mage::app()->getRequest()->getControllerName())
{
    if(Aitoc_Aitsys_Abstract_Service::get()->isMagentoVersion('>=1.4')):
    else:
    ?>
    <script>adj_nav_toolbar_init()</script>
    <?php
    endif;
}
?>