<style>
#shipping-method, .quick-access li.last{ display:none }
#main-menu-xs-toggler, #main-menu-search-toggler{ display:none }
#bbblink{ margin:0 auto!important;}
.linear-gradient-effect{
background: -moz-linear-gradient(left, #f5f5f5 0%, #ffffff 17%, #ffffff 47%, #ffffff 83%, #f5f5f5 100%); /* FF3.6+ */
background: -webkit-gradient(left top, right top, color-stop(0%, #f5f5f5), color-stop(17%, #ffffff), color-stop(47%, #ffffff), color-stop(83%, #ffffff), color-stop(100%, #f5f5f5));/* Chrome,Safari4+ */
background: -webkit-linear-gradient(left, #f5f5f5 0%, #ffffff 17%, #ffffff 47%, #ffffff 83%, #f5f5f5 100%); /* Chrome10+,Safari5.1+ */
background: -o-linear-gradient(left, #f5f5f5 0%, #ffffff 17%, #ffffff 47%, #ffffff 83%, #f5f5f5 100%); /* Opera 11.10+ */
background: -ms-linear-gradient(left, #f5f5f5 0%, #ffffff 17%, #ffffff 47%, #ffffff 83%, #f5f5f5 100%); /* IE 10+ */
background: linear-gradient(to right, #f5f5f5 0%, #ffffff 17%, #ffffff 47%, #ffffff 83%, #f5f5f5 100%);/* W3C */
}
.showcase-box-shadow{ z-index:1;}
.checkout-footer-top-border{border-top: 2px solid #dddddd;}
.login_with_facebook_btn
{
	width:136px;
	height:28px;
	background:url(/skin/frontend/ress/default/images/login-with-facebook.jpg) no-repeat;
	filter: none!important;
}
.login_with_facebook_btn:hover, .login_with_facebook_btn:focus, .login_with_facebook_btn.active
{
	background:url(/skin/frontend/ress/default/images/login-with-facebook.jpg) no-repeat;
	filter: none!important;
	
}
.valentines_heart {
	display:none !important;
}
</style>
<div class="container showcase-bg-white">
	<div class="fontsize-type2">
		<div class="page-title">
			<h1 class='h1_opc'><?php echo Mage::getStoreConfig('onepagecheckout/general/title') ?></h1>
			<?php if (!Mage::getSingleton('customer/session')->isLoggedIn()): ?>
			<div class="text-left showcase-bg-gradient-one showcase-border-thin max-margin-bottom">
				<div class="onepagecheckout_loginarea no-margin pull-left padding-type-10 showcase-bg-black hidden-xs"><a href="javascript:void(0)" class="onepagecheckout_loginlink text-on-dark " onclick='open_login();'>Already registered? Click here to login</a></div>                
				<div class="onepagecheckout_loginarea no-margin padding-type-10 showcase-bg-black  visible-xs"><a href="javascript:void(0)" class="onepagecheckout_loginlink text-on-dark " onclick='open_login();'>Already registered? Click here to login</a></div>
				<div class="pull-left hidden-xs">
					<div class="pull-left special-tip-right"></div>
					<div class="pull-left padding-type-10">
						<span class="img-circle icon-16 showcase-bg-darker text-on-dark subform-index-indicator pull-left low-margin-right">
							1
						</span>
						<span id="onepage-header-step-shopping" class="visible-md visible-sm pull-left">Shopping Cart</span></div>
					<div class="pull-left padding-type-10 max-margin-left max-padding-left">
						<span id="onepage-header-step-billing" class="img-circle icon-16 showcase-bg-green text-on-dark subform-index-indicator pull-left low-margin-right">
							2
						</span>
						<span class="visible-md visible-sm pull-left">Billing & Shipping</span></div>
					
					<div class="pull-left padding-type-10 max-margin-left max-padding-left">
						<span class="img-circle icon-16 showcase-bg-darker text-on-dark subform-index-indicator pull-left low-margin-right">
							3
						</span>
						<span class="visible-md visible-sm pull-left">Order Receipt</span></div>
				</div>
				<div class="clearfix"></div>
			</div>
            <script>
			jQuery(function(){	
				if(jQuery('#onepage-header-step-billing').hasClass('showcase-bg-green')){
					jQuery('#onepage-header-step-shopping').html('<a href="<?php echo $this->getUrl('checkout/cart/'); ?>">Shopping Cart</a>');
				}
			});
			</script>
			<div id="onepagecheckout_login-container" class="hidden">
<div class="row no-guters">
<div class="col-cs-12"><i id="onepagecheckout_login-close" class="fa fa-times padding-type-10 low-padding-bottom clickable fontsize-type7 pull-right low-margin-right"></i></div>
</div>
<div class="row max-padding-bottom">
	<div class="col-sm-4 max-margin-bottom">
		<div class="max-margin-left mmr-login">
		<?php
			echo $this->getChildHtml('customer.login');
			echo $this->getChildHtml('customer.forgot');
		?>
		</div>
		</div>
		<div class="col-sm-1 text-center max-margin-bottom relative-placeholder">
		<div class="visible-xs" >
		<div class="high-padding-top"></div>
		<div style="position: absolute; border-top: 1px solid rgb(219, 219, 219); width: 1px; left: 0px; right: 0px; top:13px; bottom:0; margin: auto; width:90%; ">
		<div style="border:1px solid #dbdbdb; display:inline-block; padding:10px; background-color:#fff;-moz-border-radius:30px; -webkit-border-radius: 30px; border-radius: 30px; font-weight:bold; position:absolute; width:39px; height:39px; margin:auto; left:0; right:0; top:-21px; ">OR</div></div>
		<div class="high-padding-bottom"></div>
		</div>
		<div class="hidden-xs" >
		<div style="position: absolute; border-right: 1px solid rgb(219, 219, 219); width: 1px; left: 0px; right: 0px; margin: auto; height: 230px;">
		<div style="border:1px solid #dbdbdb; display:inline-block; padding:10px; background-color:#fff;-moz-border-radius:30px; -webkit-border-radius: 30px; border-radius: 30px; font-weight:bold; position:absolute; width:39px; height:39px; margin:auto; top:0; bottom:0; right:-21px; ">OR</div></div>
		</div>
		</div>
		
	   <div class="col-sm-3 max-margin-bottom">
	   <div class="mmr-fb">
	   <div class="block-sub-heading high-margin-bottom ">
		<span>Facebook Users</span>
		</div>                   
		<p><?php echo $this->__('Use your Facebook account to login within our store. You\'re just one click away.') ?></p>
		<div class="max-padding-top">
		 <button rel="facebook-connect" type="button" title="<?php echo $this->__('Connect with Facebook') ?>" class="button login_with_facebook_btn"></button>
		<div class="clearfix"></div>
		 </div>
		 </div>
	   </div>
				
	<div class="col-sm-4">
		 <div class="key-font-size mpr-keys">
			<div class="high-padding-bottom"><i class="fa fa-check fa-fw text-green"></i> Faster Checkout</div>
			<div class="high-padding-bottom"><i class="fa fa-check fa-fw text-green"></i> Personalized Shopping Experience</div>
			<div class="high-padding-bottom"><i class="fa fa-check fa-fw text-green"></i> Manage & Track Your Orders</div>
			<div class="high-padding-bottom"><i class="fa fa-check fa-fw text-green"></i> Manage Wish List</div>
		</div>				
	 </div>	
	</div>
</div>
			<?php endif; ?>
		</div>
		<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
		<?php
$seq_http	= (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS']==='on');
$browser  = $_SERVER ['HTTP_USER_AGENT'];
$is_persistent = Mage::helper('onepagecheckout')->isPersistentMember();
?>
		<script type="text/javascript">
	var http_type	= '<?php if($seq_http){echo 'https';}else{echo 'http';}?>';
</script> 
		<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/onepagecheckout.js') ?>"></script> 
		<script type="text/javascript">countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?></script>
		<form action="javascript:void(0)" method="POST" id="onepagecheckout_orderform" autocomplete="on">
			<div class="row">
				<div class="col-sm-4">
					<div class="padding-type-10 padding-type-8 showcase-border-thick-green has-subform" data-subform-index="0">
					<?php echo $this->getChildHtml('billing.address') ?> 
					<?php echo $this->getChildHtml('shipping.address') ?>
                    <div id="onepage-checkout-shipping-method-additional-load"> <?php echo $this->getChildHtml('additional') ?> </div>
                    </div>
                    
				</div>
				<div class="col-sm-4">
					<div class="padding-type-10 has-subform" data-subform-index="1"><?php echo $this->getChildHtml('shipping.method') ?> <?php echo $this->getChildHtml('payment.method') ?>
						<div id="checkout-coupon-discount-load"> <?php echo $this->getChildHtml('coupon') ?> </div>
						<?php if (Mage::getStoreConfig('onepagecheckout/general/comment')) : ?>
						<div class="op_block_title"> <?php echo $this->helper('sales')->__('Comment') ?> </div>
						<div class="form_fields">
							<div class="full">
								<div class="data_area" id='comment-block'>
									<textarea name="order-comment" id="order-comment"><?php echo trim(Mage::getSingleton('customer/session')->getOrderCustomerComment()) ?></textarea>
								</div>
							</div>
						</div>
						<?php endif; ?>
						<?php if (Mage::helper('onepagecheckout')->isSubscribeNewAllowed()) : ?>
						<p class="newsletter">
							<input type="checkbox" id="newsletter-signup" name="newsletter" value="1" title="<?php echo Mage::helper('newsletter')->__('Sign up for our newsletter') ?>" class="checkbox" />
							<label for="newsletter-signup"> <?php echo Mage::helper('newsletter')->__('Sign up for our newsletter') ?> </label>
						</p>
						<?php endif; ?>		
                        <div id="checkout-review-submit">    
        <?php echo $this->getChildHtml('agreements') ?>
        <div class="buttons-set" id="review-buttons-container">
        <button type="submit" title="<?php echo $this->__('Complete Order') ?>" class="btn btn-primary btn-block btn-place-order fontsize-type5" onclick="checkout.save(); return false;"><?php echo $this->__('Complete Order') ?></button>
            <span id="review-please-wait" style="display:none;float:right;">
                <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Submitting order information...') ?>" title="<?php echo $this->__('Submitting order information...') ?>" class="v-middle" /> <?php echo $this->__('Submitting order information...') ?>
            </span>
        </div>
    </div>				
					</div>
				</div>
				<div class="col-sm-4">
					<div class="showcase-border-thin max-margin-bottom linear-gradient-effect" data-subform-index="2" style="position:relative"><?php echo $this->getChildHtml('review') ?></div>
                  	  <div class="padding-type-5 showcase-bg-light">
       <div class="padding-type-5 showcase-bg-white">
        <h1 class="min-margin-top low-margin-bottom">Need Help?</h1>
        <div class="row no-gutters text-center">
         <div class="col-xs-4 col-sm-6 col-md-4">
         <div class="padding-type-2">
         <div class="padding-type-5 showcase-bg-dark">
          <i class="fa fa-2x fa-phone text-on-light"></i>
          <span class="center-block px10">1-888-926-4272</span>
          </div>
          </div>
         </div>
         <div class="col-xs-4 hidden-sm col-md-4">
         <div class="padding-type-2">
         <a href="mailto:customer.service@angara.com"  class="no-underline" ><div class="padding-type-5 showcase-bg-dark">
          <i class="fa fa-2x fa-envelope text-on-light"></i>
          <span class="center-block px10">EMAIL</span>
          </div></a>
          </div>
         </div>
         <div class="col-xs-4 col-sm-6 col-md-4">
         <div class="padding-type-2">
         <a class="top-nav-live-chat no-underline live-chat-link" href="javascript:void(0);" onClick="javascript:window.open('https://server.iad.liveperson.net/hc/609151/?cmd=file&file=visitorWantsToChat&site=609151&imageUrl=https://server.iad.liveperson.nethttp://www.angara.comhttp://www.angara.com/store/images/lp/&referrer='+escape(document.location),'chat609151','width=475,height=400,resizable=yes');return false;"><div class="padding-type-5 showcase-bg-dark">
          <i class="fa fa-2x fa-comments text-on-light"></i>
          <span class="center-block px10">LIVE CHAT</span>
          </div></a>
          </div>
         </div>
         
        </div>
       </div>
      </div>
      					<div class="max-margin-top text-center">
                            <div class="center-block high-margin-bottom"><table width="120" border="0" style="margin:0 auto" cellpadding="0" cellspacing="0" title="Click to Verify - This site chose Symantec SSL for secure e-commerce and confidential communications.">
                    <tr>
                    <td width="120" align="center" valign="top"><script type="text/javascript" src="https://seal.verisign.com/getseal?host_name=www.angara.com&amp;size=XS&amp;use_flash=NO&amp;use_transparent=NO&amp;lang=en"></script>
                    <a href="http://www.symantec.com/verisign/ssl-certificates" target="_blank"  style="color:#000000; text-decoration:none; font:bold 7px verdana,sans-serif; letter-spacing:.5px; text-align:center; margin:0 auto; padding:0px; display:inline-block;">ABOUT SSL CERTIFICATES</a></td>
                    </tr>
                    </table></div>
					<div class="center-block high-margin-bottom">
						<?php /* https://www.bbb.org/losangelessiliconvalley/business-reviews/jewelers-retail/angaracom-in-los-angeles-ca-100082531#bbbseal */ ?>
						<a id="bbblink" class="rbhzbus" href="javascript:void(0)" title="Angara.com, Jewelers Retail, Los Angeles, CA" style="display: block;position: relative;overflow: hidden; width: 100px; height: 48px; margin: 0px; padding: 0px; cursor: default;"><img style="padding: 0px; border: none;" id="bbblinkimg" src="/skin/frontend/ress/default/images/seal-for-100082531.png" width="200" height="48" alt="Angara.com, Jewelers Retail, Los Angeles, CA" /></a>
					</div>
                            <?php /*?><div class="center-block">
                                 <script type="text/javascript">var bizrate = {small:"true"};</script> 
                                  <script src="//medals.bizrate.com/medals/js/150815_medal.js" type="text/javascript"></script> 
                                  <a class="br-button" rel="nofollow" style="margin:0 auto;"> <img src="//medals.bizrate.com/medals/dynamic/small/150815_medal.gif" width="112" height="37" border="0" usemap="#150815_medal" alt="See Angara Reviews at Bizrate.com"/>
                      <map name="150815_medal">
                        <area shape="poly" coords="1,0,1,36,61,36,61,20,111,20,111,0" href="http://www.bizrate.com/ratings_guide/merchant_detail__mid--150815.html?rf=sur" title="See Angara Reviews at Bizrate.com" target="_blank"  rel="nofollow"/>
                        <area shape="rect" coords="62,21,111,36" href="http://www.bizrate.com/?rf=sur" title="Bizrate" target="_blank"  rel="nofollow"/>
                      </map>
                      </a>
                              </div><?php */?>
                        </div>
				</div>
				<input type='submit' id='opc_submit_form' style='visibility:hidden;' />
			</div>
		</form>
           <div class="row small">
           <div class="col-sm-4 col-sm-offset-8">
   	<div class="low-margin-bottom">*Sales tax applies only to orders shipped to NY, NJ & CA.</div>
   <div>For orders shipped to locations outside of the United States: International duties, customs and taxes are the responsibility of the customer.</div>
   </div>
    </div>
</div>
<div class="row no-gutters max-margin-top max-margin-bottom fontsize-type2">
			<div class="col-sm-4 showcase-bg-dark checkout-summary-box showcase-border-thin-white">
				<div class="high-padding-left high-padding-right high-padding-bottom">
					<div class="block-sub-heading high-margin-bottom high-padding-top">Respecting Your Privacy </div>
					<ul class="list-style-disc">
						<li>We never share your personal information.</li>
						<li>We adhere to a strict <a href="/privacy-and-security.html" target="_blank">Privacy Policy.</a></li>
					</ul>
				</div>
			</div>
			<div class="col-sm-4 showcase-bg-dark checkout-summary-box showcase-border-thin-white">
				<div class="high-padding-left high-padding-right high-padding-bottom">
					<div class="block-sub-heading high-margin-bottom high-padding-top">Keeping Your Info Safe</div>
					<p>We use the strongest security measures available to keep your information safe.</p>
					<ul class="list-style-disc">
						<li>All credit card data is encrypted.</li>
						<li>Credit Card information is not stored on our systems.</li>
						<li>Our secure order processing system uses 256-bit (SSL) encryption for your protection.</li>
					</ul>                    
				</div>
			</div>
			<div class="col-sm-4 showcase-bg-dark checkout-summary-box showcase-border-thin-white">
				<div class="high-padding-left high-padding-right high-padding-bottom">
					<div class="block-sub-heading high-margin-bottom high-padding-top">The Angara Difference</div>
					<ul class="list-style-disc">
						<li>The Internet's Family Jeweler: Each and every gemstone is hand selected. No detail is overlooked.</li>
						<li>Direct from the source: We manufacture most jewelry ourselves to save you 30-40%.</li>
						<li>Exceptional Value and Quality, Guaranteed by a 110% Refund Policy: If any certified appraiser appraises our jewelry for less than 125% of your purchase price, we will issue you a 110% refund upon return (Refund Amount up to $250 above your Purchase Price).</li>
						<li><?php echo Mage::helper('function')->freeReturnDays();?>-Day Money Back Guarantee: If you don't love it, simply send it back in its original condition for a 100% refund. A FREE return/exchange shipping label will be emailed to you upon request (only for US domestic orders).</li>
					</ul>
				</div>
			</div>
		</div>


		<script type="text/javascript">
//<![CDATA[
    var checkout = new OPC('onepagecheckout_orderform', {
    	save    : '<?php echo $this->getUrl('onepagecheckout/index/saveOrder', array('_secure'=>$seq_http)) ?>',
    	update  : '<?php echo $this->getUrl('onepagecheckout/index/updateCheckout', array('_secure'=>$seq_http)) ?>',
        success : '<?php echo $this->getUrl('onepagecheckout/index/success', array('_secure'=>$seq_http)) ?>',
        failure : '<?php echo $this->getUrl('checkout/cart') ?>',
        persistent : '<?php echo $is_persistent?$this->getUrl('persistent/index/saveMethod', array('_secure'=>$seq_http)):'';?>'
    }, "<?php echo $this->__('Please agree to all the terms and conditions.') ?>");

    <?php if(Mage::helper('onepagecheckout')->isAddressVerificationEnabled()):?>
    function show_verifications_error(){

    	var w = $('address-verification-results').getWidth();
    	var hh = document.body.getHeight();

    	var view = document.viewport.getDimensions();

    	var ww = view.width;
    	var d	= (ww - w)/2;

    	<?php if (!preg_match('/MSIE 8/i', $browser) && !preg_match('/MSIE 7/i', $browser)):?>
    	var y = window.pageYOffset+70;
    	$('address-verification-results').setStyle({
			left: d+'px',
			top: y+'px'
  		});
  		<?php else:?>
    	$('address-verification-results').setStyle({
			left: d+'px'
  		});
		<?php endif;?>

    	$('address-verification-results').show();
    	
    	<?php $is_mobile	= Mage::helper('onepagecheckout')->isMobile();
    	if(!$is_mobile):?>
    	var el = $('iwdavPopupOverlay');
    	el.setStyle({
			width: ww+'px',
			height: hh+'px'
  		});
    	
    	el.show();
    	<?php else:?>
    	$('onepagecheckout_orderform').hide(); // hide form for mobile devices 
    	<?php endif;?>
    }
    function close_verification()
    {
    	<?php $is_mobile	= Mage::helper('onepagecheckout')->isMobile();
    	if(!$is_mobile):?>        
		$("iwdavPopupOverlay").hide();
		<?php else:?>
		$('onepagecheckout_orderform').show(); // show form for mobile devices
		<?php endif;?>
		$('address-verification-results').hide();
	}
	<?php endif; ?>
    
    document.observe("dom:loaded", function() {
        var win_triggers	= Array();
   		$$('.checkout-agreements .agree a').each(function(item){
   			var obj	= {
   				el: $$('.' + item.className),
   		   		event: 'click',
				window: $(item.className + '-window')
			};
   			win_triggers.push(obj);
        });
		opc_window	= new OPC.Window({triggers: win_triggers});
    });
//]]>
</script>
		<?php if(Mage::helper('onepagecheckout')->isAddressVerificationEnabled()):
$is_mobile	= Mage::helper('onepagecheckout')->isMobile();?>
		<div style='display:none;left:0;' class="iwdav_modal <?php if($is_mobile){echo ' iwdav_modal_mobile';}?>" id="address-verification-results">
			<div id="checkout-address-candidates-load"></div>
		</div>
		<?php if(!$is_mobile):?>
		<div id='iwdavPopupOverlay' class='iwdavPopupOverlay' style='display:none;'>&nbsp;</div>
		<?php endif;?>
		<?php endif; ?>
	</div>
</div>