<?php
/**
 * aheadWorks Co.
 *
 * @category   AW
 * @package    AW_Rma
 * @version    1.5.1
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php if ($this->getComments()->getSize()) : ?>
    <ul class="awrma-comments-list">
        <?php foreach ($this->getComments() as $_comment) : ?>
            <li>
                <strong>
                    <?php echo $this->formatDate($_comment->getCreatedAt(), Mage_Core_Model_Locale::FORMAT_TYPE_MEDIUM, true); ?>
                    <span class="separator">|</span>
                    <?php if ($_comment->getOwner() == AW_Rma_Model_Source_Owner::CUSTOMER) : ?>
                        <?php echo $this->getRmaRequest()->getCustomerName() ?>
                    <?php else : 
							//echo Mage::getModel('awrma/source_owner')->getOptionLabel($_comment->getOwner())
							if($_comment->getOwner()==AW_Rma_Model_Source_Owner::ADMIN){ 
								echo Mage::getModel('awrma/source_owner')->getOptionLabel($_comment->getOwner());
							}else{
								echo Mage::getModel('awrma/source_owner')->getOptionLabelAdmin($_comment->getOwner());
							}
					?>
                    <?php endif ?>
                </strong>
                <div><?php echo $_comment->getText() ?></div>
                <?php if ($_comment->getAttachments()) : ?>
                    <div>
                        <a href="<?php echo $this->getUrl('awrma_admin/adminhtml_rma/download', array('cid' => $_comment->getId())) ?>"><?php echo $_comment->getAttachments() ?></a> (<?php echo Mage::helper('awrma/files')->getTextSize($_comment->getAttachments()) ?>)
                    </div>
                <?php endif ?>
            </li>
        <?php endforeach ?>
    </ul>
<?php else : ?>
    <?php echo $this->__('No comments yet') ?>
<?php endif ?>