<?php
/**
 * Cart cross sell items template
 *
 * @see Mage_Checkout_Block_Cart_Crosssell
 */
?>
<?php if($this->getItemCount()): 
//echo $this->getItemCount();?>
<!--Added by Vaseem for 335-->
<script type="text/javascript" src="<?php echo $this->helper('core/js')->getJsUrl('jquery.jcarousel.min.js'); ?>"></script>
<link rel="stylesheet" href="<?php echo Mage::getDesign()->getSkinUrl('css/jcarousel.css');?>"/>
<script type="text/javascript">
function mycarousel_initCallback(carousel, state)
{
    // Disable autoscrolling if the user clicks the prev or next button.
    carousel.buttonNext.bind('click', function() {
        carousel.startAuto(0);
    });

    carousel.buttonPrev.bind('click', function() {
        carousel.startAuto(0);
    });

    // Pause autoscrolling if the user moves with the cursor over the clip.
    carousel.clip.hover(function() {
        carousel.stopAuto();
    }, function() {
        carousel.startAuto();
    });
};

function mycarousel_itemLastOutCallback(carousel, item, idx, state) {
	//alert(idx);
	if(idx==<?php echo $this->getItemCount()-1;?>){
		//jQuery('.jcarousel-next').hide();
	}else{
		//jQuery('.jcarousel-next').show();
	}
	if(idx==<?php echo $this->getItemCount()-2;?>){
		//jQuery('.jcarousel-prev').show();
	}
};

jQuery(document).ready(function() {
    jQuery('#mycarousel').jcarousel({
		scroll: 1,
        //auto: 1,
        wrap: 'last',
        initCallback:   mycarousel_initCallback,
        itemLastOutCallback:  mycarousel_itemLastOutCallback,
    });
});

jQuery(document).ready(function() {
	//alert(<?php echo $this->getItemCount();?>);
<?php if($this->getItemCount()<4){	// Disable arrows if there are no products to show?>
	jQuery('.jcarousel-next').hide();
	jQuery('.jcarousel-prev').hide();
	jQuery('.jcarousel-container-horizontal').css('padding-left','0');
	jQuery('.jcarousel-container-horizontal').css('padding-right','0');		
<?php } else{?>	
	jQuery('.jcarousel-next').show();
	jQuery('.jcarousel-prev').show();
<?php } ?>
});

</script>


<style>
.cart .crosssell h2 {
	font:bold 18px Arial, Helvetica, sans-serif;
	border-bottom: 1px dotted #909090;
	padding-bottom:10px;
}
.cart .crosssell {
	background:#f0f2c4;
	border:none;
	padding:20px 15px;
	width:429px;
	border-right: 1px dotted #D3D3D3;
}
button.cross-sell-cart-button {
	background:url(/skin/frontend/angara/default/images/allbuttonbgleft.jpg) left top no-repeat;
}
#crosssell-products-list li.item button.button span {
	height:auto;
}
button.cross-sell-cart-button span {
	border:none;
	background:url(/skin/frontend/angara/default/images/allbuttonbgright.jpg) right top no-repeat;
}
button.cross-sell-cart-button span span {
	padding:1px 8px;
	display:inline-block
}
.cart .crosssell li.item {
}
.cart .crosssell {
}
.regular-price span span.price {
	color:#B32D2C;
	font:bold 15px Arial, Helvetica, sans-serif;
	display:block;
	padding-top:4px;
}
/*.price {
	color:#B32D2C;
	font:bold 15px Arial, Helvetica, sans-serif;
	display:block;
	padding-top:4px;
}*/
.cart .crosssell .product-image {
	width:150px;
	height:150px;
}
.cart .crosssell .product-details {
	margin-left:100px;
}
.easy-pay-price span {
	font-size:12px !important
}
.cart .crosssell li.item {
	padding:12px 0 16px 0;
}
.product-border {
	border:solid 1px #d4d4d4;
}
.price .easy-pay-price, .price .easy-pay-price span {
	font-size:10px !important;
	width:150px;
}
</style>

<div id="wrap" style="overflow:hidden; height:280px;">
  <h2><?php echo $this->__('Matching Products:') ?></h2>
  <ul id="mycarousel" class="jcarousel-skin-tango">
    <?php foreach ($this->getItems() as $_item){ ?>
     <li class="item"> <a class="product-image" href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(150); ?>" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" class="product-border" /></a>
      <div class="product-details">
        <div class="price">
          <div class="easy-pay-price"> <?php echo $this->getPriceHtml($_item, true); ?> </div>
        </div>
      </div>
    </li>
    <?php } ?>
    <div class="clear"></div>
  </ul>
  <script type="text/javascript">decorateList('crosssell-products-list', 'none-recursive')</script> 
</div>
<?php endif; ?>