<style>
#content-showcase { display: block !important }
.showcase-bg-hero { background-color: #fff; }
.global-offer-wrapper { height: 27px; }
</style>

<div class="container-fluid showcase-border-bottom min-margin-top"><a href="/jewelry/gemstone-jewelry.html?icid=home|main|shopmobile-MOB15|08282015" title="Evergreen reminder of forever love"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/promotion/default/hero-banner-xs1.jpg" alt="Natural Gemstone Jewelry" title="Exclusive offer" class="img-responsive center-block" /></a></div>