<div class="container showcase-bg-white">
	<div class="row low-margin-bottom">
		<div class="col-xs-12">
			<div class="text-center">
				<div class="home-category-block">
					<a href="/wedding-rings/wedding-bands.html?icid=home|wedding-rings|05152015">
                		<p class="max-padding-left max-padding-right">Wedding Rings</p>
						<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/wedding-bands.jpg" class="img-responsive" alt="The Perfect pair for the Perfect Couple" title="Complementing each other" />
					</a>
				</div>
			</div>
		</div>	
    	<div class="col-xs-12">
			<div class="text-center">
				<div class="home-category-block">
					<a href="/jewelry/ruby-jewelry.html?icid=home|ruby-jewelry|06162015">
                		<p class="max-padding-left max-padding-right">Ruby Jewelry</p>
						<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/ruby-jewelry.jpg" class="img-responsive" alt="July Birthstone Jewelry" title="Ruby - The Symbol of LOVE" />
					</a>
				</div>
			</div>
		</div>		
		<div class="col-xs-12 col-md-pull-4">
			<div class="text-center">
				<div class="home-category-block">
					<a href="/jewelry/sapphire-jewelry.html?icid=home|sapphire-jewelry|05152015">
               	 		<p class="max-padding-left max-padding-right">Sapphire Jewelry</p>
						<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/sapphire-jewelry.jpg" class="img-responsive" alt=" Sapphire - The Royal Gemstone" title="Sapphire Jewelry for Sophisticated Beauty" />					
					</a>
				</div>
			</div>
		</div>  
		<div class="col-xs-12">
			<div class="text-center">
				<div class="home-category-block">
					<a href="/jewelry/emerald-jewelry.html?icid=home|emerald-jewelry|06162015">
                		<p class="max-padding-left max-padding-right">Emerald Jewelry</p>
						<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/emerald-jewelry.jpg" class="img-responsive" alt="Sacred Gemstone of Venus" title="Emerald - The Evergreen Gemstone" />
					</a>
				</div>
			</div>
		</div>
		<div class="col-xs-12">
			<div class="text-center">
				<div class="home-category-block">
					<a href="/collection/high-jewelry.html?icid=home|high-jewelry|06162015">
                		<p class="max-padding-left max-padding-right">High Jewelry</p>
						<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/high-jewelry.jpg" class="img-responsive" alt="One-of-a-kind jewelry featuring GIA Certified Stones" title="One-of-a-kind Jewelry Designs" />
					</a>
				</div>
			</div>
		</div> 	     
	</div>
	<div class="row max-margin-bottom">
		<div class="col-xs-12">
			<div class="block-heading high-margin-top">
				<h1 class="no-margin gradient-light">
					<span class="heading-highlight">
						Trending
					</span>
					Now</h1>
			</div>
		</div>
		<div class="col-xs-12 col-sm-6 col-md-4">
			<div class="popular-item-block showcase-box-side-shadow">
				<div class="row">
                	<div class="col-xs-12 text-center">
						<a href="/bracelets.html?content=no&icid=home|trend|bracelets|05152015" rel="nofollow">
							<img data-src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/bracelets.jpg" class="img-responsive center-block" alt="The perfect piece for any outfit" title="Let your hands do the talking" />
						</a>
					</div>
					<div class="col-xs-12">
						<h2 class="text-uppercase no-margin padding-type-15 high-padding-bottom">
							<a href="/bracelets.html?content=no&icid=home|trend|bracelets|05152015">Bracelets</a>
						</h2>
					</div>					
					<div class="col-xs-12">
						<ul>
							<li><a href="/bracelets/diamond-bracelets.html?icid=home|trend|bracelets-dia|05152015" class="block-display padding-type-6">Diamond<i class="fa fa-angle-right pull-right min-margin-top"></i></a></li>
							<li><a href="/bracelets/gemstone-bracelets.html?icid=home|trend|bracelets-gem|05152015" class="block-display padding-type-6">Gemstones<i class="fa fa-angle-right pull-right min-margin-top"></i></a></li>
							<li class="border-bottom-none"><a href="/bracelets/charm-bracelets.html?dir=asc&mode=grid&order=price&icid=home|trend|bracelets-charm|07092015" class="block-display padding-type-6">Charms<i class="fa fa-angle-right pull-right min-margin-top"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
		<div class="col-xs-12 col-sm-6 col-md-4">
			<div class="popular-item-block showcase-box-side-shadow">
				<div class="row">
                	<div class="col-xs-12 text-center">
						<a href="/jewelry/gemstone-jewelry.html?jewelry_styles=4183&icid=home|trend|halo|05152015" rel="nofollow">
							<img data-src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/halo-jewelry.jpg" class="img-responsive center-block" alt="Up your sparkle factor with a halo-style Jewelry" title="Up your sparkle factor with a halo-style Jewelry" />
						</a>
					</div>
					<div class="col-xs-12">
						<h2 class="text-uppercase no-margin padding-type-15 high-padding-bottom">
							<a href="/jewelry/gemstone-jewelry.html?jewelry_styles=4183&icid=home|trend|halo|05152015">Halo Jewelry</a>
						</h2>
					</div>					
					<div class="col-xs-12">
						<ul>
							<li><a href="/engagement-rings/halo-rings.html?icid=home|trend|halo-rings|05152015" class="block-display padding-type-6">Halo Rings<i class="fa fa-angle-right pull-right min-margin-top"></i></a></li>
							<li><a href="/earrings.html?jewelry_styles=4183&order=position&dir=asc&no_cache=true&icid=home|trend|halo-earrings|05152015" class="block-display padding-type-6">Halo Earrings<i class="fa fa-angle-right pull-right min-margin-top"></i></a></li>
							<li class="border-bottom-none"><a href="/pendants.html?jewelry_styles=4183&order=position&dir=asc&no_cache=true&icid=home|trend|halo-necklaces|05152015" class="block-display padding-type-6">Halo Necklaces<i class="fa fa-angle-right pull-right min-margin-top"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
		<div class="col-xs-12 col-sm-6 col-md-4">
			<div class="popular-item-block showcase-box-side-shadow">
				<div class="row">
                	<div class="col-xs-12 text-center">
						<a href="/jewelry/gemstone-jewelry.html?content=no&icid=home|trend|gemjewelry|05152015" rel="nofollow">
							<img data-src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/gemstone-jewelry.jpg" class="img-responsive center-block" alt="Colors of rainbow come your way" title="Immaculate colors of spring flowers" />
						</a>
					</div>
					<div class="col-xs-12">
						<h2 class="text-uppercase no-margin padding-type-15 high-padding-bottom">
							<a href="/jewelry/gemstone-jewelry.html?content=no&icid=home|trend|gemjewelry|05152015">Gemstone jewelry</a>
						</h2>
					</div>					
					<div class="col-xs-12">
						<ul>
							<li><a href="/rings/gemstone-rings.html?icid=home|trend|gemjewelry-rings|05152015" class="block-display padding-type-6">Rings<i class="fa fa-angle-right pull-right min-margin-top"></i></a></li>
							<li><a href="/earrings/gemstone-earrings.html?icid=home|trend|gemjewelry-earrings|05152015" class="block-display padding-type-6">Earrings<i class="fa fa-angle-right pull-right min-margin-top"></i></a></li>
							<li class="border-bottom-none"><a href="/pendants/gemstone-necklace-pendants.html?icid=home|trend|gemjewelry-necklaces|05152015" class="block-display padding-type-6">Necklaces<i class="fa fa-angle-right pull-right min-margin-top"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
		<?php /* <div class="col-xs-12 col-sm-6 col-md-4 hidden-xs">
			<div class="popular-item-block showcase-box-side-shadow">
				<div class="row">
                	<div class="col-xs-12 text-center">
						<a href="/birthstone-jewelry/birthstone-pendants.html?icid=home|trend|birjewelry|05012015" rel="nofollow">
							<img data-src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/birthstone-jewelry.jpg" class="img-responsive center-block" alt="Birthstone for May" title="Birthstone for May" />
						</a>
					</div>
					<div class="col-xs-12">
						<h2 class="text-uppercase no-margin padding-type-15 high-padding-bottom">
							<a href="/birthstone-jewelry/birthstone-pendants.html?icid=home|trend|birjewelry|05012015">Birthstone Jewelry</a>
						</h2>
					</div>					
					<div class="col-xs-12">
						<ul>
							<li><a href="/birthstone-jewelry/may-birthstone-emerald-jewelry.html?icid=home|trend|birjewelry-may|05012015" class="block-display padding-type-6">May<i class="fa fa-angle-right pull-right min-margin-top"></i></a></li>
							<li><a href="/birthstone-jewelry/june-birthstone-pearl-jewelry.html?icid=home|trend|birjewelry-june|05012015" class="block-display padding-type-6">June<i class="fa fa-angle-right pull-right min-margin-top"></i></a></li>
							<li class="border-bottom-none"><a href="/birthstone-jewelry/july-birthstone-ruby-jewelry.html?icid=home|trend|birjewelry-july|05012015" class="block-display padding-type-6">July<i class="fa fa-angle-right pull-right min-margin-top"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
		</div> */ ?>
		
	</div>	
</div>