<div class="row <?php echo $this->getContainerClassName()?>">
    <div class="col-sm-6 name-firstname high-margin-bottom">
        <div class="data_area">
        	First Name*
            <input type="text" id="<?php echo $this->getFieldId('firstname')?>" name="<?php echo $this->getFieldName('firstname')?>" value="<?php echo $this->htmlEscape($this->getObject()->getFirstname()) ?>" title="<?php echo $this->__('First Name') ?>" class="input-text t1 required-entry" <?php echo $this->getFieldParams() ?> />
        </div>
    </div>
    <div class="col-sm-6 name-lastname high-margin-bottom">
        <div class="data_area">
        	Last Name*
            <input type="text" id="<?php echo $this->getFieldId('lastname')?>" name="<?php echo $this->getFieldName('lastname')?>" value="<?php echo $this->htmlEscape($this->getObject()->getLastname()) ?>" title="<?php echo $this->__('Last Name') ?>" class="input-text t1 required-entry" <?php echo $this->getFieldParams() ?> />
        </div>
    </div>
</div>
