<?php
/*
 * Contus Support Pvt Ltd.
 * created by Vasanth on nov 02 2010.
 * vasanth@contus.in
 * In this page we can include the jw player in frontend.
 */

$_helper = $this->helper('catalog/output');
$_product = $this->getProduct();
$cids = $_product->getCategoryIds();
$_videoDetails['video'] = $_helper->productAttribute($_product, $this->htmlEscape($_product->getVideo()), 'video');
$video_arr = explode("|",$_videoDetails['video']);
$number_of_videos = count($video_arr); ?>

<link rel='stylesheet' href='<?php echo $this->getSkinUrl('css/thickbox.css'); ?>' type='text/css' media='all' />

<div id="playvedio">
	<a id="playvideoicon" href="javascript:void(0);" onclick="document.getElementById('light').style.display='block'; document.getElementById('fade').style.display='block';">
    	<img src="<?php echo $this->getSkinUrl('images/playvedioicon.png'); ?>" width="33" height="27" />
    </a>
</div>

<?php 
$videoPath = "http://media.angara.com/productVideos/";
$thumbPath = Mage::getBaseURL('media').'productVideos/'; ?>

<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jwplayer.js'); ?>"></script>  
 
<script>
jQuery(function(){
	jQuery('#light, #fade').appendTo('body');
});
</script>

<?php	
// Code added by Vaseem for iPad bugs
$iPad	=	0;
if(strstr($_SERVER['HTTP_USER_AGENT'],'iPad')){
	$iPad	=	1;
} ?>

<div id="light" class="white_content">
	<div style="color:#000; z-index: 2147483647; position: absolute; <?php if($iPad=='1'){?>top: 440px;<?php }else{ ?>top: 493px;<?php } ?> left: 7px;"><?php echo 'Video is for representation purpose only'; ?></div>
	
	<div>
		<img src="<?php echo $videoPath."img/tb-close.png"; ?>" alt="Close" style="position:absolute;top:-25px;right:-25px;z-index:999" onClick="document.getElementById('light').style.display='none'; document.getElementById('fade').style.display='none'; playerStop();"/>
	</div>
	
	<div id='mediaspace'></div>
</div>

<a href = "javascript:void(0)" onclick = "document.getElementById('light').style.display='none';document.getElementById('fade').style.display='none';playerStop();"> 
	<div id="fade" class="black_overlay"></div>
</a>

<!-- <video class="jwplayer" src="video1.mp4" poster=""></video>-->
<?php	
//	Added by Vaseem to resolve video width bug in iPad
if(strstr($_SERVER['HTTP_USER_AGENT'],'iPad')){
	$playerWidth	=	'820';	//	Width of video with jwplayer logo inside layer
	$playerHeight	=	'440';	//	Height of video with jwplayer logo
}else{
	$playerWidth	=	'960';
	if(!(in_array($_product->getSku(), $plainBandSku))){
		$playerHeight	=	'490';
	}
	else{
		$playerHeight	=	'510';
	}
}?>
<script type='text/javascript'>
	jwplayer('mediaspace').setup({
		'flashplayer': '<?php echo $this->getSkinUrl('jwplayer/player.swf'); ?>',	
		'id': 'mediaspace',
		'skin': '<?php echo $this->getSkinUrl('slim/slim.zip'); ?>',
		'start':'0',
		'width': '<?php echo $playerWidth;?>',
		'autostart': 'true',	
		'height': '<?php echo $playerHeight;?>',
		'repeat': 'single',
		'volume': '50',
		'screencolor': '#FFFFFF',
		'controlbar': 'bottom',	 
		'playlist.position':'left',
		'playlist.size':'108',
		'playlist.showtext':'false',
		'playlist.backgroundcolor':'#EEEEEE',
		'playlist': [
		<?php
		for ($i=0; $i < count($video_arr); $i++) {
		  /*Retrive uploaded videos from media*/
		  list($videoName,$thumbName) = explode(',',$video_arr[$i]); ?>
		  {
			'file': '<?php echo $videoPath."video/".$videoName; ?>',
			'image': '<?php echo $thumbPath."thumb/".$thumbName; ?>'          
		  },
		<?php 
		} ?> ],
		'plugins' : {
			'timeslidertooltipplugin-3': {}	
		}
	});
</script>

<script type='text/javascript'>
	function playerStop(){
		jwplayer('mediaspace').stop();
	}
</script>