<?php
/**
 * Customer login form template
 *
 * @see app/design/frontend/base/default/template/customer/form/login.phtml
 */
/** @var $this Mage_Customer_Block_Form_Login */
?>
<style>
.login_with_facebook_btn
{
	width:136px;
	height:28px;
	background:url(/skin/frontend/ress/default/images/login-with-facebook.jpg) no-repeat;
	filter: none!important;
}
.login_with_facebook_btn:hover, .login_with_facebook_btn:focus, .login_with_facebook_btn.active
{
	background:url(/skin/frontend/ress/default/images/login-with-facebook.jpg) no-repeat;
	filter: none!important;
}
.space-filler{ margin-top:50px;}
@media (min-width: 768px ) and (max-width: 999px) {
.space-filler{ margin-top:49px;}
}

</style>
<div class="container showcase-bg-white max-padding-top max-padding-bottom">
<div class="account-login">
    <div class="page-title max-margin-bottom">
        <h1><?php echo $this->__('Login or Create an Account') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <div class="col2-set">
            <div class="col-1 max-margin-bottom new-users">
            <div class="showcase-bg-light padding-type-16">
                <div class="content">
                    <h2><?php echo $this->__('New Customers') ?></h2>
                    <p><?php echo $this->__('By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.') ?></p>
                    <div class="high-margin-bottom high-padding-top high-margin-top text-bold">ANGARA Membership Advantages:</div>
   					<ul class="list-style-disc">
                    	<li class="high-padding-bottom">Get Free Expedited Shipping</li>
						<li class="high-padding-bottom">Get guaranteed discounts, free gifts and more</li>
						<li class="high-padding-bottom">Personalized shopping experience</li>
						<li class="high-padding-bottom">Previews of new product lines</li>
						<li class="high-padding-bottom">Access to one of a kind designs prior to launch on the site</li>
						<li class="high-padding-bottom">Faster checkout</li>
					</ul>
                </div>
                <div class="buttons-set space-filler">
                <div class="row">
                    <div class="col-xs-12"><button  style="float:right" type="button" title="<?php echo $this->__('Create an Account') ?>" class="button" onclick="window.location='<?php echo Mage::helper('persistent')->getCreateAccountUrl($this->getCreateAccountUrl()) ?>';"><span><span><?php echo $this->__('Create an Account') ?></span></span></button></div>                   
                </div> 
                </div>                
                </div>
            </div>
            <div class="col-2 max-margin-bottom registered-users">
            	<div class="showcase-bg-light padding-type-16">
                <div class="content">
              <h2><?php echo $this->__('Registered Customers') ?></h2>                    
                    <p><?php echo $this->__('If you have an account with us, please log in.') ?></p>
                    <ul class="form-list">
                        <li>
                            <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                            <div class="input-box">
                                <input type="text" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
                            </div>
                        </li>
                        <li>
                            <label for="pass" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                            <div class="input-box">
                                <input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
                            </div>
                        </li>
                        <?php echo $this->getChildHtml('form.additional.info'); ?>
                        <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                    </ul>
                    <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
                    <p class="required low-margin-bottom"><?php echo $this->__('* Required Fields') ?></p>
                </div>
                <div class="buttons-set low-padding-top high-padding-bottom" style="border-top:0; margin:6px 0 0 0;">
                    <a href="<?php echo $this->getForgotPasswordUrl() ?>" class="f-left"><?php echo $this->__('Forgot Your Password?') ?></a>
                    <button type="submit" class="button" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><span><span><?php echo $this->__('Login') ?></span></span></button>
                </div>
                <div style="border-top: 1px solid #e5e5e5; position:relative;" class="max-padding-top max-margin-top">
				<div style="border:1px solid #dbdbdb; display:inline-block; padding:10px; background-color:#fff;-moz-border-radius:30px; -webkit-border-radius: 30px; border-radius: 30px; font-weight:bold; position:absolute; width:39px; margin:auto; left:0; right:0; top:-22px; ">OR</div>
                <h2 class="low-margin-top low-margin-bottom"><?php echo $this->__('Facebook Users') ?></h2>
                    <p><?php echo $this->__('Use your Facebook account to login within our store. You\'re just one click away.') ?></p>
                    <div>
                <button rel="facebook-connect" type="button" title="<?php echo $this->__('Connect with Facebook') ?>" class="button login_with_facebook_btn" style="float:right"></button>
                <div class="clearfix"></div>
                </div>
                </div>
                </div>
            </div>
        </div>
        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif; ?>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
    //]]>
    </script>
</div>
</div>

