<title><?php echo $this->getTitle(); ?></title>
<meta name="SKYPE_TOOLBAR" content="SKYPE_TOOLBAR_PARSER_COMPATIBLE" /> 
<meta http-equiv="Content-Type" content="<?php echo $this->getContentType(); ?>" />
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()); ?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()); ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()); ?>" />

<?php
$product = Mage::registry('current_product');
if($product){ ?>
<meta property="og:title" content="<?php echo $this->getTitle(); ?>" />
<meta property="og:url" content="<?php echo  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).$product->getUrlpath();?>" />
<meta property="og:type" content="product" />
<meta property="og:image" content="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)."catalog/product".$product->getImage();?>" />
<meta property="og:description" content="<?php echo trim($product->getDescription()); ?>" />
<?php
} ?>

<link rel="icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />

<?php echo $this->getCssJsHtml();?>
<?php echo $this->getChildHtml();?>
<?php echo $this->getIncludes(); ?>
<script type="text/javascript">mboxCreate('tntGlobal');</script>