<div class="categorylist">
<ul>
	<li><a href="/rings/aquamarine-rings.html">
    <span class="imageholder"><img src="<?php echo $this->getSkinURL('images/landing/aquamarine-rings.jpg');?>" alt="Aquamarine Rings"  class="categoryimage"/></span>
    <span class="detailholder"> 
    	<span class="categorydetails">Aquamarine Rings</span>
    	<span class="startfrom">From <span class="catprice"><?php  echo Mage::helper('core')->currency($this->getLowestCatalogPrice(37));?></span></span>
    </span>
    </a></li>
    <li><a href="/earrings/aquamarine-earrings.html">
    <span class="imageholder"><img src="<?php echo $this->getSkinURL('images/landing/aquamarine-earrings.jpg');?>" alt="Aquamarine Earrings"  class="categoryimage"/></span>
    <span class="detailholder"> 
    	<span class="categorydetails">Aquamarine Earrings</span>
    	<span class="startfrom">From <span class="catprice"><?php  echo Mage::helper('core')->currency($this->getLowestCatalogPrice(52));?></span></span>
    </span>
    </a></li>
    <li><a href="/pendants/aquamarine-necklace-pendants.html">
    <span class="imageholder"><img src="<?php echo $this->getSkinURL('images/landing/aquamarine-pendants.jpg');?>" alt="Aquamarine Pendants"  class="categoryimage"/></span>
    <span class="detailholder"> 
    	<span class="categorydetails">Aquamarine Pendants</span>
    	<span class="startfrom">From <span class="catprice"><?php  echo Mage::helper('core')->currency($this->getLowestCatalogPrice(44));?></span></span>
    </span>
    </a></li>
    
</ul>
</div>