<div class="categorylist">
<ul>
	<li><a href="/rings/diamond-rings.html">
    <span class="imageholder"><img src="<?php echo $this->getSkinURL('images/landing/diamond-rings.jpg');?>" alt="Diamond Rings"  class="categoryimage"/></span>
    <span class="detailholder"> 
    	<span class="categorydetails">Diamond Rings</span>
    	<span class="startfrom">From <span class="catprice"><?php  echo Mage::helper('core')->currency($this->getLowestCatalogPrice(70));?></span></span>
    </span>
    </a></li>
    
    <li><a href="/earrings/diamond-earrings.html">
    <span class="imageholder"><img src="<?php echo $this->getSkinURL('images/landing/diamond-earrings.jpg');?>" alt="Diamond Earrings"  class="categoryimage"/></span>
    <span class="detailholder"> 
    	<span class="categorydetails">Diamond Earrings</span>
    	<span class="startfrom">From <span class="catprice"><?php  echo Mage::helper('core')->currency($this->getLowestCatalogPrice(71));?></span></span>
    </span>
    </a></li>
    
    <li><a href="/pendants/diamond-necklace-pendants.html">
    <span class="imageholder"><img src="<?php echo $this->getSkinURL('images/landing/diamond-pendants.jpg');?>" alt="Diamond Pendants"  class="categoryimage"/></span>
    <span class="detailholder"> 
    	<span class="categorydetails">Diamond Pendants</span>
    	<span class="startfrom">From <span class="catprice"><?php  echo Mage::helper('core')->currency($this->getLowestCatalogPrice(72));?></span></span>
    </span>
    </a></li>
    <li><a href="/engagement-rings/diamond-engagement-rings.html">
    <span class="imageholder"><img src="<?php echo $this->getSkinURL('images/landing/diamond-engagement-rings.jpg');?>" alt="Diamond Engagement Rings"  class="categoryimage"/></span>
    <span class="detailholder"> 
    	<span class="categorydetails">Diamond Engagement Rings</span>
    	<span class="startfrom">From <span class="catprice"><?php  echo Mage::helper('core')->currency($this->getLowestCatalogPrice(82));?></span></span>
    </span>
    </a></li>
    
</ul>
</div>