<div class="categorylist">
<ul>
	<li><a href="/rings/emerald-rings.html">
    <span class="imageholder"><img src="<?php echo $this->getSkinURL('images/landing/emerald-rings.jpg')?>" alt="Emerald Rings"  class="categoryimage"/></span>
    <span class="detailholder"> 
    	<span class="categorydetails">Emerald Rings</span>
    	<span class="startfrom">From <span class="catprice"><?php  echo Mage::helper('core')->currency($this->getLowestCatalogPrice(35));?></span></span>
    </span>
    </a></li>
    
    <li><a href="/earrings/emerald-earrings.html">
    <span class="imageholder"><img src="<?php echo $this->getSkinURL('images/landing/emerald-earrings.jpg')?>" alt="Emerald Earrings"  class="categoryimage"/></span>
    <span class="detailholder"> 
    	<span class="categorydetails">Emerald Earrings</span>
    	<span class="startfrom">From <span class="catprice"><?php  echo Mage::helper('core')->currency($this->getLowestCatalogPrice(50));?></span></span>
    </span>
    </a></li>
    
    <li><a href="/pendants/emerald-necklace-pendants.html">
    <span class="imageholder"><img src="<?php echo $this->getSkinURL('images/landing/emerald-pendants.jpg');?>" alt="Emerald Pendants"  class="categoryimage"/></span>
    <span class="detailholder"> 
    	<span class="categorydetails">Emerald Pendants</span>
    	<span class="startfrom">From <span class="catprice"><?php  echo Mage::helper('core')->currency($this->getLowestCatalogPrice(42));?></span></span>
    </span>
    </a></li>
    <li><a href="/engagement-rings/emerald-engagement-rings.html">
    <span class="imageholder"><img src="<?php echo $this->getSkinURL('images/landing/emerald-engagement-rings.jpg')?>" alt="Emerald Engagement Rings"  class="categoryimage"/></span>
    <span class="detailholder"> 
    	<span class="categorydetails">Emerald Engagement Rings</span>
    	<span class="startfrom">From <span class="catprice"><?php  echo Mage::helper('core')->currency($this->getLowestCatalogPrice(80));?></span></span>
    </span>
    </a></li>
    
</ul>
</div>