<div class="categorylist">
  <ul>
    <li><a href="/landing/jewelry/sapphire-jewelry.html"> <span class="imageholder"><img src="<?php echo $this->getSkinURL('images/landing/sapphire-jewelry.jpg');?>" alt="Sapphire Jewelry"  class="categoryimage"/></span> <span class="detailholder"> <span class="categorydetails">Sapphire Jewelry</span> <span class="startfrom">From <span class="catprice">
      <?php  echo Mage::helper('core')->currency($this->getLowestCatalogPrice(59));?>
      </span></span> </span> </a></li>
      
    <li><a href="/landing/jewelry/ruby-jewelry.html"> <span class="imageholder"><img src="<?php echo $this->getSkinURL('images/landing/ruby-jewelry.jpg');?>" alt="Ruby Jewelry"  class="categoryimage"/></span> <span class="detailholder"> <span class="categorydetails">Ruby Jewelry</span> <span class="startfrom">From <span class="catprice">
      <?php  echo Mage::helper('core')->currency($this->getLowestCatalogPrice(47));?>
      </span></span> </span> </a></li>
      
    <li><a href="/landing/jewelry/emerald-jewelry.html"> <span class="imageholder"><img src="<?php echo $this->getSkinURL('images/landing/emerald-jewelry.jpg');?>" alt="Emerald Jewelry"  class="categoryimage"/></span> <span class="detailholder"> <span class="categorydetails">Emerald Jewelry</span> <span class="startfrom">From <span class="catprice">
      <?php  echo Mage::helper('core')->currency($this->getLowestCatalogPrice(46));?>
      </span></span> </span> </a></li>
      
    <li><a href="/landing/jewelry/tanzanite-jewelry.html"> <span class="imageholder"><img src="<?php echo $this->getSkinURL('images/landing/tanzanite-jewelry.jpg')?>" alt="Tanzanite Jewelry"  class="categoryimage"/></span> <span class="detailholder"> <span class="categorydetails">Tanzanite Jewelry</span> <span class="startfrom">From <span class="catprice">
      <?php  echo Mage::helper('core')->currency($this->getLowestCatalogPrice(60));?>
      </span></span> </span> </a></li>
      
    <li><a href="/landing/jewelry/diamond-jewelry.html"> <span class="imageholder"><img src="<?php echo $this->getSkinURL('images/landing/diamond-jewelry.jpg')?>" alt="Diamond Jewelry"  class="categoryimage"/></span> <span class="detailholder"> <span class="categorydetails">Diamond Jewelry</span> <span class="startfrom">From <span class="catprice">
      <?php  echo Mage::helper('core')->currency($this->getLowestCatalogPrice(04));?>
      </span></span> </span> </a></li>
      
    <li><a href="/landing/jewelry/aquamarine-jewelry.html"> <span class="imageholder"><img src="<?php echo $this->getSkinURL('images/landing/aquamarine-jewelry.jpg')?>" alt="Aquamarine Jewelry"  class="categoryimage"/></span> <span class="detailholder"> <span class="categorydetails">Aquamarine Jewelry</span> <span class="startfrom">From <span class="catprice">
      <?php  echo Mage::helper('core')->currency($this->getLowestCatalogPrice(61));?>
      </span></span> </span> </a></li>
      
    <li><a href="/birthstone-jewelry/january-birthstone-garnet-jewelry.html"> <span class="imageholder"><img src="<?php echo $this->getSkinURL('images/landing/garnet-jewelry.jpg')?>" alt="Garnet Jewelry"  class="categoryimage"/></span> <span class="detailholder"> <span class="categorydetails">Garnet Jewelry</span> <span class="startfrom">From <span class="catprice">
      <?php  echo Mage::helper('core')->currency($this->getLowestCatalogPrice(207));?>
      </span></span> </span> </a></li>
      
    <li><a href="/birthstone-jewelry/february-birthstone-amethyst-jewelry.html"> <span class="imageholder"><img src="<?php echo $this->getSkinURL('images/landing/amethyst-jewelry.jpg')?>" alt="Amethyst Jewelry"  class="categoryimage"/></span> <span class="detailholder"> <span class="categorydetails">Amethyst Jewelry</span> <span class="startfrom">From <span class="catprice">
      <?php  echo Mage::helper('core')->currency($this->getLowestCatalogPrice(208));?>
      </span></span> </span> </a></li>
      
    <li><a href="/birthstone-jewelry/june-birthstone-pearl-jewelry.html"> <span class="imageholder"><img src="<?php echo $this->getSkinURL('images/landing/pearl-jewelry.jpg')?>" alt="Pearl Jewelry"  class="categoryimage"/></span> <span class="detailholder"> <span class="categorydetails">Pearl Jewelry</span> <span class="startfrom">From <span class="catprice">
      <?php  echo Mage::helper('core')->currency($this->getLowestCatalogPrice(211));?>
      </span></span> </span> </a></li>
      
    <li><a href="/birthstone-jewelry/august-birthstone-peridot-jewelry.html"> <span class="imageholder"><img src="<?php echo $this->getSkinURL('images/landing/peridot-jewelry.jpg')?>" alt="Peridot Jewelry"  class="categoryimage"/></span> <span class="detailholder"> <span class="categorydetails">Peridot Jewelry</span> <span class="startfrom">From <span class="catprice">
      <?php  echo Mage::helper('core')->currency($this->getLowestCatalogPrice(214));?>
      </span></span> </span> </a></li>
      
    <li><a href="/birthstone-jewelry/october-birthstone-opal-jewelry.html"> <span class="imageholder"><img src="<?php echo $this->getSkinURL('images/landing/opal-jewelry.jpg')?>" alt="Opal Jewelry"  class="categoryimage"/></span> <span class="detailholder"> <span class="categorydetails">Opal Jewelry</span> <span class="startfrom">From <span class="catprice">
      <?php  echo Mage::helper('core')->currency($this->getLowestCatalogPrice(216));?>
      </span></span> </span> </a></li>
      
    <li><a href="/birthstone-jewelry/november-birthstone-citrine-jewelry.html"> <span class="imageholder"><img src="<?php echo $this->getSkinURL('images/landing/citrine-jewelry.jpg')?>" alt="Citrine Jewelry"  class="categoryimage"/></span> <span class="detailholder"> <span class="categorydetails">Citrine Jewelry</span> <span class="startfrom">From <span class="catprice">
      <?php  echo Mage::helper('core')->currency($this->getLowestCatalogPrice(217));?>
      </span></span> </span> </a></li>
      
  </ul>
</div>
