<div class="categorylist">
<ul>
	<li><a href="/rings/ruby-rings.html">
    <span class="imageholder"><img src="<?php echo $this->getSkinURL('images/landing/ruby-rings.jpg');?>" alt="Ruby Rings"  class="categoryimage"/></span>
    <span class="detailholder"> 
    	<span class="categorydetails">Ruby Rings</span>
    	<span class="startfrom">From <span class="catprice"><?php  echo Mage::helper('core')->currency($this->getLowestCatalogPrice(34));?></span></span>
    </span>
    </a></li>
    <li><a href="/earrings/ruby-earrings.html">
    <span class="imageholder"><img src="<?php echo $this->getSkinURL('images/landing/ruby-earrings.jpg');?>" alt="Ruby Earrings"  class="categoryimage"/></span>
    <span class="detailholder"> 
    	<span class="categorydetails">Ruby Earrings</span>
    	<span class="startfrom">From <span class="catprice"><?php  echo Mage::helper('core')->currency($this->getLowestCatalogPrice(49));?></span></span>
    </span>
    </a></li>
    <li><a href="/pendants/ruby-necklace-pendants.html">
    <span class="imageholder"><img src="<?php echo $this->getSkinURL('images/landing/ruby-pendants.jpg');?>" alt="Ruby Pendants"  class="categoryimage"/></span>
    <span class="detailholder"> 
    	<span class="categorydetails">Ruby Pendants</span>
    	<span class="startfrom">From <span class="catprice"><?php  echo Mage::helper('core')->currency($this->getLowestCatalogPrice(41));?></span></span>
    </span>
    </a></li>
    <li><a href="/engagement-rings/ruby-engagement-rings.html">
    <span class="imageholder"><img src="<?php echo $this->getSkinURL('images/landing/ruby-engagement-rings.jpg')?>" alt="Ruby Engagement Rings"  class="categoryimage"/></span>
    <span class="detailholder"> 
    	<span class="categorydetails">Ruby Engagement Rings</span>
    	<span class="startfrom">From <span class="catprice"><?php  echo Mage::helper('core')->currency($this->getLowestCatalogPrice(79));?></span></span>
    </span>
    </a></li>
</ul>
</div>