<div class="categorylist">
<ul>
	<li><a href="/rings/sapphire-rings.html">
    <span class="imageholder"><img src="<?php echo $this->getSkinURL('images/landing/sapphire-rings.jpg')?>" alt="Sapphire Rings"  class="categoryimage"/></span>
    <span class="detailholder"> 
    	<span class="categorydetails">Sapphire Rings</span>
    	<span class="startfrom">From <span class="catprice"><?php  echo Mage::helper('core')->currency($this->getLowestCatalogPrice(33));?></span></span>
    </span>
    </a></li>
    <li><a href="/earrings/sapphire-earrings.html">
    <span class="imageholder"><img src="<?php echo $this->getSkinURL('images/landing/sapphire-earrings.jpg')?>" alt="Sapphire Earrings"  class="categoryimage"/></span>
    <span class="detailholder"> 
    	<span class="categorydetails">Sapphire Earrings</span>
    	<span class="startfrom">From <span class="catprice"><?php  echo Mage::helper('core')->currency($this->getLowestCatalogPrice(48));?></span></span>
    </span>
    </a></li>
    <li><a href="/pendants/sapphire-necklace-pendants.html">
    <span class="imageholder"><img src="<?php echo $this->getSkinURL('images/landing/sapphire-pendants.jpg')?>" alt="Sapphire Pendants"  class="categoryimage"/></span>
    <span class="detailholder"> 
    	<span class="categorydetails">Sapphire Pendants</span>
    	<span class="startfrom">From <span class="catprice"><?php  echo Mage::helper('core')->currency($this->getLowestCatalogPrice(40));?></span></span>
    </span>
    </a></li>
    <li><a href="/engagement-rings/sapphire-engagement-rings.html">
    <span class="imageholder"><img src="<?php echo $this->getSkinURL('images/landing/sapphire-engagement-rings.jpg');?>" alt="Sapphire Engagement Rings"  class="categoryimage"/></span>
    <span class="detailholder"> 
    	<span class="categorydetails">Sapphire Engagement Rings</span>
    	<span class="startfrom">From <span class="catprice"><?php  echo Mage::helper('core')->currency($this->getLowestCatalogPrice(78));?></span></span>
    </span>
    </a></li>
    
</ul>
</div>