<style>
.hover-bdr {top:0px;left:0;right:0;text-align:center;color:#868686;}
.hover-bdr span, .spl-ofr span {display:block;}
.hover-bdr .title, .spl-ofr .title {font-size: 26px;padding-top: 15px; color:#000000;line-height:30px;}
.hover-bdr .btn, .spl-ofr .btn {width:110px;margin:0 auto;background:transparent;padding:10px;border:1px solid #868686;line-height:10px;font-size:16px;margin-top: 15px; border-radius:2px;}
.white-bg{background:#ffffff}
#gemstone-section .hover-bdr {top:30px;left:0;right:0;text-align:center;color:#868686;}
#gemstone-section .hover-bdr .title {padding-top:5px;}


#best-sellers a:hover .hover-bdr .btn, #gemstone-section a:hover .hover-bdr .btn {border:1px solid #fa505a;color:#fa505a;}
.top20 {top:24%;}
#ang-toggle ul li{display:inline-block; margin:0px 20px; position:relative; cursor:pointer;}
#ang-toggle ul li:first-child{cursor:default;}
#ang-toggle ul li:first-child{line-height:28px!important;}
#ang-toggle ul li img{max-height:28px;}
#ang-toggle ul li.active:before,
#ang-toggle ul li.active:after{content:""; position:absolute;}
#ang-toggle ul li.active:before{border-bottom: 7px solid #000000; border-top: 7px solid transparent; border-left: 7px solid transparent; border-right: 7px solid transparent; top: -24px; left: 50%; margin-left: -4px;} 
#ang-toggle ul li.active:after{background: #000000; height: 1px; left: 0px; right: 0px; top: -11px;}
#ang-toggle .gray{display:block}
#ang-toggle .colored{display:none}
#ang-toggle .hover .gray{display:none}
#ang-toggle .hover .colored{display:block}

#homepage-latest-reviews .detail-box-bs{bottom:-100%; transition:bottom 500ms; -webkit-transition:bottom 500ms; background: rgba(255,255,255,0.8); padding:10px 30px; text-align: center;}
#homepage-latest-reviews .slick-slide:hover .detail-box-bs{bottom:0px;}
#homepage-latest-reviews .detail-box-bs .color999{font-size:14px;}
#best-sellers .hover-bdr .btn {color:#000000;border:1px solid #000000;margin-top:8px;}
#best-sellers .valentine .btn {color:#ffffff;border:1px solid #ffffff;}
#best-sellers .valentine a:hover .valentine-btn {color:#000000 !important;border:1px solid #000000 !important;}
.mewe-hover-img {display:none;}
.mewe a:hover .mewe-default-img {display:none;}
.mewe a:hover .mewe-hover-img {display:block;}
.golden-collection  .btn {color:#ffffff;border:1px solid #ffffff;}
.sub-title {color: #666666;}
@media (max-width:1024px) {
	#gemstone-section .hover-bdr {
		top:10px;
	}
	.top20 {top:22.5%;}
	#best-sellers .hover-bdr .title,
	#gemstone-section .hover-bdr .title {
		font-size:20px;
		padding-top: 5px;
	}
	#ang-toggle ul li{
		margin:0px 5px;
	}
	.mewe a:hover .mewe-default-img {display:block;}
	.mewe a:hover .mewe-hover-img {display:none;}
	.spl-ofr {bottom:4%;}
}
@media (max-width:768px) {
	#gemstone-section .hover-bdr {top:20px;}
	.hover-bdr .title {
		line-height:initial;
	}
	#best-sellers .hover-bdr .title{
		padding-top:15px;
	}
}
<?php if(!strstr($_SERVER['HTTP_USER_AGENT'],'iPad')){ ?>
@media (max-width:1024px) {
	#best-sellers .col-md-4,
	#gemstone-section .col-md-4{
		width:33.33333333333333%!important;
	}
	#best-sellers .col-md-8,
	#gemstone-section .col-md-8{
		width:66.66666666666666%!important;
	}
}
<?php } ?>
</style>

<?php $userAgent = Mage::getUserAgent(); ?>
<div class="clearfix"></div>
<div class="homepage-main-container">
	<section class="light-gray-bg angara-in-press" style="padding:10px 0px 0px;">
		<div class="container">
			<div class="content-box">
				<div id="ang-toggle-content" class="text-center hide" style="padding-bottom:10px; margin-bottom:10px; border-bottom:1px solid #dedede">
					<div class="wwd hide">"Angara offers custom engagement rings and other jewelry categories at prices generally 35 to 50 percent cheaper than at traditional retailers."</div>
					<div class="crains hide">"...taking e-commerce to the upper reaches of the jewelry market."</div>
					<div class="forbes hide">"Purchasing high-end goods online has come of age."</div>
					<div class="cheddar hide">"Online jewelry market is expected to grow 15% YOY by 2017."</div>
					<div class="topmodels hide">"See Angara's $40,000 diamond bracelet in America's Next Top Model"</div>
				</div>
				<div id="ang-toggle" class="text-center">
					<ul>
						<li data-show="blank" style="line-height:37px; font-size:30px; color:#000000">
							<span class="pull-left">Featured In</span>
						</li>
						<li data-show="wwd">
							<img class="img-responsive gray" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/new-skeleton/press/wwd-press-gray.jpg" alt=""/>
							<img class="img-responsive colored" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/new-skeleton/press/wwd-press.jpg" alt=""/>
						</li>
						<li data-show="crains">
							<img class="img-responsive gray" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/new-skeleton/press/crains-press-gray.png" alt=""/>
							<img class="img-responsive colored" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/new-skeleton/press/crains-press.png" alt=""/>
						</li>
						<li data-show="forbes">
							<img class="img-responsive gray" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/new-skeleton/press/forbes-press-gray.png" alt=""/>
							<img class="img-responsive colored" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/new-skeleton/press/forbes-press.jpg" alt=""/>
						</li>
						<li data-show="cheddar">
							<img class="img-responsive gray" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/new-skeleton/press/cheddar-gray.png" alt=""/>
							<img class="img-responsive colored" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/new-skeleton/press/cheddar.png" alt=""/>
						</li>
						<li data-show="topmodels">
							<img class="img-responsive gray" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/new-skeleton/press/topmodels-press-gray.jpg" alt=""/>
							<img class="img-responsive colored" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/new-skeleton/press/topmodels-press.jpg" alt=""/>
						</li>
					</ul>
				</div>
				<script>
					jQuery(function(){
						jQuery('#ang-toggle ul li').click(function(){
							if(jQuery(this).attr('data-show') != 'blank'){
								var cls = jQuery(this).attr('data-show');
								jQuery('#ang-toggle-content').removeClass('hide').find('.'+cls).removeClass('hide').siblings().addClass('hide');
								jQuery(this).addClass('hover active').siblings().removeClass('hover active');
							}
						});
						
						jQuery('#ang-toggle-title ul li').mouseover(function(){
							jQuery(this).addClass('hover');
						}).mouseleave(function(){
							jQuery('#ang-toggle-title ul li').removeClass('hover');
						});
						
					});
				</script>
			</div>
		</div>
	</section>
	
	<section id="best-sellers" class="white-bg">
		<div class="container">
			<div class="heading-box">
				<h2 class="heading">Best Selling Collection</h2>
				<div class="sub-heading">Shop the designs our customers love most</div>
			</div>
			<div class="content-box">
				<div class="col-md-4 col-sm-6">
					<a href="/jewelry/diamond-jewelry?icid=home|main|bestseller|april-diamond|04012017">
						<img class="img-responsive bdr-typ-1" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/new-skeleton/best-sellers-april-birthstone.jpg" alt="Explore Diamond Jewelry" title="Explore Diamond Jewelry"/>
						<div class="absolute-placeholder hover-bdr dbl">
							<span class="title">Diamond Jewelry</span>
							<span class="btn">Shop Now</span>
						</div>
					</a>
				</div>
				<div class="col-md-4 col-sm-6">
					<div id="collection-slider">
						<div class="relative-placeholder"> 
							<a href="/collection/infinity-jewelry?icid=home|main|bestseller|inf-collec|shpnow|02222017">
								<img class="img-responsive mewe-default-img hidden" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/new-skeleton/infinity-01-71836.jpg" alt="Explore Infinity Collection" title="Explore Infinity Collection"/>
								<div class="absolute-placeholder hover-bdr dbl top20">
									<span class="btn">Shop Now</span>
								</div>
							</a>
						</div>
						<div class="relative-placeholder"> 
							<a href="/collection/knotty-heart-jewelry?icid=home|main|bestseller|knotty-h-collec|shpnow|02202017">
								<img class="img-responsive mewe-default-img hidden" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/new-skeleton/knotty-1-06005.jpg" alt="Explore Knotty Heart Collection" title="Explore Knotty Heart Collection"/>
								<div class="absolute-placeholder hover-bdr dbl top20">
									<span class="btn">Shop Now</span>
								</div>
							</a>
						</div>
						<div class="relative-placeholder"> 
							<a href="/jewelry/coffee-diamond-jewelry?icid=home|main|bestseller|coffee-d-collec|shpnow|02172017">
								<img class="img-responsive mewe-default-img hidden" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/new-skeleton/coffee-1-56659.jpg" alt="Explore Coffee Diamond Collection" title="Explore Coffee Diamond Collection"/>
								<div class="absolute-placeholder hover-bdr dbl top20">
									<span class="btn">Shop Now</span>
								</div>
							</a>
						</div>
						<div class="relative-placeholder"> 
							<a href="/collection/wear-your-luck?icid=home|main|bestseller|wearurluck-collec|shpnow|04032017">
								<img class="img-responsive mewe-default-img hidden" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/new-skeleton/wearyourluck-04032017.jpg" alt="Explore Wear Your Luck Collection" title="Explore Wear Your Luck Collection"/>
								<div class="absolute-placeholder hover-bdr dbl top20">
									<span class="btn">Shop Now</span>
								</div>
							</a>
						</div>
					</div>
					<script type="text/javascript">
					jQuery(function(){
						jQuery('#collection-slider').slick({
							arrows			: 	true,
							dots			: 	false,
							slidesToShow	: 	1,
							slidesToScroll	: 	1,
							autoplay		: 	true,
							autoplaySpeed	: 	5000
						});
						jQuery('#collection-slider img').removeClass('hidden');
					});
					</script>
				</div>
				<div class="col-md-4 col-sm-6 visible-md">
					<a href="/products?icid=home|main|bestseller|review|shpnow|03072017">
						<img class="img-responsive bdr-typ-1 relative-placeholder" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/new-skeleton/best-seller-2-03072017.jpg" alt="Best Seller Jewelry" title="Best Seller Jewelry"/>
						<div class="absolute-placeholder hover-bdr">
							<span class="title">Highest Rated Jewelry</span>
							<span class="btn">Shop Now</span>
						</div>
					</a>
				</div>
			</div>
		</div>
	</section>
	
	<section id="gemstone-section" class="light-gray-bg">
		<div class="container">
			<div class="heading-box">
				<h2 class="heading">Shop Gemstone Jewelry</h2>
				<?php /* <div class="sub-heading">Discover the colors of the rainbow</div> */ ?>
			</div>
			<div class="content-box hover-two">
				<div class="col-md-8 col-sm-12 padding-type-8 gem-1 pull-left">
					<a href="/jewelry/emerald-jewelry?icid=home|main|gem-jewelry|emerald|04142017">
						<img class="img-responsive bdr-typ-6" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/new-skeleton/emerald-jewelry.jpg" alt="Explore Emerald Jewelry" title="Explore Emerald Jewelry"/>
						<div class="absolute-placeholder hover-bdr">
							<span class="title">Emerald- May Birthstone Jewelry</span>
							<span class="sub-title">Inspired by Pantone Color 2017</span>
							<span class="btn">Shop Now</span>
						</div>
					</a>
				</div>
				<div class="col-md-4 col-sm-6 padding-type-8 gem-2 visible-md">
					<a href="/jewelry/sapphire-jewelry?icid=home|main|gem-jewelry|sapphire|11062016">
						<img class="img-responsive bdr-typ-3" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/new-skeleton/gemstone-41.jpg" alt="Explore Natural Sapphire Jewelry" title="Explore Natural Sapphire Jewelry"/>
						<div class="absolute-placeholder hover-bdr">
							<span class="title">Sapphire Jewelry</span>
							<span class="btn">Shop Now</span>
						</div>
					</a>
				</div>
				<div class="col-md-4 col-sm-6 padding-type-8 gem-4" style="clear:left">
					<a href="/jewelry/ruby-jewelry?icid=home|main|gem-jewelry|ruby|04092016">
						<img class="img-responsive bdr-typ-2" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/new-skeleton/gemstone-31.jpg" alt="The Color of Love" title="Explore Ruby Jewelry"/>
						<div class="absolute-placeholder hover-bdr">
							<span class="title">Ruby Jewelry</span>
							<span class="btn">Shop Now</span>
						</div>
					</a>
				</div>
				<div class="col-md-4 col-sm-6 padding-type-8 gem-3">
					<a href="/jewelry/aquamarine-jewelry?icid=home|main|gem-jewelry|aqua|04092016">
						<img class="img-responsive bdr-typ-5" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/new-skeleton/gemstone-61.jpg" alt="Aqua Desire" title="Explore Aquamarine Jewelry"/>
						<div class="absolute-placeholder hover-bdr">
							<span class="title">Aquamarine Jewelry</span>
							<span class="btn">Shop Now</span>
						</div>
					</a>
				</div>
				<div class="col-md-4 col-sm-6 padding-type-8 gem-5">
					<a href="/jewelry/tanzanite-jewelry?icid=home|main|gem-jewelry|tanzanite|04092016">
						<img class="img-responsive bdr-typ-4" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/new-skeleton/gemstone-51.jpg" alt="Unleashing the beauty of the Tanzanite" title="Explore Tanzanite Jewelry"/>
						<div class="absolute-placeholder hover-bdr">
							<span class="title">Tanzanite Jewelry</span>
							<span class="btn">Shop Now</span>
						</div>
					</a>
				</div>
				<div class="col-md-4 col-sm-6 padding-type-8 gem-6">
					<a href="/jewelry/morganite-jewelry?icid=home|main|gem-jewelry|morganite|04142017">
						<img class="img-responsive bdr-typ-1" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/new-skeleton/morganite-jewelry.jpg" alt="Explore Morganite Jewelry" title="Explore Morganite Jewelry"/>
						<div class="absolute-placeholder hover-bdr">
							<span class="title">Morganite Jewelry</span>
							<span class="btn">Shop Now</span>
						</div>
					</a>
				</div>
				
				<div class="col-md-4 col-sm-6 padding-type-8 gem-6">
					<a href="/jewelry/garnet-jewelry?icid=home|main|gem-jewelry|garnet|04142017">
						<img class="img-responsive bdr-typ-1" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/new-skeleton/garnet-jewelry.jpg" alt="Explore Garnet Jewelry" title="Explore Garnet Jewelry"/>
						<div class="absolute-placeholder hover-bdr">
							<span class="title">Garnet Jewelry</span>
							<span class="btn">Shop Now</span>
						</div>
					</a>
				</div>
				<div class="col-md-4 col-sm-6 padding-type-8 gem-6">
					<a href="/jewelry/opal-jewelry?icid=home|main|gem-jewelry|opal|04142017">
						<img class="img-responsive bdr-typ-1" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/new-skeleton/opal-jewelry.jpg" alt="Explore Opal Jewelry" title="Explore Opal Jewelry"/>
						<div class="absolute-placeholder hover-bdr">
							<span class="title">Opal Jewelry</span>
							<span class="btn">Shop Now</span>
						</div>
					</a>
				</div>

			</div>
			<div class="button-box">
				<a href="/jewelry/gemstone-jewelry?icid=home|main|gem-jewelry|button-seeall|04092016">Shop All Gemstone Jewelry</a>
			</div>
		</div>
	</section>

	<section class="white-bg" style="padding-bottom:0px;">
		<div class="container">
			<div class="heading-box">
				<h2 class="heading">Best Sellers</h2>
			</div>
			<div class="content-box">
				<div id="latest-reviews" class="col-xs-12 has-slider">
					<div class="showcase-bg-white padding-type-10 HP1">
						<div class="HP2">
							<div id="homepage-latest-reviews">
							    <?php 
							    try
							    {
							    $resource = Mage::getSingleton('core/resource');
				                $read = $resource->getConnection('core_read');
				                $sql = "Select * from ang_bestseller";
				                $sqlQuery = $read->query($sql);
				                $iterator=0;
							    while ($row = $sqlQuery->fetch() ) 
							    {
							    	    $iterator++;
							            $sku=$row['sku'];
							            $obj = Mage::getModel('catalog/product')->getCollection()->addAttributeToSelect(array('url_key','short_description','price','special_price','image'))->addFinalPrice()->addAttributeToFilter('sku',$sku)->getFirstItem();
							            $obj2=new Mage_Catalog_Block_Product();
							            $image = $obj2->helper('catalog/image')->init($obj, 'image')->resize(175);
										$title=$obj->getShortDescription();
										$url=$obj->getProductUrl();
								?>	
							    
								<div class="relative-placeholder" style="overflow:hidden">
									<a href="<?php echo $url; ?>?icid=bestseller-widget-12142016" title="<?php echo $title;?>" class="center-block text-center">
										<img class="img-responsive bdr-typ-1" style="margin:0 auto; max-width:175px; max-height:175px" data-org="<?php echo $image ?>" alt="<?php echo $title;?>" title="<?php echo $title;?>"/>
									</a>
									<div class="detail-box-bs absolute-placeholder">
										<a href="<?php echo $url; ?>?icid=bestseller-widget-12142016">
											<p class="product-name"><?php echo $title; ?></p>
										</a>
										<span class="apricot-text high-margin-top block-inline-display"><?php echo strip_tags($obj2->getPriceHtmlBestSeller($obj, true, '-similar'),'<span>'); ?></span>
									</div>
								</div>
								<?php }
								}
								catch(Exception $e)
								{ } ?>	
							</div>
						</div>
						<script type="text/javascript">
						jQuery(function(){
							var s2s = 0;
							if(jQuery(window).width() <= 768){
								s2s = 3;
							}else if(jQuery(window).width() <= 1024 && jQuery(window).width() > 768){
								s2s = 4;
							}else{
								s2s = 5;
							}
							jQuery('#homepage-latest-reviews').slick({
								arrows			: 	true,
								dots			: 	false,
								slidesToShow	: 	s2s,
								slidesToScroll	: 	1,
								autoplay		: 	false,
								autoplaySpeed	: 	5000
							});
						});
						</script>
					</div>
				</div>
			</div>
		</div>
	</section>
	
	<section class="light-gray-bg">
		<div class="container">
			<div class="heading-box">
				<h2 class="heading">Customer Stories</h2>
				<div class="sub-heading">We love our customers and they love us, too! Hear what they're saying (yes, we're blushing).</div>
			</div>
			<div class="content-box">
				<div id="cs-content-table">
					<div class="cs-content-table-cell col-sm-6">
						<div id="cs-images">
							<div class="cs-images box-1">
								<img class="img-responsive" data-index="0" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/new-skeleton/customer-stories/cs-01.jpg" alt=""/>
								<img class="img-responsive" data-index="1" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/new-skeleton/customer-stories/cs-014.jpg" alt=""/>
								<img class="img-responsive" data-index="2" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/new-skeleton/customer-stories/cs-003.jpg" alt=""/>
								<img class="img-responsive" data-index="3" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/new-skeleton/customer-stories/cs-09.jpg" alt=""/>
							</div>
							<div class="cs-images box-2">
								<img class="img-responsive active" data-index="4" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/new-skeleton/customer-stories/cs-04.jpg" alt=""/>
								<img class="img-responsive" data-index="5" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/new-skeleton/customer-stories/cs-012.jpg" alt=""/>
								<div style="max-width:180px;">
									<img class="img-responsive" style="display:inline-block;max-width:50%;" data-index="6" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/new-skeleton/customer-stories/cs-016.jpg" alt=""/>
									<img class="img-responsive" style="float:right;max-width:50%;" data-index="7" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/new-skeleton/customer-stories/cs-015.jpeg" alt=""/>
								</div>
							</div>
							<div class="cs-images box-3">
								<img class="img-responsive" data-index="8" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/new-skeleton/customer-stories/cs-010.jpg" alt=""/>
								<img class="img-responsive" data-index="9" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/new-skeleton/customer-stories/cs-013.jpg" alt=""/>
								<img class="img-responsive" data-index="10" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/new-skeleton/customer-stories/cs-02.jpg" alt=""/>
								<img class="img-responsive" data-index="11" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/new-skeleton/customer-stories/cs-06.jpg" alt=""/>
							</div>
							<div class="cs-images box-4">
								<img class="img-responsive" data-index="12" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/new-skeleton/customer-stories/cs-005.jpg" alt=""/>
								<img class="img-responsive" data-index="13" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/new-skeleton/customer-stories/cs-011.jpeg" alt=""/>
								<img class="img-responsive" data-index="14" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/new-skeleton/customer-stories/cs-07.jpg" alt=""/>
								<img class="img-responsive" data-index="15" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/homepage/new-skeleton/customer-stories/cs-08.jpg" alt=""/>
							</div>
						</div>
					</div>
					<div id="cs-content" class="cs-content-table-cell col-sm-6">
						<div class="cs-content text-center hide">
							<p style="color:#666666">"My beautiful ring from Angara! It's GORGEOUS!"</p>
							<p style="color:#333333; margin-bottom:0px">‎-Krista</p>
							<p style="color:#999999; font-size:14px;">CA</p>
						</div>
						<div class="cs-content text-center hide">
							<p style="color:#666666">"Love the garnet stone.  It’s a deep, rich gemstone and it gives any outfit a little extra richness to it.  Handcrafted in shining silver with a designer V-bale, the pear-shaped garnet is one of my go-to classic necklaces.  The sparkle is spectacular!"</p>
							<p style="color:#333333; margin-bottom:0px">-Karen Morse</p>
							<p style="color:#999999; font-size:14px;">OH</p>
						</div>
						<div class="cs-content text-center hide">
							<p style="color:#666666">"My experience with Angara was great. I got to work with a great jeweler, Barbara Stein and got the color stone and size I wanted. I also got the ring size I wanted that fits me perfectly. I love my ring so much! The customer service was great also and I also love how the rings are not already made they are handmade. It came really fast also when you select overnight shipping for $20. I will definitely use Angara again."</p>
							<p style="color:#333333; margin-bottom:0px">-Elizabeth Abramson</p>
							<p style="color:#999999; font-size:14px;">CT</p>
						</div>
						<div class="cs-content text-center hide">
							<p style="color:#666666">"The whole experience was great. Consider me a repeat customer!"</p>
							<p style="color:#333333; margin-bottom:0px">-Jamal</p>
							<p style="color:#999999; font-size:14px;">NC</p>
						</div>
						<div class="cs-content text-center">
							<p style="color:#666666">"Actually I wanted to share my nice moments after proposal. There is good news and very good news. Which one you want to hear first?:) Ok, good is that ring size I selected is perfect on her finger (it is her first ring overall!). And very good news-she said YES with happy tears in her face .(unforgettable moment)."</p>
							<p style="color:#333333; margin-bottom:0px">-Donatas</p>
							<p style="color:#999999; font-size:14px;">LT</p>
						</div>
						<div class="cs-content text-center hide">
							<p style="color:#666666">"If you prefer to forgo birth stones, I would suggest something in a deep holiday, wintry hue like this garnet necklace. I’m a huge fan of dainty jewelry as it can pair with almost anything and adds an air of elegance to any outfit."</p>
							<p style="color:#333333; margin-bottom:0px">-Julie Hiller (Joules)</p>
							<p style="color:#999999; font-size:14px;">IL</p>
						</div>
						<div class="cs-content text-center hide">
							<p style="color:#666666">"I chose to have my pendant’s metal set in 14k yellow gold, but you can also choose from  silver or 14k white gold. Also, you can select up to 5 gemstones. An 18″ chain is shipped for free with the pendant."</p>
							<p style="color:#333333; margin-bottom:0px">-Andrea Perullo (Andi)</p>
							<p style="color:#999999; font-size:14px;">NC</p>
						</div>
						<div class="cs-content text-center hide">
							<p style="color:#666666">"Just wanted to thank you for helping make this ring "the" ring. What I wanted was the perfect ring for her and you helped me match up reality with what was rattling around in my head. She absolutely loves it! I love it, and it looks good on her too!"</p>
							<p style="color:#333333; margin-bottom:0px">-Chris</p>
							<p style="color:#999999; font-size:14px;">LT</p>
						</div>
						<div class="cs-content text-center hide">
							<p style="color:#666666">"I paired this oval garnet diamond necklace from Angara with the dress since the colors complemented one another nicely. It is a lovely delicate piece set in sterling silver that shines with a garnet pendant surrounded by tiny diamonds that give off a subtle sparkle. This would be a fabulous birthstone gift for any January babies or anyone who loves quality jewelry that you could wear everyday. I love the garnet stone for this time of the year. The deep red reminds me of berries!"</p>
							<p style="color:#333333; margin-bottom:0px">-Amanda Brezovsky</p>
							<p style="color:#999999; font-size:14px;">PA</p>
						</div>
						<div class="cs-content text-center hide">
							<p style="color:#666666">"I must say, when the beautiful package arrived to my door, I was immediately in love with my Garnet gemstone pendant. I can’t wait to wear my birthstone in such a chic style. It is the perfect size, style, and you can definitely see the quality in the cut of the piece."</p>
							<p style="color:#333333; margin-bottom:0px">-Rachel Trampel</p>
							<p style="color:#999999; font-size:14px;">MN</p>
						</div>
						<div class="cs-content text-center hide">
							<p style="color:#666666">"This pair of 14k white gold fashion earrings are perfect to wear whether you are a mother or not and make a lovely gift option for any special occasion. I cannot tell you how many compliments I have received on them since I started wearing them!"</p>
							<p style="color:#333333; margin-bottom:0px">-Andi</p>
							<p style="color:#999999; font-size:14px;">CA</p>
						</div>
						<div class="cs-content text-center hide">
							<p style="color:#666666">"I just want to say 'thank you' for going above and beyond with helping me finally get the right ring for my daughter and future husband.. I appreciate your fantastic customer service."</p>
							<p style="color:#333333; margin-bottom:0px">-Angel</p>
							<p style="color:#999999; font-size:14px;">TN</p>
						</div>
						<div class="cs-content text-center hide">
							<p style="color:#666666">"This ring was a gift to myself as a present for all I have been through in 3 years surviving a let go from my old job, moving onto a new job, getting a divorce after a 15 yr marriage came to a halt- which is now final, and dealing with my newly retired mother 😊. Big milestones. My birthday is October 5th 1976. I have never owned a ring which was made by a jeweler. Sad to say, but even my wedding ring was from my ex husband’s deceased step grandfather. The engagement ring was selected and initially paid for by my mother in law and then paid off by myself. It was 2 sizes 2 big. Replaced then by a cheap ring from Overstock.com 10 kt white gold supposedly which took on the sheen of weathered steel after a year.</p>
							<p style="color:#666666">So guess what! You can imagine my heartfelt inner peace putting on this absolutely gorgeous ring. Thank you so much for your personal assistance and touch with my order."</p>
							<p style="color:#333333; margin-bottom:0px">‎-Laura</p>
							<p style="color:#999999; font-size:14px;">MI</p>
						</div>
						<div class="cs-content text-center hide">
							<p style="color:#666666">"I just wanted to say thanks; you guys did a phenomenal job on the blue sapphire engagement ring."</p>
							<p style="color:#333333; margin-bottom:0px">‎-Matt</p>
							<p style="color:#999999; font-size:14px;">AK</p>
						</div>
						<div class="cs-content text-center hide">
							<p style="color:#666666">"It came! I love it!"</p>
							<p style="color:#333333; margin-bottom:0px">-Katherine</p>
							<p style="color:#999999; font-size:14px;">TX</p>
						</div>
						<div class="cs-content text-center hide">
							<p style="color:#666666">"OMG! I JUST GOT ENGAGED – black diamonds are my favorite!! I love you Chris Ferrand I can't wait to spend the rest of my life with you!!"</p>
							<p style="color:#333333; margin-bottom:0px">-Christopher</p>
							<p style="color:#999999; font-size:14px;">FL</p>
						</div>
					</div>
				</div>
				<script>
					jQuery(function(){
						jQuery('#cs-images img').hover(function(){
							var elem = jQuery(this);
							var index = elem.attr('data-index');
							elem.parents('#cs-images').find('img').removeClass('active');
							elem.addClass('active');
							jQuery('#cs-content .cs-content').addClass('hide')
							jQuery('#cs-content .cs-content:eq('+index+')').removeClass('hide');
						});
					});
				</script>
			</div>
		</div>
	</section>
</div>