<?php
/**
 * Product:     Layered Navigation Pro for Magento 20/04/11
 * Package:     AdjustWare_Nav_2.1.1_0.1.4_8_74006
 * Purchase ID: QgBMpw5YKeeQ8cDxt9xj7DfR5rzlpaEBHoIuAZvOxv
 * Generated:   2011-06-08 07:09:19
 * File path:   app/design/frontend/default/default/template/adjnav/filter_price_slider.phtml
 * Copyright:   (c) 2011 AITOC, Inc.
 */


if(Aitoc_Aitsys_Abstract_Service::get()->isMagentoVersion('>=1.4')){
	list($min,$max) = $this->_filter->getMinMaxPriceInt();
	list($from,$to) = explode(',', $this->_filter->getActiveState());
}

//echo '<br>min->'.$min;
//echo '<br>max->'.$max;
	
//	Code Added by Vaseem for iPad
	$iPad	=	0;
	if(strstr($_SERVER['HTTP_USER_AGENT'],'iPad')){
		$iPad	=	1;
	}
	if($iPad==1){ ?>
    <script type="text/javascript" language="javascript">
	function defaultPricing(minPrice,maxPrice){
		adj_nav_add_params('price', minPrice + ',' + maxPrice, true);
		adj_nav_make_request();
	}
	</script>
    <ol>
        <?php if($min<250 && $min!=250){ ?>
        	<li style="cursor:pointer;"><a onclick="defaultPricing(<?php echo $min;?>,250);">Below <?php echo $this->getSymbol()?>250</a></li>
        <?php } ?>
        <li style="cursor:pointer;"><a onclick="defaultPricing(250,500);"><?php echo $this->getSymbol()?>250 - <?php echo $this->getSymbol()?>500</a></li>
        <li style="cursor:pointer;"><a onclick="defaultPricing(500,1000);"><?php echo $this->getSymbol()?>500 - <?php echo $this->getSymbol()?>1000</a></li>
        <?php if($max>1000 && $max!=1000){ ?>
	        <li style="cursor:pointer;"><a onclick="defaultPricing(1000,<?php echo $max;?>);">Above <?php echo $this->getSymbol()?>1000</a></li>
        <?php } ?>
    </ol>
    <?php }  else{ 
//	Code Added by Vaseem for iPad?>


<?php
    if(Aitoc_Aitsys_Abstract_Service::get()->isMagentoVersion('>=1.4')):
//todo: move logic to the block
    list($min,$max) = $this->_filter->getMinMaxPriceInt();

    list($from,$to) = explode(',', $this->_filter->getActiveState());

    $from = floor(max($from, $min));

    if ($to)
    {
        $to   = ceil(min($to, $max));
    }
    else
    {
        $to = $max;
    }

    if ($to<1 && $from<1)
    {
        $to = $max;
    }

    $width = 170;

    if ($max)
    {
        if ($max == $min)
        {
            $firstOffset = 0;
            $secondOffset = $width;
        }
        else
        {
			//$firstOffset  = ($from-$min)*$width/($max-$min);
			//$secondOffset = ($to-$min)*$width/($max-$min);
			
			/* Exponential Customization by Hitesh */
			$firstOffset = log($from / $min) * ($width / (log($max) - log($min)) );
			$secondOffset = log($to / $min) * ($width / (log($max) - log($min)) );
        }
    }
    else
    {
        $firstOffset  = 0;
        $secondOffset = 0;
    }
?>
<ol>
    <li>
<?php if ($to != $from) {?>
<div id="adj-nav-price-slider<?php echo $this->_filter->getRequestVar()?>" class="adj-nav-slider">
    <div class="handle selected" style="left:<?php echo $firstOffset?>px"></div>
    <div class="handle" style="left:<?php echo $secondOffset?>px"></div>
  </div>
<?php }?>

	<?php if ($to != $from) {?>
		<?php echo $this->__('Range:')?>
         <?php echo $this->getSymbol()?><span id="adj-nav-range-from<?php echo $this->_filter->getRequestVar()?>"><?php echo number_format($from);?></span> - <?php echo $this->getSymbol()?><span id="adj-nav-range-to<?php echo $this->_filter->getRequestVar(); ?>"><?php echo number_format($to);?></span>
        <script type="text/javascript">
            var adj_slider = adj_nav_create_slider(<?php echo $width.', '.$firstOffset.', '.$secondOffset.', '.$min.', '.$max.',"'.$this->_filter->getRequestVar()?>");
        </script>
    <?php } else{?>
		<?php echo $this->__('Value:')?>
		<?php echo $this->getSymbol()?><span id="adj-nav-range-from<?php echo $this->_filter->getRequestVar()?>"><?php echo number_format($from);?></span>
	<?php }?>
    
<?php
	else:
	//todo: move logic to the block
    $max = $this->_filter->getMaxPriceInt();
    list($from,$to) = explode(',', $this->_filter->getActiveState());
    $from = floor(min($from, $max));
    $to   = ceil(min($to, $max));

    if ($to<1 && $from<1){
        $to = $max;
    }

    $width = 170;

    $firstOffset  = $from*$width/$max;
    $secondOffset = $to*$width/$max;

    // due to rounding values might change
    //$from = $firstOffset*$max/$width;
    // $to   = $secondOffset*$max/$width;
?>
<ol>
    <li>
<div id="adj-nav-price-slider" class="adj-nav-slider">
    <div class="handle selected" style="left:<?php echo $firstOffset?>px"></div>
    <div class="handle" style="left:<?php echo $secondOffset?>px"></div>
  </div>
  
  	
		<?php echo $this->__('Range:')?>
		<?php echo $this->getSymbol()?><span id="adj-nav-range-from"><?php echo $from?></span>-<?php echo $this->getSymbol()?><span id="adj-nav-range-to"><?php echo $to?></span>
<script type="text/javascript">
    var adj_slider = adj_nav_create_slider(<?php echo $width.', '.$firstOffset.', '.$secondOffset.', '.$max?>);
</script>
    </li>
</ol>
<?php
    endif;
	} 
?>