<?php
/**
Code added by Hitesh Agarwal
*/

?>
<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
?>
<?php 
	$sku = $_product->getSku();
	if(substr($sku, -1)==="H" || substr($sku, -1)==="B" || substr($sku, -1)==="G" || substr($sku, -1)==="L"){
		$sku = substr_replace($sku,'',-1);
	}
	if(@file_exists(Mage::getBaseDir().'/skin/frontend/angara/default/video/'.$sku.'.flv')):
?>
<script type="text/javascript">
/* Script added by hitesh */
jQuery(function(){
	jQuery('#product-video-btn').click(function(){
	jQuery('#fullsize').css('height','273px');
	jQuery('#product-image-btn').removeClass('product-media-tab-btn-selected');
	jQuery(this).addClass('product-media-tab-btn-selected');
	jQuery('.product-img-box').hide();
	jQuery('.product-video-box').show();
	jwplayer("mediaplayer").play();
})

jQuery('#product-image-btn').click(function(){
	jQuery('#product-video-btn').removeClass('product-media-tab-btn-selected');
	jQuery('#fullsize').css('height','350px');
	jQuery(this).addClass('product-media-tab-btn-selected');
	jQuery('.product-video-box').hide();
	jQuery('.product-img-box').show();
	jwplayer("mediaplayer").pause();
})
})
</script>

<div id="product-media-controls">
	<div id="product-image-btn" class="product-media-tab-btn product-media-tab-btn-selected">Images</div>
	<div id="product-video-btn" class="product-media-tab-btn">Video</div>
</div>
	<script type="text/javascript">
		jQuery(function(){
			jwplayer("mediaplayer").setup({
				flashplayer: "/skin/frontend/angara/default/video/player/player.swf",
				file: "/skin/frontend/angara/default/video/<?php echo $sku ?>.flv",
				width:350,
				height: 263
			});
		})
	</script>
<div class="product-video-box">
	<div id="mediaplayer">Loading...</div>
</div>
<?php 
	endif;
?>