<style>
.br-button {height:48px !important;width:82px !important;}
.bbIzr {display: flex;justify-content: center;}
</style>
<div class="footer-container">
    <div class="footer">
		<?php echo $this->getChildHtml('footer_showcase'); ?>	
		<?php $pageType = Mage::helper('function')->getPageType(); ?>
		<?php if($pageType != 'cart' && $pageType != 'checkout' && $pageType != 'onepagecheckout' && $pageType != 'amazon_payments'){ ?>
			<div class="foot-nav full-width fl pL10"> 
				<a href="/return-policy">Returns</a> | <a href="/shipping">Shipping</a> | <a href="/international-policies">International Shipping</a> | <a href="/faq">FAQ's</a> |  <a href="/total-protection-warranty">Warranty Plan</a> | <a href="/awrma/guest_rma/index/">Online Returns</a> | <a href="/tracking">Track Your Order</a> | <a href="/privacy-and-security">Privacy & Security</a> | <a href="/term-of-use">Terms of Use</a> | <a href="/about-us">About Angara</a>
			</div>	
			<div class="full-width p10">
				<div class="extra-block full-width">
					<div class="block shipping-destination">
						<div class="title text-center">Shipping Destination:</div>
						<?php echo $this->getChildHtml('country'); ?>
					</div>
				</div>
			</div>
		<?php } ?>
		<ul class="full-width p10 text-center bbIzr">
			<li class="bbblink" style="display:inline-block;float:none;padding-right:10px;">
				<div class="mT5 b3-logo" style="display:none">
					<a id="bbblink" class="ruhzbus" href="javascript:void(0)" title="Angara.com, Jewelers Retail, Los Angeles, CA" style="display: block;position: relative;overflow: hidden; width: 100px; height: 48px; margin: 0px; padding: 0px;"><img style="padding:0px; border:none; max-width:200%;" id="bbblinkimg" src="/skin/frontend/ress/default/images/seal-for-100082531.png" width="200" height="48" alt="Angara.com, Jewelers Retail, Los Angeles, CA" /></a>
				</div>	
				<script>
					jQuery(window).load(function(){
						jQuery('.b3-logo').show();
					});
				</script>
			</li>
			<li class="bizrate" style="display:inline-block;float:none;">
				<!-- BEGIN: Bizrate Medal (125x73 pixels) -->
					<img src="/skin/frontend/ress/default/images/bizrate.png" border="0" style="max-height:48px" alt="See Angara.com Reviews at Bizrate.com" />
				<!-- END: Bizrate Medal (125x73 pixels) -->
			</li>
		</ul>
		
        <address class="copyright full-width">&copy; <?php echo date('Y');?> Angara.com. All Rights Reserved.</address>
    </div>
</div>

<?php 
//$channelType	=	Mage::helper('function')->getChannelType();
//if($channelType!='paid-search'){
	if(!isset($_COOKIE['popupvisitor'])){?>	
	<div class="modal fade" id="newsletterModal" tabindex="-1" role="dialog" aria-hidden="true" data-clear-on-close="1">
    	<?php /*<div class="loading-indicator hide text-center" style="position:absolute; left:0px; right:0px; top:43%;">
        	<div class="modal-backdrop fade in"></div>
			<div class="loader fa fa-spinner fa-spin fa-5x max-margin-top"></div>
    	</div>*/?>
	</div>
	<?php }
//}
if(!isset($_COOKIE['returningvisitor'])){?>
	<?php /*	S:VA	International country selection popup hide ?><div class="modal fade" id="fetchcountry" tabindex="-1" role="dialog" aria-hidden="true" data-clear-on-close="1"></div><?php */?>
<?php }
if(Mage::app()->getRequest()->getModuleName() != 'onepagecheckout' && Mage::app()->getRequest()->getModuleName() != 'checkout'){
if(Mage::getSingleton('core/session')->getData('subspopmsg')){?>
	<div class="modal fade" id="thankyouModal" tabindex="-1" role="dialog" aria-hidden="true" data-clear-on-close="1">
		<div class="loading-indicator text-center" style="position:absolute; left:0px; right:0px; top:43%;">
			<div class="modal-backdrop fade in"></div>
			<div class="loader fa fa-spinner fa-spin fa-5x max-margin-top"></div>    
		</div>
	</div>
	<script type="text/javascript">
	jQuery(function(){
	  try{
	   setTimeout(function(){ jQuery('#thankyouModal').modal({remote: '/newsletter/popup/showThankYouPopup'}); },1000);
	  } catch(e) {
	   console.log(e);
	  }
  });
	</script>
<?php	
}
}
?>

<script>
	//load images on document ready
	var wH = jQuery(window).height();
	function lazyLoad(){
		jQuery('img').each(function(){
			var orgSrc = jQuery(this).attr('data-org');
			if (typeof orgSrc !== typeof undefined && orgSrc !== false) {
				var pos = jQuery(this).offset();
				if(pos.top <= wH){
					jQuery(this).attr('src',orgSrc);
					jQuery(this).removeAttr("data-org");
				}
			}
		});
	}
	lazyLoad();
	//load images on scroll
	jQuery(window).scroll(function(){
		jQuery('img').each(function(){
			var orgSrc = jQuery(this).attr('data-org');
			if (typeof orgSrc !== typeof undefined && orgSrc !== false) {
				var pos = jQuery(this).offset();
				var sTpos = jQuery(window).scrollTop();
				if(pos.top >= wH){
					var val = pos.top-(wH+sTpos);
					if(val <= 0){
						jQuery(this).attr('src',orgSrc);
						jQuery(this).removeAttr("data-org");
					}
				}
			}
		});
	});
	
	
	//:RV Option Popup Close
	jQuery('.option-popup-close').on('click',function(){
		var activePopup = jQuery(this).attr('data-active-popup');
		var activeTab = jQuery(this).attr('data-active-tab');
		jQuery('#'+activePopup).addClass('hidden');
		jQuery('#'+activeTab).removeClass('active');
		jQuery('.option-list-tab, .option-list-container').removeAttr('style');
		
		var windowHeight = jQuery(window).height();
		var holderHeight = jQuery('.product-options-wrapper-inner-box .product-optns').height();
		jQuery('.product-options-wrapper-inner-box .product-optns').css('top',(windowHeight - holderHeight)/2);
		
		jQuery('.customize-btn').find('.fa').removeClass('fa-chevron-up').addClass('fa-chevron-down');
	});
	
	//To update carat weight image
	jQuery('.user-option-metal-image').parent('.user-option-clickable').on('click',function(){
		var newCaratImageSrc = jQuery('#moreviews ul li:eq(0) img').attr('src');
		jQuery('.stone-holder-box .cwimage, .option-list-tab .user-option-image img').attr('src',newCaratImageSrc);
	});
</script>

<?php
//Start Google Code for Remarketing Tag
/*Remarketing tags may not be associated with personally identifiable information or placed on pages related to sensitive categories. See more information and instructions on how to setup the tag on: http://google.com/ads/remarketingsetup*/
if(($this->getRequest()->getControllerName() == 'cart' && $this->getRequest()->getModuleName() == 'checkout' && $this->getRequest()->getActionName() == 'index') || ($this->getRequest()->getControllerName() == 'index' && $this->getRequest()->getModuleName() == 'onepagecheckout' && $this->getRequest()->getActionName() == 'index')){  	
	$cartHelper = Mage::helper('checkout/cart')->getQuote();
	$baseGrandTotal = $cartHelper->getBaseGrandTotal();
	$items = $cartHelper->getAllVisibleItems();
	$skulist = '';
	foreach($items as $item) {
		if($item->getProduct()->getPrice() > 0) {
			$pro_skus = $item->getProduct()->getData('sku');
			//$_prod = Mage::getModel('catalog/product')->loadByAttribute('sku', $pro_skus);
			if($skulist == ''){
				$skulist = "'".$pro_skus."'";
			}
			else{
				$skulist .=",'".$pro_skus."'";
			}		
		}
	}?>
	<script type="text/javascript">
	var google_tag_params = {
	ecomm_prodid: [<?php echo $skulist; ?>],
	ecomm_pagetype: '<?php echo (($this->getRequest()->getControllerName() == 'cart' && $this->getRequest()->getModuleName() == 'checkout' && $this->getRequest()->getActionName() == 'index') ? "cart" : "checkout");?>',
	ecomm_totalvalue: <?php echo (($baseGrandTotal) ? $baseGrandTotal : 0); ?>
	};
	</script>
<?php
}
else if($this->getRequest()->getControllerName() == 'product' && $this->getRequest()->getModuleName() == 'catalog' && $this->getRequest()->getActionName() == 'view'){
	if($product = Mage::registry('current_product')){
		$sku = $product->getSku();
		$price = $product->getPrice(); ?>
		<script type="text/javascript">
		var google_tag_params = {
			ecomm_prodid: '<?php echo $sku; ?>',
			ecomm_pagetype: 'product',
			ecomm_totalvalue: <?php echo $price; ?>
		};
		</script>
	<?php
	}
}
else if($this->getRequest()->getControllerName() == 'category' && $this->getRequest()->getModuleName() == 'catalog' && $this->getRequest()->getActionName() == 'view'){
	if (Mage::registry('current_category')){
	  $catalogCategoryName = str_replace("'", "", trim(Mage::registry('current_category')->getName()));
	} ?>
	<script type="text/javascript">
	var google_tag_params = {
	ecomm_prodid: '',
	ecomm_pagetype: <?php echo (($catalogCategoryName) ? "'".$catalogCategoryName."'" : 'catalog');?>,
	ecomm_totalvalue: 0
	};
	</script>
<?php	
}
else if($this->getRequest()->getControllerName() == 'index' && $this->getRequest()->getModuleName() == 'cms' && $this->getRequest()->getActionName() == 'index'){?>
	<script type="text/javascript">
	var google_tag_params = {
	ecomm_prodid: '',
	ecomm_pagetype: 'home',
	ecomm_totalvalue: 0
	};
	</script>
<?php	
}
else if($this->getRequest()->getControllerName() == 'result' && $this->getRequest()->getModuleName() == 'catalogsearch' && $this->getRequest()->getActionName() == 'index'){?>
	<script type="text/javascript">
	var google_tag_params = {
	ecomm_prodid: '',
	ecomm_pagetype: 'searchresults',
	ecomm_totalvalue: 0
	};
	</script>
<?php	
}
else if($this->getRequest()->getControllerName() == 'account' && $this->getRequest()->getModuleName() == 'customer' && $this->getRequest()->getActionName() == 'create'){?>
	<script type="text/javascript">
	var google_tag_params = {
	ecomm_prodid: '',
	ecomm_pagetype: 'sign up',
	ecomm_totalvalue: 0
	};
	</script>
<?php	
}
else if($this->getRequest()->getControllerName() == 'account' && $this->getRequest()->getModuleName() == 'customer' && $this->getRequest()->getActionName() == 'login'){?>
	<script type="text/javascript">
	var google_tag_params = {
	ecomm_prodid: '',
	ecomm_pagetype: 'sign in',
	ecomm_totalvalue: 0
	};
	</script>
<?php	
}
else if($this->getRequest()->getControllerName() == 'account' && $this->getRequest()->getModuleName() == 'customer' && $this->getRequest()->getActionName() == 'index'){?>
	<script type="text/javascript">
	var google_tag_params = {
	ecomm_prodid: '',
	ecomm_pagetype: 'my account',
	ecomm_totalvalue: 0
	};
	</script>
<?php	
}
else if($this->getRequest()->getControllerName() == 'index' && $this->getRequest()->getModuleName() == 'wishlist' && $this->getRequest()->getActionName() == 'index'){?>
	<script type="text/javascript">
	var google_tag_params = {
	ecomm_prodid: '',
	ecomm_pagetype: 'wishlist',
	ecomm_totalvalue: 0
	};
	</script>
<?php	
}
else if($this->getRequest()->getControllerName() == 'index' && $this->getRequest()->getModuleName() == 'onepagecheckout' && $this->getRequest()->getActionName() == 'success'){
	$sOrderId = Mage::getSingleton('checkout/session')->getLastOrderId();
	$oOrder = Mage::getModel('sales/order')->load($sOrderId);
	
	$items = $oOrder->getAllVisibleItems();
	$skulist = '';
	foreach($items as $item) {
		if($item->getProduct()->getPrice() > 0) {
			$pro_skus = $item->getProduct()->getData('sku');
			//$_prod = Mage::getModel('catalog/product')->loadByAttribute('sku', $pro_skus);
			if($skulist == ''){
				$skulist = "'".$pro_skus."'";
			}
			else{
				$skulist .=",'".$pro_skus."'";
			}		
		}
	}?>
	<script type="text/javascript">
	var google_tag_params = {
	ecomm_prodid: [<?php echo $skulist; ?>],
	ecomm_pagetype: 'success',
	ecomm_totalvalue: <?php echo round($oOrder->getBaseSubtotal() + $oOrder->getBaseDiscountAmount(), 2); ?>
	};
	</script>
<?php
}
else if($this->getRequest()->getControllerName() == 'page' && $this->getRequest()->getModuleName() == 'cms' && $this->getRequest()->getActionName() == 'view'){?>
	<script type="text/javascript">
	var google_tag_params = {
	ecomm_prodid: '',
	ecomm_pagetype: 'cms',
	ecomm_totalvalue: 0
	};
	</script>
<?php
}
else{?>
	<script type="text/javascript">
	var google_tag_params = {
	ecomm_prodid: '',
	ecomm_pagetype: 'other',
	ecomm_totalvalue: 0
	};
	</script>
<?php
}?>
<script type="text/javascript">
/* <![CDATA[ */
	var google_conversion_id = 1064978809;
	var google_custom_params = window.google_tag_params;
	var google_remarketing_only = true;
	var google_conversion_format = 3;
/* ]]> */
</script>
<?php //$scripts[] = '//www.googleadservices.com/pagead/conversion.js';?>  
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js"></script>
<noscript>
	<div style="display:inline;">
		<img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/1064978809/?value=0&amp;guid=ON&amp;script=0"/>
	</div>
</noscript>
<?php //Google Code for Remarketing Tag

//Start Facebook Pixel Code ?>
<script>
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
document,'script','//connect.facebook.net/en_US/fbevents.js');

fbq('init', '583174048479877');
fbq('track', "PageView");

<?php 
if($product = Mage::registry('current_product')){	
	// Listen for 'AddToCart' event, and tag ?>
	jQuery('#addtocart-btn, #addtocart-btn-extra').click(function(e) {
		_fbq.push('track', 'AddToCart', {
			content_ids: ['<?php echo $product->getSku();?>'],
			content_type: 'product'
		});
	});
	
	<?php 
	// Listen for 'ViewContent' event, and tag 
	//$productObject = Mage::getModel('catalog/product')->load($product->getId()); 
	$productObject = Mage::getModel('catalog/product')->loadByAttribute('entity_id', $product->getId());
	$prodShDesc = str_replace("'", "", trim($productObject->getShortDescription()));
	$prodMasCat = str_replace("'", "", trim($product->getMasterCategory())); ?>
	_fbq('track', 'ViewContent', {
		content_name: '<?php echo $prodShDesc;?>',
  		content_category: '<?php echo $prodMasCat;?>',
		content_ids: ['<?php echo $product->getSku();?>'],
  		content_type: 'product',
		value: '<?php echo round($product->getPrice(), 2);?>',
		currency: 'USD'
 	});
<?php		
}

if($wishlistSku = Mage::getSingleton('core/session')->getWishlistProductSku()){	
	// Listen for 'AddToWishlist' event, and tag ?>
	_fbq.push('track', 'AddToWishlist', {
		content_ids: ['<?php echo $wishlistSku;?>'],
		content_type: 'product'
	});
<?php
Mage::getSingleton('core/session')->setWishlistProductSku('');
}
else if($this->getRequest()->getControllerName() == 'cart' && $this->getRequest()->getModuleName() == 'checkout' && $this->getRequest()->getActionName() == 'index'){   	
	$cartHelper = Mage::helper('checkout/cart');
	$items = $cartHelper->getCart()->getItems();
	$skulist = '';
	foreach($items as $item) {
		$isVisibleProduct = $item->getProduct()->isVisibleInSiteVisibility();
		if($item->getProduct()->getPrice() > 0 && $isVisibleProduct) {
			$pro_price = $item->getProduct()->getPrice();
			$pro_skus = $item->getProduct()->getData('sku');
			//$_prod = Mage::getModel('catalog/product')->loadByAttribute('sku', $pro_skus);
			if($skulist == ''){
				$skulist = "'".$pro_skus."'";
			}
			else{
				$skulist .=",'".$pro_skus."'";
			}					
		}
	}	
	// Listen for 'InitiateCheckout' event, and tag ?>
	jQuery('#cart-top-checkout-button, #cart-bottom-checkout-button').click(function(e) {
		_fbq.push('track', 'InitiateCheckout', {
			content_ids: [<?php echo $skulist; ?>],
			content_type: 'product'
		});
	});
<?php 
}
else if($this->getRequest()->getControllerName() == 'index' && $this->getRequest()->getModuleName() == 'onepagecheckout' && $this->getRequest()->getActionName() == 'success'){
	$sOrderId = Mage::getSingleton('checkout/session')->getLastOrderId();
	$oOrder = Mage::getModel('sales/order')->load($sOrderId);?>	
	_fbq.push('track', 'Purchase', {
		value: '<?php echo round($oOrder->getBaseSubtotal() + $oOrder->getBaseDiscountAmount(), 2); ?>', 
		currency: 'USD'
	});
<?php 
}?>	
</script>
<noscript><img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=583174048479877&ev=PageView&noscript=1"/></noscript>
<?php //End Facebook Pixel Code ?>

<?php //Start Twitter Pixel Code 
/*if(($this->getRequest()->getControllerName() == 'cart' && $this->getRequest()->getModuleName() == 'checkout' && $this->getRequest()->getActionName() == 'index') || ($this->getRequest()->getControllerName() == 'index' && $this->getRequest()->getModuleName() == 'onepagecheckout' && $this->getRequest()->getActionName() == 'success')){?>
	<script src="//platform.twitter.com/oct.js" type="text/javascript"></script>
<?php
}

if($this->getRequest()->getControllerName() == 'cart' && $this->getRequest()->getModuleName() == 'checkout' && $this->getRequest()->getActionName() == 'index'){
	$quote = Mage::getModel('checkout/cart')->getQuote();
	$pricelist = number_format($quote->getBaseSubtotalWithDiscount(), 2);
	$itemQty = (($quote->getItemsQty())?$quote->getItemsQty():0); ?>
	<script type="text/javascript">twttr.conversion.trackPid('nu379', { tw_sale_amount: '<?php echo $pricelist;?>', tw_order_quantity: <?php echo $itemQty;?> });</script>
	<noscript>
	<img height="1" width="1" style="display:none;" alt="" src="https://analytics.twitter.com/i/adsct?txn_id=nu379&p_id=Twitter&tw_sale_amount=<?php echo $pricelist;?>&tw_order_quantity=<?php echo $itemQty;?>" />
	<img height="1" width="1" style="display:none;" alt="" src="//t.co/i/adsct?txn_id=nu379&p_id=Twitter&tw_sale_amount=<?php echo $pricelist;?>&tw_order_quantity=<?php echo $itemQty;?>" />
	</noscript>
<?php
}
else if($this->getRequest()->getControllerName() == 'index' && $this->getRequest()->getModuleName() == 'onepagecheckout' && $this->getRequest()->getActionName() == 'success'){
	$sOrderId = Mage::getSingleton('checkout/session')->getLastOrderId();
	$oOrder = Mage::getModel('sales/order')->load($sOrderId); 
	$orderItemQty = (($oOrder->getTotalQtyOrdered())?$oOrder->getTotalQtyOrdered():0); ?>
	<script type="text/javascript">twttr.conversion.trackPid('nu315', { tw_sale_amount: '<?php echo round($oOrder->getBaseSubtotal() + $oOrder->getBaseDiscountAmount(), 2); ?>', tw_order_quantity: <?php echo $orderItemQty;?> });</script>
	<noscript>
	<img height="1" width="1" style="display:none;" alt="" src="https://analytics.twitter.com/i/adsct?txn_id=nu315&p_id=Twitter&tw_sale_amount=<?php echo round($oOrder->getBaseSubtotal() + $oOrder->getBaseDiscountAmount(), 2); ?>&tw_order_quantity=<?php echo $orderItemQty;?>" />
	<img height="1" width="1" style="display:none;" alt="" src="//t.co/i/adsct?txn_id=nu315&p_id=Twitter&tw_sale_amount=<?php echo round($oOrder->getBaseSubtotal() + $oOrder->getBaseDiscountAmount(), 2); ?>&tw_order_quantity=<?php echo $orderItemQty;?>" />
	</noscript>
<?php 
}*/?>
<?php //End Twitter Pixel Code ?>

<?php //Start Google Analytics ?>
<?php echo $this->getChildHtml('google_analytics');?>
<?php //End Google Analytics ?>

<script type="text/javascript">
setTimeout(function(){var a=document.createElement("script");
var b=document.getElementsByTagName("script")[0];
a.src=document.location.protocol+"//script.crazyegg.com/pages/scripts/0052/0819.js?"+Math.floor(new Date().getTime()/3600000);
a.async=true;a.type="text/javascript";b.parentNode.insertBefore(a,b)}, 1);
</script>






<?php //code added by ashwani ?>
<?php 
$pageType = Mage::helper('function')->getPageType();

$offerText	=	Mage::helper('function')->getOfferText();
if($offerText && ($pageType == "home" || $pageType == "category")){ ?>
	
	<?php
	$channel = Mage::getSingleton('core/session')->getVisitorChannel(); 
	$bannerMobile = Mage::getModel('promotions/banner')->load($channel->getCatalogBannerMobile());	 
	if(!$channel->getCatalogBannerMobile()){ ?>
		<style>
			body{margin-bottom:30px;}
			<?php if($pageType == "category"){ ?>
				#go-to-top-link{bottom:40px!important; right:0px!important}
			<?php } ?>
		</style>
		<?php
		$offerData 		= 	$this->getLayout()->createBlock('promotions/offer')->getOfferHeaderImage();
		$image_path		=	$offerData['image_path'];
		$image_title	=	$offerData['image_title'];
		$image_alt_text	=	$offerData['image_alt_text']; 
		?>
		<div class="clickable" id="exclusive-offer-footer-opener" style="position:fixed; bottom:-1px; left:0px; right:0px; background:#ffffff; z-index:1">		  	 
			<div class="offer-text-holder" style="font-size:14px;height:34px;line-height:34px;padding-left:5px;background:#fa505a; color:#ffffff;"><?php echo $offerText;?><span class="fr"><i style="font-size:20px;" class="fa fa-fw fa-angle-up"> </i></span></div>
			<img src="<?php echo $image_path;?>" alt="<?php echo $image_alt_text;?>" title="<?php echo $image_title;?>" class="img-responsive" style="display:none; width:50%; padding:0 25%;"/>
		</div>
		<script>
			jQuery(function(){
				jQuery('#exclusive-offer-footer-opener').click(function(){
					jQuery(this).find('img').slideToggle(100);
					jQuery('.fa-angle-up, .fa-angle-donw').toggleClass('.fa-angle-up .fa-angle-donw');
				});
			});
		</script>
	<?php 
	}
} ?>
<?php //code added by ashwani ?>

<div class="notify-me text-center" style="">
	<div class="notify-me-inner" style="">
		<span class="text pull-left"></span>
		<?php /* <span class="close pull-right" onclick="jQuery(this).parents('.notify-me').removeAttr('style');"><i class="fa fa-times-circle"></i></span> */ ?>
	</div>
</div>

<?php
/* S: Integrate Criteo */?>
<script type="text/javascript" src="//static.criteo.net/js/ld/ld.js" async="true"></script>
<?php
if(($this->getRequest()->getControllerName() == 'cart' && $this->getRequest()->getModuleName() == 'checkout' && $this->getRequest()->getActionName() == 'index')){ 	
	$cartHelper = Mage::helper('checkout/cart')->getQuote();
	$items = $cartHelper->getAllVisibleItems();
	$itemList = '';
	foreach($items as $item) {
		if($item->getProduct()->getPrice() > 0) {
			$itemProdSku = $item->getProduct()->getData('sku');
			$itemPrice = round($item->getPrice(), 2);
			$itemQty = $item->getQty();
			if($itemList == ''){
				$itemList = '{ id: "'.$itemProdSku.'", price: '.$itemPrice.', quantity: '.$itemQty.' }';
			}
			else{
				$itemList .= ',{ id: "'.$itemProdSku.'", price: '.$itemPrice.', quantity: '.$itemQty.' }';
			}		
		}
	}?>
	<script type="text/javascript">
	window.criteo_q = window.criteo_q || [];
	window.criteo_q.push(
		{ event: "setAccount", account: 32612 },
		{ event: "setEmail", email: "" },
		{ event: "setSiteType", type: "m" },
		{ event: "viewBasket", item: [ <?php echo $itemList;?> ]}
	);
	</script>
<?php
}
else if($this->getRequest()->getControllerName() == 'index' && $this->getRequest()->getModuleName() == 'onepagecheckout' && $this->getRequest()->getActionName() == 'success'){
	$orderId = Mage::getSingleton('checkout/session')->getLastRealOrderId();
	$oOrder = Mage::getModel('sales/order')->loadByIncrementId($orderId);
	
	$items = $oOrder->getAllVisibleItems();
	$itemList = '';
	foreach($items as $item) {
		if($item->getProduct()->getPrice() > 0) {
			$itemProdSku = $item->getProduct()->getData('sku');
			$itemPrice = round($item->getPrice(), 2);
			$itemQty = round($item->getQtyOrdered());
			
			$itemDiscountedPrice = ($itemPrice * $itemQty) - (($itemPrice * $itemQty) * 15/100);
			if($itemList == ''){
				$itemList = '{ id: "'.$itemProdSku.'", price: '.$itemDiscountedPrice.', quantity: '.(($itemQty)?$itemQty:0).' }';
			}
			else{
				$itemList .= ',{ id: "'.$itemProdSku.'", price: '.$itemDiscountedPrice.', quantity: '.(($itemQty)?$itemQty:0).' }';
			}
		}
	}?>
	<script type="text/javascript">
	window.criteo_q = window.criteo_q || [];
	window.criteo_q.push(
		{ event: "setAccount", account: 32612 },
		{ event: "setEmail", email: "" },
		{ event: "setSiteType", type: "m" },
		{ event: "trackTransaction", id: "<?php echo $orderId; ?>", item: [ <?php echo $itemList;?> ]}
	);
	</script>
<?php 
}
else if($this->getRequest()->getControllerName() == 'product' && $this->getRequest()->getModuleName() == 'catalog' && $this->getRequest()->getActionName() == 'view'){
	if($product = Mage::registry('current_product')){
		$productSku = $product->getSku();?>
		<script type="text/javascript">
		window.criteo_q = window.criteo_q || [];
		window.criteo_q.push(
			{ event: "setAccount", account: 32612 },
			{ event: "setEmail", email: "" },
			{ event: "setSiteType", type: "m" },
			{ event: "viewItem", item: "<?php echo $productSku; ?>" }
		);
		</script>
	<?php
	}
}
else if($this->getRequest()->getControllerName() == 'category' && $this->getRequest()->getModuleName() == 'catalog' && $this->getRequest()->getActionName() == 'view'){
	if(Mage::registry('itemList')){	
		$itemList = Mage::registry('itemList');
		$itemListDetails == '';
		foreach($itemList as $product){
			if($itemListDetails == ''){
				$itemListDetails = '"'.$product.'"';
			}
			else{
				$itemListDetails .= ',"'.$product.'"';
			}
		}
	Mage::unregister('itemList');	
	} ?>
	<script type="text/javascript">
	window.criteo_q = window.criteo_q || [];
	window.criteo_q.push(
		{ event: "setAccount", account: 32612 },
		{ event: "setEmail", email: "" },
		{ event: "setSiteType", type: "m" },
		{ event: "viewList", item:[ <?php echo $itemListDetails; ?> ]}
	);
	</script>
<?php	
}
else if($this->getRequest()->getControllerName() == 'index' && $this->getRequest()->getModuleName() == 'cms' && $this->getRequest()->getActionName() == 'index'){?>
	<script type="text/javascript">
	window.criteo_q = window.criteo_q || [];
	window.criteo_q.push(
		{ event: "setAccount", account: 32612 },
		{ event: "setEmail", email: "" },
		{ event: "setSiteType", type: "m" },
		{ event: "viewHome" }
	);
	</script>
<?php	
}
/* E: Integrate Criteo */?>
