<meta property="fb:app_id" content=118485508205347 />
<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />
<title>
<?php
//echo $this->getTitle()
$title=$this->getTitle();
$flag=0;

if(Mage::registry('current_product')) 
{
	if(Mage::registry('current_product')->getTitleSuffix())
	{
		$title.=' '.Mage::registry('current_product')->getTitleSuffix();
		$flag=1;
	}
}
else if(Mage::registry('current_category'))
{
	if(Mage::registry('current_category')->getTitleSuffix())
	{
		$title.=' '.Mage::registry('current_category')->getTitleSuffix();
		$flag=1;
	}
}
else if(Mage::app()->getRequest()->getRouteName()=='cms')
{	
	if(Mage::getSingleton('cms/page')->getTitleSuffix())
	{
		$title.=' '.Mage::getSingleton('cms/page')->getTitleSuffix();
		$flag=1;
	}
}

if ($flag==0)
{
   echo $title.' | Angara';
}
else
{	
	echo $title;
} ?></title>
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
<?php /*<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />*/?>
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />
<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=no">
<link rel="icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<?php header("Vary: User-Agent");?>
<?php echo $this->getCssJsHtml() ?>
<?php echo $this->getChildHtml() ?>
<?php echo $this->helper('core/js')->getTranslatorScript() ?>
<?php echo $this->getIncludes() ?>
<?php
// s: google crawlable pagination prev & next code.
$pages = Mage::helper('page/data')->getPages();
$pageType = Mage::helper('function')->getPageType();
$current_page = Mage::helper('page/data')->getCurrentPage();   
$currentUrl = Mage::helper('page/data')->explodeCurrentUrl();
$nextUrl = Mage::helper('page/data')->getNextPageUrl($currentUrl[0],$current_page);
$prevUrl = Mage::helper('page/data')->getPrevPageUrl($currentUrl[0],$current_page);
$lastString	= substr($currentUrl[0], strlen($currentUrl[0])-1, strlen($currentUrl[0]));
$currentUrlString = $currentUrl[0];
if($lastString=='/'){
	$currentUrlString = substr($currentUrl[0],0,-1);
}

if($pageType == 'category' || $pageType == 'catalogsearch'){
	if($current_page == 1){ ?>
		<link rel="next" href="<?php echo $nextUrl?>"/>
	<?php 
	} else if(($pages - $current_page) > 0 && $current_page > 2){?>
		<link rel="prev" href="<?php echo $prevUrl?>"/>
		<link rel="next" href="<?php echo $nextUrl?>"/>
	<?php 
	} else if(($pages - $current_page) > 0 && $current_page == 2){?>
		<link rel="prev" href="<?php echo $currentUrlString;?>"/>
		<link rel="next" href="<?php echo $nextUrl?>"/>
	<?php 
	} else if(($pages > 1)&& $pages == $current_page){?>
		<link rel="prev" href="<?php echo $prevUrl?>"/>
	<?php 
	}
}
// s: google crawlable pagination prev & next code. ?>
<link rel="dns-prefetch" href="http://cdn.angara.com">
<link rel="dns-prefetch" href="http://payments.amazon.com">
<link rel="dns-prefetch" href="http://facebook.com">
<link rel="dns-prefetch" href="http://angara.tt.omtrdc.net">
<link rel="dns-prefetch" href="http://images-na.ssl-images-amazon.com">
<link rel="dns-prefetch" href="http://nsg.symantec.com">
<link rel="dns-prefetch" href="http://server.iad.liveperson.net">
<link rel="dns-prefetch" href="http://seal-sanjose.bbb.org">
<link rel="dns-prefetch" href="http://google-analytics.com">
<link rel="dns-prefetch" href="http://seal.websecurity.norton.com">
<link rel="dns-prefetch" href="http://googleads.g.doubleclick.net">
<link rel="dns-prefetch" href="http://googleadservices.com">
<link rel="dns-prefetch" href="http://medals.bizrate.com">
<link rel="dns-prefetch" href="http://google.com">
<link rel="dns-prefetch" href="http://d2lo2tipcl3aii.cloudfront.net">
<link rel="dns-prefetch" href="http://metrics.angara.com">
<link rel="dns-prefetch" href="http://seal.verisign.com">
<link rel="dns-prefetch" href="http://s-static.ak.facebook.com">
<link rel="dns-prefetch" href="http://connect.facebook.net">
<link rel="dns-prefetch" href="http://static.ak.facebook.com">
<?php 
$product = Mage::registry('current_product');
if($product) {
	if($product->getId() && $product->getTypeId() == 'configurable'){	
		if($product->hasTrioSku() && strlen($product->getTrioSku()) > 0){
			$block = Mage::getBlockSingleton('Ayasoftware_SimpleProductPricing_Catalog_Block_Product_View_Type_Configurable')->setProduct($product);
		} else { 
			$block = Mage::getBlockSingleton('Mage_Catalog_Block_Product_View_Type_Configurable')->setProduct($product);
		}
		$block->getJsonConfig();
		$selectedProduct = Mage::registry('current_selected_product');
		$product->setPrice($selectedProduct->getPrice());
		$product->setFinalPrice($selectedProduct->getFinalPrice());
		$product->setMsrp($selectedProduct->getMsrp());
		$product->setImage($selectedProduct->getImage());
		$product->setMediaGalleryImages($selectedProduct->getMediaGalleryImages());
		Mage::unregister('current_product');
		Mage::register('current_product',$product);
	}
	else {
		$selectedProduct = $product;
	}	

	$_coreHelper = $this->helper('core');
	$socialDescription = htmlspecialchars(trim(Mage::helper('core')->stripTags($selectedProduct->getDescription())));
	if(!$socialDescription){
		$socialDescription = htmlspecialchars($selectedProduct->getMetaTitle()); 
	}	
	if(!$socialDescription){
		$socialDescription = htmlspecialchars($selectedProduct->getShortDescription()); 
	}?>
<meta property="og:site_name" content="Angara" />
<meta property="og:title" content="<?php echo $selectedProduct->getShortDescription(); ?>" />
<meta property="og:description" content="<?php echo $socialDescription; ?>" />
<meta property="og:url" content="<?php echo $selectedProduct->getProductUrl();?>" />
<meta property="og:type" content="product" />
<meta property="og:image" content="<?php echo Mage::getBaseUrl().'media/catalog/product'.$selectedProduct->getImage();?>" />
<meta property="og:price:amount" content="<?php echo $_coreHelper->currency($this->htmlEscape($selectedProduct->getPrice()),true,false); ?>" />
<meta property="og:price:standard_amount" content="<?php echo $_coreHelper->currency($this->htmlEscape($selectedProduct->getMsrp()),true,false); ?>" />
<meta property="og:price:currency" content="<?php echo Mage::app()->getStore()->getCurrentCurrencyCode(); ?>" />
<meta property="og:availability" content="instock" />
<meta name="twitter:card" content="product" />
<meta name="twitter:site" content="@Angara" />
<meta name="twitter:title" content="<?php echo $selectedProduct->getShortDescription(); ?>" />
<meta name="twitter:description" content="<?php echo $socialDescription; ?>" />
<meta name="twitter:creator" content="@Angara" />
<meta name="twitter:url" content="<?php echo $selectedProduct->getProductUrl();?>" />
<meta name="twitter:image" content="<?php echo Mage::getBaseUrl().'media/catalog/product'.$selectedProduct->getImage();?>" />
<meta name="twitter:image:width" content="200" />
<meta name="twitter:data1" content="<?php echo $_coreHelper->currency($this->htmlEscape($selectedProduct->getPrice()),true,false);?>" />
<meta name="twitter:label1" content="Price" />
<meta name="twitter:data2" content="<?php echo $product->getSku();?>" />
<meta name="twitter:label2" content="SKU" />
<?php	
}
else{
	$urlCurrent = Mage::helper('core/url')->getCurrentUrl();?>
<meta property="og:site_name" content="Angara" />
<meta property="og:type" content="website" />
<meta property="og:url" content="<?php echo $urlCurrent;?>" />
<meta property="og:title" content="<?php echo $title;?>" />
<meta property="og:description" content="<?php echo trim($this->getDescription());?>" />

<meta name="twitter:card" content="website">
<meta name="twitter:site" content="@Angara">
<meta name="twitter:title" content="<?php echo $title;?>">
<meta name="twitter:description" content="<?php echo trim($this->getDescription());?>">
<meta name="twitter:url" content="<?php echo $urlCurrent;?>" />
<?php	
} ?>
<script type="application/javascript">(function(w,d,t,r,u){w[u]=w[u]||[];w[u].push({'projectId':'10000','properties':{'pixelId':'37535'}});var s=d.createElement(t);s.src=r;s.async=true;s.onload=s.onreadystatechange=function(){var y,rs=this.readyState,c=w[u];if(rs&&rs!="complete"&&rs!="loaded"){return}try{y=YAHOO.ywa.I13N.fireBeacon;w[u]=[];w[u].push=function(p){y([p])};y(c)}catch(e){}};var scr=d.getElementsByTagName(t)[0],par=scr.parentNode;par.insertBefore(s,scr)})(window,document,"script","https://s.yimg.com/wi/ytc.js","dotq");</script>

<?php
if($pageType == 'home'){?>
	<script type="application/ld+json">
	{
		<?php // site search ?>
		"@context"	: "http://schema.org",
		"@type"		: "WebSite",
		"url"		: "<?php echo Mage::getBaseUrl();?>",
		"potentialAction": {
			"@type"		: "SearchAction",
			"target"	: "<?php echo Mage::getBaseUrl();?>catalogsearch/result/?q={search_term_string}",
			"query-input"	: "required name=search_term_string"
		},
		<?php // customer service ?>
		"@type" 	: "Organization",
		"name" 		: "Angara",
		"url" 		: "<?php echo Mage::getBaseUrl();?>",
		"legalName"	: "Angara INC",
		"logo" 		: "<?php echo Mage::getBaseUrl();?>skin/frontend/ress/default/images/logo.png",
		"brand"		: "Angara",
		"description"	: "<?php echo htmlspecialchars($this->getDescription())?>",
		"contactPoint" 	: [{
			"@type" 	: "ContactPoint",
			"telephone"	: "+1-888-926-4272",
			"contactType" : "customer service"
		}],
		"location": [
		{
		  "@type": "PostalAddress",
		  "streetAddress": "550 South Hill St, Suite 1015",
		  "addressLocality": "Los Angeles",
		  "addressRegion": "CA",
		  "postalCode": "90013"
		}],
		<?php // social profiles ?>
		"sameAs" : [
			"https://www.facebook.com/Angaradotcom",
			"https://twitter.com/angara",
			"https://plus.google.com/+Angara",
			"http://www.youtube.com/user/angarainc",
			"https://www.pinterest.com/angarajewelry"
		]	
	}
	</script>
<?php 
}?>	