<?php
/**
 * Top menu for store
 *
 * @see Mage_Page_Block_Html_Topmenu
 */
?>
<ul class="level0">
    <li class="level0">
        <a  class="level0" href="javascript:void(0)">Rings <i class="fa fa-plus"></i></a>
        <ul class="level1">
            <li class="level1">
                <a class="level1" href="javascript:void(0)">Shop By Colored Gemstone<i class="fa fa-plus"></i></a>
                <ul class="level2">
					<li class="level2" >
						<a href="/rings/sapphire-rings" onclick="categoryNavSelect('Sapphire Rings|topnav')">Sapphire</a>
					</li>
					<li class="level2" >
						<a href="/rings/ruby-rings" onclick="categoryNavSelect('Ruby Rings|topnav')">Ruby</a>
					</li>
					<li class="level2" >
						<a href="/rings/emerald-rings" onclick="categoryNavSelect('Emerald Rings|topnav')">Emerald</a>
					</li>
					<li class="level2" >
						<a href="/rings/tanzanite-rings" onclick="categoryNavSelect('Tanzanite Rings|topnav')">Tanzanite</a>
					</li>
					<li class="level2" >
						<a href="/rings/aquamarine-rings" onclick="categoryNavSelect('Aquamarine Rings|topnav')">Aquamarine</a>
					</li>
					<li class="level2 view-more">
                        <a href="javascript:void(0)">More +</a>
                    </li>
					<li class="level2" >
						<a href="/rings/blue-topaz-rings" onclick="categoryNavSelect('Blue Topaz Rings|topnav')">Blue Topaz</a>
					</li>
					<li class="level2" >
						<a href="/rings/black-onyx-rings" onclick="categoryNavSelect('Black Onyx Rings|topnav')">Black Onyx</a>
					</li>
					<li class="level2" >
						<a href="/rings/citrine-rings" onclick="categoryNavSelect('Citrine Rings|topnav')">Citrine</a>
					</li>
					<li class="level2" >
						<a href="/rings/pearl-rings" onclick="categoryNavSelect('Pearl Rings|topnav')">Pearl</a>
					</li>
					<li class="level2" >
						<a href="/rings/morganite-rings" onclick="categoryNavSelect('Morganite Rings|topnav')">Morganite</a>
					</li>
					<li class="level2" >
						<a href="/rings/garnet-rings" onclick="categoryNavSelect('Garnet Rings|topnav')">Garnet</a>
					</li>
					<li class="level2" >
						<a href="/rings/opal-rings" onclick="categoryNavSelect('Opal Rings|topnav')">Opal</a>
					</li> 
					<li class="level2" >
						<a href="/rings/amethyst-rings" onclick="categoryNavSelect('Amethyst Rings|topnav')">Amethyst</a>
					</li>
					<li class="level2" >
						<a href="/rings/peridot-rings" onclick="categoryNavSelect('Peridot Rings|topnav')">Peridot</a>
					</li>	
					<li class="level2" >
						<a href="/rings/pink-tourmaline-rings" onclick="categoryNavSelect('Pink Tourmaline Rings|topnav')">Pink Tourmaline</a>
					</li>
					<li class="level2" >
						<a href="/rings/moissanite-rings" onclick="categoryNavSelect('Moissanite Rings|topnav')">Moissanite</a>
					</li>
					<li class="level2" >
						<a href="/lab-jewelry/lab-created-sapphire-rings" onclick="categoryNavSelect('Lab Created Sapphire Rings|topnav')">Lab Created Sapphire</a>
					</li>
					<li class="level2" >
						<a href="/lab-jewelry/lab-created-emerald-rings" onclick="categoryNavSelect('Lab Created Emerald Rings|topnav')">Lab Created Emerald</a>
					</li>
					<li class="level2" >
						<a href="/lab-jewelry/lab-created-ruby-rings" onclick="categoryNavSelect('Lab Created Ruby Rings|topnav')">Lab Created Ruby</a>
					</li>
                </ul>
            </li>
			<li class="level1">
                <a class="level1" href="javascript:void(0)">Shop By Diamond<i class="fa fa-plus"></i></a>
                <ul class="level2">
                    <li class="ie8-remove level2">
						<a href="/buildyourown/ring?userStartWithPreference=diamonds" onclick="categoryNavSelect('Design Your Own Diamond Ring|topnav')">Design Your Own Diamond Ring</a>
					</li>
					<li class="level2">
						<a href="/rings/diamond-rings" onclick="categoryNavSelect('Diamond Rings|topnav')">Diamond</a>
					</li>
					<li class="level2">
						<a href="/rings/colored-diamond-rings/enhanced-blue-diamond" onclick="categoryNavSelect('Blue Diamond Rings|topnav')">Blue Diamond</a>
					</li>
					<li class="level2">
						<a href="/rings/colored-diamond-rings/enhanced-black-diamond" onclick="categoryNavSelect('Black Diamond Rings|topnav')">Black Diamond</a>
					</li>
					<li class="level2">
						<a href="/rings/coffee-diamond-rings" onclick="categoryNavSelect('Coffee Diamond Rings|topnav')">Coffee Diamond</a>
					</li>
                </ul>
            </li>
            <li class="level1">
                <a class="level1" href="javascript:void(0)">Shop By Style <i class="fa fa-plus"></i></a>
                <ul class="level2">
					<li class="level2" >
						<a href="/engagement-rings/halo-rings" onclick="categoryNavSelect('Halo Rings|topnav')">Halo</a>
					</li>
					<li class="level2" >
						<a href="/rings/eternity-rings" onclick="categoryNavSelect('Eternity Rings|topnav')">Eternity</a>
					</li>
					<li class="level2" >
						<a href="/engagement-rings/solitaire-rings" onclick="categoryNavSelect('Solitaire Rings|topnav')">Solitaire</a>
					</li>
					<li class="level2" >
						<a href="/engagement-rings/three-stone-rings" onclick="categoryNavSelect('Three Stone Rings|topnav')">Three Stone</a>
					</li>
					<li class="level2" >
						<a href="/collection/stackables" onclick="categoryNavSelect('Stackables Rings|topnav')">Stackables</a>
					</li>
					<li class="level2" >
						<a href="/collection/vintage" onclick="categoryNavSelect('Vintage Rings|topnav')">Vintage</a>
					</li>
					<li class="level2" >
						<a href="/rings/heart-rings"  onclick="categoryNavSelect('Hearts Rings|topnav')">Heart</a>
					</li>
					<li class="level2" >
						<a href="https://www.angara.com/rings?jewelry_styles=5944&amp;dir=asc" onclick="categoryNavSelect('Knot Rings|topnav')">Knot</a>
					</li>
					<li class="level2" >
						<a href="/rings?order=position&amp;dir=asc&amp;no_cache=true&amp;jewelry_styles=4181" onclick="categoryNavSelect('Five Stone Rings|topnav')">Five Stone</a>
					</li>
					<li class="level2" >
						<a href="/rings/split-shank-rings" onclick="categoryNavSelect('Split Shank Rings|topnav')">Split Shank</a>
					</li>
					<?php /* <li class="level2" ><a href="/jewelry/illusion-set-diamonds" onclick="categoryNavSelect('Illusion Set Rings|topnav')">Illusion Set</a>
					</li> */?>
					<li class="level2" >
						<a href="/mothers-jewelry/mother-rings" onclick="categoryNavSelect('Mothers Rings|topnav')">Mother's</a>
					</li>
					<li class="level2" >
						<a href="/birthstone-jewelry/birthstone-rings" onclick="categoryNavSelect('Birthstone Rings|topnav')">Birthstone</a>
					</li>
                </ul>
            </li>
            <li class="level1">
                <a class="level1" href="javascript:void(0)">Shop By Price <i class="fa fa-plus"></i></a>
                <ul class="level2">
                    <li class="level2">
                    <a href="/rings?content=no&dir=asc&order=price&p=1&price=1,250" onclick="categoryNavSelect('$250 & Under Rings|topnav')">$250 & Under</a>	
                    </li>
                    <li class="level2">
                    <a href="/rings?content=no&dir=asc&order=price&p=1&price=251,500" onclick="categoryNavSelect('$251 - $500 Rings|topnav')">$251 - $500</a>
                    </li>
                    <li class="level2">
                    <a href="/rings?content=no&dir=asc&order=price&p=1&price=501,1000" onclick="categoryNavSelect('$501 - $1000 Rings|topnav')">$501 - $1000</a>
                    </li>
                    <li class="level2">
                    <a href="/rings?content=no&dir=asc&order=price&p=1&price=1001,1500" onclick="categoryNavSelect('$1001 - $1500 Rings|topnav')">$1001 - $1500</a>
                    </li>
                    <li class="level2">
                    <a href="/rings?content=no&dir=asc&order=price&p=1&price=1501,2500" onclick="categoryNavSelect('$1501 - $2500 Rings|topnav')">$1501 - $2500</a>
                    </li><li class="level2">
                    <a href="/rings?content=no&dir=asc&order=price&p=1&price=2501,99999" onclick="categoryNavSelect('Over $2500 Rings|topnav')">Over $2500</a>
                    </li>
                </ul>
            </li>
            <li class="level1 view-all">
                <a href="/rings" class="no-transition" onclick="categoryNavSelect('Rings|topnav')">View All <i class="fa fa-chevron-right"></i></a>
            </li>
        </ul>
    </li>
    
    <!--necklaces categories starts-->
    <li class="level0">
        <a  class="level0" href="javascript:void(0)">Necklaces <i class="fa fa-plus"></i></a>
        <ul class="level1">
            <li class="level1">
                <a class="level1" href="javascript:void(0)">Shop By Colored Gemstone <i class="fa fa-plus"></i></a>
                <ul class="level2">
                   <li class="level2" >
						<a href="/pendants/sapphire-necklace-pendants" onclick="categoryNavSelect('Sapphire Necklaces|topnav')">Sapphire</a>
					</li>
					<li class="level2" >
						<a href="/pendants/ruby-necklace-pendants" onclick="categoryNavSelect('Ruby Necklaces|topnav')">Ruby</a>
					</li>
					<li class="level2" >
						<a href="/pendants/emerald-necklace-pendants" onclick="categoryNavSelect('Emerald Necklaces|topnav')">Emerald</a>
					</li>
					<li class="level2" >
						<a href="/pendants/tanzanite-necklace-pendants" onclick="categoryNavSelect('Tanzanite Necklaces|topnav')">Tanzanite</a>
					</li>
					<li class="level2" >
						<a href="/pendants/aquamarine-necklace-pendants" onclick="categoryNavSelect('Aquamarine Necklaces|topnav')">Aquamarine</a>
					</li>
					<li class="level2" >
						<a href="/pendants/blue-topaz-necklace-pendants" onclick="categoryNavSelect('Blue Topaz Necklaces|topnav')">Blue Topaz</a>
					</li>
					<li class="level2 view-more">
                        <a href="javascript:void(0)">More +</a>
                    </li>
					<li class="level2" >
						<a href="/pendants/black-onyx-necklace-pendants" onclick="categoryNavSelect('Black Onyx Necklaces|topnav')">Black Onyx</a>
					</li>
					<li class="level2" >
						<a href="/pendants/citrine-necklace-pendants" onclick="categoryNavSelect('Citrine Necklaces|topnav')">Citrine</a>
					</li>
					<li class="level2" >
						<a href="/pendants/pearl-necklace-pendants" onclick="categoryNavSelect('Pearl Necklaces|topnav')">Pearl</a>
					</li>
					<li class="level2" >
						<a href="/pendants/morganite-necklace-pendants" onclick="categoryNavSelect('Morganite Necklaces|topnav')">Morganite</a>
					</li>
					<li class="level2" >
						<a href="/pendants/garnet-necklace-pendants" onclick="categoryNavSelect('Garnet Necklaces|topnav')">Garnet</a>
					</li>
					<li class="level2" >
						<a href="/pendants/opal-necklace-pendants" onclick="categoryNavSelect('Opal Necklaces|topnav')">Opal</a>
					</li>
					<li class="level2" >
						<a href="/pendants/amethyst-necklace-pendants" onclick="categoryNavSelect('Amethyst Necklaces|topnav')">Amethyst</a>
					</li>
					<li class="level2" >
						<a href="/pendants/peridot-necklace-pendants" onclick="categoryNavSelect('Peridot Necklaces|topnav')">Peridot</a>
					</li>
					<li class="level2" >
						<a href="/pendants/pink-tourmaline-necklace-pendants" onclick="categoryNavSelect('Pink Tourmaline Necklaces|topnav')">Pink Tourmaline</a>
					</li>
					<li class="level2" >
						<a href="/pendants/moissanite-necklace-pendants" onclick="categoryNavSelect('Moissanite Necklaces|topnav')">Moissanite</a>
					</li>
					<li class="level2" >
						<a href="/lab-jewelry/lab-created-sapphire-necklace-pendants" onclick="categoryNavSelect('Lab Created Necklaces|topnav')">Lab Created Sapphire</a>
					</li>
					<li class="level2" >
						<a href="/lab-jewelry/lab-created-emerald-necklace-pendants" onclick="categoryNavSelect('Lab Created Necklaces|topnav')">Lab Created Emerald</a>
					</li>
					<li class="level2" >
						<a href="/lab-jewelry/lab-created-ruby-necklace-pendants" onclick="categoryNavSelect('Lab Created Necklaces|topnav')">Lab Created Ruby</a>
					</li>
                </ul>
            </li>
			<li class="level1">
                <a class="level1" href="javascript:void(0)">Shop By Diamond<i class="fa fa-plus"></i></a>
                <ul class="level2">
                    <li class="ie8-remove level2">
						<a href="/buildyourown/pendant?userStartWithPreference=diamonds" onclick="categoryNavSelect('Design Your Own Diamond Pendant|topnav')">Design Your Own Diamond Pendant</a>
					</li>
					<li class="level2">
						<a href="/pendants/diamond-necklace-pendants" onclick="categoryNavSelect('Diamond Necklaces|topnav')">Diamond</a>
					</li>
					<li class="level2">
						<a href="/pendants/colored-diamond-necklace-pendants/enhanced-blue-diamond" onclick="categoryNavSelect('Blue Diamond Necklace|topnav')">Blue Diamond</a>
					</li>
					<li class="level2">
						<a href="/pendants/colored-diamond-necklace-pendants/enhanced-black-diamond" onclick="categoryNavSelect('Black Diamond Necklace|topnav')">Black Diamond</a>
					</li>
					<li class="level2">
						<a href="/pendants/coffee-diamond-pendant-necklaces" onclick="categoryNavSelect('Coffee Diamond Necklace|topnav')">Coffee Diamond</a>
					</li>
                </ul>
            </li>
            <li class="level1">
                <a class="level1" href="javascript:void(0)">Shop By Style <i class="fa fa-plus"></i></a>
                <ul class="level2">
                    <li class="level2">
                        <a href="/pendants?order=position&dir=asc&no_cache=true&jewelry_styles=4183" onclick="categoryNavSelect('Halo Necklaces|topnav')">Halo</a>	
                    </li>
                    <li class="level2">
                        <a href="/pendants/v-bale-pendants" onclick="categoryNavSelect('V-Bale Necklaces|topnav')">V-Bale</a>
                    </li>
                    <li class="level2">
                    <a href="/pendants/solitaire-necklace-pendants" onclick="categoryNavSelect('Solitaire Necklaces|topnav')">Solitaire</a>	
                    </li>
                    <li class="level2">
                    <a href="/pendants?order=position&dir=asc&no_cache=true&jewelry_styles=4176" onclick="categoryNavSelect('Dangle Necklaces|topnav')">Dangle</a>	
                    </li>
                    <li class="level2">
                    <a href="/pendants/journey-necklace-pendants" onclick="categoryNavSelect('Journey Necklaces|topnav')">Journey</a>	
                    </li>
                    <li class="level2">
                    <a href="/pendants/cross-necklace-pendants" onclick="categoryNavSelect('Crosses Necklaces|topnav')">Crosses</a>	
                    </li>
                    <?php /* <li class="level2">
                    <a href="/pendants/fashion-necklace-pendants" onclick="categoryNavSelect('Fashion Necklaces|topnav')">Fashion</a>	
                    </li> */ ?>
					<li class="level2">
						<a href="/pendants/heart-necklace-pendants" onclick="categoryNavSelect('Heart Necklaces|topnav')">Heart</a>
					</li>
					<li class="level2">
						<a href="/pendants?jewelry_styles=5944&amp;dir=asc" onclick="categoryNavSelect('Knot Necklaces|topnav')">Knot</a>
					</li>
					<li class="level2">
						<a href="/pendants?jewelry_styles=4172"  onclick="categoryNavSelect('Cluster Necklaces|topnav')">Cluster</a>
					</li>
					<li class="level2">
						<a href="/collection/facets" onclick="categoryNavSelect('Matching Set|topnav')">Matching Set</a>
					</li>
					<li class="level2">
						<a href="/jewelry/dancing-gemstone-jewelry" onclick="categoryNavSelect('Dancing Diamonds|topnav')">Dancing Gemstones</a>
					</li>
					<li class="level2">
						<a href="/birthstone-jewelry/birthstone-pendants" onclick="categoryNavSelect('Birthstone Necklaces|topnav')">Birthstone</a>
					</li>
                </ul>
            </li>
            <li class="level1">
                <a class="level1" href="javascript:void(0)">Shop By Price <i class="fa fa-plus"></i></a>
                <ul class="level2">
                    <li class="level2">
                        <a href="/pendants?content=no&dir=asc&order=price&p=1&price=1,250" onclick="categoryNavSelect('$250 & Under Necklaces|topnav')">$250 & Under</a>
                    </li>
                    <li class="level2">
                    <a href="/pendants?content=no&dir=asc&order=price&p=1&price=251,500" onclick="categoryNavSelect('$251 - $500 Necklaces|topnav')">$251 - $500</a>	
                    </li>
                    <li class="level2">
                    <a href="/pendants?content=no&dir=asc&order=price&p=1&price=501,1000" onclick="categoryNavSelect('$501 - $1000 Necklaces|topnav')">$501 - $1000</a>	
                    </li>
                    <li class="level2">
                    <a href="/pendants?content=no&dir=asc&order=price&p=1&price=1001,1500" onclick="categoryNavSelect('$1001 - $1500 Necklaces|topnav')">$1001 - $1500</a>	
                    </li>
                    <li class="level2">
                    <a href="/pendants?content=no&dir=asc&order=price&p=1&price=1501,2500" onclick="categoryNavSelect('$1501 - $2500 |topnav')">$1501 - $2500</a>	
                    </li>
                    <li class="level2">
                    <a href="/pendants?content=no&dir=asc&order=price&p=1&price=2501,99999" onclick="categoryNavSelect('Over $2500 Necklaces|topnav')">Over $2500</a>	
                    </li>
                    
                </ul>
            </li>
            <li class="level1 view-all">
                <a href="/pendants" class="no-transition" onclick="categoryNavSelect('Necklaces|topnav')">View All <i class="fa fa-chevron-right"></i></a>
            </li>
        </ul>
    </li>
    
    
    <!--earrings categories starts-->
    
    <li class="level0">
        <a  class="level0" href="javascript:void(0)">Earrings <i class="fa fa-plus"></i></a>
        <ul class="level1">
            <li class="level1">
                <a class="level1" href="javascript:void(0)">Shop By Colored Gemstone <i class="fa fa-plus"></i></a>
                <ul class="level2">
					<li class="level2" >
						<a href="/earrings/sapphire-earrings" onclick="categoryNavSelect('Sapphire Earrings|topnav')">Sapphire</a>
					</li>
					<li class="level2" >
						<a href="/earrings/ruby-earrings" onclick="categoryNavSelect('Ruby Earrings|topnav')">Ruby</a>
					</li>
					<li class="level2" >
						<a href="/earrings/emerald-earrings" onclick="categoryNavSelect('Emerald Earrings|topnav')">Emerald</a>
					</li>
					<li class="level2" >
						<a href="/earrings/tanzanite-earrings" onclick="categoryNavSelect('Tanzanite Earrings|topnav')">Tanzanite</a>
					</li>
					<li class="level2" >
						<a href="/earrings/aquamarine-earrings" onclick="categoryNavSelect('Aquamarine Earrings|topnav')">Aquamarine</a>
					</li>
					 <li class="level2 view-more">
                        <a href="javascript:void(0)">More +</a>
                    </li>
					<li class="level2" >
						<a href="/earrings/blue-topaz-earrings" onclick="categoryNavSelect('Blue Topaz Earrings|topnav')">Blue Topaz</a>
					</li>
					<li class="level2" >
						<a href="/earrings/black-onyx-earrings" onclick="categoryNavSelect('Black Onyx Earrings|topnav')">Black Onyx</a>
					</li>
					<li class="level2" >
						<a href="/earrings/citrine-earrings" onclick="categoryNavSelect('Citrine Earrings|topnav')">Citrine</a>
					</li>
					<li class="level2" >
						<a href="/earrings/pearl-earrings" onclick="categoryNavSelect('Pearl Earrings|topnav')">Pearl</a>
					</li>
					<li class="level2" >
						<a href="/earrings/morganite-earrings" onclick="categoryNavSelect('Morganite Earrings|topnav')">Morganite</a>
					</li>
					<li class="level2" >
						<a href="/earrings/garnet-earrings" onclick="categoryNavSelect('Garnet Earrings|topnav')">Garnet</a>
					</li>
					<li class="level2" >
						<a href="/earrings/opal-earrings" onclick="categoryNavSelect('Opal Earrings|topnav')">Opal</a>
					</li>
					<li class="level2" >
						<a href="/earrings/amethyst-earrings" onclick="categoryNavSelect('Amethyst Earrings|topnav')">Amethyst</a>
					</li>
					<li class="level2" >
						<a href="/earrings/peridot-earrings" onclick="categoryNavSelect('Peridot Earrings|topnav')">Peridot</a>
					</li>
					<li class="level2" >
						<a href="/earrings/pink-tourmaline-earrings" onclick="categoryNavSelect('Pink Tourmaline Earrings|topnav')">Pink Tourmaline</a>
					</li>						
					<li class="level2" >
						<a href="/earrings/moissanite-earrings" onclick="categoryNavSelect('Moissanite Earrings|topnav')">Moissanite</a>
					</li>
					<li class="level2" >
						<a href="/lab-jewelry/lab-created-sapphire-earrings" onclick="categoryNavSelect('Lab Created Sapphire Earrings|topnav')">Lab Created Sapphire</a>
					</li>
					<li class="level2" >
						<a href="/lab-jewelry/lab-created-emerald-earrings" onclick="categoryNavSelect('Lab Created Emerald Earrings|topnav')">Lab Created Emerald</a>
					</li>
					<li class="level2" >
						<a href="/lab-jewelry/lab-created-ruby-earrings" onclick="categoryNavSelect('Lab Created Ruby Earrings|topnav')">Lab Created Ruby</a>
					</li>
            </ul>
            </li>
			 <li class="level1">
                <a class="level1" href="javascript:void(0)">Shop By Diamond<i class="fa fa-plus"></i></a>
                <ul class="level2">
					<li class="level2">
						<a href="/earrings/diamond-earrings" onclick="categoryNavSelect('Diamond Earrings|topnav')">Diamond</a>
					</li>
					<li class="level2">
						<a href="/earrings/colored-diamond-earrings/enhanced-blue-diamond" onclick="categoryNavSelect('Blue Diamond Earrings|topnav')">Blue Diamond</a>
					</li>
					<li class="level2">
						<a href="/earrings/colored-diamond-earrings/enhanced-black-diamond" onclick="categoryNavSelect('Black Diamond Earrings|topnav')">Black Diamond</a>
					</li>
					<li class="level2">
						<a href="/earrings/coffee-diamond-earrings" onclick="categoryNavSelect('Coffee Diamond Earrings|topnav')">Coffee Diamond</a>
					</li>
                </ul>
            </li>
            <li class="level1">
                <a class="level1" href="javascript:void(0)">Shop By Style<i class="fa fa-plus"></i></a>
                <ul class="level2">
                    <li class="level2">
                        <a href="/earrings?jewelry_styles=4183&order=position&dir=asc&no_cache=true" onclick="categoryNavSelect('Halo Earrings|topnav')">Halo</a>	
                    </li>
                    <li class="level2">
                    <a href="/earrings/drop-earrings" onclick="categoryNavSelect('Drops Earrings|topnav')">Drops</a>	
                    </li>
                    <li class="level2">
                    <a href="/earrings/hoop-earrings" onclick="categoryNavSelect('Hoops Earrings|topnav')">Hoops</a>	
                    </li>
                    <li class="level2">
                    <a href="/earrings/journey-earrings" onclick="categoryNavSelect('Journey Earrings|topnav')">Journey</a>	
                    </li>
                    <li class="level2">
                    <a href="/earrings/three-stone-earrings" onclick="categoryNavSelect('Three Stone Earrings|topnav')">Three Stone</a>	
                    </li>
                    <li class="level2">
                    <a href="/earrings/leverback-earrings" onclick="categoryNavSelect('Leverback Earrings|topnav')">Leverback</a>	
                    </li>
                    <?php /* <li class="level2">
                    <a href="/earrings/fashion-earrings" onclick="categoryNavSelect('Fashion Earrings|topnav')">Fashion</a>	
                    </li> */ ?>
					<li class="level2">
						<a href="/earrings/stud-earrings" onclick="categoryNavSelect('Stud Earrings|topnav')">Stud Earrings</a>
					</li>
					<li class="level2">
						<a href="/earrings/heart-earrings"  onclick="categoryNavSelect('Hearts Earrings|topnav')">Heart</a>
					</li>
					<li class="level2">
						<a href=" https://www.angara.com/earrings?jewelry_styles=5944&amp;dir=asc" onclick="categoryNavSelect('Knot Earrings|topnav')">Knot</a>
					</li>
					<li class="level2">
						<a href="/jewelry/dancing-gemstone-jewelry" onclick="categoryNavSelect('Dancing Diamonds|topnav')">Dancing Gemstones</a>
					</li>
					<li class="level2">
						<a href="/birthstone-jewelry/birthstone-earrings" onclick="categoryNavSelect('Birthstone Earrings|topnav')">Birthstone</a>
					</li>
                </ul>
            </li>
            <li class="level1">
                <a class="level1" href="javascript:void(0)">Shop By Price<i class="fa fa-plus"></i></a>
                <ul class="level2">
                    <li class="level2">
                    <a href="/earrings?content=no&dir=asc&order=price&p=1&price=1,250" onclick="categoryNavSelect('$250 & Under Earrings|topnav')">$250 & Under</a>	
                    </li>
                    <li class="level2">
                    <a href="/earrings?content=no&dir=asc&order=price&p=1&price=251,500" onclick="categoryNavSelect('$251 - $500 Earrings|topnav')">$251 - $500</a>	
                    </li>
                    <li class="level2">
                    <a href="/earrings?content=no&dir=asc&order=price&p=1&price=501,1000" onclick="categoryNavSelect('$501 - $1000 Earrings|topnav')">$501 - $1000</a>	
                    </li>
                    <li class="level2">
                    <a href="/earrings?content=no&dir=asc&order=price&p=1&price=1001,1500" onclick="categoryNavSelect('$1001 - $1500 Earrings|topnav')">$1001 - $1500</a>	
                    </li>
                    <li class="level2">
                    <a href="/earrings?content=no&dir=asc&order=price&p=1&price=1501,2500" onclick="categoryNavSelect('$1501 - $2500 Earrings|topnav')">$1501 - $2500</a>	
                    </li>
                    <li class="level2">
                    <a href="/earrings?content=no&dir=asc&order=price&p=1&price=2501,99999" onclick="categoryNavSelect('Over $2500 Earrings|topnav')">Over $2500</a>	
                    </li>
                    
                </ul>
            </li>
                
            <li class="level1 view-all">
                <a href="/earrings" class="no-transition" onclick="categoryNavSelect('Earrings|topnav')">View All<i class="fa fa-chevron-right"></i></a>
            </li>
        </ul>
    </li>
    
    
    
     <!--engagement categories starts-->
    
    <li class="level0">
        <a  class="level0" href="javascript:void(0)">Engagement<i class="fa fa-plus"></i></a>
        <ul class="level1">
            <li class="level1">
                <a class="level1" href="javascript:void(0)">Shop By Stone <i class="fa fa-plus"></i></a>
                <ul class="level2">
                    <li class="level2">
                    <a href="/engagement-rings/sapphire-engagement-rings" onclick="categoryNavSelect('Sapphire Engagement|topnav')">Sapphire</a>	
                    </li>
                    <li class="level2">
                    <a href="/engagement-rings/ruby-engagement-rings" onclick="categoryNavSelect('Ruby Engagement|topnav')">Ruby</a>	
                    </li>
                    <li class="level2">
                    <a href="/engagement-rings/emerald-engagement-rings" onclick="categoryNavSelect('Emerald Engagement|topnav')">Emerald</a>	
                    </li>
                    <li class="level2">
                    <a href="/engagement-rings/tanzanite-engagement-rings" onclick="categoryNavSelect('Tanzanite Engagement|topnav')">Tanzanite</a>	
                    </li>
                    <li class="level2">
                    <a href="/engagement-rings/diamond-engagement-rings" onclick="categoryNavSelect('Diamond Engagement|topnav')">Diamond</a>	
                    </li>
                    <li class="level2">
                    <a href="/engagement-rings/colored-diamond-engagement-rings/enhanced-black-diamond-engagement" onclick="categoryNavSelect('Black Diamond Engagement|topnav')">Black Diamond</a>	
                    </li>
                    <li class="level2">
                    <a href="/engagement-rings/colored-diamond-engagement-rings/enhanced-blue-diamond-engagement" onclick="categoryNavSelect('Blue Diamond Engagement|topnav')">Blue Diamond</a>	
                    </li>
                    
                    <li class="level2">
                    <a href="/engagement-rings/black-onyx-engagement-rings" onclick="categoryNavSelect('Black Onyx Engagement|topnav')">Black Onyx</a>	
                    </li>
                </ul>
            </li>
            <li class="level1">
                <a class="level1" href="javascript:void(0)">Shop By Style <i class="fa fa-plus"></i></a>
                <ul class="level2">
                    <li class="level2">
                    <a href="/engagement-rings/halo-rings" onclick="categoryNavSelect('Halo Engagement|topnav')">Halo</a>	
                    </li>
                    <li class="level2">
                    <a href="/rings/eternity-rings" onclick="categoryNavSelect('Eternity Engagement|topnav')">Eternity</a>	
                    </li>
                    <li class="level2">
                    <a href="/engagement-rings/solitaire-rings" onclick="categoryNavSelect('Solitaire Engagement|topnav')">Solitaire</a>	
                    </li>
                    <li class="level2">
                    <a href="/engagement-rings/three-stone-rings" onclick="categoryNavSelect('Three Stone Engagement|topnav')">Three Stone</a>	
                    </li>
                    <li class="level2">
                    <a href="/rings?jewelry_styles=4169&order=position&dir=asc&no_cache=true" onclick="categoryNavSelect('Cathedral Engagement|topnav')">Cathedral</a>	
                    </li>
                    <?php /* <li class="level2">
                    <a href="/engagement-rings?content=no&order=position&dir=asc&no_cache=true&jewelry_styles=4180" onclick="categoryNavSelect('Fashion Engagement|topnav')">Fashion</a>	
                    </li> */ ?>
                </ul>
            </li>
            <li class="level1">
                <a class="level1" href="javascript:void(0)">Shop By Collection <i class="fa fa-plus"></i></a>
                <ul class="level2">
                    <li class="level2">
                    <a href="/collection/vintage" onclick="categoryNavSelect('Vintage Engagement|topnav')">Vintage</a>	
                    </li>
                    <li class="level2">
                    <a href="/engagement-rings/promise-rings" onclick="categoryNavSelect('Promise Engagement|topnav')">Promise</a>	
                    </li>
                    <li class="level2">
                    <a href="/wedding-rings/wedding-bands" onclick="categoryNavSelect('Wedding Engagement|topnav')">Wedding</a>	
                    </li>
                    <li class="level2">
                    <a href="/engagement-rings/wedding-ring-set" onclick="categoryNavSelect('Ring Set Engagement|topnav')">Bridal Set</a>	
                    </li>
                </ul>
            </li>
            <li class="level1">
                <a class="level1" href="javascript:void(0)">Shop By Metal <i class="fa fa-plus"></i></a>
                <ul class="level2">
                    <li class="level2">
                    <a href="/engagement-rings?content=no&filterable_metal_types=4159&order=position&dir=asc&no_cache=true"
onclick="categoryNavSelect('Silver Engagement|topnav')">Silver</a>	
                    </li>
                    <li class="level2">
                    <a href="/engagement-rings?content=no&filterable_metal_types=4160&order=position&dir=asc&no_cache=true"
onclick="categoryNavSelect('White Gold Engagement|topnav')">White Gold</a>	
                    </li>
                    <li class="level2">
                    <a href="/engagement-rings?content=no&filterable_metal_types=4161&order=position&dir=asc&no_cache=true"
onclick="categoryNavSelect('Yellow Gold Engagement|topnav')">Yellow Gold</a>	
                    </li>
                    <li class="level2">
                 <?php /*   <a href="/engagement-rings?content=no&filterable_metal_types=4164&order=position&dir=asc&no_cache=true"
onclick="categoryNavSelect('Two Tone Gold Engagement|topnav')">Two Tone Gold</a>	*/ ?>
                    </li>
                    <li class="level2">
                    <a href="/engagement-rings?content=no&filterable_metal_types=4162&order=position&dir=asc&no_cache=true"        
onclick="categoryNavSelect('Platinum Engagement|topnav')">Platinum</a>	
                    </li>
                </ul>
            </li>
            <li class="level1">
                <a class="level1" href="javascript:void(0)">Shop By Price <i class="fa fa-plus"></i></a>
                <ul class="level2">
                    <li class="level2">
                    <a href="/engagement-rings?content=no&dir=asc&order=price&p=1&price=1,250" 
onclick="categoryNavSelect('$250 & Under Engagement|topnav')">$250 & Under</a>	
                    </li>
                    <li class="level2">
                    <a href="/engagement-rings?content=no&dir=asc&order=price&p=1&price=251,500" 
onclick="categoryNavSelect('$251 - $500 Engagement|topnav')">$251 - $500</a>	
                    </li>
                    <li class="level2">
                    <a href="/engagement-rings?content=no&dir=asc&order=price&p=1&price=501,1000" 
onclick="categoryNavSelect('$501 - $1000 Engagement|topnav')">$501 - $1000</a>	
                    </li>
                    <li class="level2">
                    <a href="/engagement-rings?content=no&dir=asc&order=price&p=1&price=1001,1500" 
onclick="categoryNavSelect('$1001 - $1500 Engagement|topnav')">$1001 - $1500</a>	
                    </li>
                    <li class="level2">
                    <a href="/engagement-rings?content=no&dir=asc&order=price&p=1&price=1501,2500" 
onclick="categoryNavSelect('$1501 - $2500 Engagement|topnav')">$1501 - $2500</a>	
                    </li>
                    <li class="level2">
                    <a href="/engagement-rings?content=no&dir=asc&order=price&p=1&price=2501,99999" 
onclick="categoryNavSelect('Over $2500 Engagement|topnav')">Over $2500</a>	
                    </li>
                </ul>
            </li>
            <li class="level1 view-all">
                <a  href="/engagement-rings" class="no-transition" onclick="categoryNavSelect('Engagement|topnav')">View All<i class="fa fa-chevron-right"></i></a>
            </li>
        </ul>
    </li>    
    
<!--wedding categories starts-->  
  
    <li class="level0">
        <a  class="level0" href="javascript:void(0)">Wedding<i class="fa fa-plus"></i></a>
        <ul class="level1">
            <li class="level1">
                <a class="level1" href="javascript:void(0)">For Him <i class="fa fa-plus"></i></a>
                <ul class="level2">
					 <li class="level2">
                        <a href="/wedding-rings/mens-plain-wedding-bands" onclick="categoryNavSelect('Plain Wedding Bands|topnav')">Plain</a>
                    </li>
                    <li class="level2">
						<a href="/wedding-rings/mens-gemstone-and-diamond-bands" onclick="categoryNavSelect('Gemstone Wedding Bands|topnav')">Gemstone</a>	
                    </li>
					<li class="level2">
						<a href="/wedding-rings/mens-diamond-wedding-bands" onclick="categoryNavSelect('Diamond Wedding Bands|topnav')">Diamond</a>	
                    </li>
                    <li class="level1 view-all">
                        <a href="/wedding-rings/mens-wedding-bands" onclick="categoryNavSelect('Mens Wedding Bands|topnav')">All Bands</a>
                    </li>
                </ul>
            </li>
			<li class="level1">
                <a class="level1" href="javascript:void(0)">For Her <i class="fa fa-plus"></i></a>
                <ul class="level2">
					<li class="level2">
						<a href="/wedding-rings/womens-plain-wedding-bands" onclick="categoryNavSelect('Plain Wedding Bands|topnav')">Plain</a>	
                    </li>
                    <li class="level2">
                        <a href="/wedding-rings/womens-gemstone-and-diamond-bands" onclick="categoryNavSelect('Gemstone Wedding Bands|topnav')">Gemstone</a>	
                    </li>
					<li class="level2">
                        <a href="/wedding-rings/womens-diamond-wedding-bands" onclick="categoryNavSelect('Diamond Wedding Bands|topnav')">Diamond</a>
                    </li>
                    <li class="level1 view-all">
                        <a href="/wedding-rings/womens-wedding-bands" onclick="categoryNavSelect('Womens Wedding Bands|topnav')">All Bands</a>
                    </li>
                </ul>
            </li>
            <li class="level1">
                <a class="level1" href="javascript:void(0)">Shop By Type <i class="fa fa-plus"></i></a>
                <ul class="level2">
                    <li class="level2">
						<a href="/wedding-rings/wedding-bands?order=position&amp;dir=asc&amp;no_cache=true&amp;jewelry_styles=4553" onclick="categoryNavSelect('Half Eternity Wedding Bands|topnav')">Half Eternity</a>
					</li>
					<li class="level2">
						<a href="/wedding-rings/wedding-bands?jewelry_styles=4179&amp;order=position&amp;dir=asc&amp;no_cache=true" onclick="categoryNavSelect('Eternity Wedding Bands|topnav')">Eternity</a>
					</li>
					<li class="level2">
						<a href="/rings/stackable-bands" onclick="categoryNavSelect('Stackables Wedding Bands|topnav')">Stackables</a>
					</li>
					<li class="level2">
						<a href="/wedding-rings/comfort-fit-wedding-bands" onclick="categoryNavSelect('Comfort-Fit Wedding Bands|topnav')">Comfort-Fit</a>
					</li>
                </ul>
            </li>
            <li class="level1">
                <a class="level1" href="javascript:void(0)">Shop By Stone<i class="fa fa-plus"></i></a>
                <ul class="level2">
                    <li class="level2">
                        <a href="/wedding-rings/wedding-bands?filterable_stone_names=4130&order=position&dir=asc&no_cache=true" onclick="categoryNavSelect('Diamond Wedding Bands|topnav')">Diamond</a>
                    </li>
                    <li class="level2">
                        <a href="/wedding-rings/wedding-bands?filterable_stone_names=4556&order=position&dir=asc&no_cache=true" onclick="categoryNavSelect('Blue Diamond Wedding Bands|topnav')">Blue Diamond</a>
                    </li>
                    <li class="level2">
                        <a href="/wedding-rings/wedding-bands?filterable_stone_names=4555&order=position&dir=asc&no_cache=true" onclick="categoryNavSelect('Black Diamond Wedding Bands|topnav')">Black Diamond</a>
                    </li>
					<li class="level2">
						<a href="/wedding-rings/wedding-bands?filterable_stone_names=4144&order=position&dir=asc&no_cache=true" onclick="categoryNavSelect('Sapphire Wedding Bands|topnav')">Sapphire</a>	
                    </li>
                    <li class="level2">
                        <a href="/wedding-rings/wedding-bands?filterable_stone_names=4143&order=position&dir=asc&no_cache=true" onclick="categoryNavSelect('Ruby Wedding Bands|topnav')">Ruby</a>
                    </li>
                    <li class="level2">
                        <a href="/wedding-rings/wedding-bands?filterable_stone_names=4131&order=position&dir=asc&no_cache=true" onclick="categoryNavSelect('Emerald Wedding Bands|topnav')">Emerald</a>
                    </li>
					<li class="level2">
						<a href="/wedding-rings/wedding-bands?order=position&amp;dir=asc&amp;no_cache=true&amp;filterable_stone_names=4124" onclick="categoryNavSelect('Aquamarine Wedding Bands|topnav')">Aquamarine</a>
					</li>
					<li class="level2">
						<a href="/wedding-rings/wedding-bands?order=position&amp;dir=asc&amp;no_cache=true&amp;filterable_stone_names=4146" onclick="categoryNavSelect('Tanzanite Wedding Bands|topnav')">Tanzanite</a>
					</li>
                </ul>
            </li>
			<li class="level1">
                <a class="level1" href="javascript:void(0)">Shop By Metal <i class="fa fa-plus"></i></a>
                <ul class="level2">
                    <li class="level2">
                    <a href="/wedding-rings/wedding-bands?filterable_metal_types=4159&order=position&dir=asc&no_cache=true" onclick="categoryNavSelect('Silver Wedding Bands|topnav')">Silver</a>	
                    </li>
                    <li class="level2">
                    <a href="/wedding-rings/wedding-bands?filterable_metal_types=4160&order=position&dir=asc&no_cache=true" onclick="categoryNavSelect('White Gold Wedding Bands|topnav')">White Gold</a>	
                    </li>
                    <li class="level2">
                     <a href="/wedding-rings/wedding-bands?filterable_metal_types=4161&order=position&dir=asc&no_cache=true" onclick="categoryNavSelect('Yellow Gold Wedding Bands|topnav')">Yellow Gold</a>	
                    </li>
                    <li class="level2">
                        <a href="/wedding-rings/wedding-bands?filterable_metal_types=4164&order=position&dir=asc&no_cache=true" onclick="categoryNavSelect('Two Tone Gold Wedding Bands|topnav')">Two Tone Gold</a>
                    </li>
                    <li class="level2">
                        <a href="/wedding-rings/wedding-bands?filterable_metal_types=4162&order=position&dir=asc&no_cache=true" onclick="categoryNavSelect('Platinum Wedding Bands|topnav')">Platinum</a>
                    </li>
                </ul>
            </li>
            <li class="level1">
                <a class="level1" href="javascript:void(0)">Shop By Price <i class="fa fa-plus"></i></a>
                <ul class="level2">
                    <li class="level2">
                    <a href="/wedding-rings/wedding-bands?dir=asc&order=price&p=1&price=1,250" onclick="categoryNavSelect('$250 & Under Wedding Bands|topnav')">$250 & Under</a>	
                    </li>
                    <li class="level2">
                    <a href="/wedding-rings/wedding-bands?dir=asc&order=price&p=1&price=251,500" onclick="categoryNavSelect('$251 - $500 Wedding Bands|topnav')">$251 - $500</a>
                    </li>
                    <li class="level2">
                    <a href="/wedding-rings/wedding-bands?dir=asc&order=price&p=1&price=501,1000" onclick="categoryNavSelect('$501 - $1000 Wedding Bands|topnav')">$501 - $1000</a>	
                    </li>
                    <li class="level2">
                        <a href="/wedding-rings/wedding-bands?dir=asc&order=price&p=1&price=1001,1500" onclick="categoryNavSelect('$1001 - $1500 Wedding Bands|topnav')">$1001 - $1500</a>
                    </li>
                    <li class="level2">
                        <a href="/wedding-rings/wedding-bands?dir=asc&order=price&p=1&price=1501,2000" onclick="categoryNavSelect('$1501 - $2000 Wedding Bands|topnav')">$1501 - $2000</a>
                    </li>
                    <li class="level2">
                        <a href="/wedding-rings/wedding-bands?dir=asc&order=price&p=1&price=2001,99999" onclick="categoryNavSelect('Over $2000 Wedding Bands|topnav')">Over $2000</a>
                    </li>
                </ul>
            </li>
            <li class="level1 view-all">
                <a href="/wedding-rings" class="no-transition" onclick="categoryNavSelect('Wedding|topnav')">View All<i class="fa fa-chevron-right"></i></a>
            </li>
        </ul>
    </li>
        
<!--bracelet categories starts-->		
    
    <li class="level0">
        <a  class="level0" href="javascript:void(0)">Bracelets<i class="fa fa-plus"></i></a>
        <ul class="level1">
            <li class="level1">
                <a class="level1" href="javascript:void(0)">Shop By Stone <i class="fa fa-plus"></i></a>
                <ul class="level2">
                    <li class="level2">
                    <a href="/bracelets/diamond-bracelets" onclick="categoryNavSelect('Diamond Bracelets|topnav')">Diamond</a>	
                    </li>
                    <li class="level2">
                    <a href="/bracelets/gemstone-bracelets?filterable_stone_names=4144" onclick="categoryNavSelect('Sapphire Bracelets|topnav')">Sapphire</a>	
                    </li>
                    <li class="level2">
                    <a href="/bracelets/gemstone-bracelets?filterable_stone_names=4143" onclick="categoryNavSelect('Ruby Bracelets|topnav')">Ruby</a>	
                    </li>
                    <li class="level2">
                        <a href="/bracelets/gemstone-bracelets?filterable_stone_names=4131" onclick="categoryNavSelect('Emerald Bracelets|topnav')">Emerald</a>
                    </li>
                </ul>
            </li>
            <li class="level1">
                <a class="level1" href="javascript:void(0)">Shop By Style <i class="fa fa-plus"></i></a>
                <ul class="level2">
                    <li class="level2">
                    <a href="/bracelets?jewelry_styles=6188" onclick="categoryNavSelect('Tennis Bracelets|topnav')">Tennis</a>	
                    </li>
                    <li class="level2">
                    <a href="/bracelets?jewelry_styles=6189" onclick="categoryNavSelect('Infinity Bracelets|topnav')">Infinity</a>	
                    </li>
                    <li class="level2">
                    <a href="/bracelets?jewelry_styles=4184" onclick="categoryNavSelect('Heart Bracelets|topnav')">Heart</a>	
                    </li>
                    <?php /* <li class="level2">
                    <a href="/bracelets?jewelry_styles=4180" onclick="categoryNavSelect('Fashion Bracelets|topnav')">Fashion</a>	
                    </li> */ ?>
                    <li class="level2">
                    <a href="/bracelets/charm-bracelets" onclick="categoryNavSelect('Charms Bracelets|topnav')">Charms</a>	
                    </li>
                </ul>
            </li>
            
            <li class="level1">
                <a class="level1" href="javascript:void(0)">Shop By Metal <i class="fa fa-plus"></i></a>
                <ul class="level2">
                    <li class="level2">
                    <a href="/bracelets?filterable_metal_types=4159" onclick="categoryNavSelect('Silver Bracelets|topnav')">Silver</a>	
                    </li>
                    <li class="level2">
                        <a href="/bracelets?filterable_metal_types=4160" onclick="categoryNavSelect('White Gold Bracelets|topnav')">White Gold</a>
                    </li>
                    <li class="level2">
                        <a href="/bracelets?filterable_metal_types=4161" onclick="categoryNavSelect('Yellow Gold Bracelets|topnav')">Yellow Gold</a>
                    </li>
                </ul>
            </li>
            <li class="level1">
                <a class="level1" href="javascript:void(0)">Shop By Price <i class="fa fa-plus"></i></a>
                <ul class="level2">
                    <li class="level2">
                    <a href="/bracelets?dir=asc&order=price&p=1&price=1,500" onclick="categoryNavSelect('$500 & Under Bracelets|topnav')">$500 & Under</a>	
                    </li>
                    <li class="level2">
                    <a href="/bracelets?dir=asc&order=price&p=1&price=501,1000" onclick="categoryNavSelect('$501 - $1000 Bracelets|topnav')">$501 - $1000</a>	
                    </li>
                    <li class="level2">
                        <a href="/bracelets?dir=asc&order=price&p=1&price=1001,1500" onclick="categoryNavSelect('$1000 - $1500 Bracelets|topnav')">$1000 - $1500</a>
                    </li>
                    <li class="level2">
                        <a href="/bracelets?dir=asc&order=price&p=1&price=1501,2000" onclick="categoryNavSelect('$1500 - $2000 Bracelets|topnav')">$1500 - $2000</a>
                    </li>
                    <li class="level2">
                        <a href="/bracelets?dir=asc&order=price&p=1&price=2001,99999" onclick="categoryNavSelect('Over $2000 Bracelets|topnav')">Over $2000</a>
                    </li>
                </ul>
            </li>
            <li class="level1 view-all">
                <a href="/bracelets" class="no-transition" onclick="categoryNavSelect('Bracelets|topnav')">View All<i class="fa fa-chevron-right"></i></a>
            </li>
        </ul>
    </li>   
    
    <!--gift categories starts-->
    <li class="level0">
        <a  class="level0" href="javascript:void(0)">Gifts<i class="fa fa-plus"></i></a>
        <ul class="level1">
			<li class="level1">
                <a class="level1" href="javascript:void(0)">Collection <i class="fa fa-plus"></i></a>
                <ul class="level2">
                    <li class="level2">
						<a href="/collection/knotty-heart-jewelry" onclick="categoryNavSelect('Knotty Heart Collection|topnav')">Knotty Heart</a>
					</li>
					<li class="level2">
						<a href="/collection/infinity-jewelry" onclick="categoryNavSelect('Infinity Collection|topnav')">Infinity</a>
					</li>
					<li class="level2">
						<a href="/jewelry/coffee-diamond-jewelry" onclick="categoryNavSelect('Coffee Diamond Collection|topnav')">Coffee Diamond</a>
					</li>
					<li class="level2">
						<a href="/jewelry/two-stone-jewelry" onclick="categoryNavSelect('MeWe Collection|topnav')">Me We</a>
					</li>
					<li class="level2">
						<a href="/collection/wear-your-luck" onclick="categoryNavSelect('wear your luck Collection|topnav')">Wear Your Luck</a>
					</li>
                </ul>
            </li>
            <li class="level1">
                <a class="level1" href="javascript:void(0)">Special Day <i class="fa fa-plus"></i></a>
                <ul class="level2">
                    <li class="level2" >
						<a href="/valentine-gifts" onclick="categoryNavSelect('Valentines Day Gifts|topnav')">Valentine's Day</a>
					</li>
					<li class="level2" >
						<a href="/mothers-jewelry" onclick="categoryNavSelect('Mothers Day Jewelry Gifts|topnav')">Mother's Day</a>
					</li>
					<li class="level2" >
						<a href="/jewelry-gifts/st-patricks-gifts" onclick="categoryNavSelect('St. Patricks Gifts|topnav')">St. Patrick's Day</a>
					</li>
					<li class="level2" >
						<a href="/jewelry-gifts/thanksgiving-gifts" onclick="categoryNavSelect('Thanksgiving Gifts|topnav')">Thanksgiving</a>
					</li>
					<li class="level2" >
						<a href="/jewelry-gifts/christmas-gifts" onclick="categoryNavSelect('Christmas Gifts|topnav')">Christmas</a>
					</li>
					<li class="level2" >
						<a href="/jewelry-gifts/birthday-gifts" onclick="categoryNavSelect('Birthday Gifts|topnav')">Birthday</a>
					</li>
					<li class="level2" >
						<a href="/anniversary-gifts" onclick="categoryNavSelect('Anniversary Gifts|topnav')">Anniversary</a>
					</li>
					<li class="level2" >
						<a href="/wedding-rings" onclick="categoryNavSelect('Wedding Gifts|topnav')">Wedding</a>
					</li>
					<li class="level2" >
						<a href="/jewelry-gifts/graduation-gifts" onclick="categoryNavSelect('Sapphire Gifts|topnav')">Graduation</a>
					</li>
					<?php /* <li class="level2" >
						<a href="/black-friday-deals" onclick="categoryNavSelect('Black Friday|topnav')">Black Friday</a>
					</li>
					<li class="level2" >
						<a href="/cyber-monday-deals" onclick="categoryNavSelect('Cyber Monday|topnav')">Cyber Monday</a>
					</li>
					<li class="level2" >
						<a href="/green-monday-deals" onclick="categoryNavSelect('Green Monday|topnav')">Green Monday</a>
					</li> */ ?>
                </ul>
            </li>
			<li class="level1">
                <a class="level1" href="javascript:void(0)">Category <i class="fa fa-plus"></i></a>
                <ul class="level2">
                    <li class="level2" >
						<a href="/jewelry/pantone-color-of-the-year" onclick="categoryNavSelect('Pantone Color 2017 Gifts|topnav')">Pantone Color 2017</a>
					</li>
					<li class="level2" >
						<a href="/collection/high-jewelry" onclick="categoryNavSelect('Certified Jewelry Gifts|topnav')">Certified Jewelry</a>
					</li>
					<li class="level2" >
						<a href="/wedding-rings/mens-wedding-bands" onclick="categoryNavSelect('Gifts for Him Gifts|topnav')">Gifts for Him</a>
					</li>
					<li class="level2" >
						<a href="/mothers-jewelry" onclick="categoryNavSelect('Mothers Jewelry Gifts|topnav')">Mother's Jewelry</a>
					</li>
					<li class="level2" >
						<a href="/jewelry-gifts/baby-jewelry" onclick="categoryNavSelect('Gifts for Kids Gifts|topnav')">Gifts for Kids</a>
					</li>
					<li class="level2" >
						<a href="/jewelry-gifts/gift-cards" onclick="categoryNavSelect('Gift Cards|topnav')">Gift Cards</a>
					</li>
					<li class="level2" >
						<a href="/birthstone-jewelry" onclick="categoryNavSelect('Birthstone Gifts|topnav')">Birthstone Jewelry</a>
					</li>
					<li class="level2" >
						<a href="/jewelry-gifts/gifts-for-her" onclick="categoryNavSelect('Gifts for Her Gifts|topnav')">Gifts for Her</a>
					</li>
					<li class="level2" >
						<a href="/jewelry/two-stone-jewelry" onclick="categoryNavSelect('Two Stone Jewelry|topnav')">Two Stone Jewelry</a>
					</li>
					<?php /* <li class="level2" >
						<a href="/jewelry/illusion-set-diamonds" onclick="categoryNavSelect('Illusion Set Gifts|topnav')">Illusion Set</a>
					</li>  */ ?>
                </ul>
            </li>
            <li class="level1">
                <a class="level1" href="javascript:void(0)">Shop By Gemstone <i class="fa fa-plus"></i></a>
                <ul class="level2">
                    <li class="level2" >
						<a href="/jewelry/sapphire-jewelry" onclick="categoryNavSelect('Sapphire Gifts|topnav')">Sapphire</a>
					</li>
					<li class="level2" >
						<a href="/jewelry/ruby-jewelry" onclick="categoryNavSelect('Ruby Gifts|topnav')">Ruby</a>
					</li>
					<li class="level2" >
						<a href="/jewelry/emerald-jewelry" onclick="categoryNavSelect('Emerald Gifts|topnav')">Emerald</a>
					</li>
					<li class="level2" >
						<a href="/jewelry/diamond-jewelry" onclick="categoryNavSelect('Diamond Rings|topnav')">Diamond</a>
					</li>
					<li class="level2" >
						<a href="/jewelry/colored-diamond-jewelry?filterable_stone_names=4556&amp;order=position&amp;dir=asc&amp;no_cache=true" onclick="categoryNavSelect('Blue Diamond Gifts|topnav')">Blue Diamond</a>
					</li>
					<li class="level2" >
						<a href="/jewelry/colored-diamond-jewelry?filterable_stone_names=4555&amp;order=position&amp;dir=asc&amp;no_cache=true" onclick="categoryNavSelect('Black Diamond Gifts|topnav')">Black Diamond</a>
					</li>
					<li class="level2 view-more">
                        <a href="javascript:void(0)">More +</a>
                    </li>
					<li class="level2" >
						<a href="/jewelry/peridot-jewelry" onclick="categoryNavSelect('Peridot Gifts|topnav')">Peridot</a></li>
					<li class="level2" >
						<a href="/jewelry/pink-tourmaline-jewelry" onclick="categoryNavSelect('Pink Tourmaline Gifts|topnav')">Pink Tourmaline</a>
					</li>
					<li class="level2" >
						<a href="/jewelry/citrine-jewelry" onclick="categoryNavSelect('Citrine Gifts|topnav')">Citrine</a>
					</li>
					<li class="level2" >
						<a href="/jewelry/pearl-jewelry" onclick="categoryNavSelect('Pearl Gifts|topnav')">Pearl</a>
					</li>
					<li class="level2" >
						<a href="/jewelry/morganite-jewelry" onclick="categoryNavSelect('Morganite Gifts|topnav')">Morganite</a>
					</li>
					<li class="level2" >
						<a href="/jewelry/tanzanite-jewelry" onclick="categoryNavSelect('Tanzanite Gifts|topnav')">Tanzanite</a>
					</li>
					<li class="level2" >
						<a href="/jewelry/opal-jewelry" onclick="categoryNavSelect('Opal Gifts|topnav')">Opal</a>
					</li>
					<li class="level2" >
						<a href="/jewelry/garnet-jewelry" onclick="categoryNavSelect('Garnet Gifts|topnav')">Garnet</a>
					</li>
					<li class="level2" >
						<a href="/jewelry/amethyst-jewelry" onclick="categoryNavSelect('Amethyst Gifts|topnav')">Amethyst</a>
					</li>
					<li class="level2" >
						<a href="/jewelry/aquamarine-jewelry" onclick="categoryNavSelect('Aquamarine Gifts|topnav')">Aquamarine</a>
					</li>
					<li class="level2" >
						<a href="/jewelry/blue-topaz-jewelry" onclick="categoryNavSelect('Blue Topaz Gifts|topnav')">Blue Topaz</a>
					</li>
					<li class="level2" >
						<a href="/jewelry/black-onyx-jewelry" onclick="categoryNavSelect('Black Onyx Gifts|topnav')">Black Onyx</a>
					</li>
					<li class="level2" >
						<a href="/jewelry/moissanite-jewelry" onclick="categoryNavSelect('Moissanite Gifts|topnav')">Moissanite</a>
					</li>
					<li class="level2" >
						<a href="/lab-jewelry/lab-created-sapphire-jewelry" onclick="categoryNavSelect('Lab Created Sapphire Gifts|topnav')">Lab Created Sapphire</a>
					</li>
					<li class="level2" >
						<a href="/lab-jewelry/lab-created-emerald-jewelry" onclick="categoryNavSelect('Lab Created Emerald Gifts|topnav')">Lab Created Emerald</a>
					</li>
					<li class="level2" >
						<a href="/lab-jewelry/lab-created-ruby-jewelry" onclick="categoryNavSelect('Lab Created Ruby Gifts|topnav')">Lab Created Ruby</a>
					</li>
                </ul>
            </li>
            
            <li class="level1">
                <a class="level1" href="javascript:void(0)">Shop By Price <i class="fa fa-plus"></i></a>
                <ul class="level2">
                    <li class="level2">
                    <a href="/products?dir=asc&order=price&p=1&price=1,250" onclick="categoryNavSelect('$250 & Under Gifts|topnav')">$250 & Under</a>	
                    </li>
                    <li class="level2">
                    <a href="/products?dir=asc&order=price&p=1&price=251,500" onclick="categoryNavSelect('$251 - $500 Gifts|topnav')">$251 - $500</a>	
                    </li>
                    <li class="level2">
                        <a href="/products?dir=asc&order=price&p=1&price=501,1000" onclick="categoryNavSelect('$501 - $1000 Gifts|topnav')">$501 - $1000</a>
                    </li>
                    <li class="level2">
                        <a href="/products?dir=asc&order=price&p=1&price=1001,1500" onclick="categoryNavSelect('$1001 - $1500 Gifts|topnav')">$1001 - $1500</a>
                    </li>
                    <li class="level2">
                        <a href="/products?dir=asc&order=price&p=1&price=1501,2500" onclick="categoryNavSelect('$1501 - $2500 Gifts|topnav')">$1501 - $2500</a>
                    </li>
                    <li class="level2">
                        <a href="/products?dir=asc&order=price&p=1&price=2501,99999" onclick="categoryNavSelect('Over $2500 Gifts|topnav')">Over $2500</a>
                    </li>
                </ul>
            </li>
            <li class="level1 view-all">
                <a href="/jewelry-gifts" class="no-transition" onclick="categoryNavSelect('Gifts|topnav')"><span class="nav-link-text no-transition">View All</span><i class="fa fa-chevron-right"></i></a>
            </li>
        </ul>
    </li>
</ul>