<style>
.p0{padding:0px;}
.full-width{width:100%;float:left;}
.cr-block{width:100%;float:left; background:#f9f9f9}
.img-qt-block{}
.qt-block{background:#f9f9f9 url(<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/customer-reviews/qt-icon-3.png) no-repeat 3px 3px; padding: 22px 10px 10px 45px;}
.img{}
.qt{padding:10px 10px 10px 35px; background:#f9f9f9 url(<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/customer-reviews/qt-icon-1.png) no-repeat 3px 3px;}
.name{color:#b2674b;}
</style>
<div class="container showcase-bg-white min-padding-top relative-placeholder">	
	<div class="col-sm-12 p0 max-margin-bottom">
		<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/customer-reviews/cr-1.jpg" alt=""/>
	</div>
	<div class="col-sm-4">
		<div class="img-qt-block cr-block high-margin-bottom">
			<div class="img full-width">
				<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/customer-reviews/cr-2.jpg" alt=""/>
			</div>
			<div class="qt full-width">
				We were worried this would not get here on time because we were unaware that these are all HAND MADE! Even though there was a misunderstanding on our part - Angara made sure we had our gift EXACTLY as promised and it was BEAUTIFUL. 
				<br>
				<br>
				<span class="name">- Ted </span>
			</div>
		</div>
		<div class="qt-block cr-block high-margin-bottom">
			Service excellent, delivery expeditious, and my wife LOVES the ring which is exactly as described on an excellent website. I recommend this store to everyone.
			<br>
			<br>
			<span class="name">- DocHelm </span>
		</div>
		<div class="qt-block cr-block high-margin-bottom">
			You guys totally came through for me and I will recommend you to my friends and family! Thank you so much for being the company that you are! 
			<br>
			<br>
			<span class="name">- Andrew</span>
		</div>
		<div class="img-qt-block cr-block high-margin-bottom">
			<div class="img full-width">
				<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/customer-reviews/cr-3.jpg" alt=""/>
			</div>
		</div>
	</div>
	<div class="col-sm-4">
		<div class="qt-block cr-block high-margin-bottom">
			Great Customer Service!!!! That is the number one reason for shopping at Angara! The Customer executive was wonderful helping me to decide which Ruby pendant would be ideal for my Daughter, Elizabeth's Sweet 16! Gorgeous piece! ! Brilliant Ruby! Looks like a museum piece! Will buy other pieces for other occasions to match and make a complete set! Fast shipping! Secure! Packing superb! 5 star rating! Thanks, Kathy.
			<br>
			<br>
			<span class="name">- spa4skin</span>
		</div>
		<div class="img-qt-block cr-block high-margin-bottom">
			<div class="img full-width">
				<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/customer-reviews/cr-4.jpg" alt=""/>
			</div>
		</div>
		<div class="qt-block cr-block high-margin-bottom">
			This was my first experience ordering jewelry on-line and I would not hesitate to order again from Angara. I had found a ring at a local jeweler that was the same as the Classic Seven-Stone ring from Angara and the Angara ring was priced 60% less. 
			<br>
			<br>
			<span class="name">- Bill</span>
		</div>
		<div class="img-qt-block cr-block high-margin-bottom">
			<div class="img full-width">
				<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/customer-reviews/cr-5.jpg" alt=""/>
			</div>
		</div>
	</div>
	<div class="col-sm-4">
		<div class="img-qt-block cr-block high-margin-bottom">
			<div class="img full-width">
				<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/customer-reviews/cr-6.jpg" alt=""/>
			</div>
			<div class="qt full-width">
				The tanzanite earrings are top notch - I just love the rich velvety corn blue colour - just amazing! A massive thank to their Customer Executive who sorted my order out! Big thank you for your outstanding help! 
				<br>
				<br>
				<span class="name">- Mohamed</span>
			</div>
		</div>
		<div class="qt-block cr-block high-margin-bottom">
			The ring is perfect and the customer service helped me make some crucial decisions. I am completely satisfied. Angara has exceeded all of my expectations and I thank you for helping me find the ring I will wear the rest of my days.
			<br>
			<br>
			<span class="name">- Die for it</span>
		</div>
		<div class="qt-block cr-block high-margin-bottom">
			I truly felt Angara gave me excellent treatment and I did not have to leave my house in bad weather to find what I was looking for. 
			<br>
			<br>
			<span class="name">- Corey</span>
		</div>
		<div class="img-qt-block cr-block high-margin-bottom">
			<div class="img full-width">
				<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/customer-reviews/cr-7.jpg" alt=""/>
			</div>
			<div class="qt full-width">
				Engaged to the most wonderful woman. Thank you Angara. 
				<br>
				<br>
				<span class="name">- Brandon</span>
			</div>
		</div>
	</div>
</div>