<style>
.padd-btm {padding-bottom:16px;}
.fine-jewelry {max-width:1500px;margin:0 auto;}
.txt {top:10%;left:0;right:0;text-align:center;}
.txt span {display:block;font-size:28px;color:#3c3c3c;}
.txt .btn {width:150px;margin:0 auto;background: transparent;border:1px solid #3c3c3c;font-size:15px;}
.txt .btn:hover {border:1px solid #fa505a;}
.txt .btn:hover a {color:#fa505a;}
.txt .btn a:hover, .txt .btn a.active, .txt .btn a:focus {text-decoration:none;}
.banner .txt {width:35%;top:30%;left:9%;}
.banner .title{text-align: left;font-size: 36px;}
.banner p{font-size:14px;text-align: left;}

@media (max-width:1024px) {
.txt {top:5%;}
.txt span {font-size:24px;}	
.banner .txt {top:25%;}
}

@media (max-width:768px) {
.txt span {font-size: 20px;padding-bottom:2px;}
.txt .btn {width: 100px;font-size: 10px;height: 25px;line-height: 25px;}
.banner .txt {top:15%;width:38%;left:5%;}
.banner .title{text-align: left;font-size:32px;}
.banner p{font-size:13px;}
}
</style>

<div class="container valentine-top20 padd-btm col-sm-12">
	<div class="banner relative-placholder">
		<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/fine-jewelry/herobanner.jpg"/>
		<div class="absolute-placeholder txt">
			<span class="title high-padding-bottom">Fine Jewelry</span>
			<p>Jewelry that definess life's finest moments - rings, earrings and pendants adorned with the finest gemstones and handcrafted to perfection -there's one for everyone, every occasion and every special person in your life, including you.</p>
		</div>
	</div>
</div>
<section class="fine-jewelry">
<div class="item col-sm-12 padd-btm pull-left">
	<div class="col-md-4 col-sm-4 relative-placholder">
			<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/fine-jewelry/01-sapphire.jpg" alt="View Sapphire Jewelry" title="Shop Sapphire Jewelry"/>
		<div class="absolute-placeholder txt">
			<span class="title max-padding-bottom">Sapphire Jewelry</span>
			<span class="btn"><a href="/jewelry/sapphire-jewelry?icid=jewelrypage|sapphire|09272016">View Collection</a></span>
		</div>
	</div>
	<div class="col-md-4 col-sm-4 relative-placholder ">
			<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/fine-jewelry/02-ruby.jpg" alt="View Ruby Jewelry" title="Shop Ruby Jewelry"/>
		<div class="absolute-placeholder txt">
			<span class="title max-padding-bottom">Ruby Jewelry</span>
			<span class="btn"><a href="/jewelry/ruby-jewelry?icid=jewelrypage|ruby|09272016">View Collection</a></span>
		</div>
	</div>
	<div class="col-md-4 col-sm-4 relative-placholder ">
			<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/fine-jewelry/03-aquamarine.jpg" alt="View Aquamarine Jewelry" title="Shop Aquamarine Jewelry"/>
		<div class="absolute-placeholder txt">
			<span class="title max-padding-bottom">Aquamarine Jewelry</span>
			<span class="btn"><a href="/jewelry/aquamarine-jewelry?icid=jewelrypage|aqua|09272016">View Collection</a></span>
		</div>
	</div>
</div>
<div class="clearfix"></div>
<div class="item col-sm-12 padd-btm pull-left">
	<div class="col-md-4 col-sm-4 relative-placholder ">
			<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/fine-jewelry/04-emerald.jpg" alt="View Emerald Jewelry" title="Shop Emerald Jewelry"/>
		<div class="absolute-placeholder txt">
			<span class="title max-padding-bottom">Emerald Jewelry <br> <span style="font-size:16px;">Pantone Color 2017 Inspired</span> </span>
			<span class="btn"><a href="/jewelry/emerald-jewelry?icid=jewelrypage|emerald|09272016">View Collection</a></span>
		</div>
	</div>
	<div class="col-md-4 col-sm-4 relative-placholder  relative-placholder ">
			<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/fine-jewelry/05-diamond.jpg" alt="View Diamond Jewelry" title="Shop Diamond Jewelry"/>
		<div class="absolute-placeholder txt">
			<span class="title max-padding-bottom">Diamond Jewelry</span>
			<span class="btn"><a href="/jewelry/diamond-jewelry?icid=jewelrypage|diamond|09272016">View Collection</a></span>
		</div>
	</div>
	<div class="col-md-4 col-sm-4 relative-placholder ">
			<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/fine-jewelry/06-pearl.jpg" alt="View Pearl Jewelry" title="Shop Pearl Jewelry"/>
		<div class="absolute-placeholder txt">
			<span class="title max-padding-bottom">Pearl Jewelry</span>
			<span class="btn"><a href="/jewelry/pearl-jewelry?icid=jewelrypage|pearl|09272016">View Collection</a></span>
		</div>
	</div>
</div>
<div class="clearfix"></div>
<div class="item col-sm-12 padd-btm pull-left">
	<div class="col-md-4 col-sm-4 relative-placholder ">
			<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/fine-jewelry/07-moraganite.jpg" alt="View Morganite Jewelry" title="Shop Morganite Jewelry"/>
		<div class="absolute-placeholder txt">
			<span class="title max-padding-bottom">Morganite Jewelry</span>
			<span class="btn"><a href="/jewelry/morganite-jewelry?icid=jewelrypage|morganite|09272016">View Collection</a></span>
		</div>
	</div>
	<div class="col-md-4 col-sm-4 relative-placholder  relative-placholder ">
			<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/fine-jewelry/08-peridot.jpg" alt="View Peridot Jewelry" title="Shop Peridot Jewelry"/>
		<div class="absolute-placeholder txt">
			<span class="title max-padding-bottom">Peridot Jewelry <br> <span style="font-size:16px;">Pantone Color 2017 Inspired</span> </span>
			<span class="btn"><a href="/jewelry/peridot-jewelry?icid=jewelrypage|peridot|09272016">View Collection</a></span>
		</div>
	</div>
	<div class="col-md-4 col-sm-4 relative-placholder ">
			<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/fine-jewelry/09-amethyst.jpg" alt="View Amethyst Jewelry" title="Shop Amethyst Jewelry"/>
		<div class="absolute-placeholder txt">
			<span class="title max-padding-bottom">Amethyst Jewelry</span>
			<span class="btn"><a href="/jewelry/amethyst-jewelry?icid=jewelrypage|amethyst|09272016">View Collection</a></span>
		</div>
	</div>
</div>
<div class="clearfix"></div>
<div class="item col-sm-12 padd-btm pull-left">
	<div class="col-md-4 col-sm-4 relative-placholder ">
			<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/fine-jewelry/10-garnet.jpg" alt="View Garnet Jewelry" title="Shop Garnet Jewelry"/>
		<div class="absolute-placeholder txt">
			<span class="title max-padding-bottom">Garnet Jewelry</span>
			<span class="btn"><a href="/jewelry/garnet-jewelry?icid=jewelrypage|garnet|09272016">View Collection</a></span>
		</div>
	</div>
	<div class="col-md-4 col-sm-4 relative-placholder  relative-placholder ">
			<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/fine-jewelry/11-opal.jpg" alt="View Opal Jewelry" title="Shop Opal Jewelry"/>
		<div class="absolute-placeholder txt">
			<span class="title max-padding-bottom">Opal Jewelry</span>
			<span class="btn"><a href="/jewelry/opal-jewelry?icid=jewelrypage|opal|09272016">View Collection</a></span>
		</div>
	</div>
	<div class="col-md-4 col-sm-4 relative-placholder ">
			<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/fine-jewelry/12-citrine.jpg" alt="View Citrine Jewelry" title="Shop Citrine Jewelry"/>
		<div class="absolute-placeholder txt">
			<span class="title max-padding-bottom">Citrine Jewelry</span>
			<span class="btn"><a href="/jewelry/citrine-jewelry?icid=jewelrypage|citrine|09272016">View Collection</a></span>
		</div>
	</div>
</div>
<div class="clearfix"></div>
<div class="item col-sm-12 padd-btm pull-left">
	<div class="col-md-4 col-sm-4 relative-placholder ">
			<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/fine-jewelry/13-pink-tourmaline.jpg" alt="View Pink Tourmaline Jewelry" title="Shop Pink Tourmaline Jewelry"/>
		<div class="absolute-placeholder txt">
			<span class="title max-padding-bottom">Pink Tourmaline Jewelry</span>
			<span class="btn"><a href="/jewelry/pink-tourmaline-jewelry?icid=jewelrypage|pink-tourmaline|09272016">View Collection</a></span>
		</div>
	</div>
	<div class="col-md-4 col-sm-4 relative-placholder  relative-placholder ">
			<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/fine-jewelry/14-blue-topaz.jpg" alt="View Blue Topaz Jewelry" title="Shop Blue Topaz Jewelry"/>
		<div class="absolute-placeholder txt">
			<span class="title max-padding-bottom">Blue Topaz Jewelry</span>
			<span class="btn"><a href="/jewelry/blue-topaz-jewelry?icid=jewelrypage|topaz|09272016">View Collection</a></span>
		</div>
	</div>
	<div class="col-md-4 col-sm-4 relative-placholder ">
			<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/fine-jewelry/15-black-onyx.jpg" alt="View Black Onyx Jewelry" title="Shop Black Onyx Jewelry"/>
		<div class="absolute-placeholder txt">
			<span class="title max-padding-bottom">Black Onyx Jewelry</span>
			<span class="btn"><a href="/jewelry/black-onyx-jewelry?icid=jewelrypage|black-onyx|09272016">View Collection</a></span>
		</div>
	</div>
</div>
<div class="clearfix"></div>
<div class="item col-sm-12">
	<div class="col-md-4 col-sm-4 relative-placholder ">
			<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/fine-jewelry/16-black-diamond.jpg" alt="View Black Diamond Jewelry" title="Shop Black Diamond Jewelry"/>
		<div class="absolute-placeholder txt">
			<span class="title max-padding-bottom">Black Diamond Jewelry</span>
			<span class="btn"><a href="/jewelry/colored-diamond-jewelry?filterable_stone_names=4555?icid=jewelrypage|black-diamond|09272016">View Collection</a></span>
		</div>
	</div>
	<div class="col-md-4 col-sm-4 relative-placholder  relative-placholder ">
			<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/fine-jewelry/17-blue-diamond.jpg" alt="View Blue Diamond Jewelry" title="Shop Blue Diamond Jewelry"/>
		<div class="absolute-placeholder txt">
			<span class="title max-padding-bottom">Blue Diamond Jewelry</span>
			<span class="btn"><a href="/jewelry/colored-diamond-jewelry?filterable_stone_names=4556?icid=jewelrypage|blue-diamond|09272016">View Collection</a></span>
		</div>
	</div>
	<div class="col-md-4 col-sm-4 relative-placholder ">
			<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/fine-jewelry/18-tanzanite.jpg" alt="View Tanzanite Jewelry" title="Shop Tanzanite Jewelry"/>
		<div class="absolute-placeholder txt">
			<span class="title max-padding-bottom">Tanzanite Jewelry</span>
			<span class="btn"><a href="/jewelry/tanzanite-jewelry?icid=jewelrypage|tanzanite|09272016">View Collection</a></span>
		</div>
	</div>
</div>
</section>