<style>
.infinity-container {max-width:1920px;margin:0 auto;}
.bg-two .absolute-placeholder, .bg-four .absolute-placeholder {
	top:0;
	left:0;
	right:0;
	margin:0 auto;
	width:100%;
}
.bg-comman {min-height:100px;}
.bg-comman .text-bold {color:#000000;font-size:28px;}
.bg-comman p {font-size:36px;}
.bg-three .cinzelregular {color:#ffffff;}
.bg-two .absolute-placeholder {
	top:31.25%;
	max-width:24.37%;
}
.bg-three .absolute-placeholder {
	top:30.17%;
	left:6.35%;
	max-width:26.40%;
	width:100%;
}
.bg-four .absolute-placeholder { 
	top:28.52%;
	max-width:26.66%;
}
.explore-button{
		display:inline-block;
		border:1px solid #000000;
		color:#000000;
		font-size:22px;
		border-radius:2px;
		line-height:54px;
		padding:0px 50px;
		text-decoration:none!important;
	}
	.explore-button:hover{
		border-color:#fa505a;
		color:#fa505a;
		text-decoration:none;
	}
	.explore-button.white-btn:hover{
		border-color:#ffffff;
		color:#ffffff!important;
		text-decoration:none;
	}
.left-right-btn {
	position:absolute;
	top: 71.74%;
	z-index:1;
}
@media (max-width:1680px) { .bg-comman .text-bold {font-size:26px;} .bg-comman p {font-size:32px;} }
@media (max-width:1500px) { .explore-button {font-size:18px;padding:0px 30px;line-height:45px;} .bg-comman .text-bold {font-size:23px;} .bg-comman p {font-size:28px;} }
@media (max-width:1368px) { .bg-comman .text-bold {font-size:20px;} .bg-comman p {font-size:26px;} }
@media (max-width:1280px) { .explore-button {font-size:16px;line-height:35px;padding:0px 20px;} .bg-comman .text-bold {font-size:21px;} .bg-comman p {font-size:24px;} }
@media (max-width:1024px) { .explore-button {font-size:14px;} .bg-comman .text-bold {font-size:16px;} .bg-comman p {font-size:19px;} }
@media (max-width:768px)  {  .explore-button {font-size:12px;line-height:30px;} .bg-comman .text-bold {font-size:13px;} .bg-comman p {font-size:15px;} }
.half-width {width:50%;position:absolute;top:0;height:100%;}
</style>
<section class="infinity-container">
    <div class="col-sm-12 no-padding bg-comman bg-one max-margin-top relative-placeholder">
		<a href="/jewelry/infinity-jewelry?order=position&dir=asc&no_cache=true&jewelry_styles=6189&icid=infinitypage|new-arrival|image-click|02082017">
            <img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/infinity/one-1.gif" alt="">
		</a>
    </div>
    <div class="clearfix"></div>
	<div class="col-sm-12 no-padding bg-comman bg-two relative-placeholder">
		<a href="/pendants/infinity-pendant-necklaces?icid=infinitypage|inf-pendants|explrcol|02082017">
            <img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/infinity/two.jpg" alt="">
			<div class="absolute-placeholder text-center">
				<p class="text-bold">Infinite Love</P>
				<p class="cinzelregular apricot-text">A BEAUTIFUl REMINDER<br>OF THE ENDLESS LOVE<br>YOU SHARE</p>
				<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/infinity/two-text.png" alt="">
				<span class="explore-button max-margin-top max-margin-bottom text-center">
					Explore Infinity Pendants
				</span>
			</div>
		</a>
    </div>
    <div class="clearfix"></div>
	<div class="col-sm-12 no-padding bg-comman bg-three relative-placeholder">
		<a href="/rings/infinity-rings?icid=infinitypage|inf-rings|explrcol|02082017">
            <img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/infinity/three.jpg" alt="">
			<div class="absolute-placeholder text-center">
				<p class="text-bold">Infinite Beauty</P>
				<p class="cinzelregular">An expression of love<br>that knows no limits </p>
				<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/infinity/three-text.png" alt="">
				<span class="explore-button white-btn max-margin-top max-margin-bottom text-center">
					Explore Infinity Rings
				</span>
			</div>
		</a>
    </div>
    <div class="clearfix"></div>
	<div class="col-sm-12 no-padding bg-comman bg-four relative-placeholder">
            <img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/infinity/four.jpg" alt="">
			<div class="absolute-placeholder text-center">
				<p class="text-bold">Infinite Grace</P>
				<p class="cinzelregular apricot-text"> Endearing symbols of<br>continuous love and<br>admiration</p>
				<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/infinity/four-text.png" alt="">
			</div>
			<div class="left-right-btn" style="left:5%;">
				<a class="explore-button max-margin-top max-margin-bottom text-center pull-left" href="/earrings/infinity-earrings?icid=infinitypage|inf-earrings|explrcol|02082017">
						Explore Infinity Earrings
				</a>
			</div>
			<div class="left-right-btn" style="right:5%;">
				<a class="explore-button max-margin-top max-margin-bottom text-center pull-right" href="/bracelets/infinity-bracelets?icid=infinitypage|inf-bracelets|explrcol|02082017">
						Explore Infinity Bracelets
				</a>
			</div>
		<a class="half-width pull-left" style="left:0;" href="/earrings/infinity-earrings?icid=infinitypage|inf-earrings|explrcol|02082017"></a>
		<a class="half-width pull-right" style="right:0;" href="/bracelets/infinity-bracelets?icid=infinitypage|inf-bracelets|explrcol|02082017"></a>
    </div>
</section>