<style>
	.dark-bg{background-color:#f7f7f7;}
	.white-bg{background-color:#ffffff;}
	.pearl-button{display:block; color:#4e4e4f; font-size:16px; max-width:220px; width:100%; text-align:center; line-height:50px; border:1px solid #000000; margin:20px auto 0px;}
	.pearl-button:hover{text-decoration:none; border-color:#fa505a; background:#fff6f7;}
	.pearl-button:focus{text-decoration:none;}
	.low-padding-right{padding-right:5px!important}
	.low-padding-left{padding-left:5px!important}
	.max-padding-right{padding-right:15px!important}
	.max-padding-left{padding-left:15px!important}
	.high-padding-right{padding-right:10px!important}
	.high-padding-left{padding-left:10px!important}
	.center-align{margin:0 auto 5px;}
	
	.breadcrumb{display:none} 
	#footer{margin-top:0px!important;}

	.collection .heading{font-size:40px; font-weight:normal; margin-top:50px; margin-bottom:30px;}
	.collection .heading:before{content:""; width:66px; height:1px; background-color:#000000; position:absolute; left:50%; margin-left:-33px; top:68px;}
	.collection .sub-heading{font-size:16px; padding:0px 30px;}
	.pearl-jewelry{bottom:20px; left:20px; right:20px; text-align:center; padding:10px; background:rgba(255,255,255,0.5);}
	.pearl-jewelry .heading{margin-top:20px}
	.pearl-jewelry .heading:before{top:95px}
	.pearl-jewelry p{font-size:18px; padding:0px 80px; margin-bottom:30px;}
	.pearl-info .title{font-size:18px;}
	.pearl-info .image-box{display:block; width:160px; height:160px; border:1px solid #e5e5e5; border-radius:90px; overflow:hidden; margin:0 auto 25px;}
	.pearl-info .image-box span{display:block; width:120px; height:121px; background:url(<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/pearl/pearl-sprite.jpg) no-repeat; margin:0 auto; border:19px solid transparent; border-radius:150px; box-sizing:content-box;}
	.pearl-info .image-box span.freshwater{background-position:0px 0px;}
	.pearl-info .image-box span.white-akoya{background-position:0px -121px;}
	.pearl-info .image-box span.golden-akoya{background-position:0px -242px;}
	.pearl-info .image-box span.tahitian{background-position:0px -363px;}
	.pearl-info .image-box span.white-south-sea{background-position:0px -484px;}
	.pearl-info .image-box span.golden-south-sea{background-position:0px -605px;}
	.pearl-info a:hover{text-decoration:none; color:#fa505a;}
	.pearl-info a:hover .image-box{border-color:#fa505a;}
	.pearl-info a:hover .image-box span{border-color:#fff6f7;}
	.shop-by-color.desktop{position:absolute; padding-bottom:50px; left:30px; right:10px; bottom:0px; background:#ffffff;}
	.shop-by-pearl-type .sub-heading{max-width:850px; margin:0 auto}
	.start-here .heading:before{top:108px;}
	.start-here img{margin:60px 0px 30px;}
	.start-here p, .pearl-education p{font-size:16px;}
	.pearl-education img{margin:0 auto;}
	.pearl-education .pearl-button{margin-top:0px;}
	.recent-reviews .white-bg{padding-bottom: 30px!important;}
	.review-slider .item{display:table-row;}
	.review-slider .item .col-sm-4,
	.review-slider .item .col-sm-8{display:table-cell; float:none!important; vertical-align:middle;}
	.review-slider .item .date{font-size:12px;}
	.start-here .white-bg, .pearl-education .white-bg, .recent-reviews .white-bg{min-height:401px;}
	.start-here .heading, .pearl-education .heading, .recent-reviews .heading{margin-top:40px;}
	.shop-by-jewelry-type .jewelry-box .heading{font-size:30px;}
	.shop-by-jewelry-type .jewelry-box .heading:before{top:105px;}
	.shop-by-jewelry-type .jewelry-box{border:1px solid #d5d5d5; transition:border 500ms; -webkit-transition:border 500ms;}
	.shop-by-jewelry-type .jewelry-box:hover{border-color:#fa505a}
	.shop-by-jewelry-type .jewelry-box:hover .heading:before{background-color:#fa505a;}
	.shop-by-jewelry-type .jewelry-box .img-box{min-height:350px;}
	.shop-by-jewelry-type .jewelry-box img{max-width:350px; margin:0 auto;}
	.shop-by-jewelry-type .jewelry-box img.ring{max-width:250px; margin:50px auto 0px;}
	.shop-by-jewelry-type .jewelry-box .pearl-button{margin-top:10px; max-width:100%;}
	
	.slick-dots{text-align:center!important; margin-bottom:0px!important}
	
	@media (max-width:1439px) and (min-width:769px){
		.collection .heading{margin-top:20px}
		.shop-by-color.desktop{padding-bottom:20px}
		.pearl-info{margin-top: 0px;}
		.shop-by-jewelry-type .jewelry-box .heading:before{
			top:73px;
		}
	}
	@media (max-width:1279px) and (min-width:769px){
		.pearl-jewelry p{padding:0px 10px;}
		.pearl-info .image-box{width:120px; height:120px;}
		.pearl-info .image-box span{width:80px; height:81px;}
		.pearl-info .image-box span.freshwater{background-position:-20px -20px;}
		.pearl-info .image-box span.white-akoya{background-position:-20px -141px;}
		.pearl-info .image-box span.golden-akoya{background-position:-20px -262px;}
		.pearl-info .image-box span.tahitian{background-position:-20px -383px;}
		.pearl-info .image-box span.white-south-sea{background-position:-20px -504px;}
		.pearl-info .image-box span.golden-south-sea{background-position:-20px -625px;}
	}
	@media (max-width:768px){
		.collection .heading{margin-top:30px}
		.pearl-jewelry .heading{margin-top:10px; font-size:25px;}
		.pearl-jewelry .heading:before{top:68px;}
		.pearl-jewelry p{font-size:14px; padding:0px; margin-bottom:20px;}
		.shop-by-jewelry-type .jewelry-box .heading:before{top:85px;}
		.shop-by-jewelry-type .jewelry-box .img-box{min-height:250px;}
		.shop-by-jewelry-type .jewelry-box img{max-width:250px; margin:0 auto;}
		.shop-by-jewelry-type .jewelry-box img.ring{max-width:200px; margin:30px auto 0px;}
		.start-here .heading{margin-top:80px;}
		.start-here .heading:before{top:145px;}
		.jewelry-box .col-sm-7{margin-top:35px;}
	}
	html[data-useragent*='MSIE 9.0'] .review-slider .item .col-sm-4, html[data-useragent*='MSIE 9.0'] .review-slider .item .col-sm-8,
	html[data-useragent*='MSIE 10.0'] .review-slider .item .col-sm-4, html[data-useragent*='MSIE 10.0'] .review-slider .item .col-sm-8,
	html[data-useragent*='rv:11.0'] .review-slider .item .col-sm-4, html[data-useragent*='rv:11.0'] .review-slider .item .col-sm-4{
		float:left!important;
	}
	
	
</style>
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/css/slick-slider.css" media="all" />
<script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/js/slick.min.js"></script>
<script>
	function startHere(){
		jQuery('body').css({'overflow':'hidden'});
		jQuery('.black-back, #start-here').show();
	}
</script>
<section class="dark-bg max-padding-top max-padding-bottom">
	<div class="container max-padding-top max-padding-bottom">
		<div class="col-sm-6">
			<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/pearl/pearl-jewelry-main-banner.jpg" alt="Explore Cultured Pearl Jewelry" title="Angara's Pearl Jewelry" />
			<div class="absolute-placeholder collection pearl-jewelry">
				<h1 class="heading">Pearl Jewelry</h1>
				<p>Evoking a sense of timeless elegance, our esteemed collection of pearl jewelry exhibits superior quality, extraordinary style and remarkable craftsmanship. Choose from a wide array of masterpieces that beautifully capture the charm of the 'queen of gems'.</p>
			</div>
		</div>
		<div class="col-sm-6">
			<?php if(!strstr($_SERVER['HTTP_USER_AGENT'],'iPad')){ ?>
			<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/pearl/pearl-jewelry-title.jpg" alt="Cultured Pearl Jewelry By Angara" title="Explore Cultured Pearl Jewelry" />
			<div class="shop-by-color desktop collection text-center">
				<div class="col-sm-12 max-margin-bottom max-padding-bottom">
					<h2 class="heading">Shop By Color</h2>
					<p class="sub-heading">From pristine white to mysterious black and majestic golden, the choice in colors will delight every jewelry lover. Choose the color that fascinates you the most.</p>
				</div>
				<div class="clearfix"></div>
				<div class="col-sm-12 pearl-info max-margin-top">
					<div class="col-sm-4">
						<a href="/birthstone-jewelry/june-birthstone-pearl-jewelry?order=position&dir=asc&no_cache=true&filterable_stone_names=6416&icid=pearhome|color|white|09152016">
							<span class="image-box">
								<span class="white-akoya"></span>
							</span>
							<span class="title">White</span>
						</a>
					</div>
					<div class="col-sm-4">
						<a href="/birthstone-jewelry/june-birthstone-pearl-jewelry?order=position&dir=asc&no_cache=true&filterable_stone_names=6419&icid=pearhome|color|black|09152016">
							<span class="image-box">
								<span class="tahitian"></span>
							</span>
							<span class="title">Black</span>
						</a>
					</div>
					<div class="col-sm-4">
						<a href="/birthstone-jewelry/june-birthstone-pearl-jewelry?order=position&dir=asc&no_cache=true&filterable_stone_names=6417&icid=pearhome|color|golden|09152016">
							<span class="image-box">
								<span class="golden-akoya"></span>
							</span>
							<span class="title">Golden</span>
						</a>
					</div>
				</div>
			</div>
			<?php }else{ ?>
				<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/pearl/pearl-jewelry-title-ipad.jpg" alt="Cultured Pearl Jewelry By Angara" title="Explore Cultured Pearl Jewelry" />
			<?php } ?>
		</div>
		
		<?php if(strstr($_SERVER['HTTP_USER_AGENT'],'iPad')){ ?>
			<div class="col-sm-12 shop-by-color ipad pull-left collection text-center max-margin-top">
				<div class="col-sm-12 shop-by-color ipad collection text-center white-bg pull-left max-padding-bottom">
					<div class="col-sm-12 max-margin-bottom max-padding-bottom">
						<h2 class="heading">Shop By Color</h2>
						<p class="sub-heading">From pristine white to mysterious black and majestic golden, the choice in colors will delight every jewelry lover. Choose the color that fascinates you the most.</p>
					</div>
					<div class="clearfix"></div>
					<div class="col-sm-12 pearl-info pull-left max-margin-top max-padding-bottom">
						<div class="col-sm-4">
							<a href="/birthstone-jewelry/june-birthstone-pearl-jewelry?order=position&dir=asc&no_cache=true&filterable_stone_names=6416&icid=pearhome|color|white|09152016">
								<span class="image-box">
									<span class="white-akoya"></span>
								</span>
								<span class="title">White</span>
							</a>
						</div>
						<div class="col-sm-4">
							<a href="/birthstone-jewelry/june-birthstone-pearl-jewelry?order=position&dir=asc&no_cache=true&filterable_stone_names=6419&icid=pearhome|color|black|09152016">
								<span class="image-box">
									<span class="tahitian"></span>
								</span>
								<span class="title">Black</span>
							</a>
						</div>
						<div class="col-sm-4">
							<a href="/birthstone-jewelry/june-birthstone-pearl-jewelry?order=position&dir=asc&no_cache=true&filterable_stone_names=6417&icid=pearhome|color|golden|09152016">
								<span class="image-box">
									<span class="golden-akoya"></span>
								</span>
								<span class="title">Golden</span>
							</a>
						</div>
					</div>
				</div>
			</div>
		<?php } ?>
	</div>
</section>	

<section class="max-padding-bottom">
	<div class="container max-padding-bottom">
		<div class="col-sm-12 shop-by-jewelry-type collection text-center no-padding">
			<div class="col-sm-12 max-margin-bottom max-padding-bottom">
				<h2 class="heading">Shop By Jewelry Type</h2>
				<p class="sub-heading">Discover a gorgeous assortment of exquisitely crafted pendants, rings and earrings in a variety of appealing designs.</p>
			</div>
			<div class="clearfix"></div>
			<div class="col-sm-12 pull-left max-margin-top max-margin-bottom max-padding-bottom no-padding">
				<div class="col-sm-12 col-md-4">
					<div class="col-sm-12 jewelry-box no-padding pull-left max-margin-bottom">
						<div class="img-box pull-left col-md-12 col-sm-5 no-padding">
							<a href="/pendants/pearl-necklace-pendants?icid=pearhome|sbj|pendant|09072016">
								<img class="img-responsive pendant" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/pearl/pearl-pendant.jpg" alt="Explore Cultured Pearl Pendants" title="Angara's Pearl Pendants" />
							</a>
						</div>
						<div class=" col-md-12 col-sm-7 no-padding pull-left">
							<h2 class="heading">Pearl Pendants</h2>
							<p class="sub-heading">Authentic and versatile designs that embody unmatched luxury and grace.</p>
						</div>
						<div class=" col-md-12 col-sm-12 no-padding pull-left">
							<div class="col-sm-6 low-padding-right">
								<a class="pearl-button" href="/pendants/freshwater-cultured-pearl-pendant-necklaces?icid=pearhome|sbj|pendant|freshwater|09072016">Freshwater Pendants</a>
							</div>
							<div class="col-sm-6 low-padding-left">
								<a class="pearl-button" href="/pendants/akoya-cultured-pearl-pendant-necklaces?icid=pearhome|sbj|pendant|akoya|09072016">Akoya Pendants</a>
							</div>
							<div class="col-sm-6 low-padding-right">
								<a class="pearl-button" href="/pendants/pearl-necklace-pendants?icid=pearhome|sbj|pendant|tahitian|09072016&order=position&dir=asc&no_cache=true&filterable_stone_names=6419">Tahitian Pendants</a>
							</div>
							<div class="col-sm-6 low-padding-left">
								<a class="pearl-button" href="/pendants/south-sea-cultured-pearl-pendant-necklaces?icid=pearhome|sbj|pendant|southsea|09072016">South Sea Pendants</a>
							</div>
						</div>
						<div class=" col-md-12 col-sm-12 pull-left high-margin-bottom">
							<a class="pearl-button" href="/pendants/pearl-necklace-pendants?icid=pearhome|sbj|viewall|pendant|09072016">View All Pendants</a>	
						</div>
					</div>
				</div>
				<div class="col-sm-12 col-md-4">
					<div class="col-sm-12 jewelry-box no-padding pull-left max-margin-bottom">
						<div class="img-box pull-left col-md-12 col-sm-5 no-padding">
							<a href="/rings/pearl-rings?icid=pearhome|sbjt|rings|09072016">
								<img class="img-responsive ring" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/pearl/pearl-ring.jpg" alt="Explore Cultured Pearl Rings" title="Angara's Pearl Rings" />
							</a>
						</div>
						<div class=" col-md-12 col-sm-7 no-padding pull-left">
							<h2 class="heading">Pearl Rings</h2>
							<p class="sub-heading">Elegantly simple to extravagantly ornate, there’s a broad variety to choose from.</p>
						</div>
						<div class=" col-md-12 col-sm-12 no-padding pull-left">
							<div class="col-sm-6 low-padding-right">
								<a class="pearl-button" href="/rings/freshwater-cultured-pearl-rings?icid=pearhome|sbjt|rings|freshwater|09072016">Freshwater Rings</a>
							</div>
							<div class="col-sm-6 low-padding-left">
								<a class="pearl-button" href="/rings/akoya-cultured-pearl-rings?icid=pearhome|sbjt|rings|akoya|09072016">Akoya Rings</a>
							</div>
							<div class="col-sm-6 low-padding-right">
								<a class="pearl-button" href="/rings/pearl-rings?icid=pearhome|sbjt|rings|tahitian|09072016&order=position&dir=asc&no_cache=true&filterable_stone_names=6419">Tahitian Rings</a>
							</div>
							<div class="col-sm-6 low-padding-left">
								<a class="pearl-button" href="/rings/south-sea-cultured-pearl-rings?icid=pearhome|sbjt|rings|southsea|09072016">South Sea Rings</a>
							</div>
						</div>
						<div class=" col-md-12 col-sm-12 pull-left high-margin-bottom">
							<a class="pearl-button" href="/rings/pearl-rings?icid=pearhome|sbjt|viewall|rings|09072016">View All Rings</a>	
						</div>
					</div>
				</div>
				<div class="col-sm-12 col-md-4">
					<div class="col-sm-12 jewelry-box no-padding pull-left max-margin-bottom">
						<div class="img-box pull-left col-md-12 col-sm-5 no-padding">
							<a href="/earrings/pearl-earrings?icid=pearhome|sbjt|earrings|09072016">
								<img class="img-responsive earring" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/pearl/pearl-earring.jpg" alt="Explore Cultured Pearl Earrings" title="Angara's Pearl Earrings" />
							</a>
						</div>
						<div class=" col-md-12 col-sm-7 no-padding pull-left">
							<h2 class="heading">Pearl Earrings</h2>
							<p class="sub-heading">Flawlessly designed pieces that exude the essence of classic style.</p>
						</div>
						<div class=" col-md-12 col-sm-12 no-padding pull-left">
							<div class="col-sm-6 low-padding-right">
								<a class="pearl-button" href="/earrings/freshwater-cultured-pearl-earrings?icid=pearhome|sbjt|earrings|freshwater|09072016">Freshwater Earrings</a>
							</div>
							<div class="col-sm-6 low-padding-left">
								<a class="pearl-button" href="/earrings/akoya-cultured-pearl-earrings?icid=pearhome|sbjt|earrings|akoya|09072016">Akoya Earrings</a>
							</div>
							<div class="col-sm-6 low-padding-right">
								<a class="pearl-button" href="/earrings/pearl-earrings?order=position&dir=asc&no_cache=true&filterable_stone_names=6419&icid=pearhome|sbjt|earrings|tahitian|09072016">Tahitian Earrings</a>
							</div>
							<div class="col-sm-6 low-padding-left">
								<a class="pearl-button" href="/earrings/south-sea-cultured-pearl-earrings?icid=pearhome|sbjt|earrings|southsea|09072016">South Sea Earrings</a>
							</div>
						</div>
						<div class=" col-md-12 col-sm-12 pull-left high-margin-bottom">
							<a class="pearl-button" href="/earrings/pearl-earrings?icid=pearhome|sbjt|viewall|earrings|09072016">View All Earrings</a>	
						</div>
					</div>	
				</div>
			</div>
		</div>
	</div>
</section>

<section class="dark-bg max-padding-top">
	<div class="container max-padding-top">
		<div class="col-sm-12 shop-by-pearl-type collection text-center max-padding-bottom">
			<div class="col-sm-12 white-bg pull-left max-padding-bottom">
				<div class="col-sm-12 max-margin-bottom max-padding-bottom">
					<h2 class="heading">Shop By Pearl Type</h2>
					<p class="sub-heading">Pearls are classified into several categories on the basis of their origin. Explore jewelry that’s adorned with the pearl of your choice.</p>
				</div>
				<div class="clearfix"></div>
				<div class="col-sm-12 pearl-info pull-left max-margin-bottom max-padding-bottom">
					<div class="col-sm-4 col-md-2 pull-left max-margin-top">
						<a href="/jewelry/freshwater-cultured-pearl-jewelry?icid=pearhome|sbpt|freshwater|09072016">
							<span class="image-box">
								<span class="freshwater"></span>
							</span>
							<span class="title">Freshwater</span>
						</a>
					</div>
					<div class="col-sm-4 col-md-2 pull-left max-margin-top">
						<a href="/jewelry/akoya-cultured-pearl-jewelry?icid=pearhome|sbpt|akoya|09072016">
							<span class="image-box">
								<span class="white-akoya"></span>
							</span>
							<span class="title">White Akoya</span>
						</a>
					</div>
					<div class="col-sm-4 col-md-2 pull-left max-margin-top">
						<a href="/jewelry/golden-japanese-cultured-pearl-jewelry?icid=pearhome|sbpt|goldenjapanese|09072016">
							<span class="image-box">
								<span class="golden-akoya"></span>
							</span>
							<span class="title">Golden Japanese</span>
						</a>
					</div>
					<div class="col-sm-4 col-md-2 pull-left max-margin-top">
						<a href="/jewelry/tahitian-cultured-pearl-jewelry?icid=pearhome|sbpt|tahitian|09072016">
							<span class="image-box">
								<span class="tahitian"></span>
							</span>
							<span class="title">Tahitian</span>
						</a>
					</div>
					<div class="col-sm-4 col-md-2 pull-left max-margin-top">
						<a href="/jewelry/south-sea-cultured-pearl-jewelry/white-south-sea-cultured-pearl-jewelry?icid=pearhome|sbpt|whitesouthsea|09142016">
							<span class="image-box">
								<span class="white-south-sea"></span>
							</span>
							<span class="title">White South Sea</span>
						</a>
					</div>
					<div class="col-sm-4 col-md-2 pull-left max-margin-top">
						<a href="/jewelry/south-sea-cultured-pearl-jewelry/golden-south-sea-cultured-pearl-jewelry?icid=pearhome|sbpt|goldensouthsea|09142016">
							<span class="image-box">
								<span class="golden-south-sea"></span>
							</span>
							<span class="title">Golden South Sea</span>
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<section class="dark-bg max-padding-top">
	<div class="container max-padding-bottom max-padding-top">
		<div class="col-md-6 col-sm-12 recent-reviews collection pull-left max-margin-bottom">
			<div class="col-sm-12 no-padding-left <?php if(strstr($_SERVER['HTTP_USER_AGENT'],'iPad')){ echo 'no-padding-right'; }?>">
				<div class="col-sm-12 no-padding pull-left white-bg">
					<div class="col-sm-12 no-padding text-center max-margin-bottom max-padding-bottom">
						<h2 class="heading">Recent Reviews</h2>
					</div>
					<div class="clearfix"></div>
					<div class="col-sm-12 no-padding">
						<div id="review-slider" class="review-slider">
							<div class="item text-center">
								<div class="col-sm-4">
									<a href="/p/round-akoya-cultured-pearl-and-diamond-halo-pendant-sp0347pr">
										<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/pearl/sp0347pr.jpg" alt=""/>
									</a>
								</div>
								<div class="col-sm-8">
									<p>This pearl pendant has a lovely presence. It is a petite proportion as I wanted. The pearl itself has a nice patina which reflects the glow of the surrounding stones. It looks better in person than in the online photograph. This was a good purchase.</p>
									<div class="full-width">
										<div class="rating-box center-align">
											<div class="rating" style="width:100%;"></div>
										</div>
										<span><strong>- Luvsgems</strong></span>
									</div>
								</div>
							</div>
							<div class="item text-center">
								<div class="col-sm-4">
									<a href="/p/round-akoya-cultured-pearl-and-diamond-ring-sr0272pr">
										<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/pearl/sr0272prd.jpg" alt=""/>
									</a>
								</div>
								<div class="col-sm-8">
									<p>Between product quality and the time it took to get here was amazing. Also, receiving a phone call to verify all the information before the piece was actually crafted, was amazing as well. The lady was super nice over the phone and I'll be buying again from them.</p>
									<div class="full-width">
										<div class="rating-box center-align">
											<div class="rating" style="width:100%;"></div>
										</div>
										<span><strong>- Matt</strong></span>
									</div>
								</div>
							</div>
						</div>
						<script type="text/javascript">
						jQuery(document).ready(function(){
							jQuery('#review-slider').slick({
								arrows			: 	false,
								dots: true,
								slidesToShow	: 	1,
								slidesToScroll	: 	1,
								autoplay: true,
								autoplaySpeed: 5000
							});
						});
						</script>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-6 col-sm-12 pearl-education collection pull-left max-margin-bottom">
			<div class="col-sm-12 <?php if(strstr($_SERVER['HTTP_USER_AGENT'],'iPad')){ echo 'no-padding-right no-padding-left'; }?>">
				<div class="col-sm-12 no-padding pull-left white-bg">
					<div class="col-sm-12 no-padding text-center max-margin-bottom max-padding-bottom">
						<h2 class="heading">Pearl Education</h2>
					</div>
					<div class="clearfix"></div>
					<div class="col-sm-12 text-center">
						<p>Right from the birth of a pearl to the different pearl types and quality factors, we have all the information you’ll need to pick that perfect piece.</p>
						<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/pearl/pearl-education-bg.jpg" alt="Pearl Education" />
						<a class="pearl-button" href="/jewelry-guide/caring-for-pearls">Learn More</a>
					</div>
				</div>
			</div>
		</div>
		<?php /* <div class="col-md-4 col-sm-12 start-here collection pull-left max-margin-bottom">
			<div class="col-sm-12 no-padding-right <?php if(strstr($_SERVER['HTTP_USER_AGENT'],'iPad')){ echo 'no-padding-left'; }?>">
				<div class="col-sm-12 no-padding pull-left white-bg">
					<div class="col-sm-5 text-center max-margin-bottom max-padding-bottom">
						<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/pearl/pearl-start-here.jpg" alt="Start Here"/>
					</div>
					<div class="col-sm-7 max-margin-top text-center">
						<h2 class="heading">Start Here</h2>
						<p class="max-padding-left max-padding-right">Wondering where to start? Simply follow the steps in our guide to find pearl jewelry that suits your style.</p>
						<a class="pearl-button" href="javascript:void(0)" onclick="startHere();">Start Here</a>
					</div>
				</div>
			</div>
		</div> */ ?>
	</div>
</section>
<?php /*
<style>
	.black-back{position:fixed; left:0px; right:0px; top:0px; bottom:0px; display:none; background:rgba(0,0,0,0.5); z-index:100;}
	.start-here-popup{display:none; width:750px; height:400px; position:fixed; left:50%; top:50%; margin-left:-375px; margin-top:-200px; z-index:101;}
	.start-here-box{top:10px; bottom:10px; left:10px; right:10px;}
	
	.start-here-box .collection .heading:before{top:118px;}
	
	.start-here-box .process-indicator{bottom:-10px; left:-10px; right:-10px; line-height: 40px;}
	.start-here-box .process-indicator ul{margin-bottom:0px;}
	.start-here-box .process-indicator li{width:19%; float:left; display:block; text-align:center; margin-right:1%; background: #f7f7f7;}
	.start-here-box .process-indicator li.completed,
	.start-here-box .process-indicator li.active{color:#ffffff; background:#fa505a;}
	
	.start-here-box .shopping-assistant p{font-size:18px; margin:50px 20px 40px;}
	
	.start-here-box .button-holder{width:240px}
	.start-here-box .button-holder .pearl-button{width: 110px; margin-left: 10px; line-height: 40px; margin-top: 5px;}
	
	.start-here-box .sa.collection .heading{font-size: 30px; font-weight: normal; margin-top: 0px; margin-bottom: 0px; line-height: 50px;}
	.start-here-box .sa.collection .heading:before{display:none;}
	
	
</style>
<script>
	function switchNextTab(currentElem, elem){
		jQuery('#'+currentElem).addClass('hidden');
		jQuery('#'+elem).removeClass('hidden');
		
		//Mangae Process Indicator
		jQuery('.process-indicator ul li').each(function(){
			if(jQuery(this).attr('data-id') == currentElem){
				jQuery(this).addClass('completed').removeClass('active');
			}else if(jQuery(this).attr('data-id') == elem){
				jQuery(this).addClass('active');
			}
		});
	}
	
	function switchPrevTab(currentElem, elem){
		jQuery('#'+currentElem).addClass('hidden');
		jQuery('#'+elem).removeClass('hidden');
		
		//Mangae Process Indicator
		jQuery('.process-indicator ul li').each(function(){
			if(jQuery(this).attr('data-id') == currentElem){
				jQuery(this).removeClass('completed active');
			}else if(jQuery(this).attr('data-id') == elem){
				jQuery(this).addClass('active');
			}
		});
	}
	
</script>
<div class="black-back" onclick="jQuery(this).hide(); jQuery('#start-here').hide();"></div>
<div id="start-here" class="start-here-popup white-bg">
	<div class="absolute-placeholder start-here-box">
		<div class="col-sm-12 pull-left shopping-assistant collection text-center" id="shopping-assistant">
			<h2 class="heading">Shopping Assistant</h2>
			<p>Not sure where to start? Use this simple and easy 4-step guide to find the perfect piece of pearl jewelry for that special someonesss.</p>
			<a id="begin" class="pearl-button text-left" href="javascript:void(0)" onclick="switchNextTab('shopping-assistant','jewelry-type')">Begin <i class="fa fa-angle-right"></i></a>
			<!-- <a id="submit" href="javascript:void(0)">Submit</a> -->
		</div>
		<div class="col-sm-12 pull-left sa jewelry-type collection text-center hidden" id="jewelry-type">
			<div class="col-sm-12 no-padding pull-left">
				<h2 class="heading pull-left">Jewelry Type</h2>
				<div class="button-holder pull-right">
					<a class="pearl-button text-left pull-left high-margin-right" href="javascript:void(0)" onclick="switchPrevTab('jewelry-type','shopping-assistant')"><i class="fa fa-angle-left"></i> Back</a>
					<a class="pearl-button text-left pull-left" href="javascript:void(0)" onclick="switchNextTab('jewelry-type','pearl-color')">Next <i class="fa fa-angle-right"></i></a>
				</div>
			</div>
			<div class="col-sm-12 no-padding pull-left">
				<div class="col-sm-4 pull-left" id="jewelry-type-pendant">
					<img src="" alt=""/>
					<br>
					<span>Pendant</span>
				</div>
				<div class="col-sm-4 pull-left" id="jewelry-type-ring">
					<img src="" alt=""/>
					<br>
					<span>Ring</span>
				</div>
				<div class="col-sm-4 pull-left" id="jewelry-type-earring">
					<img src="" alt=""/>
					<br>
					<span>Earring</span>
				</div>
				<span id="jewelry-type-holder" class="hidden" data-value=""></span>
			</div>
		</div>
		<div class="col-sm-12 pull-left sa pearl-color collection text-center hidden" id="pearl-color">
			<div class="col-sm-12 no-padding pull-left">
				<h2 class="heading pull-left">Pearl Color</h2>
				<div class="button-holder pull-right">
					<a class="pearl-button text-left pull-left" href="javascript:void(0)" onclick="switchPrevTab('pearl-color','jewelry-type')"><i class="fa fa-angle-left"></i> Back</a>
					<a class="pearl-button text-left pull-left" href="javascript:void(0)" onclick="switchNextTab('pearl-color','pearl-type')">Next <i class="fa fa-angle-right"></i></a>
				</div>
			</div>
			<div class="col-sm-12 no-padding pull-left">
				<div class="col-sm-4 pull-left" id="pearl-color-white">
					<img src="" alt=""/>
					<br>
					<span>White</span>
				</div>
				<div class="col-sm-4 pull-left" id="pearl-color-black">
					<img src="" alt=""/>
					<br>
					<span>Black</span>
				</div>
				<div class="col-sm-4 pull-left" id="pearl-color-golden">
					<img src="" alt=""/>
					<br>
					<span>Golden</span>
				</div>
				<span id="pearl-color-holder" class="hidden" data-value=""></span>
			</div>
		</div>
		<div class="col-sm-12 pull-left sa pearl-type collection text-center hidden" id="pearl-type">
			<div class="col-sm-12 no-padding pull-left">
				<h2 class="heading pull-left">Pearl Type</h2>
				<div class="button-holder pull-right">
					<a class="pearl-button text-left pull-left high-margin-right" href="javascript:void(0)" onclick="switchPrevTab('pearl-type','pearl-color')"><i class="fa fa-angle-left"></i> Back</a>
					<a class="pearl-button text-left pull-left" href="javascript:void(0)" onclick="switchNextTab('pearl-type','price-range')">Next <i class="fa fa-angle-right"></i></a>
				</div>
			</div>
			<div class="col-sm-12 no-padding pull-left">
				<div class="col-sm-4 pull-left" id="pearl-color-white">
					<img src="" alt=""/>
					<br>
					<span>Freshwater</span>
				</div>
				<div class="col-sm-4 pull-left" id="pearl-color-black">
					<img src="" alt=""/>
					<br>
					<span>Akoya</span>
				</div>
				<div class="col-sm-4 pull-left" id="pearl-color-golden">
					<img src="" alt=""/>
					<br>
					<span>Tahitian</span>
				</div>
				<div class="col-sm-4 pull-left" id="pearl-color-golden">
					<img src="" alt=""/>
					<br>
					<span>Japanese</span>
				</div>
				<div class="col-sm-4 pull-left" id="pearl-color-golden">
					<img src="" alt=""/>
					<br>
					<span>South Sea</span>
				</div>
				<span id="pearl-color-holder" class="hidden" data-value=""></span>
			</div>
		</div>
		<div class="col-sm-12 pull-left sa price-range collection text-center hidden" id="price-range">
			<div class="col-sm-12 no-padding pull-left">
				<h2 class="heading pull-left">Price Range</h2>
				<div class="button-holder pull-right">
					<a class="pearl-button text-left pull-right" href="javascript:void(0)" onclick="switchPrevTab('price-range','pearl-type')"><i class="fa fa-angle-left"></i> Back</a>
				</div>
			</div>
			<div class="col-sm-12 no-padding pull-left">
			
			</div>
		</div>
		
		
		
		<div class="process-indicator absolute-placeholder">
			<ul class="col-sm-12 pull-left no-padding">
				<li class="introduction active" data-id="shopping-assistant">Introduction</li>
				<li class="jewelry-type" data-id="jewelry-type">Jewelry Type</li>
				<li class="pearl-color" data-id="pearl-color">Pearl Color</li>
				<li class="pearl-type" data-id="pearl-type">Pearl Type</li>
				<li class="price-range" data-id="price-range">Price Range</li>
			</ul>
		</div>
	</div>
</div>

<script type="text/javascript">
    jQuery(document).ready(function() {
      jQuery('#submit').click(function(){
			var jewelryType = 'rings',
			pearlColor = 'black',
			pearlType = 'tahitian',
			priceRange = '0-500';
			if(jewelryType == 'rings' && pearlColor=='black' && pearlType=='tahitian' && priceRange=='0-500'){
				window.location = "/rings/pearl-rings?order=position&dir=asc&no_cache=true&filterable_stone_names=6419";
			}else if(jewelryType == 'rings' && pearlColor=='white' && pearlType=='akoya' && priceRange=='0-500'){
				window.location = "/rings/pearl-rings?order=position&dir=asc&no_cache=true&filterable_stone_names=6416";
			}
		});
    });
</script> 

*/ ?>










