<section class="container">
	<div class="col-md-12 val-block block-1">
		<div class="col-md-12"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/valentine/angara-place-holder-png.png" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/valentine/row1-bg.jpg"/></div>
		<div class="col-md-12 blk-text">Radiant Love Collection<br><span>Happiness is Giving</span></div>
	</div>
	<div class="clearfix"></div>
	<div class="col-md-6 col-sm-12 val-block block-2">
		<div class="col-md-12"><a href="/jewelry/ruby-jewelry?icid=Valentinepage|rj|02072016" style="display:block"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/valentine/angara-place-holder-png.png" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/valentine/row2-bg.jpg"/></a></div>

		<div class="col-md-12 blk-text"><div class="border-bottom">The Essence of Passionate Love</div></div>
		<div class="col-md-12 blk-button"><a href="/jewelry/ruby-jewelry?icid=Valentinepage|rj|02072016">Browse Our Ruby Jewelry</a></div>
	</div>
	<div class="col-md-6 col-sm-12 val-block block-3">
		<div class="col-md-12"><a href="/jewelry/ruby-jewelry?icid=Valentinepage|rj|02072016" style="display:block"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/valentine/angara-place-holder-png.png" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/valentine/row3-bg.jpg"/></a></div>
	</div>
	<div class="clearfix"></div>
	<div class="col-md-6 col-sm-12 val-block block-4">
		<div class="col-md-12"><a href="/jewelry/tanzanite-jewelry?icid=Valentinepage|tj|02072016" style="display:block"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/valentine/angara-place-holder-png.png" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/valentine/row4-bg.jpg"/></a></div>
	</div>
	<div class="col-md-6 col-sm-12 val-block block-5">
		<div class="col-md-12"><a href="/jewelry/tanzanite-jewelry?icid=Valentinepage|tj|02072016" style="display:block"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/valentine/angara-place-holder-png.png" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/valentine/row5-bg.jpg"/></a></div>

		<div class="col-md-12 blk-text"><div class="border-bottom">A Token of Love, Hope and Purity</div></div>
		<div class="col-md-12 blk-button"><a href="/jewelry/tanzanite-jewelry?icid=Valentinepage|tj|02072016">Browse Our Tanzanite Jewelry</a></div>
	</div>
	<div class="clearfix"></div>
	<div class="col-md-12 val-block block-6">
		<div class="col-md-12"><a href="/jewelry/sapphire-jewelry?icid=Valentinepage|sj|02072016" style="display:block"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/valentine/angara-place-holder-png.png" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/valentine/row6-bg.jpg"/></a></div>

		<div class="col-md-12 blk-text"><div class="border-bottom">Symbol of Truth and Sincerity</div></div>
		<div class="col-md-12 blk-button"><a href="/jewelry/sapphire-jewelry?icid=Valentinepage|sj|02072016">Browse Our Sapphire Jewelry</a></div>
	</div>
	<div class="clearfix"></div>
	<div class="col-md-12 val-block block-7">
		<div class="col-md-12"><a href="/jewelry/emerald-jewelry?icid=Valentinepage|ej|02072016" style="display:block"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/valentine/angara-place-holder-png.png" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/valentine/row7-bg.jpg"/></a></div>

		<div class="col-md-12 blk-text"><div class="border-bottom">A Symbol of Everlasting Love</div></div>
		<div class="col-md-12 blk-button"><a href="/jewelry/emerald-jewelry?icid=Valentinepage|ej|02072016">Browse Our Emerald Jewelry</a></div>
	</div>
	<div class="clearfix"></div>
	<div class="col-md-12 val-block block-8">
		<div class="col-md-6"><a href="/jewelry/diamond-jewelry?icid=Valentinepage|dj|02072016" style="display:block"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/valentine/angara-place-holder-png.png" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/valentine/row8-bg.jpg"/></a></div>

		<div class="txt-holder">
			<div class="col-md-12 blk-text"><div class="border-bottom">For Love That's Pure and Kind</div></div>
			<div class="col-md-12 blk-button"><a href="/jewelry/diamond-jewelry?icid=Valentinepage|dj|02072016">Browse Our Diamond Jewelry</a></div>
		</div>
	</div>
	<div class="clearfix"></div>
	<div class="col-md-6 col-sm-12 val-block block-9">
		<div class="col-md-12"><a href="/jewelry/knot-jewelry?icid=Valentinepage|kj|02072016" style="display:block"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/valentine/angara-place-holder-png.png" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/valentine/row9-bg.jpg"/></a></div>

	</div>
	<div class="col-md-6 col-sm-12 val-block block-10">
		<div class="col-md-12 blk-text"><div class="border-bottom">Reflection of Eternal Love</div></div>
		<div class="col-md-12 blk-button"><a href="/jewelry/knot-jewelry?icid=Valentinepage|kj|02072016">Browse Our Love Knot Jewelry</a></div>
	</div>
	<div class="clearfix"></div>
	<div class="col-md-12 val-block block-11">
		<div class="col-md-12"><a href="/engagement-rings/promise-rings?icid=Valentinepage|promise-r|02072016" style="display:block"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/valentine/angara-place-holder-png.png" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/valentine/row11-bg.jpg"/></a></div>

		<div class="col-md-12 blk-text"><div class="border-bottom">SOME THINGS YOU DON'T HAVE TO PROMISE. YOU JUST DO.</div></div>
		<div class="col-md-12 blk-button"><a href="/engagement-rings/promise-rings?icid=Valentinepage|promise-r|02072016">Browse Our Promise Rings</a></div>
	</div>
	<div class="clearfix"></div>
	<div class="col-md-12 val-block block-12">
		<div class="col-md-12"><a href="/catalogsearch/result/?q=Heart+Jewelry&dir=asc?icid=Valentinepage|heart-j|02072016" style="display:block"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/valentine/angara-place-holder-png.png" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/valentine/row12-bg.jpg"/></a></div>
		<div class="col-md-12 blk-text"><div class="border-bottom">An Expression of Tender Love</div></div>
		<div class="col-md-12 blk-button"><a href="/catalogsearch/result/?q=Heart+Jewelry&dir=asc?icid=Valentinepage|heart-j|02072016">Browse Our Heart Jewelry</a></div>
	</div>
	<div class="clearfix"></div>
	<div class="col-md-12 val-block block-13">
		<div class="col-md-12"><a href="/earrings/stud-earrings?icid=Valentinepage|stud-earrings|02072016" style="display:block"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/valentine/angara-place-holder-png.png" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/valentine/row13-bg.jpg"/></a></div>

		<div class="col-md-12 blk-text"><div class="border-bottom">Studded to Perfection</div></div>
		<div class="col-md-12 blk-button"><a href="/earrings/stud-earrings?icid=Valentinepage|stud-earrings|02072016">Browse Our Stud Earrings</a></div>
	</div>
	<div class="clearfix"></div>
	<div class="col-md-12 val-block block-14">
		<div class="col-md-12"><a href="/wedding-rings/mens-wedding-bands?icid=Valentinepage|mens-band|02072016" style="display:block"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/valentine/angara-place-holder-png.png" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/valentine/row14-bg.jpg"/></a></div>

		<div class="col-md-12 blk-text"><div class="border-bottom">For Him</div></div>
		<div class="col-md-12 blk-button"><a href="/wedding-rings/mens-wedding-bands?icid=Valentinepage|mens-band|02072016">Browse Our Men's Band</a></div>
	</div>
	<div class="clearfix"></div>
	<div class="col-md-12 val-block block-15">
		<div class="col-md-12"><a href="/top-twenty-gifts?icid=Valentinepage|top-20|02072016" style="display:block"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/valentine/angara-place-holder-png.png" data-org="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/valentine/row15-bg.jpg"/></a></div>

		<div class="col-md-12 blk-text"><div class="border-bottom">Top Twenty Valentine's Gifts</div></div>
		<div class="col-md-12 blk-button"><a href="/top-twenty-gifts?icid=Valentinepage|top-20|02072016">Browse Our Gifts</a></div>
	</div>
	<div class="clearfix"></div>
</section>