<style>
.gray-box img{
	width:100%!important;
}

<?php if(strstr($_SERVER['HTTP_USER_AGENT'],'iPad')){ ?>
.wear-your-luck .details-justify a:hover, .wear-your-luck .details-justify a.active, .wear-your-luck .details-justify a:focus {
    color: #ffffff !important;
    border: 1px solid #ffffff;
}

.info-popup .dismiss-popup {right:40px !important;}
<?php } ?>
</style>
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/css/slick-slider.css" media="all" />
<script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/js/slick.min.js"></script>

<div class="wyl-main-banner relative-placeholder max-margin-bottom max-padding-bottom" id="wyl--banner"> 
	<div class="slide-banner">
		<a href="/jewelry/wear-your-luck?icid=wearurluckpage|home|hb|04062017" >
			<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/main-banner.jpg" alt="Wear Your Lucky Jewelry" title="Wear Your Lucky Jewelry">
		</a>
	</div>
	<div class="slide-banner">
		<a href="/jewelry/wear-your-luck?icid=wearurluckpage|home|hb|04062017" >
			<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/main-banner-two.jpg" alt="Wear Your Lucky Jewelry" title="Wear Your Lucky Jewelry">
		</a>
	</div>
</div>

<script type="text/javascript">
			jQuery(document).ready(function(){
				jQuery('#wyl--banner').slick({
					arrows			: 	false,
					dots: false,
					slidesToShow	: 	1,
					slidesToScroll	: 	1,
					autoplay: true,
					autoplaySpeed: 5000,
					adaptiveHeight: true
				});
			});
</script>

<div class="clearfix"></div>
<section class="container wear-your-luck">
    <div class="about-collection col-xs-12 max-padding-bottom text-center">
		<div class="about-title low-margin-bottom">About Collection</div>
		<div class="about-text">Intricately crafted to enchant, each jewelry piece is unique and significant in its own way. These symbols of good luck and prosperity are adorned with glimmering gems that take the design to new heights. Wear them to attract the good things in life or to simply make a powerful statement of style.</div>
	</div>
    <div class="tab-holder col-xs-12 no-padding max-margin-bottom max-margin-top">
        <ul class="tab">
            <li>
                <a href="javascript:void(0)" data-go-to="#Clover" id="come2top">
					<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/clover.svg" alt="" />
					<span class="text-center">Clover</span>
				</a>
            </li>
            <li>
				<a href="javascript:void(0)" data-go-to="#HorSeShoe">
					<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/horseshoe.svg" alt="" />
					<span class="text-center">Horse Shoe</span>
				</a>
            </li>
            <li>
				<a href="javascript:void(0)" data-go-to="#Hamsa">
					<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/hamsa.svg" alt="" />
					<span class="text-center">Hamsa</span>
				</a>
            </li>
            <li>
				<a href="javascript:void(0)" data-go-to="#EvilEye">
					<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/evileye.svg" alt="" />
					<span class="text-center">Evil Eye</span>
				</a>
            </li>
            <li>
				<a href="javascript:void(0)" data-go-to="#Key">
					<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/key.svg" alt="" />
					<span class="text-center">Key</span>
				</a>
            </li>
			<li>
				<a href="javascript:void(0)" data-go-to="#Cross">
					<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/cross.svg" alt="" />
					<span class="text-center">Cross/Faith</span>
				</a>
            </li>
			<li>
				<a href="javascript:void(0)" data-go-to="#ShootingStar">
					<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/shootingstar.svg" alt="" />
					<span class="text-center">Shooting Star</span>
				</a>
            </li>
			<li>
				<a href="javascript:void(0)" data-go-to="#StarofDavid">
					<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/starofdavid.svg" alt="" />
					<span class="text-center">Star of David</span>
				</a>
            </li>
			<li>
				<a href="javascript:void(0)" data-go-to="#WishBone">
					<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/wishbone.svg" alt="" />
					<span class="text-center">Wish Bone</span>
				</a>
            </li>
			<li>
				<a href="javascript:void(0)" data-go-to="#Peace">
					<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/peace.svg" alt="" />
					<span class="text-center">Peace</span>
				</a>
            </li>
			<li>
				<a href="javascript:void(0)" data-go-to="#Wheel">
					<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/wheel.svg" alt="" />
					<span class="text-center">Wheel</span>
				</a>
            </li>
			<li>
				<a href="javascript:void(0)" data-go-to="#YinYang">
					<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/yinyang.svg" alt="" />
					<span class="text-center">Yin Yang</span>
				</a>
            </li>
			<li>
				<a href="javascript:void(0)" data-go-to="#Axe">
					<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/axe.svg" alt="" />
					<span class="text-center">Axe</span>
				</a>
            </li>
			<li>
				<a href="javascript:void(0)" data-go-to="#BarnStar">
					<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/barnstar.svg" alt="" />
					<span class="text-center">Barn Star</span>
				</a>
            </li>
        </ul>
    </div>
    <div class="clearfix"></div>
    <div class="col-sm-12 col-xs-12 no-padding info-holder full-width max-margin-top max-margin-bottom table-row" id="Clover">
		<div class="col-sm-6 col-xs-12 no-padding table-cell gray-box">
            <img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/bg-1.jpg" alt="Lucky Clover Jewelry" title="Lucky Clover Jewelry">
        </div>
        <div class="col-sm-6 col-xs-12 no-padding table-cell apri-box explr-btn" popup-id="#clover-popup">
            <div class="details-box text-center">
                <h1>Discover Good Fortune</h1>
				<div class="details-justify">
					<span class="sab-head">Clover</span>
					<p>A clover is a traditional symbol of luck. Each leaf on the clover represents a different characteristic, namely health, wealth, love and fame. Carry your luck wherever you go by wearing gorgeous clover jewelry.</p>
					<a href="javascript:void(0)" >Explore Collection</a>
				</div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
	<div class="col-sm-12 col-xs-12 no-padding info-holder full-width max-margin-bottom table-row" id="HorSeShoe">
		<div class="col-sm-6 col-xs-12 no-padding table-cell gray-box">
            <img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/bg-2.jpg" alt="Lucky Horseshoe Jewelry" title="Lucky Horseshoe Jewelry">
        </div>
        <div class="col-sm-6 col-xs-12 no-padding table-cell apri-box explr-btn" popup-id="#Horseshoe-popup">
            <div class="details-box text-center">
                <h1> Luck is Yours</h1>
				<div class="details-justify">
					<span class="sab-head">Horseshoe</span>
					<p>The horseshoe symbol is commonly considered as a sign of good luck and protection. Adorn yourself with an ornate horseshoe for that extra boost of luck whenever you need it.</p>
					<a href="javascript:void(0)">Explore Collection</a>
				</div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
	<div class="col-sm-12 col-xs-12 no-padding info-holder full-width max-margin-bottom table-row" id="Hamsa">
		<div class="col-sm-6 col-xs-12 no-padding table-cell gray-box">
            <img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/bg-3.jpg" alt="Hamsa Hand Lucky Jewelry" title="Hamsa Hand Lucky Jewelry">
        </div>
        <div class="col-sm-6 col-xs-12 no-padding table-cell apri-box explr-btn" popup-id="#Hamsa-popup">
            <div class="details-box text-center">
                <h1>Love & Protection</h1>
				<div class="details-justify">
					<span class="sab-head">Hamsa /Fatima hand</span>
					<p>Symbolizing the hand of God, the Hamsa was used as an amulet in ancient times. It is also believed to be a protective sign by most faiths. Wear this symbol to attract love, happiness, health and good fortune.</p>
					<a href="javascript:void(0)">Explore Collection</a>
				</div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
	<div class="col-sm-12 col-xs-12 no-padding info-holder full-width max-margin-bottom table-row" id="EvilEye">
		<div class="col-sm-6 col-xs-12 no-padding table-cell gray-box">
            <img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/bg-4.jpg" alt="Evil Eye Lucky Jewelry" title="Evil Eye Lucky Jewelry">
        </div>
        <div class="col-sm-6 col-xs-12 no-padding table-cell apri-box">
            <div class="details-box text-center">
                <h1>Protect Your Aura</h1>
				<div class="details-justify">
					<span class="sab-head">Evil Eye</span>
					<p>An evil eye is a lucky charm that protects the wearer from curses caused due to malevolent glares, also known as the evil eye. Ward off misfortunes, bad luck or injury by wearing evil eye jewelry.</p>
					<a href="/p/blue-sapphire-evil-eye-pendant-with-diamond-accents-sp1194sd?icid=wearurluckpage|evil-eye|sp1194sd|04062017">Shop Now</a>
				</div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
	<div class="col-sm-12 col-xs-12 no-padding info-holder full-width max-margin-bottom table-row" id="Key">
		<div class="col-sm-6 col-xs-12 no-padding table-cell gray-box">
            <img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/bg-5.jpg" alt="Lucky Key Jewelry" title="Lucky Key Jewelry">
        </div>
        <div class="col-sm-6 col-xs-12 no-padding table-cell apri-box explr-btn" popup-id="#Key-popup">
            <div class="details-box text-center">
                <h1>Unlock New Possibilities</h1>
				<div class="details-justify">
					<span class="sab-head">Key</span>
					<p>The key is symbolic of new paths, new adventures and new undertakings. Wear an ornate key as a reminder to yourself that you hold the key to your future and there is nothing that you can't overcome.</p>
					<a href="javascript:void(0)">Explore Collection</a>
				</div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
	<div class="col-sm-12 col-xs-12 no-padding info-holder full-width max-margin-bottom table-row" id="Cross">
		<div class="col-sm-6 col-xs-12 no-padding table-cell gray-box">
            <img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/bg-6.jpg" alt="Religious lucky Jewelry" title="Religious lucky Jewelry">
        </div>
        <div class="col-sm-6 col-xs-12 no-padding table-cell apri-box explr-btn" popup-id="#Cross-popup">
            <div class="details-box text-center">
                <h1>Celebrate your faith with endless sparkle!</h1>
				<div class="details-justify">
					<span class="sab-head">Faith/Cross</span>
					<p>The cross is worn as an indication of one's commitment to the Christian faith. It is also believed to protect the wearer from evil. Express your faith in style without having to say a word by donning cross jewelry.</p>
					<a href="javascript:void(0)">Explore Collection</a>
				</div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
	<div class="col-sm-12 col-xs-12 no-padding info-holder full-width max-margin-bottom table-row" id="ShootingStar">
		<div class="col-sm-6 col-xs-12 no-padding table-cell gray-box">
            <img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/bg-7.jpg" alt="Shooting Star Jewelry" title="Shooting Star Jewelry">
        </div>
        <div class="col-sm-6 col-xs-12 no-padding table-cell apri-box">
            <div class="details-box text-center">
                <h1>Wish upon a Star</h1>
				<div class="details-justify">
					<span class="sab-head">Shooting Star</span>
					<p>A shooting star is considered to be a sign of good luck. It is a symbol of magic, dreams and wishes. Adorn this sparkling symbol of hope to draw positivity into your life.</p>
					<a href="/p/cluster-diamond-shooting-star-pendant-sp1197d?icid=wearurluckpage|shooting-star|sp1197d|04062017">Shop Now</a>
				</div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
	<div class="col-sm-12 col-xs-12 no-padding info-holder full-width max-margin-bottom table-row" id="StarofDavid">
		<div class="col-sm-6 col-xs-12 no-padding table-cell gray-box">
            <img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/bg-8.jpg" alt="Star of David Jewelry" title="Star of David Jewelry">
        </div>
        <div class="col-sm-6 col-xs-12 no-padding table-cell apri-box">
            <div class="details-box text-center">
                <h1>Guard Yourself</h1>
				<div class="details-justify">
					<span class="sab-head">Star of David</span>
					<p>The shield of David, more commonly known as the star of David, is a symbol associated with Judaism. It represents the belief that God protects you from all six directions. Adorn the star of David jewelry for protection and blessings to achieve your goals.</p>
					<a href="/p/star-of-david-diamond-pendant-with-milgrain-sp1198d?icid=wearurluckpage|star-of-david|sp1198d|04062017">Shop Now</a>
				</div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
	<div class="col-sm-12 col-xs-12 no-padding info-holder full-width max-margin-bottom table-row" id="WishBone">
		<div class="col-sm-6 col-xs-12 no-padding table-cell gray-box">
            <img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/bg-9.jpg" alt="Lucky Wishbone Jewelry" title="Lucky Wishbone Jewelry">
        </div>
        <div class="col-sm-6 col-xs-12 no-padding table-cell apri-box explr-btn" popup-id="#Wishbone-popup">
            <div class="details-box text-center">
                <h1>Make a Wish</h1>
				<div class="details-justify">
					<span class="sab-head">Wishbone</span>
					<p>Wishbones are associated with the Thanksgiving tradition of tugging on the V-shaped bone, obtained from the carcass of the turkey, and making a wish. Wear wishbone jewelry as a reminder to wish big and make it happen.</p>
					<a href="javascript:void(0)">Explore Collection</a>
				</div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
	<div class="col-sm-12 col-xs-12 no-padding info-holder full-width max-margin-bottom table-row" id="Peace">
		<div class="col-sm-6 col-xs-12 no-padding table-cell gray-box">
            <img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/bg-10.jpg" alt="Peace Sign Jewelry" title="Peace Sign Jewelry">
        </div>
        <div class="col-sm-6 col-xs-12 no-padding table-cell apri-box explr-btn" popup-id="#Peace-popup">
            <div class="details-box text-center">
                <h1>Find Peace</h1>
				<div class="details-justify">
					<span class="sab-head">Peace</span>
					<p>Originally created to signify nuclear disarmament, the peace sign has become a popular jewelry motif. Wear it to silently support a cause or simply adorn the symbol of universal peace as a personal style statement.</p>
					<a href="javascript:void(0)">Explore Collection</a>
				</div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
	<div class="col-sm-12 col-xs-12 no-padding info-holder full-width max-margin-bottom table-row" id="Wheel">
		<div class="col-sm-6 col-xs-12 no-padding table-cell gray-box">
            <img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/bg-11.jpg" alt="Wheel of Life Jewelry" title="Wheel of Life Jewelry">
        </div>
        <div class="col-sm-6 col-xs-12 no-padding table-cell apri-box">
            <div class="details-box text-center">
                <h1>Wheel of Life</h1>
				<div class="details-justify">
					<span class="sab-head">Wheel</span>
					<p>The wheel symbolizes the circulatory motion of wealth and prosperity in life. Adorn wheel jewelry to remind yourself that everything in life is temporary, and that change is inevitable.</p>
					<a href="/p/round-diamond-wheel-of-life-pendant-sp1201d?icid=wearurluckpage|wheel|sp1201d|04062017">Shop Now</a>
				</div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
	<div class="col-sm-12 col-xs-12 no-padding info-holder full-width max-margin-bottom table-row" id="YinYang">
		<div class="col-sm-6 col-xs-12 no-padding table-cell gray-box">
            <img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/bg-12.jpg" alt="Yin Yang Jewelry" title="Yin Yang Jewelry">
        </div>
        <div class="col-sm-6 col-xs-12 no-padding table-cell apri-box">
            <div class="details-box text-center">
                <h1>Find Your Balance</h1>
				<div class="details-justify">
					<span class="sab-head">Yin Yang</span>
					<p>The Yin-Yang is a historical symbol that represents harmony and balance within the universe. It promotes the belief that opposites or seemingly contrary forces are interconnected. Wear Yin-Yang jewelry to indicate the need for balance in all things.</p>
					<a href="/p/black-and-white-diamond-yin-yang-pendant-sp1202bkdd?icid=wearurluckpage|yin-yang|sp1202bkdd|04062017">Shop Now</a>
				</div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
	<div class="col-sm-12 col-xs-12 no-padding info-holder full-width max-margin-bottom table-row" id="Axe">
		<div class="col-sm-6 col-xs-12 no-padding table-cell gray-box">
            <img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/bg-13.jpg" alt="Axe Jewelry" title="Axe Jewelry">
        </div>
        <div class="col-sm-6 col-xs-12 no-padding table-cell apri-box">
            <div class="details-box text-center">
                <h1>Aim Big</h1>
				<div class="details-justify">
					<span class="sab-head">Axe</span>
					<p>Since the ancient times, the axe as a symbol is believed to attract success. Historical art depicts double bladed axes as a sign of power. Adorn ornate axe jewelry to bring in success and positivity.</p>
					<a href="/p/prong-set-diamond-axe-pendant-sp1203d?icid=wearurluckpage|axe|sp1203d|04062017">Shop Now</a>
				</div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
	<div class="col-sm-12 col-xs-12 no-padding info-holder full-width low-margin-top max-margin-bottom table-row" id="BarnStar">
		<div class="col-sm-6 col-xs-12 no-padding table-cell gray-box">
            <img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/bg-14.jpg" alt="Lucky Barnstar Jewelry" title="Lucky Barnstar Jewelry">
        </div>
        <div class="col-sm-6 col-xs-12 no-padding table-cell apri-box explr-btn" popup-id="#Barnstar-popup">
            <div class="details-box text-center">
                <h1>Attract Good Luck</h1>
				<div class="details-justify">
					<span class="sab-head">Barnstar</span>
					<p>Barnstars are decorative five-sided stars that were usually painted outside houses and barns. They are believed to bring in good fortune. Wear this symbol to attract a little extra luck when required.</p>
					<a href="javascript:void(0)">Explore Collection</a>
				</div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
    
</section>

<div class="info-popup hide">
		<img class="img-responsive dismiss-popup" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default//images/optionpopupclose.png" style="position: absolute;right:65px;width:20px;top:40px;cursor: pointer; z-index: 1;">
		
		<div class="col-sm-12 no-padding hide popup-holder" id="clover-popup">
			<div class="popup-overflow">
			<div class="col-sm-6 no-padding big-img-box">
				<div class="pro-img full-width">
					<a href="/p/round-emerald-and-diamond-border-clover-pendant-sp0178e?icid=wearurluckpage|clover|sp0178e|04062017">
						<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/clover-1.png" alt="Diamond Framed Emerald Clover Pendant Necklace" />
					</a>
				</div>
				<div class="pro-info text-center">
					<a class="pro-title full-width" href="/p/round-emerald-and-diamond-border-clover-pendant-sp0178e?icid=wearurluckpage|clover|sp0178e|04062017">Diamond Framed Emerald Clover Pendant Necklace</a>
					<div class="pro-details-btn full-width" >
						<div class="pro-price apricot-text low-margin-top">$379 - $1,829</div>
						<a class="btn add-view-btn" href="/p/round-emerald-and-diamond-border-clover-pendant-sp0178e?icid=wearurluckpage|clover|sp0178e|04062017">Shop Now</a>
					</div>
				</div>
			</div>
			<div class="col-sm-6 no-padding small-img-box">
				<div class="find-more-txt col-sm-12 max-padding-bottom max-margin-bottom">Explore more from this collection</div>
				<div class="find-more-img col-sm-12 no-padding">
					<div class="col-sm-3 collection-img high-padding-top high-padding-bottom active">
						<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/clover-1.png" class="img-responsive small-image" data-name="Diamond Framed Emerald Clover Pendant Necklace" data-trackurl="/p/round-emerald-and-diamond-border-clover-pendant-sp0178e?icid=wearurluckpage|clover|sp0178e|04062017" data-price="$379 - $1,829" />
					</div>
					<div class="col-sm-3 collection-img high-padding-top high-padding-bottom">
						<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/clover-2.png" class="img-responsive small-image" data-name="Round Diamond Clover Station Necklace" data-trackurl="/p/round-diamond-clover-station-necklace-sp1199d?icid=wearurluckpage|clover|sp1199d|04062017" data-price="$439 - $709" />
					</div>
					<div class="col-sm-3 collection-img high-padding-top high-padding-bottom">
						<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/clover-3.png" class="img-responsive small-image" data-name="Classic Emerald Four Petal Clover Pendant" data-trackurl="/p/classic-emerald-four-petal-flower-pendant-sp0756e?icid=wearurluckpage|clover|sp0756e|04062017" data-price="$329 - $1,279" />
					</div>
					<div class="col-sm-3 collection-img high-padding-top high-padding-bottom">
						<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/clover-4.png" class="img-responsive small-image" data-name="Round Diamond Clover Dangle Earrings" data-trackurl="/p/leverback-round-diamond-flower-dangle-earrings-se1227d?icid=wearurluckpage|clover|se1227d|04062017" data-price="$739 - $3,129" />
					</div>
					<div class="col-sm-3 collection-img high-padding-top high-padding-bottom">
						<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/clover-5.png" class="img-responsive small-image" data-name="Solitaire Diamond Clover Bypass Ring" data-trackurl="/p/camellia-flower-diamond-bypass-promise-ring-sr1702d?icid=wearurluckpage|clover|SR1702D|04062017" data-price="$929 - $2,979" />
					</div>
					<div class="col-sm-3 collection-img high-padding-top high-padding-bottom">
						<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/clover-6.png" class="img-responsive small-image" data-name="Round Emerald Clover Ring with Diamond Accents" data-trackurl="/p/round-emerald-and-diamond-clover-ring-sr0176e?icid=wearurluckpage|clover|sr0176e|04062017" data-price="$839 - $2,119" />
					</div>
					<div class="col-sm-3 collection-img high-padding-top high-padding-bottom">
						<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/clover-7.png" class="img-responsive small-image" data-name="Pear Shaped Sapphire Clover Stud Earrings with Diamond Halo" data-trackurl="/p/pear-shaped-sapphire-clover-stud-earrings-with-diamond-halo-se1049sd?icid=wearurluckpage|clover|se1049sd|04062017" data-price="$1,129 - $5,519" />
					</div>
				</div>
			</div>
			</div>
		</div>
	<div class="clearfix"></div>
		<div class="col-sm-12 no-padding hide popup-holder" id="Horseshoe-popup">
			<div class="popup-overflow">
			<div class="col-sm-6 no-padding big-img-box">
				<div class="pro-img full-width">
					<a href="/p/gypsy-set-diamond-horseshoe-pendant-sp1189d?icid=wearurluckpage|horseshoe|sp1189d|04062017">
						<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/horseshoe-1.png" alt="Gypsy Set Diamond Horseshoe Pendant" />
					</a>
				</div>
				<div class="pro-info text-center">
					<a class="pro-title full-width" href="/p/gypsy-set-diamond-horseshoe-pendant-sp1189d?icid=wearurluckpage|horseshoe|sp1189d|04062017">Gypsy Set Diamond Horseshoe Pendant</a>
					<div class="pro-details-btn full-width" >
						<div class="pro-price apricot-text low-margin-top">$309 - $1,149</div>
						<a class="btn add-view-btn" href="/p/gypsy-set-diamond-horseshoe-pendant-sp1189d?icid=wearurluckpage|horseshoe|sp1189d|04062017">Shop Now</a>
					</div>
				</div>
			</div>
			<div class="col-sm-6 no-padding small-img-box">
				<div class="find-more-txt col-sm-12 max-padding-bottom max-margin-bottom">Explore more from this collection</div>
				<div class="find-more-img col-sm-12 no-padding">
					<div class="col-sm-3 collection-img high-padding-top high-padding-bottom active">
						<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/horseshoe-1.png" class="img-responsive small-image" data-name="Gypsy Set Diamond Horseshoe Pendant" data-trackurl="/p/gypsy-set-diamond-horseshoe-pendant-sp1189d?icid=wearurluckpage|horseshoe|sp1189d|04062017" data-price="$309 - $1,149" />
					</div>
					<div class="col-sm-3 collection-img high-padding-top high-padding-bottom">
						<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/horseshoe-2.png" class="img-responsive small-image" data-name="Pave Set Diamond Horseshoe Stud Earrings" data-trackurl="/p/pave-set-diamond-horseshoe-stud-earrings-se1481d?icid=wearurluckpage|horseshoe|se1481d|04062017" data-price="$289 - $469" />
					</div>
					<div class="col-sm-3 collection-img high-padding-top high-padding-bottom">
						<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/horseshoe-3.png" class="img-responsive small-image" data-name="Classic Diamond Horseshoe Pendant Necklace" data-trackurl="/p/classic-diamond-horseshoe-pendant-sp0719d?icid=wearurluckpage|horseshoe|sp0719d|04062017" data-price="$509 - $1,409" />
					</div>
					<div class="col-sm-3 collection-img high-padding-top high-padding-bottom">
						<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/horseshoe-4.png" class="img-responsive small-image" data-name="Pave-Set Ruby and Diamond Horseshoe Pendant Necklace" data-trackurl="/p/pave-ruby-and-diamond-lucky-horseshoe-charm-pendant-sp0758rd?icid=wearurluckpage|horseshoe|sp0758rd|04062017" data-price="$609 - $1,859" />
					</div>
				</div>
			</div>
			</div>
		</div>
	<div class="clearfix"></div>
		<div class="col-sm-12 no-padding hide popup-holder" id="Hamsa-popup">
			<div class="popup-overflow">
			<div class="col-sm-6 no-padding big-img-box">
				<div class="pro-img full-width">
					<a href="/p/bezel-set-diamond-hamsa-hand-pendant-sp1190d?icid=wearurluckpage|hamsa-hand|SP1190D|04062017">
						<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/hamsa-1.png" alt="Bezel Set Diamond Hamsa Hand Pendant" />
					</a>
				</div>
				<div class="pro-info text-center">
					<a class="pro-title full-width" href="/p/bezel-set-diamond-hamsa-hand-pendant-sp1190d?icid=wearurluckpage|hamsa-hand|SP1190D|04062017">Bezel Set Diamond Hamsa Hand Pendant</a>
					<div class="pro-details-btn full-width" >
						<div class="pro-price apricot-text low-margin-top">$639 - $1,029</div>
						<a class="btn add-view-btn" href="/p/bezel-set-diamond-hamsa-hand-pendant-sp1190d?icid=wearurluckpage|hamsa-hand|SP1190D|04062017">Shop Now</a>
					</div>
				</div>
			</div>
			<div class="col-sm-6 no-padding small-img-box">
				<div class="find-more-txt col-sm-12 max-padding-bottom max-margin-bottom">Explore more from this collection</div>
				<div class="find-more-img col-sm-12 no-padding">
					<div class="col-sm-3 collection-img high-padding-top high-padding-bottom active">
						<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/hamsa-1.png" class="img-responsive small-image" data-name="Bezel Set Diamond Hamsa Hand Pendant" data-trackurl="/p/bezel-set-diamond-hamsa-hand-pendant-sp1190d?icid=wearurluckpage|hamsa-hand|SP1190D|04062017" data-price="$639 - $1,029" />
					</div>
					<div class="col-sm-3 collection-img high-padding-top high-padding-bottom">
						<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/hamsa-2.png" class="img-responsive small-image" data-name="Diamond Open Hamsa Hand Pendant" data-trackurl="/p/diamond-open-hamsa-hand-pendant-sp1191d?icid=wearurluckpage|hamsa-hand|SP1191D|04062017" data-price="$479 - $1,079" />
					</div>
				</div>
			</div>
			</div>
		</div>
	<div class="clearfix"></div>
		<div class="col-sm-12 no-padding hide popup-holder" id="Key-popup">
			<div class="popup-overflow">
			<div class="col-sm-6 no-padding big-img-box">
				<div class="pro-img full-width">
					<a href="/p/daisy-key-diamond-pendant-in-two-tone-sp1192d?icid=wearurluckpage|key|SP1192D|04062017">
						<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/Key-1.png" alt="Daisy Key Diamond Pendant in Two Tone" />
					</a>
				</div>
				<div class="pro-info text-center">
					<a class="pro-title full-width" href="/p/daisy-key-diamond-pendant-in-two-tone-sp1192d?icid=wearurluckpage|key|SP1192D|04062017">Daisy Key Diamond Pendant in Two Tone</a>
					<div class="pro-details-btn full-width" >
						<div class="pro-price apricot-text low-margin-top">$229 - $309</div>
						<a class="btn add-view-btn" href="/p/daisy-key-diamond-pendant-in-two-tone-sp1192d?icid=wearurluckpage|key|SP1192D|04062017">Shop Now</a>
					</div>
				</div>
			</div>
			<div class="col-sm-6 no-padding small-img-box">
				<div class="find-more-txt col-sm-12 max-padding-bottom max-margin-bottom">Explore more from this collection</div>
				<div class="find-more-img col-sm-12 no-padding">
					<div class="col-sm-3 collection-img high-padding-top high-padding-bottom active">
						<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/Key-1.png" class="img-responsive small-image" data-name="Daisy Key Diamond Pendant in Two Tone" data-trackurl="/p/daisy-key-diamond-pendant-in-two-tone-sp1192d?icid=wearurluckpage|key|SP1192D|04062017" data-price="$229 - $309" />
					</div>
					<div class="col-sm-3 collection-img high-padding-top high-padding-bottom">
						<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/Key-2.png" class="img-responsive small-image" data-name="Diamond Fleur De Lis Key Pendant" data-trackurl="/p/diamond-fleur-de-lis-key-pendant-sp1193d?icid=wearurluckpage|key|SP1193D|04062017" data-price="$739 - $1,259" />
					</div>
				</div>
			</div>
			</div>
		</div>
	<div class="clearfix"></div>
		<div class="col-sm-12 no-padding hide popup-holder" id="Cross-popup">
			<div class="popup-overflow">
			<div class="col-sm-6 no-padding big-img-box">
				<div class="pro-img full-width">
					<a href="/p/round-sapphire-and-diamond-cross-pendant-sp0120sd-n?icid=wearurluckpage|faith|sp0120sd-n|04062017">
						<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/cross-1.png" alt="Flat Prong-Set Blue Sapphire and Diamond Cross Pendant" />
					</a>
				</div>
				<div class="pro-info text-center">
					<a class="pro-title full-width" href="/p/round-sapphire-and-diamond-cross-pendant-sp0120sd-n?icid=wearurluckpage|faith|sp0120sd-n|04062017">Flat Prong-Set Blue Sapphire and Diamond Cross Pendant</a>
					<div class="pro-details-btn full-width" >
						<div class="pro-price apricot-text low-margin-top">$749 - $2,249</div>
						<a class="btn add-view-btn" href="/p/round-sapphire-and-diamond-cross-pendant-sp0120sd-n?icid=wearurluckpage|faith|sp0120sd-n|04062017">Shop Now</a>
					</div>
				</div>
			</div>
			<div class="col-sm-6 no-padding small-img-box">
				<div class="find-more-txt col-sm-12 max-padding-bottom max-margin-bottom">Explore more from this collection</div>
				<div class="find-more-img col-sm-12 no-padding">
					<div class="col-sm-3 collection-img high-padding-top high-padding-bottom active">
						<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/cross-1.png" class="img-responsive small-image" data-name="Flat Prong-Set Blue Sapphire and Diamond Cross Pendant" data-trackurl="/p/round-sapphire-and-diamond-cross-pendant-sp0120sd-n?icid=wearurluckpage|faith|sp0120sd-n|04062017" data-price="$749 - $2,249" />
					</div>
					<div class="col-sm-3 collection-img high-padding-top high-padding-bottom">
						<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/cross-2.png" class="img-responsive small-image"  data-name="Gypsy Set Round Ruby Cross Pendant" data-trackurl="/p/round-ruby-cross-pendant-sp0470rb?icid=wearurluckpage|faith|sp0470rb|04062017" data-price="$499" />
					</div>
				</div>
			</div>
			</div>
		</div>
	<div class="clearfix"></div>
		<div class="col-sm-12 no-padding hide popup-holder" id="Wishbone-popup">
			<div class="popup-overflow">
			<div class="col-sm-6 no-padding big-img-box">
				<div class="pro-img full-width">
					<a href="/p/solitaire-moissanite-wishbone-drop-pendant-sp1196ml?icid=wearurluckpage|wishbone|SP1196ML|04062017">
						<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/wishbone-1.png" alt="Solitaire Moissanite Wishbone Drop Pendant" />
					</a>
				</div>
				<div class="pro-info text-center">
					<a class="pro-title full-width" href="/p/solitaire-moissanite-wishbone-drop-pendant-sp1196ml?icid=wearurluckpage|wishbone|SP1196ML|04062017">Solitaire Moissanite Wishbone Drop Pendant</a>
					<div class="pro-details-btn full-width" >
						<div class="pro-price apricot-text low-margin-top">$329 - $429</div>
						<a class="btn add-view-btn" href="/p/solitaire-moissanite-wishbone-drop-pendant-sp1196ml?icid=wearurluckpage|wishbone|SP1196ML|04062017">Shop Now</a>
					</div>
				</div>
			</div>
			<div class="col-sm-6 no-padding small-img-box">
				<div class="find-more-txt col-sm-12 max-padding-bottom max-margin-bottom">Explore more from this collection</div>
				<div class="find-more-img col-sm-12 no-padding">
					<div class="col-sm-3 collection-img high-padding-top high-padding-bottom active">
						<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/wishbone-1.png" class="img-responsive small-image" data-name="Solitaire Moissanite Wishbone Drop Pendant" data-trackurl="/p/solitaire-moissanite-wishbone-drop-pendant-sp1196ml?icid=wearurluckpage|wishbone|SP1196ML|04062017" data-price="$329 - $429" />
					</div>
					<div class="col-sm-3 collection-img high-padding-top high-padding-bottom">
						<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/wishbone-2.png" class="img-responsive small-image" data-name="Pave Set Diamond Sideways Wishbone Necklace" data-trackurl="/p/pave-set-diamond-sideways-wishbone-necklace-sp1195d?icid=wearurluckpage|wishbone|SP1195D|04062017" data-price="$359 - $559" />
					</div>
					<div class="col-sm-3 collection-img high-padding-top high-padding-bottom">
						<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/wishbone-3.png" class="img-responsive small-image" data-name="Round Diamond Wishbone Stud Earrings" data-trackurl="/p/round-diamond-wishbone-stud-earrings-se1376d?icid=wearurluckpage|wishbone|SE1376D|04062017" data-price="$139 - $199" />
					</div>
				</div>
			</div>
			</div>
		</div>
	<div class="clearfix"></div>
		<div class="col-sm-12 no-padding hide popup-holder" id="Peace-popup">
			<div class="popup-overflow">
			<div class="col-sm-6 no-padding big-img-box">
				<div class="pro-img full-width">
					<a href="/p/tapered-shank-diamond-peace-sign-ring-sr1828d?icid=wearurluckpage|peace|SR1828D|04062017">
						<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/peace-1.png" alt="Tapered-Shank Diamond Peace Sign Ring" />
					</a>
				</div>
				<div class="pro-info text-center">
					<a class="pro-title full-width" href="/p/tapered-shank-diamond-peace-sign-ring-sr1828d?icid=wearurluckpage|peace|SR1828D|04062017">Tapered-Shank Diamond Peace Sign Ring</a>
					<div class="pro-details-btn full-width" >
						<div class="pro-price apricot-text low-margin-top">$439 - $689</div>
						<a class="btn add-view-btn" href="/p/tapered-shank-diamond-peace-sign-ring-sr1828d?icid=wearurluckpage|peace|SR1828D|04062017">Shop Now</a>
					</div>
				</div>
			</div>
			<div class="col-sm-6 no-padding small-img-box">
				<div class="find-more-txt col-sm-12 max-padding-bottom max-margin-bottom">Explore more from this collection</div>
				<div class="find-more-img col-sm-12 no-padding">
					<div class="col-sm-3 collection-img high-padding-top high-padding-bottom active">
						<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/peace-1.png" class="img-responsive small-image" data-name="Tapered-Shank Diamond Peace Sign Ring" data-trackurl="/p/tapered-shank-diamond-peace-sign-ring-sr1828d?icid=wearurluckpage|peace|SR1828D|04062017" data-price="$439 - $689" />
					</div>
					<div class="col-sm-3 collection-img high-padding-top high-padding-bottom">
						<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/peace-3.png" class="img-responsive small-image" data-name="Prong-Set Diamond Peace Sign Pendant" data-trackurl="/p/prong-set-diamond-peace-sign-pendant-sp1200d?icid=wearurluckpage|peace|SP1200D|04062017" data-price="$539 - $889" />
					</div>
					<div class="col-sm-3 collection-img high-padding-top high-padding-bottom">
						<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/peace-2.png" class="img-responsive small-image" data-name="Diamond Peace Sign Leverback Earrings" data-trackurl="/p/diamond-peace-sign-leverback-earrings-se1480d?icid=wearurluckpage|peace|SE1480D|04062017" data-price="$679 - $1,139" />
					</div>
				</div>
			</div>
			</div>
		</div>
	<div class="clearfix"></div>
		<div class="col-sm-12 no-padding hide popup-holder" id="Barnstar-popup">
		<div class="popup-overflow">
			<div class="col-sm-6 no-padding big-img-box">
				<div class="pro-img full-width">
					<a href="/p/star-shaped-diamond-cluster-stud-earrings-se1130d?icid=wearurluckpage|barnstar|SE1130D|04062017">
						<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/barnstar-1.png" alt="Diamond Cluster Star Stud Earrings" />
					</a>
				</div>
				<div class="pro-info text-center">
					<a class="pro-title full-width" href="/p/star-shaped-diamond-cluster-stud-earrings-se1130d?icid=wearurluckpage|barnstar|SE1130D|04062017">Diamond Cluster Star Stud Earrings</a>
					<div class="pro-details-btn full-width" >
						<div class="pro-price apricot-text low-margin-top">$649 - $2,449</div>
						<a class="btn add-view-btn" href="/p/star-shaped-diamond-cluster-stud-earrings-se1130d?icid=wearurluckpage|barnstar|SE1130D|04062017">Shop Now</a>
					</div>
				</div>
			</div>
			<div class="col-sm-6 no-padding small-img-box">
				<div class="find-more-txt col-sm-12 max-padding-bottom max-margin-bottom">Explore more from this collection</div>
				<div class="find-more-img col-sm-12 no-padding">
					<div class="col-sm-3 collection-img high-padding-top high-padding-bottom active">
						<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/barnstar-1.png" class="img-responsive small-image" data-name="Diamond Cluster Star Stud Earrings" data-trackurl="/p/star-shaped-diamond-cluster-stud-earrings-se1130d?icid=wearurluckpage|barnstar|SE1130D|04062017" data-price="$649 - $2,449" />
					</div>
					<div class="col-sm-3 collection-img high-padding-top high-padding-bottom">
						<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/images/landingpage/wear-your-luck/barnstar-2.png" class="img-responsive small-image" data-name="Diamond Open Star Bypass Ring" data-trackurl="/p/round-bypass-diamond-open-star-ring-sr1403d?icid=wearurluckpage|barnstar|SR1403D|04062017" data-price="$689 - $1,429" />
					</div>
				</div>
			</div>
			</div>
		</div>
</div>

<script language="javascript">
jQuery(function(){
	jQuery('.tab li a, .go2top a').click(function(){
		var id = jQuery(this).attr('data-go-to');
		var headerHeight = jQuery("#main-head-inner").height();
		var headerHeight2 = jQuery("#main-head-inner").outerHeight();
		if(jQuery(window).width() > 1024){
			jQuery('html, body').animate({
				scrollTop: jQuery(id).offset().top - headerHeight
			}, 500);
		}else{
			jQuery('html, body').animate({
				scrollTop: jQuery(id).offset().top - headerHeight2
			}, 500);
		}
	});
	
	jQuery('.apri-box.explr-btn').click(function(){
		var id = jQuery(this).attr('popup-id');
		jQuery( ".info-popup").removeClass('hide');
		jQuery(id).removeClass('hide');
		jQuery(".popup-overflow").addClass('popup-flex');
	});
	jQuery('.info-popup .dismiss-popup').click(function(){
		jQuery(".info-popup, .popup-holder").addClass('hide');
		jQuery(".popup-overflow").removeClass('popup-flex');
	});
	
	
	jQuery('.small-image').click(function(){
	  jQuery(this).parent('.collection-img').addClass('active').siblings('.collection-img').removeClass('active');
	  
	  var proImae = jQuery(this).attr('src');
	  var proName = jQuery(this).attr('data-name');
	  var proURL = jQuery(this).attr('data-trackurl');
	  var proPrice = jQuery(this).attr('data-price');
	  
	  jQuery(this).parents('.popup-holder').find('.big-img-box img').attr('src',proImae);
	  jQuery(this).parents('.popup-holder').find('.big-img-box img').attr('alt',proName);
	  jQuery(this).parents('.popup-holder').find('.big-img-box .pro-title').text(proName);
	  jQuery(this).parents('.popup-holder').find('.pro-details-btn .pro-price').text(proPrice);
	  jQuery(this).parents('.popup-holder').find('.big-img-box a').attr('href',proURL);
	});
	
	
});
</script>