<style>
.more-views li {
	position:relative;
}
.more-views li img.playvideothumb {
	height:56px;
	width:56px;
	cursor: pointer;
	position:absolute;
	top:1px;
	left:1px;
	z-index:10;
	filter:alpha(opacity=80);
	opacity:0.8;
}
.more-views li img.playvideothumb:hover {
	filter:alpha(opacity=100);
	opacity:1;
}
<!--Code Added by Vaseem for Zoom--> 
.magnifyarea { /* CSS to add shadow to magnified image. Optional */
	box-shadow: 5px 5px 7px #D3D3D3;
	background: white;
}
.targetarea { /* CSS for container div(s) of the zoomable image */
	width: 350px; /* wide or wider than the widest zoomable image */
	height: 350px; /* high or higher than the tallest zoomable image */
}
#two { /* Added CSS for second target div of zoomable images */
	height: 350px; /* high or higher than the tallest zoomable image */
}
.targetarea img { /* zoomable image */
	margin: auto; /* for horizontal centering */
	display: block; /* also for horizontal centering */
	position: relative; /* along with on the fly calculations in script, for vertical centering */
	border-width: 0;
}
.zoomtracker
{
z-index:800!important;
}
</style>
<script language="javascript" src="<?php echo $this->helper('core/js')->getJsUrl('zoom/multizoom.js'); ?>" type="text/javascript"></script>
<script type="text/javascript">
function changeImage(angle,actualHeight,actualWidth){
	var varAngle	=	function(){
							jQuery("#"+angle).click();
							jQuery('#image').css({'width':actualHeight,'height':actualWidth});
						};
	setTimeout(varAngle,1000);
}
jQuery('#image').multizoomhide();
jQuery(document).ready(function($){ //Load multizoom on document ready:
	$('#image').addimagezoom({ // options same as for previous Featured Image Zoomer's addimagezoom unless noted as '- new'
		magnifiersize:[350, 350],
		cursorshade: true
		//zoomrange: [3, 10],
		//disablewheel: true // even without variable zoom, mousewheel will not shift image position while mouse is over image (optional) - new
	});
	jQuery('div.metaltype').click(function(){
		var curAngle	=	jQuery('#angleType').html();
		actualHeight	=	jQuery('#image').height();
		actualWidth	=	jQuery('#image').width();
		//alert(actualHeight); alert(actualWidth);
		jQuery('#image').css({'width':'350px','height':'350px'});
		jQuery('#angle_10').click();
		changeImage(curAngle,actualHeight,actualWidth);
	});
});

jQuery(window).load(function() {		// This will load after the complete page elements load	
	videosHtml	=	jQuery('#videos').html();
	jQuery('#videosAppend').html(videosHtml);
});

</script>
<!--Code Added by Vaseem for Zoom-->
<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
?>
<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>

<div style="border:solid 1px #d3d3d3;margin-bottom:10px; width:350px; height:351px;text-align:center;vertical-align:middle;line-height:349px;position:relative;">
  <?php
		$extra_style = '';
		if($_product->getAttributeSetId() != '12'){
			$extra_style = 'vertical-align:middle';
		}
		$zoom_img = $this->helper('catalog/image')->init($_product, 'image'); //'/js/zoom/SR0608S.png';
		$main_img = '/js/zoom/Round-Sapphire-and-Diamond-WOW-Engagement-Ring-in-Two-Tone-Metal-SR0608S-WG-AA-SA.png';
        $_img = '<a href="'.$this->helper('catalog/image')->init($_product, 'image').'"><img id="image" height="350" width="350" src="'.$this->helper('catalog/image')->init($_product, 'image').'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" style="'.$extra_style.'" /></a>';
		// Code added by Vaseem for 588
		$_imgother = '<img id="imageother" height="350" width="350" src="'.$this->helper('catalog/image')->init($_product, 'image').'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" style="'.$extra_style.'; display:none;" />';
         echo '<div class="targetarea" id="two">'.$_helper->productAttribute($_product, $_img, 'image').'</div>';
		echo $_helper->productAttribute($_product, $_imgother, 'image');	// Code added by Vaseem for 588
    ?>
  <?php if($_product->getAttributeSetId() == '12'){?>
  <div class="chaintxt">
    <?php
    $exclude_chain_prod_arr=array('SP0359PR','SP0358PR','SP0357PR','SP0355PR','SP0137R','SP0137S','SP0138R','SP0138S','SP0139R','SP0139S','SPY0138R','SP0373D','SP0352PR','SP0371D');
    if (!in_array($_product->getSku(), $exclude_chain_prod_arr)) // skip chain message for selected products Ticket: #500
    {
	?>
    (<?php echo $_product->getAttributeText('pendant_chain_length') ?> inch <span id="pendantmsg"><?php echo $_product->getAttributeText('metal') ?></span> chain shipped FREE with pendant)
    <?php    
	}
	?>
  </div>
  <?php }else{?>
  <div class="chaintxt" style="display:none;"><span id="pendantmsg"></span></div>
  <?php }?>
</div>
<?php else: ?>
<p class="product-image" style="border:solid 1px #d3d3d3;margin-bottom:10px">
  <?php
        $_img = '<img id="image" src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(265).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
    ?>
</p>
<?php endif; ?>
<?php 
$tmp_main_img_path = ''; 
$p=0; 
$moreimg_file_arr = array();
?>
<div id="moreviews" class="more-views">
  <div class="image thumbs">
    <ul>
      <?php
		$cnt = 4; //Mage::getBlockSingleton('hprcv/hprcv')->getCountCustomImages($_product->getSku());
		$defaultGrade = Mage::getBlockSingleton('hprcv/hprcv')->getDefaultGrade($_product);
		for($i=1;$i<=$cnt;$i++)
		{	
			if(trim($_product->getImagesku()) != ''){
				$imageskuval = $_product->getImagesku();
			}else{
				$imageskuval = $_product->getSku();
			}
			//echo $imageskuval.'---';
			$url = Mage::getBlockSingleton('hprcv/hprcv')->returnimage($imageskuval,$_product->getShortDescription(),$_product->getAttributeText('metal_type'),$defaultGrade,'angle_' . $i,$_product->getAttributeText('de_stone_type'),$_product);
			
			$angdir = Mage::getBaseDir().'/media/catalog/product/images/customj/'.$imageskuval.'/angle_'.$i;
			$sideimgfname = basename($url);
			//echo $angdir.'/'.$sideimgfname.'<br><br>';
			if (!@file_exists($angdir.'/'.$sideimgfname))
			{
			?>
      <li style="display:none;"> <img title="" src="/media/catalog/product/placeholder/default/ANGARA-place-holder.jpg" width="56" height="56" id="angle_<?php echo $i; ?>" /> </li>
      <?php	
                    continue;
                }			
        ?>
      <li> <a href="<?php echo $url?>" id="multizoom_<?php echo $i?>"><img onClick="changecurrentview('<?php echo $i?>'); return false;" title='' src="/image_thumb.php?width=56&height=56&image=<?php echo $url ?>" width="56" height="56" id="angle_<?php echo $i?>"/></a> </li>
      <?php		
		}
	?>
      <?php 
		$arr = Mage::getBlockSingleton('hprcv/hprcv')->getOtImage($_product->getSku());
		$sku = $_product->getSku();
		if($_product->getImagesku()!='')
		{
			$sku = $_product->getImagesku();
		}
		$tmp_main_img_dir = Mage::getBlockSingleton('hprcv/hprcv')->getrootpath();		
		sort($arr);
		for($i=0;$i<count($arr);$i++):
		if($arr[$i] != ".svn"){
		$url = "http://" .  $_SERVER['HTTP_HOST'] . $tmp_main_img_dir. $sku . "/angle_other/" . $arr[$i];
		$j=	$i+20;
	?>
      <li rel="otherangleimages"><a href="<?php echo $url?>" id="multizoom_<?php echo $j?>"><img onclick="document.getElementById('image').style.width = '350px';document.getElementById('image').style.height = '350px';changecurrentview('<?php echo $i?>');return false;"  src="/image_thumb.php?width=56&height=56&image=<?php echo $url ?>" width="56" height="56" id="angle_<?php echo $i?>"/></a> </li>
      <?php
		}
		endfor;
	?>
<span id="otherImgAppend"></span>
     <li style="display:none;"> <a href="<?php echo Mage::getBaseUrl().'js/zoom/ajax-loader-large-350.gif';?>" id="multizoom_10"><img onclick="changecurrentview('10'); return false;" title='' src="<?php echo Mage::getBaseUrl().'js/zoom/ajax-loader-large-350.gif';?>" width="56" height="56" id="angle_10"/></a> </li>
     <span id="videosAppend"></span>
    </ul>
    
    <div style="clear:both"></div>
  </div>
  <!--Showing video after closing the zoom div-->
  <ul id="videos" style="display:none;">
     <?php
		$newmediaval = $_helper->productAttribute($_product, $this->htmlEscape($_product->getNewmedia()), 'newmedia');	
		if($newmediaval!=''){
			$video_arr = explode("|",$newmediaval);
			$number_of_videos = count($video_arr);
			$thumbPath = Mage::getBaseURL('media').'productVideos/';
			for ($i=0; $i < count($video_arr); $i++)
			{
				list($videoName,$thumbName) = explode(',',$video_arr[$i]);
				//if($i==0){continue;}
				//echo $newmediaval;
				?>
      <li> <a href = "javascript:void(0)" onclick = "document.getElementById('light').style.display='block';document.getElementById('fade').style.display='block'"> <img title='' src="/image_thumb.php?width=56&height=56&image=<?php echo $thumbPath."thumb/".$thumbName; ?>" width="56" height="56" /> <img src="/skin/frontend/angara/default/images/play-video-thumb.png" width="56" height="56"  class="playvideothumb" alt="Play Video" title="Play Video" /> </a> </li>
      <?php	
				break;
			}
		}
		?>
        <!--<li id="pckImg" rel="customj"></li>-->
    </ul>
    <!--Showing video after closing the zoom div-->
  <div style="clear:both;display:none;" id="angleType">angle_1</div>
</div>