<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
<link href="/skin/frontend/angara/default/css/countrypoup.css" rel="stylesheet" type="text/css" />
</head>

<body bgcolor="#000000">
<div class="countrywrapper">
	<div class="logo"><img src="/skin/frontend/angara/default/images/popup/angara-logo.jpg"  alt="Angara" /></div>
    <div class="closebtn"><img src="/skin/frontend/angara/default/images/popup/close-popup.jpg" alt="close" /></div>
    <div class="clear"></div>
    <div class="countrybox">
        <div class="flagbox">
            <div class="countryflag country-us"></div>
          <div class="countryname">Now Shipping to Australia</div>
            <div class="arrow"></div>
        </div>       
	</div>
    <div class="heading">We make it easy to shop from Australia with:</div>
    <div class="points">
    <ul>
    <li>Free shipping to Australia</li>
    <li>Prices Displayed in your currency.</li>
    <li>Product will be received 4-7 business days once shipped.</li>
    </ul>
    </div>
  <div class="moreinfo">More information about shipping internationally is available on our website.</div>
    <div class="continuebtn"><a href="#"><img src="/skin/frontend/angara/default/images/popup/continue-shopping.jpg" alt="Continue Shopping" title="Continue Shopping" /></a></div>
    <div class="bottomstrip">Not shipping to India? <span><a href="#" style="color:#ba0000;">Click here</a></span></div>
</div>
</body>
</html>
