<link href="/skin/frontend/angara/default/css/writereview.css" rel="stylesheet" type="text/css" />
<div id='one'></div>
<?php $orders = $this->getCustomerOrders();
$reviews = $this->getCustomerReviews();
//$reviews = $mod = Mage::getModel('customerreview/customerreviewsubmission')->getCollection();
//$abc = ($reviews->getData());
?>
<div id='engagementbodyhome'>
	<?php 
	$orderLoopCount=0;
	$forEachOuterCount=0;
	foreach($orders as $order) 
	{
		$orderLoopCount=$orderLoopCount+1;
	
		$items = $order->getAllItems();
		$orderId = $order->getIncrementId();
		$cumstomerFname =  $order->getCustomerFirstname();
		if($orderLoopCount==1) {
	?>	
    
	<div class='welcomecustomer'>Welcome <span style='color:#a50041'><?php echo $order->getCustomerFirstname() ?></span></div>
	<div id="messages"></div>
	   <div class='colheading'> 
		   <span class='colorderitem'>Order Item</span> 
		   <span class='colorderdetail'>Order Details</span> 
		   <span class='colreviewstatus'>Order Review Status</span> 
	   </div>
		
		<?php 
		} // If condition ends
		$forEachInnerCount=0;
		foreach($items as $item)	
		{
		$temp = $reviews->getItemByColumnValue('item_id', $item->getId()); 
		$sku = $item->getSku();
		if(strtolower(substr($sku, 0,2))=='fr' OR count($temp)>0) {
			continue;
		}
		$dashIndex = strpos($sku, "-")>0 ?  strpos($sku, "-") : strlen($sku); 
		$skuPre = substr($sku,0,  $dashIndex);
		$sku = '"' . $skuPre . '"';
		$product = Mage::getModel('catalog/product')->load($item->getProductId());
		?>
        <div class='productdetails'> 
		<?php if(count($temp)>0) { ?>
		        <span class='orderitemimg'><img src="<?php echo Mage::helper('catalog/image')->init($product, 'image')->resize(100); ?>" width="100" height="100" alt=""/></span> 
		<?php } else {?>
        <span class='orderitemimg'><img src="<?php echo Mage::helper('catalog/image')->init($product, 'image')->resize(100); ?>" width="100" height="100" alt="" onclick='javascript:showReviewForm(this, <?php echo $order->getId();?> , <?php echo $item->getId();?>, <?php echo $sku; ?> );'/></span> 
		<?php } ?>
            <span class='orderdetails'> 
                <span class='productname'><a target="_blank" href= "/<?php echo $product->getUrlPath() ?>"><?php echo $item->getName() ?></a></span>
                    <dl class='details'>
                      <dt>SKU:</dt>
                      <dd><?php echo $skuPre ?></dd>
                      <dt>Order No:</dt>
                      <dd><?php echo $orderId ?></dd>
                      <dt>Purchase Date:</dt>
                      <dd><?php echo date('d-M-y', strtotime($order->getCreatedAt()));?></dd>
                     <!-- <dt>Item Price:</dt>
                      <dd><?php echo $this->helper('core')->currency($item->getPrice()); ?></dd>-->
                    </dl>
            </span> 
          <span class='reviewstatus'>          
			<?php 				
				if(count($temp)>0)
					{$add= "<div class='reviewstatustxt'> Product Reviewed </div>";} 
				else 
					{
					$forEachCount = $forEachCount +1;
					$add="
								<div class='clickhere' id='clickhere-$forEachCount-$forEachOuterCount' onclick='javascript:showReviewForm(this," . $order->getId() . ",". $item->getId()."," . $sku . ");'><img id='clickimg' src='/skin/adminhtml/base/default/images/reviewemail/clickview.jpg' alt='Click Here' /></div>
								 <div style='display:none' class='cancel' onclick='javascript:hideReviewForm(this);'><button type='button' title='cancel' class='button cancelbtn'><span><span>Cancel</span></span></button></div>
								";} 
								
					echo $add;	
				if($forEachCount==1) {
						$forEachOuterCount=$forEachOuterCount+1;
						$scriptToDump= "<script type='text/javascript'> jQuery(document).ready(function(){jQuery('#clickhere-1-0').click();});</script>";
				}					
            ?>
            
        	</span>
				<div class='clear'></div>
 			 </div>	
<?php					
		}
	}
	echo $scriptToDump;
?>

<!-- Show reviewed products -->

	<?php 
	$orderLoopCount=0;
	$forEachOuterCount=0;
	foreach($orders as $order) 
	{
		$orderLoopCount=$orderLoopCount+1;
	
		$items = $order->getAllItems();
		$orderId = $order->getIncrementId();
		$cumstomerFname =  $order->getCustomerFirstname();
		if($orderLoopCount==1) {
	?>	
		
		<?php 
		} // If condition ends
		$forEachInnerCount=0;
		foreach($items as $item)	
		{
		$temp = $reviews->getItemByColumnValue('item_id', $item->getId()); 
		$sku = $item->getSku();
		if(strtolower(substr($sku, 0,2))=='fr' OR count($temp)==0) {
			continue;
		}
		$dashIndex = strpos($sku, "-")>0 ?  strpos($sku, "-") : strlen($sku); 
		$skuPre = substr($sku,0,  $dashIndex);
		$sku = '"' . $skuPre . '"';
		$product = Mage::getModel('catalog/product')->load($item->getProductId());
		?>
        <div class='productdetails'> 
		<?php if(count($temp)>0) { ?>
		        <span class='orderitemimg'><img src="<?php echo Mage::helper('catalog/image')->init($product, 'image')->resize(100); ?>" width="100" height="100" alt=""/></span> 
		<?php } else {?>
        <span class='orderitemimg'><img src="<?php echo Mage::helper('catalog/image')->init($product, 'image')->resize(100); ?>" width="100" height="100" alt="" onclick='javascript:showReviewForm(this, <?php echo $order->getId();?> , <?php echo $item->getId();?>, <?php echo $sku; ?> );'/></span> 
		<?php } ?>
            <span class='orderdetails'> 
                <span class='productname'><a target="_blank" href= "/<?php echo $product->getUrlPath() ?>"><?php echo $item->getName() ?></a></span>
                    <dl class='details'>
                      <dt>SKU:</dt>
                      <dd><?php echo $skuPre ?></dd>
                      <dt>Order No:</dt>
                      <dd><?php echo $orderId ?></dd>
                      <dt>Purchase Date:</dt>
                      <dd><?php echo date('d-M-y', strtotime($order->getCreatedAt()));?></dd>
                     <!-- <dt>Item Price:</dt>
                      <dd><?php echo $this->helper('core')->currency($item->getPrice()); ?></dd>-->
                    </dl>
            </span> 
          <span class='reviewstatus'>          
			<?php 				
				if(count($temp)>0)
					{$add= "<div class='reviewstatustxt'> Product Reviewed </div>";} 								
					echo $add;					
            ?>
            
        	</span>
				<div class='clear'></div>
 			 </div>	
<?php					
		}
	}
?>

  <div class='clear'></div>
</div>
<div id='custom-review-form' style="display:none"> <?php echo $this->getLayout()->getBlock('reviewform')->toHtml();?> </div>
<script type="text/javascript" >
	function showReviewForm(node, orderId, itemId, sku) {
		//hide all cancel buttons and show all write review buttons
		jQuery('.cancel').each(function(i){jQuery(this).hide()});
		jQuery('.clickhere').each(function(i){jQuery(this).show()});
		var item = jQuery(node);
		if(!item.attr("class"))
		{
			item = jQuery(node).parent().next().next().children().eq(0); 
		}
		item.after(jQuery('#custom-review-form').after());
		jQuery('#custom-review-form').show();
		
		var cancelReviewBtn = item.next().next();
		cancelReviewBtn.show();
		
		item.hide();
		
		jQuery(window).scrollTop(item.parent().position().top);		
		jQuery('#order_id').val(orderId);
		jQuery('#item_id').val(itemId);
		jQuery('#sku').val(sku);
		jQuery('#rule').val("<?php echo $this->getRequest()->getParam('order'); ?>");
			
	}
	function hideReviewForm(node)	{
		var item = jQuery(node);
		var writeReviewBtn = item.prev().prev();
		writeReviewBtn.show();
		item.hide();
		jQuery('#custom-review-form').hide();
		jQuery(window).scrollTop(writeReviewBtn.position().top);
	}
	</script>
