<style>
.checkout-footer-top-border{border-top: 2px solid #dddddd;}
.success-msg{display:none}
.valentines_heart{display:none !important;}
.btn-cart.add-to-cart.btn-primary{width:90%; background:#fa505a; border:none; line-height:25px; border-radius:2px; text-transform:capitalize!important; font-size:18px;}


.checkout-footer-top-border{border-top: 2px solid #dddddd;}
.success-msg{display:none}
.valentines_heart {
	display:none !important;
}

#best-sellers a:hover .hover-bdr .btn, #gemstone-section a:hover .hover-bdr .btn {border:1px solid #fa505a;color:#fa505a;}
#best-sellers .hover-bdr .btn {color:#000000;border:1px solid #000000;margin-top:8px;}
#best-sellers .valentine .btn {color:#ffffff;border:1px solid #ffffff;}
#best-sellers .valentine a:hover .valentine-btn {color:#000000 !important;border:1px solid #000000 !important;}


#homepage-latest-reviews .detail-box-bs{bottom:-100%; transition:bottom 500ms; -webkit-transition:bottom 500ms; background: rgba(255,255,255,0.8); padding:10px 30px; text-align: center;}
#homepage-latest-reviews .slick-slide:hover .detail-box-bs{bottom:0px;}
#homepage-latest-reviews .detail-box-bs .color999{font-size:14px;}
.new-arrivals {width:90%;margin:0 auto;}
.new-arrivals .col-sm-3 {padding-left:15px;padding-right:15px;}
.white-bg .heading-box .heading, .new-arrivals .heading, .rview h2, .block-heading  {
    font-size:20px;
    margin:15px 0px;
    color: #333333;
	text-align:center;
	font-weight: 600;
	text-shadow: none;
}
.sep {
    position: absolute;
    height: 2px;
    background: #dddddd;
    left: 0px;
    right: 0px;
}

.slick-prev:before, .slick-next:before {
	background-color: transparent !important;
}
.fullmargin img {
	margin:0 auto;
}
.fullmargin .btn {
	padding:8px;
	border:1px solid #000000;
	text-align:center;
	display:block;
	text-shadow: none;
	width:140px;
	margin:0 auto;
	
}
.slick-dots {bottom: 25% !important;text-align:center !important;}
.slick-dots li button:before {
	font-size:10px !important;
}
.slick-dots li {width:10px !important;}

.slick-prev:before, .slick-next:before {
	font-size: 24px !important;
    color: #777777 !important;
    font-weight: bold !important;
	
}
.slick-prev {left:20px !important;opacity:1 !important;} 
.slick-next {right:20px !important;opacity:1 !important;}

</style>
<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magentocommerce.com for more information.
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2012 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>

<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/default/css/slick-slider.css" media="all" />
<script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/imobile/js/slick.min.js"></script>

<div class="container empty-cart">

<div class="container showcase-bg-white">

<div class="col-sm-12 text-center">
	<div class="block-heading text-bold pB5 pT10 no-padding no-margin">Your Shopping Cart is Empty.</div>
	<div class="title-text pB10">
		To begin shopping, view our bestsellers and new arrivals below or click <a href="/products?icid=emptycartpage|clickhere|03072017" class="text-bold" style="text-decoration: underline;">here</a> to view the entire collection.
	</div>
</div>
<div class="clearfix"></div>
	<span class="sep"></span>
<div class="clearfix"></div>

<section class="white-bg" style="padding-bottom:0px;">
	<div class="container">
		<div class="heading-box">
			<h2 class="heading">Best Sellers</h2>
		</div>
		<div class="content-box">
			<div id="latest-reviews" class="col-xs-12 has-slider">
				<div class="showcase-bg-white padding-type-10 HP1">
					<div class="HP2">
						<div id="homepage-latest-reviews">
							<?php 
							try
							{
							$resource = Mage::getSingleton('core/resource');
							$read = $resource->getConnection('core_read');
							$sql = "Select * from ang_bestseller";
							$sqlQuery = $read->query($sql);
							$iterator=0;
							while ($row = $sqlQuery->fetch() ) 
							{
									$iterator++;
									$sku=$row['sku'];
									$obj = Mage::getModel('catalog/product')->getCollection()->addAttributeToSelect(array('url_key','short_description','price','special_price','image'))->addFinalPrice()->addAttributeToFilter('sku',$sku)->getFirstItem();
									$obj2=new Mage_Catalog_Block_Product();
									$image = $obj2->helper('catalog/image')->init($obj, 'image')->resize(175);
									$title=$obj->getShortDescription();
									$url=$obj->getProductUrl();
							?>	
							
							<div class="relative-placeholder" style="overflow:hidden">
								<a href="<?php echo $url; ?>?icid=emptycartpage|bestseller-widget|03072017" title="<?php echo $title;?>" class="center-block text-center">
									<img class="img-responsive bdr-typ-1" style="margin:0 auto; max-width:175px; max-height:175px" src="<?php echo $image ?>" alt="<?php echo $title;?>" title="<?php echo $title;?>"/>
								</a>
							</div>
							<?php }
							}
							catch(Exception $e)
							{ } ?>	
						</div>
					</div>
					<script type="text/javascript">
						jQuery('#homepage-latest-reviews').slick({
							arrows			: 	true,
							dots			: 	false,
							slidesToShow	: 	1,
							slidesToScroll	: 	1,
							autoplay		: 	false,
							autoplaySpeed	: 	5000
						});
					</script>
				</div>
			</div>
		</div>
	</div>
</section>
<div class="clearfix"></div>
	<span class="sep"></span>
<div class="clearfix"></div>

<!-- slider box -->
	<div class="full-width no-padding-LR max-padding-bottom rview pull-left">
		<h2 class="heading max-padding-bottom max-padding-top text-center">Shop Our New Arrivals</h2>
		<div id="review-slider" class="review-slider">
			<div class="fullmargin">
				<a href="/collection/knotty-heart-jewelry?icid=emptycartpage|explr-collec|knotty-h|03072017">
					<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/imobile/images/landingpage/empty-cart/knotty.jpg" alt="Knotty Heart Collection From Angara" title="Knotty Heart Jewelry"/>
				</a>
			</div>
			<div class="fullmargin">
				<a href="/collection/infinity-jewelry?icid=emptycartpage|explr-collec|infinity|03072017">
					<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/imobile/images/landingpage/empty-cart/infinity.jpg" alt="Infinity Collection From Angara" title="Infinity Jewelry"/>
				</a>
			</div>
			<div class="fullmargin">
				<a href="/jewelry/coffee-diamond-jewelry?icid=emptycartpage|explr-collec|coffee-d|03072017">
					<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/imobile/images/landingpage/empty-cart/coffee.jpg" alt="Coffee Diamond Collection From Angara" title="Coffee Diamond Jewelry"/>
				</a>
			</div>
			<div class="fullmargin">
				<a href="/jewelry/two-stone-jewelry?icid=emptycartpage|explr-collec|me-we|03072017">
					<img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/ress/imobile/images/landingpage/empty-cart/mewe.jpg" alt="Me-We Collection From Angara" title="Two-Stone Jewelry"/>
				</a>
			</div>
		</div>
		<script type="text/javascript">
				jQuery(document).ready(function(){
					jQuery('#review-slider').slick({
						arrows			: 	true,
						dots: true,
						slidesToShow	: 	1,
						slidesToScroll	: 	1,
						autoplay: false,
					});
				});
		</script>
	</div>
<!-- slider box -->
</div>