<style>
.tab-large-text { font-weight: bold; text-transform: uppercase; text-align: center; line-height: 23px; font-size: 17px; color:#fff;}
.contact-heading { background-color:#786f6a; background-size: 100% auto; color: white; padding: .67em 0; text-align: center; text-shadow: 1px 1px 1px black; }
.phone-caption-text { margin: 0 auto; width: 70%; }
</style>
<div class="container max-margin-top max-padding-top text-center fontsize-type2">
	<div class="row showcase-bg-white block-inline-display padding-type-4 max-margin-top" style="width:300px; height:400px;">
		<div class="col-xs-12">
        	<div class="row"><i class="fa fa-times close" data-dismiss="modal"></i></div>
			<div class="row low-margin-top contact-heading">
            	<div class="col-xs-12 block-sub-heading text-center tab-large-text">contact</div>
            </div>
            <div class="row max-margin-top">
            	<div class="col-xs-12 phone-caption-text fontsize-type3">Click below to be connected with one of our Angara advisors.</div>
            </div>
            <div class="row max-margin-top">
            	<div class="col-xs-12">
                	<a href="tel:18889264272" rel="nofollow">
                    	<span class="button"><i class="fa fa-phone"></i> 1-888-926-4272</span>
                    </a>
                </div>    
            </div>
            <div class="row low-padding-top">
            	<div class="col-xs-12">Business Hours : 24 * 7</div>    
            </div>
            <div class="row max-margin-top max-padding-top">
            	<div class="col-xs-12"><span class="fontsize-type5"><strong><i class="fa fa-envelope-o"></i> Email</strong></span></div>    
            </div>
            <div class="row max-padding-top">
            	<div class="col-xs-12 phone-caption-text fontsize-type3">For any product/service related questions, please email us at <a href="mailto:customer.service@angara.com" >customer.service@angara.com</a></div>    
            </div>
            
        </div>    
	</div>
</div>