<style>
.catmailcapture
{
width:202px;
height:135px;
background:url(/skin/frontend/angara/default/images/popup/enter-to-win-catalog.jpg) no-repeat top;
}
.block-subscribe
{
width:181px;
margin:0 auto;
position:relative;
}
.usermsg
{
position:absolute;
top:-17px;
left:-5px;
}


.catrespect
{
cursor:pointer;
color:#000;
text-decoration:underline;
width:68px;
margin:0 auto;
}
.catcapturebtn button {
 font: bold 16px/26px Arial,Helvetica,sans-serif,Tahoma;
}

.popuprules {
width:500px;
background-color:#f1f1f1;
padding:8px;
font:11px Arial, Helvetica, sans-serif;
position:absolute;
top:64px;
left:131px;
display:none;
z-index:100;
}
.popuprules ul{ padding:5px ; margin:0; list-style:none; background-color:#fff;}
.popuprules li{ list-style: disc outside none; padding:0; font:11px Arial, Helvetica, sans-serif; color:#000; margin:2px 0 0 15px; line-height:12px;}

input.input-text, select, textarea {
    background: none;
    border: 0 solid #B6B6B6;
    position: relative;
    z-index: 0;
}
.catemailcaptureinput .input-text {
    height: 22px;
    padding: 0 4px;
    width: 171px;
}
.block-subscribe input.input-text {
    border: medium none;
    display: block;
    margin: 0;
    width: 171px;
}
.block {
    border: none;   
}
.catcapturebtn {
    background: url(/skin/frontend/angara/ADVRP/images/catoffer-btn.jpg) no-repeat scroll 0 0 transparent;
    color: #FFFFFF;
    display: block;
    height: 32px;
    position: relative;
    text-align: center;
    width: 181px;
}
.catemailcaptureinput {
    background: url(/skin/frontend/angara/ADVRP//images/catoffcerinputbg.jpg) no-repeat scroll 0 0 transparent;
    border: 1px solid #B1371E;
    height: 22px;
    margin: 15px 0 5px;
    width: 179px;
}
.catcapturebtn button {
    background: none repeat scroll 0 0 transparent;
    border: medium none;
    color: #FFFFFF;
    cursor: pointer;
    display: block;
    font: bold 14px/26px Arial,Helvetica,sans-serif,Tahoma;
    height: 26px;
    outline: medium none;
    padding: 0;
    text-transform: uppercase;
    width: 181px;
}

</style>

<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magentocommerce.com for more information.
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2011 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php $newslettertext = "Enter Your Email Address"; ?>

<div class="block block-layered-nav adj-nav">
  <dl>
    <div id="mailcapturecat" class="popupboxnew"></div>
    <dd class="even" style="padding:0; width:202px">
      <ol>
        <div class="catmailcapture"></div>
        <div style="clear:both"></div>
        <div class="block block-subscribe">
            <form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail-cat-bottom">
            <div style="clear:both"></div>
			<div class="catemailcaptureinput">
			  	<div id="spnerror99" class="usermsg" style="display:none ;color:red; padding-left:5px;">Invalid Email Address</div>  
				<div id='99-Catalog-Bottom-Contest-err' class="usermsg" style="display:none; padding-left:5px;"></div> 
				<div id='99-Catalog-Bottom-Contest-suc' class="usermsg" style="display:none; padding-left:5px;"></div> 	
				<input type="text" name="email" id="newsletter99" value="<?php echo $newslettertext; ?>" class="input-text required-entry validate-email catcaptureinput" onfocus="if(this.value=='<?php echo $newslettertext; ?>') this.value = ''" onblur="if(this.value=='') this.value = '<?php echo $newslettertext; ?>'"  />
				<input type="hidden" name="ref_url" value="<?php echo $this->helper('core/url')->getCurrentUrl();?>" />
				<input type="hidden" name="newslettertype" value="99-Catalog-Bottom-Contest" />
            </div>						
            <div class="catcapturebtn">
              <button type="submit" onclick="return emailvalidate99();">Submit</button>
            </div>
            <div class="catrespect" id="official-rules">Official Rules</div>           
              <div id="official-rulescat" class="popuprules" >
                <ul>
                 <li>No purchase is required to win the Sapphire Pendant.</li>
<li>Angara.com will bear all shipping expenses.</li>
<li>A purchase won't improve chances of winning.</li>
<li>Retail worth of the Sapphire Pendant is $1,799.99.</li>
<li>A lucky winner will be identified once a year in the 2nd week of December and notified via email that is used to participate.</li>
<li>The winner will send the proof of age and address in reply to the winning notification email from Angara at the earliest.</li>
<li>After receiving verification details from the winner, we will publish it on Angara.com, Angara Blog, Angara Facebook page and our other sites.</li>
<li>It will be delivered in 1-2 weeks after verifying the details of the identified winner.</li>
<li>Participants must be legal resident(s) of the United States of America and at least 18 years of age.</li>
<li>Online entries must be made by an individual from a stand-alone computer device and must not be made by proxy or any electronic / automated means such as script, bot, macro or any other similar software or program.</li>
<li>All federal, state and local laws, regulations and ordinances apply. This contest is void where such contests are prohibited, licensed, restricted or taxed.</li>
<li>A prize will be awarded only if it is claimed properly according to these Official Rules.</li>
<li>All discovered entries made in violation of these Official Rules will be eliminated from the contest.</li>
<li>By participating in this contest, you agree to be bound by these Official Rules and the decisions of Angara.com.</li>
<li>The displayed Sapphire pendant is a symbolic representation. The type, color, shape, style might vary of the actual pendant.</li>
<li>By enrolling for this contest, you also confirm to receive promotional offers from Angara.com which you may opt out any time.</li>
                </ul>
              </div>                           
            <div style="clear:both"></div>            
          </form>
          	<script type="text/javascript">	
				jQuery(function(){
					jQuery('#official-rules').hover(
						function(){
							jQuery('#official-rulescat').show();
						},
						function(){
							jQuery('#official-rulescat').hide();
						}
					)
				})
			//<![CDATA[
				var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail-cat-bottom');
				
				jQuery(function(){
					jQuery('#newsletter').focusin(function(){
						if(jQuery(this).val()=='<?php echo $newslettertext; ?>'){
							jQuery(this).val('');
						}
					})
					jQuery('#newsletter').focusout(function(){
						if(jQuery(this).val()==''){
							jQuery(this).val('<?php echo $newslettertext; ?>');
						}})})				
			//]]>
			function emailvalidate99() 
			{				 
				var reg = /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;
				var address = document.getElementById("newsletter99").value;
				if(reg.test(address) == false) 
				{
					document.getElementById("newsletter99").value = "Enter Your Email Address";
					document.getElementById("spnerror99").style.display="block";
					return false;
				}
				document.getElementById("spnerror99").style.display="none";
			}
			</script>
            
        </div>
      </ol>
    </dd>
  </dl>
</div>
