<style>
#playvedio {
	position:absolute;
	z-index:100;
	left:2px;
	top:2px;
}

#playvedio a {
	width:36px;
	height:38px;
	display:block;
}

#playvedio a:hover {
	width:36px;
	height:38px;
	display:block;
	background-color:#e6e6e6;
	border-bottom-left-radius:3px;
	-moz-border-radius-bottomleft:3px;
	-webkit-border-bottom-left-radius:3px;
	-moz-box-shadow:-1px 1px 4px #797979;
	-webkit-box-shadow:-1px 1px 4px #797979;
	box-shadow:-1px 1px 4px #797979;
}

#playvedio a img {
	height:27px;
	width:33px;
	padding:6px 0 0 2px;
}
</style>

<link rel='stylesheet' href='<?php echo $this->getSkinUrl('css/thickbox.css') ?>' type='text/css' media='all' />

<?php
/*
 * Contus Support Pvt Ltd.
 * created by Vasanth on nov 02 2010.
 * vasanth@contus.in
 * In this page we can include the jw player in frontend.
 */

$_helper = $this->helper('catalog/output');
$_product = $this->getProduct();
$cids = $_product->getCategoryIds();
$_videoDetails['video'] = $_helper->productAttribute($_product, $this->htmlEscape($_product->getVideo()), 'video');

$video_arr = explode("|",$_videoDetails['video']);
$number_of_videos = count($video_arr);
?>

<div id="playvedio">
	<a href = "javascript:void(0)" onclick = "document.getElementById('light').style.display='block';document.getElementById('fade').style.display='block'">
    	<img src="<?php echo $this->getSkinUrl('images/playvedioicon.png') ?>" width="33" height="27" />
    </a>
</div>

<?php 
$videoPath = Mage::getBaseUrl('media').'productVideos/';
$thumbPath = Mage::getBaseURL('media').'productVideos/';
?>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jwplayer.js') ?>"></script>   
<script>
	jQuery(function(){
		jQuery('#light, #fade').appendTo('body');
	});
</script>
<div id="light" class="white_content">
	<div style="color:#000; z-index: 2147483647; position: absolute; top: 281px; left: 43px; font-size:10px;"><?php echo 'Video is for representation purpose only'; ?></div>
	<div>
		<img src="<?php echo $videoPath."img/tb-close.png";?>" alt="Close" style="position:absolute;top:-17px;right:-21px;z-index:999;width:41px;" onClick="document.getElementById('light').style.display='none';document.getElementById('fade').style.display='none';playerStop();"/>
	</div>
	<div id='mediaspace'></div>
</div>

<a href = "javascript:void(0)" onclick = "document.getElementById('light').style.display='none';document.getElementById('fade').style.display='none';playerStop();"> 
	<div id="fade" class="black_overlay"></div>
</a>

<script type='text/javascript'>
  jwplayer('mediaspace').setup({
	'flashplayer': '<?php echo $this->getSkinUrl('jwplayer/player.swf');?>',	
    'id': 'mediaspace',
	'skin': '<?php echo $this->getSkinUrl('slim/slim.zip');?>',
    'start':'0',
    'width': '275',
	'autostart': 'true',
	<?php 
	if(!(in_array($_product->getSku(), $plainBandSku))){?>	
	'height': '282',
	<?php 
	}
	else{?>
	'height': '294',
	<?php }?>
	'repeat': 'always',
	'volume': '90',
	'screencolor': '#FFFFFF',
	'stretching' : 'fill',
	'controlbar': 'bottom',
	'playlist.position':'none',
	'playlist.size':'95',
	'playlist.showtext':'false',
	'playlist.backgroundcolor':'#EFEFEF',
	'playlist': [
	<?php
	for ($i=0; $i < count($video_arr); $i++)
	{
	/*Retrive uploaded videos from media*/
	  list($videoName,$thumbName) = explode(',',$video_arr[$i]);	
    ?>
        {
           'file': '<?php echo $videoPath."video/".$videoName;?>',
           'image': '<?php echo $thumbPath."thumb/".$thumbName;?>'          
        },
    <?php 
	}  ?>  ],
	'plugins' : {
        'timeslidertooltipplugin-3': {}	
    }
  }); 
</script>

<script type='text/javascript'>
function playerStop() {
	jwplayer('mediaspace').stop();
}
</script>