<?php
$_item 				= $this->getItem();
$isVisibleProduct 	= $_item->getProduct()->isVisibleInSiteVisibility();
$_recInfo 			= $this->getRecurringInfo();
$_options 			= $this->getOptionList();

$product 			= Mage::getModel('catalog/product');
$_product 			= $product->load($_item->getProductId());
$freeProdSku 		= array('fr','fb','fe','fp');
$strLowerFreeProd 	= strtolower(substr($_product->getSku(), 0, 2));
$mothersflag = 0;
$categoryIds 		= $_product->getCategoryIds();
foreach($categoryIds as $categoryId) {
	$category = Mage::getModel('catalog/category')->load($categoryId);
	$url = $category->getUrlPath();
	if($url == "mothers-jewelry.html") {
		$mothersflag = 1;
	}
}

$imgurl = '';
if($mothersflag == 1) {
	$b_hp = Mage::getBlockSingleton('hprcv/hprcv');
	$b_hp->getimageforcartproduct($_item,$this->getOptionList());
	$imgurl="/media/catalog/product/images/mothers/cartproducts/" . $_item->getId() . "_thumb.png";
}
// HPRAHI CODES CUSTOMISATION END
?>
<div class="">
	<div class="row no-gutters">
        <div class="col-sm-2 col-xs-2 cart-product-image high-padding-top high-padding-bottom">
		
		
		<?php if($this->hasProductUrl()){ ?>
			<a href="<?php echo $this->getProductUrl();?>">
		<?php } ?>
		
		<?php 
        if($mothersflag==1){
            $set_prod_arr = array('SG0107S','SG0108AM','SG0111P','SG0112PAMAQ','SG0113R','SG0109CT','SG0110PT');
            if(!in_array($_item->getProduct()->getData('sku'), $set_prod_arr)) {
            	// skip mother type image for set products ?>
            	<img src="<?php echo $imgurl;?>" width="150" height="150" alt="<?php echo $this->htmlEscape($_product->getProductName());?>"  class="img-responsive"/>
            <?php	
            } 
			else {?>
            	<img src="<?php echo $this->getProductThumbnail()->resize(150);?>" width="150" height="150" alt="<?php echo $this->htmlEscape($this->getProductName());?>" class="img-responsive" />
            <?php
            }
		}
		elseif($product->getSku() == 'ANGCBYO007'){
			$diamondShape = '';
			foreach($_options as $_option){
				if($_option['label'] == 'SecureInformation'){
					$diamondInfo = unserialize($_option['value']);
					$diamondShape = $diamondInfo['diamond']['shape'];
					$stockNumber = strrev('ANG'.$diamondInfo['diamond']['diamond_id']);
				}
			}
			?>
			<img src="/skin/frontend/ress/default/images/buildyourown/diamond/<?php echo $diamondShape; ?>_top_diamond.jpg" width="150" height="150" alt="<?php echo $this->htmlEscape($this->getProductName());?>" class="img-responsive" />
        <?php 
		}
		else{?>
            <img src="<?php echo $this->getProductThumbnail()->resize(150);?>" width="150" height="150" alt="<?php echo $this->htmlEscape($this->getProductName());?>" class="img-responsive" />
        <?php 
		}?>
		<?php if($this->hasProductUrl()){ ?>
			</a>
		<?php } ?>
        <?php if(!in_array($strLowerFreeProd, $freeProdSku)){ ?>
			<?php if(strstr($_SERVER['HTTP_USER_AGENT'],'iPad')){ ?>
				<a href="<?php echo $this->getProductUrl();?>" style="float:left; display:block; width:40%; text-align:center; margin-top:10px"><i class="fa fa-eye"></i></a>
				<span style="float:left; display:block; width:20%; text-align:center; margin-top:10px" class="color999"> | </span>
				<?php if($_item->getCalculationPrice() > 1){ ?>
					<span class="text-light hidden-xs pull-left" style="float:left; display:block; width:40%; text-align:center; margin-top:10px">
						<?php if($_item->getSku()=='OP0001SC' || $_item->getSku()=='EMOP0001SC'){?>
							<a style="display:block; width:100%" class="remove-item" href="<?php echo $this->getUrl('checkout/cart');?>removechain/sku/<?php echo $_item->getSku();?>" title="<?php echo $this->__('Remove item');?>"><?php echo $closeBox; ?><i class="fa fa-trash-o"></i></a>
						<?php } else {?>
							<a style="display:block; width:100%" class="remove-item" href="<?php echo $this->getDeleteUrl() ?>form_key/<?php echo Mage::getSingleton('core/session')->getFormKey();?>" title="<?php echo $this->__('Remove item');?>"><?php echo $closeBox; ?><i class="fa fa-trash-o"></i></a>
						<?php }?>
					</span>
				<?php 
				}else{
					$giftIdsData 	= 	Mage::helper('gifts')->getGiftsIds();
					$giftIds 		= 	$giftIdsData['ids'];
					
					if(is_array($giftIds) && count($giftIds) && Mage::helper('gifts')->isGiftUsed()){?> 
					<span class="text-light hidden-xs pull-left" style="float:left; display:block; width:40%; text-align:center; margin-top:10px">
						<?php if($_item->getSku()=='OP0001SC' || $_item->getSku()=='EMOP0001SC'){?>
							<a style="display:block; width:100%" class="remove-item" href="<?php echo $this->getUrl('checkout/cart');?>removechain/sku/<?php echo $_item->getSku();?>" title="<?php echo $this->__('Remove item');?>"><i class="fa fa-trash-o"></i></a>
						<?php } else {?>
							<a style="display:block; width:100%" class="remove-item" href="<?php echo $this->getDeleteUrl() ?>form_key/<?php echo Mage::getSingleton('core/session')->getFormKey();?>" title="<?php echo $this->__('Remove item');?>"><i class="fa fa-trash-o"></i></a>
						<?php }?>
					</span>
			<?php 	}
				}
			} ?>

		<?php } ?>
        </div>
        <div class="col-sm-6 col-md-7 col-xs-7 cart-product-details">
            <div class="detail-part">
            	<div class="showcase-border-thin-white padding-type-10">
                	<h2 class="product-name min-padding-bottom">
                    <?php 
					if((strtolower(substr($_item->getProduct()->getData('sku'), 0, 2)) == 'by')){
						$additionalTextByo = '<span class="text-light fontsize-type0">(Setting Only)</span>';
					}
					else{
						$additionalTextByo = '';
					}
                    if($this->hasProductUrl()):
						if(in_array($strLowerFreeProd, $freeProdSku)){?>
							<a href="<?php echo $this->getProductUrl();?>"><?php echo $_item->getName();?></a>
						<?php
						}
						else{	
							if($_item->getCalculationPrice() > 0){?>
								<a href="<?php echo $this->getProductUrl();?>"><?php echo $_item->getName();?></a>
							<?php 
							}
							else{
								echo $this->htmlEscape($this->getProductName());
							}
						}	
                    else:
                        echo $this->htmlEscape($this->getProductName());
                    endif; 
					
					echo $additionalTextByo;?>
               		</h2>
					<?php if(!in_array($strLowerFreeProd, $freeProdSku)){ ?>
                	<div class="cart-product-sku high-padding-bottom">
                        <span>
                        <?php 
						if($_item->getProduct()->getData('sku') == 'ANGCBYO007'){?>						
                            <span>Stock Number: <span class="text-light"><?php echo $stockNumber;?></span></span>
						<?php
						}
						else{?>						
                            <span>SKU: <span class="text-light"><?php echo $_item->getProduct()->getData('sku');?></span></span>
						<?php 
						}?>
                        </span>
                        <?php /* <span>Qty: <span class="text-light"><?php echo $this->getQty();?></span></span> */ ?>
                    </div>
					<?php } ?>
                <?php
				if(in_array($strLowerFreeProd, $freeProdSku)){				
					if(stristr($_item->getProduct()->getName(), "pendant")){
						$silverChain = Mage::getSingleton('checkout/session')->getData('silverchain');
						$goldChain = Mage::getSingleton('checkout/session')->getData('goldchain');?>
                       	<div class="add-free-chain" style="margin-top:10px">
							<div class="afc" style="position:relative">
								<input type="checkbox" id="addslchain" value="op0001sc"<?php if($silverChain=='1'){echo ' checked="checked"';}?>> 
								<span class="chb mac-check <?php if($silverChain!='1'){echo 'hide';}?>"></span><span class="chb mac-uncheck <?php if($silverChain=='1'){echo 'hide';}?>"></span>
								<label for="addslchain" class="addChain">Add Silver Chain for <?php echo $this->helper('core')->currency(25);?></label>
							</div>
							<div class="afc" style="position:relative">
								<input type="checkbox" id="addglchain" value="emop0001sc"<?php if($goldChain=='1'){echo ' checked="checked"';}?>> 
								<span class="chb mac-check <?php if($goldChain!='1'){echo 'hide';}?>"></span><span class="chb mac-uncheck <?php if($goldChain=='1'){echo 'hide';}?>"></span>
								<label for="addglchain" class="addChain <?php if($goldChain=='1'){echo 'checked';}?>">Add Gold Chain for <?php echo $this->helper('core')->currency(99);?></label>
							</div>
						</div>
					<?php
					}
				} 
				if($_options):?>
                	<div>
                    <?php 
					foreach($_options as $_option) :
						if($_option['label'] != 'ItemType' && $_option['label'] != 'SecureInformation'):
							$_formatedOptionValue = $this->getFormatedOptionValue($_option);
							if($this->htmlEscape($_option['label']) != 'Center Diamond Size'):
								if($this->htmlEscape($_option['label']) == 'Accent Stone 1 Grade'):?>
									<div class="pull-left min-padding-right"><?php if($this->htmlEscape($_option['label'])=='Free Jewelry Appraisal'){echo 'Jewelry Appraisal';}else{echo $this->htmlEscape("Diamond 2 Grade");}?>:</div>
								<?php 
								else:?>
									<div class="pull-left min-padding-right"><?php if($this->htmlEscape($_option['label'])=='Free Jewelry Appraisal'){echo 'Jewelry Appraisal';}else{echo Mage::helper('function')->getStaticValues($this->htmlEscape($_option['label']));}?>:</div>
								<?php
								endif;?>
								<div class="pull-left text-light">
									
									<?php 
									if(isset($_formatedOptionValue['full_view'])):
										echo $_formatedOptionValue['full_view'];
									else:
										//	S:VA
										echo Mage::helper('function')->getStaticValues($_formatedOptionValue['value'], $_option['code'], $_item->getProduct()->getSku());
									endif;
									
									if(($this->htmlEscape($_option['label'])=='Engraving' || $this->htmlEscape($_option['label'])=='Free Jewelry Appraisal') && ($this->htmlEscape($_option['price'])=='0.00' || $this->htmlEscape($_option['price'])=='0' || $this->htmlEscape($_option['price'])=='0.0'))
										echo '<span class="fontcolor-type1"> (Free)</span>';?>
									
								</div>
								<div class="clearfix"></div>
                    		<?php 	
							endif;
						endif;
					endforeach;?>
               	 	</div>
                <?php 
				endif;
				
				/*	
				//S:VA	Copy this code in mobile theme also
				$couponCode			=	Mage::getSingleton('checkout/session')->getQuote()->getData('coupon_code');
				$skuTwoString		=	strtolower(substr($_item->getProduct()->getData('sku'), 0, 2));
				$todaysCouponCode	=	Mage::helper('function')->getTodaysCouponCode();
				
				//if($couponCode!='' && $_item->getDiscountAmount()<1 && $strLowerFreeProd!= 'in' && $strLowerFreeProd!= 'ja' && !in_array($strLowerFreeProd, $freeProdSku)){
				if(strtolower($couponCode)==strtolower($todaysCouponCode) && $_item->getDiscountAmount()<1 ){
					echo '<div class="apricot-text">This coupon code is not applicable on this item.</div>';
				}
				//	E:VA
                */
				
				if($_recInfo):
					if(Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()):
						$am_hp = ($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition());
					else:
						$am_hp =  ($_item->getCalculationPrice());
					endif;
                	
					$ItemInstallmentAmt = Mage::getBlockSingleton('checkout/cart')->getCartItemInstallmentWithDiscAmount($_item->getCalculationPrice(),$_item->getNoOfInstallment(),$_recInfo['qty'],$_item->getDiscountAmount());
                	$am_hp = $ItemInstallmentAmt;?>
                    <div class="space max-padding-top">
                        <div class="pull-left min-padding-right">You Selected:</div>
                        <div class="pull-left text-light"><?php echo $_item->getNoOfInstallment();?> payments of <?php echo $this->helper('checkout')->formatPrice($ItemInstallmentAmt);?></div>
                        <div class="clearfix"></div>
                    </div>
                    <div id="pay-today-text" class="fontcolor-type1">
                        <div class="pull-left min-padding-right"><span class="text-red">Pay Now:</span></div>
                        <div class="pull-left"><?php echo $this->helper('checkout')->formatPrice($am_hp);?>
                            <span class="text-light" style="font-size:10px">
                                (Order processes today for shipment)
                            </span>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                	<div>
                    <?php 
					if($_item->getNoOfInstallment() == 3):?>
                    	<div class="pull-left min-padding-right">Amount to be charged on <?php echo date("m/d/Y",strtotime("+1 months"));?>:</div>
                    	<div class="pull-left text-light"><?php echo $this->helper('checkout')->formatPrice($ItemInstallmentAmt);?></div>
                    	<div class="clearfix"></div>
                    	<div class="pull-left min-padding-right">Amount to be charged on <?php echo date("m/d/Y",strtotime("+2 months"));?>:</div>
                    	<div class="pull-left text-light"><?php echo $this->helper('checkout')->formatPrice($ItemInstallmentAmt);?></div>
                    	<div class="clearfix"></div>
                    <?php 
					else: ?>
                        <div class="pull-left min-padding-right">Amount to be charged on <?php echo date("m/d/Y",strtotime("+1 months"));?>:</div>
                        <div class="pull-left text-light"><?php echo $this->helper('checkout')->formatPrice($ItemInstallmentAmt);?></div>
                        <div class="clearfix"></div>
                    <?php 
					endif; ?>
                </div>
                <?php 
				endif;
				
				if($messages = $this->getMessages()):
					foreach($messages as $message):?>
                		<p class="item-msg <?php echo $message['type'] ?>">* <?php echo $message['text'];?></p>
                	<?php 
					endforeach;
				endif;
				
				if($addtInfoBlock = $this->getProductAdditionalInformationBlock()):
					echo $addtInfoBlock->setItem($_item)->toHtml();
				endif;?>
                
				<?php //:RV ?>
					<?php if(!in_array($strLowerFreeProd, $freeProdSku)){	?>
					
					<?php if(strstr($_SERVER['HTTP_USER_AGENT'],'iPad')){ ?> 
						<?php //to manage quick load of apricot close image on remove link hover ?>
						<img src="/skin/frontend/ress/default/images/optionpopupclose-apricot.png" class="hidden" />
						
						<?php 	
							$relativePlaceholder = 'relative-placeholder';
							$absolutePlaceholder = 'absolute-placeholder'; 
							$closeBox = '<i class="close-img"></i>';
						?>
						<style>
							.action-buttons.relative-placeholder{height:30px;}
							.action-buttons .action-buttons-holder{width:210px; left:0px; top:0px;}
						</style>
					<?php } ?>
					<?php if(!strstr($_SERVER['HTTP_USER_AGENT'],'iPad')){  ?>
					<div class="col-sm-12 no-padding high-margin-top clearfix action-buttons <?php echo $relativePlaceholder; ?>">
						<div class="action-buttons-holder <?php echo $absolutePlaceholder; ?>">
							<?php /* if($this->hasProductUrl()){ ?>
								<a href="<?php echo $this->getProductUrl();?>" class="cart-action-link edit-item block-inline-display pull-left low-padding-top low-padding-bottom color999 clickable">Edit</a>
								<span class="cart-seprator block-inline-display pull-left padding-type-5">|</span>
							} */ ?>
							
							<?php if($_item->getCalculationPrice() > 1){ ?>
								<span class="text-light hidden-xs pull-left low-padding-top low-padding-bottom">
									<?php if($_item->getSku()=='OP0001SC' || $_item->getSku()=='EMOP0001SC'){?>
										<a class="remove-item color999" href="<?php echo $this->getUrl('checkout/cart');?>removechain/sku/<?php echo $_item->getSku();?>" title="<?php echo $this->__('Remove item');?>"><?php echo $closeBox; ?>Remove</a>
									<?php } else {?>
										<a class="remove-item color999" href="<?php echo $this->getDeleteUrl() ?>form_key/<?php echo Mage::getSingleton('core/session')->getFormKey();?>" title="<?php echo $this->__('Remove item');?>"><?php echo $closeBox; ?>Remove</a>
									<?php }?>
								</span>
								<span class="text-light visible-xs">
									<?php 
									if ($this->hasProductUrl()):?>
										<a href="<?php echo $this->getProductUrl();?>" title="<?php echo $this->htmlEscape($this->getProductName());?>"><i class="fa fa-eye"></i></a> |
									<?php 
									endif;?>
									<?php if($_item->getSku()=='OP0001SC' || $_item->getSku()=='EMOP0001SC'){?>
										<a class="remove-item" href="<?php echo $this->getUrl('checkout/cart');?>removechain/sku/<?php echo $_item->getSku();?>" title="<?php echo $this->__('Remove item');?>"><i class="fa fa-trash-o"></i></a>
									<?php } else {?>
										<a class="remove-item" href="<?php echo $this->getDeleteUrl() ?>form_key/<?php echo Mage::getSingleton('core/session')->getFormKey();?>" title="<?php echo $this->__('Remove item');?>"><i class="fa fa-trash-o"></i></a>
									<?php } ?>
									
								</span>
							<?php 
							}else{
								$giftIdsData 	= 	Mage::helper('gifts')->getGiftsIds();
								$giftIds 		= 	$giftIdsData['ids'];
								
								if(is_array($giftIds) && count($giftIds) && Mage::helper('gifts')->isGiftUsed()){?> 
								<span class="text-light hidden-xs pull-left low-padding-top low-padding-bottom">
									<?php if($_item->getSku()=='OP0001SC' || $_item->getSku()=='EMOP0001SC'){?>
										<a class="remove-item color999" href="<?php echo $this->getUrl('checkout/cart');?>removechain/sku/<?php echo $_item->getSku();?>" title="<?php echo $this->__('Remove item');?>">Remove</a>
									<?php } else {?>
										<a class="remove-item color999" href="<?php echo $this->getDeleteUrl() ?>form_key/<?php echo Mage::getSingleton('core/session')->getFormKey();?>" title="<?php echo $this->__('Remove item');?>">Remove</a>
									<?php }?>
								</span>
								<span class="text-light visible-xs">
									<?php 
									if($this->hasProductUrl()):?>
										<a href="<?php echo $this->getProductUrl();?>" title="<?php echo $this->htmlEscape($this->getProductName());?>"><i class="fa fa-eye"></i></a> |
									<?php 
									endif;?>
									<?php if($_item->getSku()=='OP0001SC' || $_item->getSku()=='EMOP0001SC'){?>
										<a class="remove-item" href="<?php echo $this->getUrl('checkout/cart');?>removechain/sku/<?php echo $_item->getSku();?>" title="<?php echo $this->__('Remove item');?>"><i class="fa fa-trash-o"></i></a>
									<?php } else {?>
										<a class="remove-item" href="<?php echo $this->getDeleteUrl() ?>form_key/<?php echo Mage::getSingleton('core/session')->getFormKey();?>" title="<?php echo $this->__('Remove item');?>"><i class="fa fa-trash-o"></i></a>
									<?php }?>
								</span>
							<?php }
							}	?>              
							<?php //	S:VA
							$checkProductInWishlist	=	Mage::helper('function')->checkProductInWishlist($_item->getProductId());
							if($checkProductInWishlist){?>
								<span class="cart-seprator block-inline-display pull-left padding-type-5">|</span>
								<a href="<?php echo Mage::getUrl('wishlist'); ?>" class="cart-action-link view-in-wishlist block-inline-display pull-left low-padding-top low-padding-bottom color999 clickable"><?php echo $this->__('View in Wishlist'); ?></a>
						<?php }else{
								if ($this->helper('wishlist')->isAllowInCart() && $isVisibleProduct) { 
								//if ($isVisibleProduct) { ?>
                                    <span class="cart-seprator block-inline-display pull-left padding-type-5">|</span>
                                    <a href="<?php echo $this->helper('wishlist')->getMoveFromCartUrl($_item->getId()); ?>" class="cart-action-link add-to-wishlist block-inline-display pull-left low-padding-top low-padding-bottom color999 clickable"><?php echo $this->__('Add To Wishlist'); ?></a>
							<?php } 
								}	?>
						</div>
					</div>
					<?php } ?>
					<?php } ?>
				<?php //:RV ?>
				<?php if(!in_array($strLowerFreeProd, $freeProdSku)){	?>
                <div id="delivery_date_<?php echo $_item->getId();?>"><?php echo Mage::getBlockSingleton('catalog/product_deliverydate')->getArrivesByDateAtCart($_item);?></div>			
				<?php 
				}
				if(!strstr($_SERVER['HTTP_USER_AGENT'],'iPad')){
					echo Mage::helper('function')->getAdditionalCartText($_item, $this->getQty()); 
				} ?>                
            	</div>
            </div>
        </div>
        <div class="col-md-1 col-xs-1 col-sm-2 hidden-xs high-padding-top editable-qty-box text-center">  
			<?php 
			$checkFreeProductSku	=	Mage::helper('function')->canEditQtyForProducts($product);
			if($checkFreeProductSku==true){	?>
			<div class="item-edit-holder">
            	<?php /*?><input type="text" class="input-text block-inline-display" name="cart[<?php echo $_item->getId() ?>][qty]" value="<?php echo $this->getQty() ?>" id="qtyeditor" /><button type="submit" class="btn btn-primary block-inline-display" href="#">Update</button><?php */?>
                <select name="cart[<?php echo $_item->getId() ?>][qty]" onchange="this.form.submit()" class="input-text block-inline-display">
                    <?php for($i=1; $i<=6; $i++){?>
                        <option value='<?php echo $i;?>' <?php if($this->getQty() == $i){ echo 'selected="selected"';} ?>><?php echo $i;?></option>
                    <?php } ?>
                </select>
            </div>
			<?php }else{?>
				<span class="item-qty"><?php echo $this->getQty();?></span>
			<?php }?>
        </div>
        <div class="col-sm-2 col-xs-2 text-right cart-price high-padding-top">
            <?php 
			if($_recInfo):
				echo $this->helper('core')->currency($_item->getProduct()->getFinalPrice() * $this->getQty());
			elseif(Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()):
				echo $this->helper('checkout')->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition());
			else:
				if($_item->getCalculationPrice() > 0){	
                	echo $this->helper('checkout')->formatPrice($_item->getRowTotal());
                }else{
					if(Mage::getSingleton('checkout/session')->getQuote()->getData('coupon_code')){
						echo '<span class="apricot-text"><strong>Free</strong> </span> <br> with code <span class="text-uppercase">'.Mage::getSingleton('checkout/session')->getQuote()->getData('coupon_code').'</span>';
					}
					else{
						echo '<span class="apricot-text"><strong>Free</strong> </span>';
					}	
                }
			endif; ?>
        </div>
    </div>
</div>
<?php
$currentCurrencyCode =  Mage::app()->getStore()->getCurrentCurrencyCode();
$baseCurrencyCode = Mage::app()->getStore()->getBaseCurrencyCode();?>