<style>
.errorwrapper{width:auto}
.errormsgbox{width:auto;height:auto}	
.errormsg{height:auto}
</style>
<div class="errorwrapper">
<div class="errormsgbox">
<div class="errormsg"><span class="errorimg"><img src="/skin/frontend/angara/default/images/errorimg.jpg" alt="" /></span>Seems like the tech guy on the other end messed up.. or are you trying some broken link? In any case, same techie is now working hard to make everything work fine for you and is thanking you for the patience!!</div>
</div>
</div>