<?php $_creditmemo = $this->getCreditmemo() ?>
<?php $_order      = $this->getOrder() ?>
<?php if ($_creditmemo && $_order): ?>

<tr>
  <td valign="top" colspan="2"><table width="100%" border="0" cellspacing="0" cellpadding="0"  style="border:1px solid #333; border-bottom:none;" >
      <tr>
        <th scope="col" width="130" style="padding:8px 0 8px 15px; text-align:left;font:15px Arial, Helvetica, sans-serif; background-color:#999; color:#fff;border-bottom:1px solid #333; border-right:1px solid #333;">Item</th>
        <th scope="col" width="230" style="padding:8px 0 8px 15px; text-align:left;font:15px Arial, Helvetica, sans-serif; background-color:#999; color:#fff;border-bottom:1px solid #333; border-right:1px solid #333;">Description</th>
        <th scope="col" class="100" style="padding:8px 0 8px 5px; text-align:left;font:15px Arial, Helvetica, sans-serif; background-color:#999; color:#fff;border-bottom:1px solid #333; border-right:1px solid #333;">Quantity</th>
        <th scope="col" class="95" style="padding:8px 0 8px 15px; text-align:left;font:15px Arial, Helvetica, sans-serif; background-color:#999; color:#fff;border-bottom:1px solid #333; border-right:1px solid #333;">Rate</th>
        <th scope="col" width="90"  style="padding:8px 0 8px 15px; text-align:left;font:15px Arial, Helvetica, sans-serif; background-color:#999; color:#fff;border-bottom:1px solid #333;">Amount</th>
      </tr>
    	<?php $i=0; foreach ($_creditmemo->getAllItems() as $_item): ?>
    	<?php if($_item->getOrderItem()->getParentItem()) continue; else $i++; ?>
      	<?php //echo get_class($this);die;
	  		echo $this->getItemHtml($_item); //	default.phtml code includes?>
      	<?php endforeach; ?>
    </table></td>
</tr>

<tr>
  <td valign="top" colspan="2"><table width="100%" border="0" cellspacing="0" cellpadding="0" style="border-left:1px solid #333; border-right:1px solid #333; border-bottom:1px solid #333;">
      <tr>
        <td width="300"  valign="top"><table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td style="border-top:1px solid #333;">&nbsp;</td>
            </tr>
          </table></td>
        <td width="350" valign="top" ><table width="100%" border="0" cellspacing="0" cellpadding="0" style="border-left:1px solid #333;">
            <?php echo $this->getChildHtml('creditmemo_totals');?>
          </table></td>
      </tr>
    </table></td>
</tr>
<?php endif;?>
