<?php echo $this->getChildHtml('items_before'); ?>
<div id="checkout-review-table-wrapper">
    <table class="order-products-table table table-condensed table-no-border" id="checkout-review-table" style="margin-bottom:0px;">
        <col />
        <col width="1" />
        <col width="1" />
        <?php
        $colspan	= 1; 
        if ($this->helper('tax')->displayCartBothPrices()):
        	$colspan	= 2; 
        ?>
        <col width="1" />
        <?php endif; ?>        
        
        <?php echo $this->getChildHtml('totals'); ?>       
    </table>
</div>
<script type="text/javascript">
//<![CDATA[
    decorateTable('checkout-review-table');
    truncateOptions();
//]]>
</script>
